$palette=@{'Storefront 0'='#43d9bb';'Storefront 1'='#ff8d7f';'Storefront 2'='#ffd477';'Storefront 3'='#9cc8ff'}
$letters=@{'Storefront 0'='M';'Storefront 1'='D';'Storefront 2'='A';'Storefront 3'='G'}
$sections=foreach($phase in @('before','after')) {
 $rows=Import-Csv "Docs/CR019/$phase-sites.csv"
 $tags=foreach($r in $rows){$px=960+([double]$r.x+155)*1080/490;$py=540-([double]$r.z-540)*1080/490;$fill=$palette[$r.prefab];$letter=$letters[$r.prefab];'<g><title>'+[System.Net.WebUtility]::HtmlEncode($r.id+' / '+$r.sign)+'</title><circle cx="'+$px.ToString('F1',[cultureinfo]::InvariantCulture)+'" cy="'+$py.ToString('F1',[cultureinfo]::InvariantCulture)+'" r="17" fill="'+$fill+'" stroke="#10202a" stroke-width="2"/><text x="'+$px.ToString('F1',[cultureinfo]::InvariantCulture)+'" y="'+($py+6).ToString('F1',[cultureinfo]::InvariantCulture)+'" text-anchor="middle" fill="#10202a" font-size="20" font-weight="700">'+$letter+'</text></g>'}
 '<h2>'+ $phase.ToUpper()+'</h2><svg viewBox="0 0 1920 1080" role="img" aria-label="Annotated '+$phase+' commercial overview"><image href="'+$phase+'-overhead.png" width="1920" height="1080"/>'+($tags -join '')+'</svg>'
}
$roads=foreach($x in @('-460','-160','140')){foreach($dir in @('-1','1')){
 $heading=if($dir -eq '1'){'Eastbound'}else{'Westbound'}
 $figures=foreach($phase in @('before','after')){
  $caption=if($phase -eq 'before'){'Aligned storefront pairs, repeated spacing.'}else{'Independent store order, staggered fronts and coordinated paving.'}
  '<figure><img loading="lazy" src="'+$phase+'-road-'+$x+'-'+$dir+'.png" alt="'+$phase+' '+$heading+' commercial street"><figcaption>'+ $phase.ToUpper()+' · '+$caption+'</figcaption></figure>'
 }
 '<h3>'+ $heading+' · camera station x='+$x+' m</h3><div class="pair">'+($figures -join '')+'</div>'
}}
$html=@'
<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Racer · CR-019 visual review</title><style>body{margin:0;background:#122128;color:#eef4ed;font:17px/1.55 system-ui,sans-serif}main{max-width:1500px;margin:auto;padding:40px}h1{font-size:42px;line-height:1.15;margin:8px 0 18px}h2{margin-top:40px;color:#ffd477}h3{margin-top:34px}p{max-width:1000px}.tag{color:#43d9bb;letter-spacing:.1em}svg,img{width:100%;display:block;border-radius:10px}svg{border:1px solid #58716e}.pair{display:grid;grid-template-columns:1fr 1fr;gap:18px}figure{margin:0}figcaption{padding:10px 0;color:#b9cecb;font-size:14px}.legend{display:flex;gap:24px;flex-wrap:wrap;margin:18px 0}.legend b{color:#122128;border-radius:5px;padding:4px 10px}a{color:#7ee5d4}li{margin:8px 0}@media(max-width:850px){.pair{grid-template-columns:1fr}main{padding:20px}}</style><main><div class="tag">PHASE 8 · AWAITING DAN'S VISUAL REVIEW</div><h1>A staggered commercial street</h1><p>All 22 businesses retained: 11 on each side. Labels identify the four existing storefront assets. Screenshots are actual Unity camera renders at identical before/after positions, 1920 × 1080. North is up; west is left. Hover a label for its site and sign.</p><div class="legend"><span><b style="background:#43d9bb">M</b> Corner Market</span><span><b style="background:#ff8d7f">D</b> Hilltop Diner</span><span><b style="background:#ffd477">A</b> Auto Service</span><span><b style="background:#9cc8ff">G</b> General Store</span></div><p><strong>Compare:</strong> the original paired labels and uniform gaps with the independent rows below. The wide south-side gap near the east bend and the north-side gap in the middle occur at different places. Paving follows each new frontage; woodland remains open between sites.</p>
'@
$html+=($sections -join "`n")+'<h2>Road-level comparison · both directions</h2><p>Six fixed road-level viewpoints cover the west, center and east parts of the commercial stretch. These are camera evidence; the separate <a href="driving.txt">drive report</a> records the ordinary-frame vehicle tests.</p>'+($roads -join "`n")+'<h2>Review checklist</h2><ul><li>Drive both ways: do the store order and irregular gaps feel natural?</li><li>Check storefronts, foundations, paving and driveway access.</li><li>Confirm the restrained colors and preserved woodland fit the low-poly street.</li></ul><p><a href="VALIDATION.md">Validation and authoring notes</a> · <a href="after-sites.csv">Exact site inventory</a></p></main></html>'
Set-Content -LiteralPath Docs/CR019/review.html -Value $html -Encoding utf8

