#include "core.hpp"
#include "pinned_key.hpp"
#include "vendor/miniz.h"
#include <winhttp.h>
#include <bcrypt.h>
#include <wincrypt.h>
#include <shlobj.h>
#include <fstream>
#include <set>
#include <map>
#include <chrono>
#include <algorithm>
#include <sstream>
#pragma comment(lib,"winhttp.lib")
#pragma comment(lib,"bcrypt.lib")
#pragma comment(lib,"crypt32.lib")
#pragma comment(lib,"shell32.lib")
#pragma comment(lib,"ole32.lib")
namespace wr {
static void Require(bool yes,const std::string& text){if(!yes)throw std::runtime_error(text);}
static void Nt(NTSTATUS status){Require(status>=0,"Windows cryptography operation failed");}
static std::string Lower(std::string value){std::transform(value.begin(),value.end(),value.begin(),[](unsigned char c){return (char)std::tolower(c);});return value;}
static std::string Hex(const BYTE* data,size_t length){static const char* digits="0123456789abcdef";std::string out;out.reserve(length*2);for(size_t i=0;i<length;i++){out+=digits[data[i]>>4];out+=digits[data[i]&15];}return out;}
static std::vector<BYTE> Unhex(const std::string& text){Require(text.size()%2==0,"Invalid hex data");std::vector<BYTE> out;for(size_t i=0;i<text.size();i+=2){auto digit=[](char c)->int{if(c>='0'&&c<='9')return c-'0';if(c>='a'&&c<='f')return c-'a'+10;if(c>='A'&&c<='F')return c-'A'+10;throw std::runtime_error("Invalid hex digit");};out.push_back(BYTE(digit(text[i])*16+digit(text[i+1])));}return out;}
static std::string Transaction(){BYTE data[16];Nt(BCryptGenRandom(nullptr,data,16,BCRYPT_USE_SYSTEM_PREFERRED_RNG));return Hex(data,16);}
std::wstring Wide(const std::string& s){if(s.empty())return {};int length=MultiByteToWideChar(CP_UTF8,MB_ERR_INVALID_CHARS,s.data(),(int)s.size(),nullptr,0);Require(length>0,"Invalid UTF-8 text");std::wstring result(length,0);MultiByteToWideChar(CP_UTF8,MB_ERR_INVALID_CHARS,s.data(),(int)s.size(),result.data(),length);return result;}
std::string Utf8(const std::wstring& s){if(s.empty())return {};int length=WideCharToMultiByte(CP_UTF8,WC_ERR_INVALID_CHARS,s.data(),(int)s.size(),nullptr,0,nullptr,nullptr);Require(length>0,"Invalid Unicode path");std::string result(length,0);WideCharToMultiByte(CP_UTF8,WC_ERR_INVALID_CHARS,s.data(),(int)s.size(),result.data(),length,nullptr,nullptr);return result;}
void CheckNoLinks(const fs::path& path){auto p=fs::absolute(path).lexically_normal();for(;;){DWORD attributes=GetFileAttributesW(p.c_str());if(attributes!=INVALID_FILE_ATTRIBUTES)Require(!(attributes&FILE_ATTRIBUTE_REPARSE_POINT),"Linked directories/files are not supported: "+Utf8(p.wstring()));else{DWORD e=GetLastError();Require(e==ERROR_FILE_NOT_FOUND||e==ERROR_PATH_NOT_FOUND,"Cannot inspect path: "+Utf8(p.wstring()));}auto parent=p.parent_path();if(parent.empty()||parent==p)break;p=parent;}}
fs::path SafePath(const fs::path& root,const std::string& relative){
 Require(!relative.empty()&&relative.size()<1024&&relative.front()!='/'&&relative.find('\\')==std::string::npos&&relative.find(':')==std::string::npos,"Unsafe relative path");
 for(unsigned char c:relative)Require(c>=32&&c!=127,"Control character in path");
 std::stringstream stream(relative);std::string part;while(std::getline(stream,part,'/')){Require(!part.empty()&&part!="."&&part!=".."&&part.back()!='.'&&part.back()!=' ',"Unsafe path component");auto stem=Lower(part.substr(0,part.find('.')));Require(stem!="con"&&stem!="prn"&&stem!="aux"&&stem!="nul"&&!(stem.size()==4&&(stem.substr(0,3)=="com"||stem.substr(0,3)=="lpt")&&stem[3]>='0'&&stem[3]<='9'),"Reserved Windows filename");}
 auto base=fs::absolute(root).lexically_normal();auto target=(base/fs::path(Wide(relative))).lexically_normal();auto prefix=Lower(Utf8(base.wstring()))+"\\";Require(Lower(Utf8(target.wstring())).rfind(prefix,0)==0,"Path escaped installation root");CheckNoLinks(target);return target;
}
std::string Read(const fs::path& path,size_t maxBytes){CheckNoLinks(path);Require(fs::file_size(path)<=maxBytes,"Metadata file too large");std::ifstream in(path,std::ios::binary);Require(bool(in),"Cannot read metadata");return std::string(std::istreambuf_iterator<char>(in),{});}
void AtomicWrite(const fs::path& path,const std::string& data){CheckNoLinks(path);fs::create_directories(path.parent_path());auto temporary=path;temporary+=L".tmp-"+Wide(Transaction());HANDLE h=CreateFileW(temporary.c_str(),GENERIC_WRITE,0,nullptr,CREATE_NEW,FILE_ATTRIBUTE_NORMAL,nullptr);Require(h!=INVALID_HANDLE_VALUE,"Cannot create transaction file");DWORD done=0;bool ok=WriteFile(h,data.data(),(DWORD)data.size(),&done,nullptr)&&done==data.size()&&FlushFileBuffers(h);CloseHandle(h);Require(ok,"Cannot persist transaction file");DWORD error=0;bool moved=false;for(int attempt=0;attempt<8;attempt++){if(MoveFileExW(temporary.c_str(),path.c_str(),MOVEFILE_REPLACE_EXISTING|MOVEFILE_WRITE_THROUGH)){moved=true;break;}error=GetLastError();if(error!=ERROR_SHARING_VIOLATION&&error!=ERROR_ACCESS_DENIED)break;Sleep(50);}Require(moved,"Cannot atomically select installed version (Windows error "+std::to_string(error)+")");}
struct Digest {BCRYPT_ALG_HANDLE algorithm=nullptr;BCRYPT_HASH_HANDLE hash=nullptr;Digest(){Nt(BCryptOpenAlgorithmProvider(&algorithm,BCRYPT_SHA256_ALGORITHM,nullptr,0));Nt(BCryptCreateHash(algorithm,&hash,nullptr,0,nullptr,0,0));}~Digest(){if(hash)BCryptDestroyHash(hash);if(algorithm)BCryptCloseAlgorithmProvider(algorithm,0);}void Add(const void* p,size_t n){Nt(BCryptHashData(hash,(PUCHAR)p,(ULONG)n,0));}std::vector<BYTE> Finish(){std::vector<BYTE> out(32);Nt(BCryptFinishHash(hash,out.data(),32,0));return out;}};
std::string HashBytes(const std::string& data){Digest hash;hash.Add(data.data(),data.size());auto bytes=hash.Finish();return Hex(bytes.data(),bytes.size());}
std::string Hash(const fs::path& path){CheckNoLinks(path);std::ifstream in(path,std::ios::binary);Require(bool(in),"Cannot hash file");Digest hash;std::vector<char> buffer(1024*1024);while(in){in.read(buffer.data(),buffer.size());if(in.gcount())hash.Add(buffer.data(),(size_t)in.gcount());}Require(in.eof(),"File read failed while hashing");auto out=hash.Finish();return Hex(out.data(),out.size());}
static std::vector<BYTE> Base64(const std::string& input){Require(input.size()<12*1024*1024,"Signed metadata too large");DWORD length=0;Require(CryptStringToBinaryA(input.data(),(DWORD)input.size(),CRYPT_STRING_BASE64|CRYPT_STRING_STRICT,nullptr,&length,nullptr,nullptr)!=0,"Invalid signature encoding");std::vector<BYTE> result(length);Require(CryptStringToBinaryA(input.data(),(DWORD)input.size(),CRYPT_STRING_BASE64|CRYPT_STRING_STRICT,result.data(),&length,nullptr,nullptr)!=0,"Invalid signature encoding");result.resize(length);return result;}
json Verify(const std::string& text){
 Require(text.size()<=12*1024*1024,"Signed metadata too large");auto envelope=json::parse(text);Require(envelope.at("keyId")==KeyId,"Unknown publisher signing key");auto payload=Base64(envelope.at("payload").get<std::string>()),signature=Base64(envelope.at("signature").get<std::string>());Digest digest;digest.Add(payload.data(),payload.size());auto hash=digest.Finish();auto modulus=Unhex(ModulusHex),exponent=Unhex(ExponentHex);
 BCRYPT_RSAKEY_BLOB header{BCRYPT_RSAPUBLIC_MAGIC,(ULONG)modulus.size()*8,(ULONG)exponent.size(),(ULONG)modulus.size(),0,0};std::vector<BYTE> blob(sizeof(header));memcpy(blob.data(),&header,sizeof(header));blob.insert(blob.end(),exponent.begin(),exponent.end());blob.insert(blob.end(),modulus.begin(),modulus.end());BCRYPT_ALG_HANDLE algorithm=nullptr;BCRYPT_KEY_HANDLE key=nullptr;Nt(BCryptOpenAlgorithmProvider(&algorithm,BCRYPT_RSA_ALGORITHM,nullptr,0));NTSTATUS imported=BCryptImportKeyPair(algorithm,nullptr,BCRYPT_RSAPUBLIC_BLOB,&key,blob.data(),(ULONG)blob.size(),0);BCRYPT_PKCS1_PADDING_INFO padding{BCRYPT_SHA256_ALGORITHM};NTSTATUS valid=imported>=0?BCryptVerifySignature(key,&padding,hash.data(),(ULONG)hash.size(),signature.data(),(ULONG)signature.size(),BCRYPT_PAD_PKCS1):imported;if(key)BCryptDestroyKey(key);BCryptCloseAlgorithmProvider(algorithm,0);Require(valid>=0,"Publisher signature is invalid; installed game unchanged");auto result=json::parse(payload.begin(),payload.end());Require(result.at("schema")==LauncherSchema,"This update requires a newer launcher; current game remains playable");return result;
}
void CheckInventory(const fs::path& root,const json& files,bool exact){
 Require(files.is_array()&&files.size()<=250000,"Invalid runtime inventory");std::set<std::string> wanted;
 for(const auto& file:files){auto relative=file.at("path").get<std::string>();Require(wanted.insert(Lower(relative)).second,"Duplicate inventory path");auto path=SafePath(root,relative);Require(fs::is_regular_file(path)&&fs::file_size(path)==file.at("bytes").get<uint64_t>()&&Hash(path)==Lower(file.at("sha256").get<std::string>()),"Runtime inventory mismatch: "+relative);}
 if(exact){size_t found=0;for(auto& entry:fs::recursive_directory_iterator(root)){CheckNoLinks(entry.path());if(entry.is_regular_file()){found++;Require(wanted.count(Lower(Utf8(fs::relative(entry.path(),root).generic_wstring())))>0,"Unexpected runtime file");}}Require(found==wanted.size(),"Incomplete runtime inventory");}
}
void Extract(const fs::path& archive,const fs::path& destination,const json& files){
 CheckNoLinks(destination);Require(!fs::exists(destination),"Extraction target already exists");fs::create_directories(destination);std::map<std::string,json> expected;for(const auto& f:files){auto p=f.at("path").get<std::string>();SafePath(destination,p);Require(expected.emplace(Lower(p),f).second,"Duplicate inventory filename");}
 FILE* file=nullptr;_wfopen_s(&file,archive.c_str(),L"rb");Require(file!=nullptr,"Cannot open downloaded archive");mz_zip_archive zip{};if(!mz_zip_reader_init_cfile(&zip,file,0,0)){fclose(file);throw std::runtime_error("Invalid ZIP archive");}
 try{Require(mz_zip_reader_get_num_files(&zip)<=250000,"Too many ZIP entries");std::set<std::string> seen;
  for(mz_uint i=0;i<mz_zip_reader_get_num_files(&zip);i++){mz_zip_archive_file_stat stat{};Require(mz_zip_reader_file_stat(&zip,i,&stat)!=0,"Invalid ZIP entry");Require(((stat.m_external_attr>>16)&0170000)!=0120000&&!(stat.m_bit_flag&1),"ZIP links/encryption are forbidden");mz_uint size=mz_zip_reader_get_filename(&zip,i,nullptr,0);Require(size>1&&size<1024,"Invalid ZIP filename");std::vector<char> name(size);mz_zip_reader_get_filename(&zip,i,name.data(),size);Require(strlen(name.data())==size-1,"Embedded zero in ZIP filename");std::string relative(name.data());bool directory=mz_zip_reader_is_file_a_directory(&zip,i)!=0;if(directory&&relative.back()=='/')relative.pop_back();auto path=SafePath(destination,relative);if(directory)continue;auto normalized=Lower(relative);Require(seen.insert(normalized).second,"Duplicate ZIP entry");auto found=expected.find(normalized);Require(found!=expected.end()&&stat.m_uncomp_size==found->second.at("bytes").get<uint64_t>(),"ZIP entry not in signed inventory");fs::create_directories(path.parent_path());
   struct Output {HANDLE handle;uint64_t maximum,written=0;} output{CreateFileW(path.c_str(),GENERIC_WRITE,0,nullptr,CREATE_NEW,FILE_ATTRIBUTE_NORMAL,nullptr),stat.m_uncomp_size};Require(output.handle!=INVALID_HANDLE_VALUE,"Cannot create extracted file");
   auto write=[](void* opaque,mz_uint64 offset,const void* data,size_t count)->size_t{auto& o=*(Output*)opaque;if(offset!=o.written||count>o.maximum-o.written||count>MAXDWORD)return 0;DWORD written=0;if(!WriteFile(o.handle,data,(DWORD)count,&written,nullptr))return 0;o.written+=written;return written;};bool success=mz_zip_reader_extract_to_callback(&zip,i,write,&output,0)!=0;CloseHandle(output.handle);Require(success&&output.written==output.maximum,"ZIP decompression/CRC failed");
  }
 }catch(...){mz_zip_reader_end(&zip);fclose(file);throw;}mz_zip_reader_end(&zip);fclose(file);CheckInventory(destination,files,true);
}
struct Internet {HINTERNET h=nullptr;explicit Internet(HINTERNET value):h(value){Require(h!=nullptr,"Network connection failed");}~Internet(){if(h)WinHttpCloseHandle(h);}operator HINTERNET()const{return h;}};
static void Request(const std::string& url,uint64_t maximum,std::atomic<bool>& cancel,const std::function<void(const BYTE*,size_t)>& consume,Progress progress,bool fixture){
 auto u=Wide(url);URL_COMPONENTS components{};components.dwStructSize=sizeof(components);components.dwHostNameLength=components.dwUrlPathLength=components.dwExtraInfoLength=components.dwUserNameLength=components.dwPasswordLength=(DWORD)-1;Require(WinHttpCrackUrl(u.c_str(),(DWORD)u.size(),0,&components)!=0,"Invalid download URL");std::wstring host(components.lpszHostName,components.dwHostNameLength);Require(components.dwUserNameLength==0&&components.dwPasswordLength==0,"Credentials in download URLs are forbidden");Require(components.nScheme==INTERNET_SCHEME_HTTPS||(fixture&&components.nScheme==INTERNET_SCHEME_HTTP&&(host==L"127.0.0.1"||host==L"localhost")),"Only HTTPS downloads are permitted");
 Internet session(WinHttpOpen(L"WoodstockRushLauncher/1",WINHTTP_ACCESS_TYPE_AUTOMATIC_PROXY,WINHTTP_NO_PROXY_NAME,WINHTTP_NO_PROXY_BYPASS,0));WinHttpSetTimeouts(session,3000,5000,5000,5000);Internet connection(WinHttpConnect(session,host.c_str(),components.nPort,0));std::wstring route(components.lpszUrlPath,components.dwUrlPathLength);if(components.dwExtraInfoLength)route.append(components.lpszExtraInfo,components.dwExtraInfoLength);Internet request(WinHttpOpenRequest(connection,L"GET",route.c_str(),nullptr,WINHTTP_NO_REFERER,WINHTTP_DEFAULT_ACCEPT_TYPES,components.nScheme==INTERNET_SCHEME_HTTPS?WINHTTP_FLAG_SECURE:0));
 Require(!cancel,"Cancelled");Require(WinHttpSendRequest(request,WINHTTP_NO_ADDITIONAL_HEADERS,0,WINHTTP_NO_REQUEST_DATA,0,0,0)&&WinHttpReceiveResponse(request,nullptr),"Update service unavailable; current game is still playable");DWORD status=0,length=sizeof(status);Require(WinHttpQueryHeaders(request,WINHTTP_QUERY_STATUS_CODE|WINHTTP_QUERY_FLAG_NUMBER,nullptr,&status,&length,nullptr)!=0&&status==200,"Download HTTP error "+std::to_string(status));
 std::vector<BYTE> buffer(128*1024);uint64_t total=0;auto start=GetTickCount64();for(;;){Require(!cancel,"Download cancelled; installed version unchanged");Require(GetTickCount64()-start<(maximum<=8*1024*1024?15000ULL:600000ULL),"Download timeout; current version retained");DWORD received=0;Require(WinHttpReadData(request,buffer.data(),(DWORD)buffer.size(),&received)!=0,"Download interrupted; installed version unchanged");if(!received)break;Require(received<=maximum-total,"Download exceeds signed size limit");consume(buffer.data(),received);total+=received;if(progress)progress("Downloading",total,maximum);}
}
std::string Fetch(const std::string& url,std::atomic<bool>& cancel,bool fixture){std::string result;Request(url,8*1024*1024,cancel,[&](const BYTE* p,size_t n){result.append((const char*)p,n);},{},fixture);return result;}
void Download(const std::string& url,const fs::path& output,uint64_t bytes,const std::string& hash,std::atomic<bool>& cancel,Progress progress,bool fixture){Require(bytes>0&&bytes<2ULL*1024*1024*1024,"Invalid download size (maximum asset size is below 2 GiB)");CheckNoLinks(output);fs::create_directories(output.parent_path());Require(!fs::exists(output),"Download staging path already exists");std::ofstream file(output,std::ios::binary);Require(bool(file),"Cannot create download staging file");Request(url,bytes,cancel,[&](const BYTE* p,size_t n){file.write((const char*)p,n);Require(bool(file),"Storage write failed");},progress,fixture);file.close();Require(!cancel&&fs::file_size(output)==bytes&&Hash(output)==Lower(hash),"Downloaded file failed length/SHA256 verification");}
}
