#define UNICODE
#define _UNICODE
#include "core.hpp"
#include <shellapi.h>
#include <gdiplus.h>
#include <xinput.h>
#include <thread>
#include <memory>
#include <fstream>
#pragma comment(lib,"gdiplus.lib")
#pragma comment(lib,"user32.lib")
#pragma comment(lib,"gdi32.lib")
using namespace wr;
static HWND window;static std::unique_ptr<Store> store;static fs::path cover,ready,testSave,evidence;
static std::wstring status=L"Ready. Play starts shortly; any input opens update controls.",version;
static UpdateInfo update;static std::thread worker;static bool busy=false,playAfter=false,closing=false,testing=false,readySeen=false,timeoutShown=false,managed=false;
static int selected=0;static PROCESS_INFORMATION child{};static uint64_t opened=0,launched=0;static std::string nonce;
static constexpr UINT Done=WM_APP+1,ProgressMessage=WM_APP+2;
static std::vector<std::wstring> labels={L"Play current version",L"Check for updates",L"Update game and play",L"Update soundtrack",L"Restore previous version",L"Cancel download",L"Exit"};
struct Completion{std::wstring message;UpdateInfo info;bool checked=false,success=false;};
static std::wstring Quote(const std::wstring& s){std::wstring r=L"\"";size_t slash=0;for(wchar_t c:s){if(c==L'\\'){slash++;continue;}r.append(c==L'\"'?slash*2+1:slash,L'\\');slash=0;r+=c;}r.append(slash*2,L'\\');return r+L"\"";}
static void Refresh(){version=store->Installed()?Wide(store->state["game"]["manifest"]["version"].get<std::string>()):L"Not installed";InvalidateRect(window,nullptr,FALSE);}
static void Text(Gdiplus::Graphics& g,const std::wstring& s,float x,float y,float size,Gdiplus::Color color,float width,float height=80){Gdiplus::Font font(L"Segoe UI",size,0,Gdiplus::UnitPixel);Gdiplus::SolidBrush brush(color);g.DrawString(s.c_str(),-1,&font,Gdiplus::RectF(x,y,width,height),nullptr,&brush);}
static void Draw(Gdiplus::Graphics& g){g.Clear(Gdiplus::Color(255,12,23,27));if(fs::exists(cover)){Gdiplus::Bitmap art(cover.c_str());if(art.GetLastStatus()==Gdiplus::Ok){float scale=std::min(420.f/art.GetWidth(),420.f/art.GetHeight());g.DrawImage(&art,20,90,int(art.GetWidth()*scale),int(art.GetHeight()*scale));}}Text(g,L"WOODSTOCK RUSH",460,26,30,Gdiplus::Color(255,107,239,211),600);Text(g,L"Installed: "+version,460,70,18,Gdiplus::Color::White,600);
 for(int i=0;i<7;i++){Gdiplus::SolidBrush bg(i==selected?Gdiplus::Color(255,38,114,113):Gdiplus::Color(255,29,48,58));g.FillRectangle(&bg,460,115+i*51,595,43);Text(g,labels[i],476,float(120+i*51),21,Gdiplus::Color::White,560);}
 Text(g,status,460,486,17,Gdiplus::Color(255,215,223,220),595,170);Text(g,L"D-pad / arrows: choose\nA / Enter: confirm   B / Esc: cancel\nUpdates are optional. Personal music stays local.",22,530,17,Gdiplus::Color(255,174,194,199),410,110);}
static void Snapshot(){if(evidence.empty())return;fs::create_directories(evidence);Gdiplus::Bitmap b(1080,680,PixelFormat32bppARGB);Gdiplus::Graphics g(&b);Draw(g);UINT n=0,bytes=0;Gdiplus::GetImageEncodersSize(&n,&bytes);std::vector<BYTE> buffer(bytes);auto enc=(Gdiplus::ImageCodecInfo*)buffer.data();Gdiplus::GetImageEncoders(n,bytes,enc);for(UINT i=0;i<n;i++)if(wcscmp(enc[i].MimeType,L"image/png")==0){b.Save((evidence/L"launcher.png").c_str(),&enc[i].Clsid);break;}}
static void Play(){if(child.hProcess)return;if(busy){store->cancel=true;playAfter=true;status=L"Finishing the cancelled check, then starting your installed game.";return;}auto exe=store->GamePath();nonce=std::to_string(GetCurrentProcessId())+"-"+std::to_string(GetTickCount64());ready=store->root/L"startup"/(Wide(nonce)+L".ready");std::wstring command=Quote(exe.wstring())+L" -racerManagedMusic "+Quote(store->ManagedMusic().wstring())+L" -racerPersonalMusic "+Quote(store->PersonalMusic().wstring())+L" -racerLauncherReady "+Quote(ready.wstring())+L" -racerLauncherNonce "+Quote(Wide(nonce));
 if(testing){fs::create_directories(testSave);if(!fs::exists(testSave/L"settings.json"))AtomicWrite(testSave/L"settings.json",R"({"version":1,"master":0,"frameLimit":60,"vsync":false})");command+=L" -racerSkipTitle -batchmode -racerTestSave "+Quote(testSave.wstring())+L" -logFile "+Quote((evidence/L"game.log").wstring());}
 STARTUPINFOW si{sizeof(si)};if(testing){si.dwFlags=STARTF_USESHOWWINDOW;si.wShowWindow=SW_HIDE;}if(!CreateProcessW(exe.c_str(),command.data(),nullptr,nullptr,FALSE,0,nullptr,exe.parent_path().c_str(),&si,&child))throw std::runtime_error("Game launch failed; retry or restore previous version");CloseHandle(child.hThread);child.hThread=nullptr;store->SetRunning(child.dwProcessId,exe,nonce);launched=GetTickCount64();readySeen=timeoutShown=false;store->Log("Game child started; launcher remains alive");ShowWindow(window,SW_HIDE);}
static void Work(int action){if(busy||child.hProcess)return;busy=true;store->cancel=false;status=L"Working… Play current and Cancel remain available.";worker=std::thread([action]{auto result=new Completion;try{if(action==1){result->info=store->Check();result->checked=true;auto& i=result->info;result->message=i.gameAvailable?L"Game "+Wide(i.game["version"])+L" · "+std::to_wstring(i.game["package"]["bytes"].get<uint64_t>()/1024/1024)+L" MiB\n"+Wide(i.game.value("notes","")):L"No newer game available.";if(i.musicAvailable)result->message+=L"\nSoundtrack: +"+std::to_wstring(i.added)+L" / changed "+std::to_wstring(i.changed)+L" / removed "+std::to_wstring(i.removed)+L" · "+std::to_wstring(i.musicBytes/1024)+L" KiB";}else if(action==2){store->InstallGame(update.game);result->message=L"Game update installed.";}else if(action==3){store->InstallMusic(update.music);result->message=L"Soundtrack updated. Personal songs preserved.";}else if(action==4){store->Rollback();result->message=L"Previous game selected. Current saves retained; backups available.";}result->success=true;}catch(const std::exception& e){result->message=Wide(e.what());store->Log(e.what());}PostMessageW(window,Done,action,(LPARAM)result);});}
static void Confirm(){managed=true;if(selected==0)Play();else if(selected==5){store->cancel=true;playAfter=false;}else if(selected==6){if(busy){closing=true;store->cancel=true;}else if(!child.hProcess)DestroyWindow(window);}else if(selected==2){if(update.gameAvailable){playAfter=true;Work(2);}else status=L"Check for updates first; no newer game is selected.";}else if(selected==3){if(update.musicAvailable)Work(3);else status=L"Check for updates first; no newer soundtrack is selected.";}else Work(selected);InvalidateRect(window,nullptr,FALSE);}
static void Key(UINT key){managed=true;if(key==VK_UP)selected=(selected+6)%7;else if(key==VK_DOWN)selected=(selected+1)%7;else if(key==VK_RETURN||key==VK_SPACE)Confirm();else if(key==VK_ESCAPE){if(busy){store->cancel=true;playAfter=false;}else selected=0;}InvalidateRect(window,nullptr,FALSE);}
static BOOL CALLBACK CloseChild(HWND h,LPARAM pid){DWORD p;GetWindowThreadProcessId(h,&p);if(p==(DWORD)pid)PostMessageW(h,WM_CLOSE,0,0);return TRUE;}
static LRESULT CALLBACK Proc(HWND h,UINT m,WPARAM w,LPARAM l){try{switch(m){case WM_PAINT:{PAINTSTRUCT p;auto dc=BeginPaint(h,&p);Gdiplus::Graphics g(dc);Draw(g);EndPaint(h,&p);return 0;}case WM_KEYDOWN:Key((UINT)w);return 0;case WM_LBUTTONUP:{int x=LOWORD(l),y=HIWORD(l);managed=true;if(x>=460&&x<=1055&&y>=115&&y<472){selected=(y-115)/51;Confirm();}return 0;}
 case Done:{std::unique_ptr<Completion> r((Completion*)l);if(worker.joinable())worker.join();busy=false;status=r->message;if(r->checked)update=r->info;else if(r->success&&w==2)update.gameAvailable=false;else if(r->success&&w==3)update.musicAvailable=false;Refresh();if(closing)DestroyWindow(window);else if(playAfter){playAfter=false;if(w==1||r->success)Play();}return 0;}
 case ProgressMessage:{std::unique_ptr<std::wstring> text((std::wstring*)l);status=*text;InvalidateRect(h,nullptr,FALSE);return 0;}
 case WM_TIMER:{using Poll=DWORD(WINAPI*)(DWORD,XINPUT_STATE*);static HMODULE module=LoadLibraryW(L"xinput1_4.dll");static auto poll=module?(Poll)GetProcAddress(module,"XInputGetState"):nullptr;static WORD previous=0;if(poll&&!child.hProcess){XINPUT_STATE s{};if(poll(0,&s)==ERROR_SUCCESS){WORD edge=s.Gamepad.wButtons&~previous;previous=s.Gamepad.wButtons;if(edge&XINPUT_GAMEPAD_DPAD_UP)Key(VK_UP);if(edge&XINPUT_GAMEPAD_DPAD_DOWN)Key(VK_DOWN);if(edge&XINPUT_GAMEPAD_A)Key(VK_RETURN);if(edge&XINPUT_GAMEPAD_B)Key(VK_ESCAPE);}}
 if(!managed&&!child.hProcess&&!busy&&GetTickCount64()-opened>3000){managed=true;Play();}
 if(child.hProcess){if(!readySeen&&fs::exists(ready)&&Read(ready,1024)==nonce){readySeen=true;store->Log("PASS nonce startup handshake; parent still alive");if(testing)AtomicWrite(evidence/L"startup.json",json{{"ready",true},{"parentAlive",true},{"child",child.dwProcessId},{"game",Utf8(store->GamePath().wstring())},{"save",Utf8(testSave.wstring())}}.dump(2));}
 if(WaitForSingleObject(child.hProcess,0)==WAIT_OBJECT_0){DWORD code;GetExitCodeProcess(child.hProcess,&code);CloseHandle(child.hProcess);child.hProcess=nullptr;store->ClearRunning(nonce);store->Log("Child exit "+std::to_string(code));if(readySeen&&code==0){DestroyWindow(window);return 0;}status=L"Startup did not complete. Retry Play or Restore previous version. Diagnostics retained.";ShowWindow(window,SW_SHOW);managed=true;Refresh();if(testing){AtomicWrite(evidence/L"failure.txt",Utf8(status));DestroyWindow(window);}}
 else if(testing&&readySeen&&GetTickCount64()-launched>12000){EnumWindows(CloseChild,child.dwProcessId);}
 else if(!readySeen&&!timeoutShown&&GetTickCount64()-launched>90000){timeoutShown=true;status=L"Startup confirmation timed out. Close the game, then Retry or Restore previous. Diagnostics retained.";ShowWindow(window,SW_SHOW);Refresh();if(testing)EnumWindows(CloseChild,child.dwProcessId);}}
 return 0;}
 case WM_CLOSE:if(busy){closing=true;store->cancel=true;}else if(!child.hProcess)DestroyWindow(h);return 0;case WM_DESTROY:PostQuitMessage(0);return 0;}}catch(const std::exception& e){status=Wide(e.what());InvalidateRect(h,nullptr,FALSE);}return DefWindowProcW(h,m,w,l);}
int WINAPI wWinMain(HINSTANCE instance,HINSTANCE,PWSTR,int show){try{wchar_t path[32768];GetModuleFileNameW(nullptr,path,32768);fs::path root=fs::path(path).parent_path();int argc=0;auto argv=CommandLineToArgvW(GetCommandLineW(),&argc);for(int i=1;i<argc;i++){std::wstring a=argv[i];if(a==L"--manage")managed=true;else if(a==L"--startup-check")testing=managed=true;else if(i+1<argc){if(a==L"--root")root=argv[++i];else if(a==L"--test-save")testSave=argv[++i];else if(a==L"--evidence")evidence=argv[++i];}}LocalFree(argv);if(testing&&(testSave.empty()||evidence.empty()))throw std::runtime_error("Startup fixtures require isolated saves and evidence");store=std::make_unique<Store>(root,testing,testSave);if(!store->Installed())throw std::runtime_error("Extract the complete starter package before launching");cover=root/L"WoodstockRush-Cover.png";Gdiplus::GdiplusStartupInput input;ULONG_PTR token;Gdiplus::GdiplusStartup(&token,&input,nullptr);WNDCLASSW wc{};wc.hInstance=instance;wc.lpfnWndProc=Proc;wc.lpszClassName=L"WoodstockRushLauncher";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);RegisterClassW(&wc);window=CreateWindowW(wc.lpszClassName,L"Woodstock Rush",WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU|WS_MINIMIZEBOX,CW_USEDEFAULT,CW_USEDEFAULT,1096,719,nullptr,nullptr,instance,nullptr);store->progress=[](const std::string& s,uint64_t done,uint64_t total){static uint64_t last=0;auto now=GetTickCount64();if(now-last<150&&done!=total)return;last=now;PostMessageW(window,ProgressMessage,0,(LPARAM)new std::wstring(Wide(s)+L" "+std::to_wstring(done/1024)+L" / "+std::to_wstring(total/1024)+L" KiB"));};Refresh();opened=GetTickCount64();SetTimer(window,1,100,nullptr);if(testing){Snapshot();Play();}else ShowWindow(window,show);MSG msg;while(GetMessageW(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}if(worker.joinable()){store->cancel=true;worker.join();}Gdiplus::GdiplusShutdown(token);return 0;}catch(const std::exception& e){MessageBoxW(nullptr,Wide(e.what()).c_str(),L"Woodstock Rush launcher",MB_OK|MB_ICONERROR);return 1;}}
