#include "core.hpp"
#include <shlobj.h>
#include <fstream>
#include <map>
#include <set>
#include <algorithm>
namespace wr {
static void Need(bool b,const std::string& s){if(!b)throw std::runtime_error(s);}
static std::string Id(){return std::to_string(GetCurrentProcessId())+"-"+std::to_string(GetTickCount64());}
static std::string PathText(const fs::path& p){return Utf8(p.generic_wstring());}
static uint64_t Bytes(const json& m){uint64_t n=0;for(auto& f:m.at("files")){auto b=f.at("bytes").get<uint64_t>();Need(b<2ULL*1024*1024*1024&&n<100ULL*1024*1024*1024-b,"Manifest size limit exceeded");n+=b;}return n;}
static void Manifest(const json& m,const char* type){Need(m.at("schema")==1&&m.at("type")==type&&m.at("platform")=="windows-x64","Incompatible release manifest");Need(m.at("minLauncher").get<int>()<=1,"Install the newer launcher manually; Play remains available");Need(m.at("build").get<uint64_t>()>0,"Invalid build number");Need(m.at("files").is_array()&&!m.at("files").empty(),"Empty release inventory");Bytes(m);}
static void Copy(const fs::path& a,const fs::path& b){CheckNoLinks(a);CheckNoLinks(b);fs::create_directories(b.parent_path());Need(fs::copy_file(a,b,fs::copy_options::none),"Cannot copy preserved file");}
Store::Store(fs::path directory,bool fixtures,fs::path saves):fixtures_(fixtures),root(fs::absolute(directory).lexically_normal()){
 CheckNoLinks(root);fs::create_directories(root);lock_=CreateFileW((root/L"launcher.lock").c_str(),GENERIC_READ|GENERIC_WRITE,0,nullptr,OPEN_ALWAYS,FILE_ATTRIBUTE_NORMAL,nullptr);Need(lock_!=INVALID_HANDLE_VALUE,"Another launcher is already using this installation");
 try{if(fixtures){Need(!saves.empty(),"Fixture saves must be isolated");saveRoot_=fs::absolute(saves);}else{PWSTR p=nullptr;Need(SUCCEEDED(SHGetKnownFolderPath(FOLDERID_LocalAppDataLow,0,nullptr,&p)),"Cannot locate existing Unity saves");saveRoot_=fs::path(p)/L"DefaultCompany"/L"Racer";CoTaskMemFree(p);}state=fs::exists(root/L"state.json")?json::parse(Read(root/L"state.json")):json{{"schema",1}};Need(state.at("schema")==1,"Unsupported local state");Recover();fs::create_directories(PersonalMusic());}catch(...){CloseHandle(lock_);lock_=INVALID_HANDLE_VALUE;throw;}
}
Store::~Store(){if(lock_!=INVALID_HANDLE_VALUE)CloseHandle(lock_);}
void Store::Log(const std::string& s){CheckNoLinks(root/L"recovery.log");std::ofstream(root/L"recovery.log",std::ios::app)<<GetTickCount64()<<" "<<s<<"\n";}
void Store::SaveState(const json& next){AtomicWrite(root/L"state.json",next.dump(2));state=next;}
void Store::Journal(const json& record){AtomicWrite(root/L"transaction.json",record.dump(2));}
void Store::Recover(){if(fs::exists(root/L"transaction.json")){auto j=json::parse(Read(root/L"transaction.json"));if(j.value("phase","")=="prepared"){Log("Recovered interrupted activation; atomic state pointer remains authoritative. Staging preserved for diagnostics.");j["phase"]="recovered";Journal(j);}}if(state.contains("game"))Need(fs::is_regular_file(GamePath()),"Selected game is missing; inspect recovery log or reinstall starter beside existing data");}
bool Store::Installed()const{return state.contains("game");}
fs::path Store::GamePath()const{return SafePath(root,state.at("game").at("directory").get<std::string>()+"/Racer.exe");}
fs::path Store::ManagedMusic()const{return state.contains("music")?SafePath(root,state.at("music").at("directory").get<std::string>()):root/L"shared"/L"soundtracks"/L"empty";}
fs::path Store::PersonalMusic()const{return root/L"shared"/L"PersonalMusic";}
void Store::RequireIdle(){if(!state.contains("running"))return;auto r=state["running"];HANDLE p=OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION|SYNCHRONIZE,FALSE,r.at("pid").get<DWORD>());if(p){bool active=WaitForSingleObject(p,0)==WAIT_TIMEOUT;wchar_t path[32768];DWORD n=32768;bool same=QueryFullProcessImageNameW(p,0,path,&n)&&fs::equivalent(fs::path(path),fs::path(Wide(r.at("exe").get<std::string>())));CloseHandle(p);Need(!(active&&same),"Game is running; install after it exits");}else Need(GetLastError()==ERROR_INVALID_PARAMETER,"Cannot verify running game; retry when it has exited");auto next=state;next.erase("running");SaveState(next);}
void Store::SetRunning(DWORD pid,const fs::path& exe,const std::string& nonce){auto next=state;next["running"]={{"pid",pid},{"exe",PathText(fs::absolute(exe))},{"nonce",nonce}};SaveState(next);}
void Store::ClearRunning(const std::string& nonce){if(state.contains("running")&&state["running"].value("nonce","")==nonce){auto next=state;next.erase("running");SaveState(next);}}
void Store::Space(uint64_t bytes){auto available=fs::space(root).available;if(fixtures_&&state.contains("fixtureAvailableBytes"))available=state["fixtureAvailableBytes"].get<uint64_t>();Need(available>bytes+64*1024*1024,"Insufficient free storage; current installation unchanged");}
void Store::BackupSaves(const std::string& transaction){if(!fs::exists(saveRoot_))return;CheckNoLinks(saveRoot_);auto dest=SafePath(root,"save-backups/"+transaction);for(auto& e:fs::recursive_directory_iterator(saveRoot_)){CheckNoLinks(e.path());if(e.is_regular_file())Copy(e.path(),dest/fs::relative(e.path(),saveRoot_));}Log("Saved pre-update backup; never automatically restored: "+transaction);}
void Store::Prune(const json& retired){if(retired.is_null())return;try{auto relative=retired.at("directory").get<std::string>();for(auto name:{"game","previousGame","music","previousMusic"})if(state.contains(name)&&state[name]["directory"]==relative)return;Need(relative.rfind("versions/",0)==0||relative.rfind("shared/soundtracks/",0)==0,"Refusing cleanup outside version storage");auto path=SafePath(root,relative);if(!fs::exists(path))return;CheckInventory(path,retired["manifest"]["files"],true);fs::remove_all(path);Log("Retired verified older version: "+relative);}catch(const std::exception& e){Log(std::string("Retained older modified/inaccessible version: ")+e.what());}}
UpdateInfo Store::Check(const std::string& url){cancel=false;UpdateInfo result;result.catalog=Verify(Fetch(url,cancel,fixtures_));Need(result.catalog.at("type")=="catalog","Expected signed release catalog");if(result.catalog.contains("game")){result.game=Verify(Fetch(result.catalog["game"].get<std::string>(),cancel,fixtures_));Manifest(result.game,"game");auto build=result.game.at("build").get<uint64_t>();result.gameAvailable=build>(state.contains("game")?state["game"]["manifest"]["build"].get<uint64_t>():0)&&build>=state.value("highestGameBuild",uint64_t(0))&&build!=suppressedBuild;}
 if(result.catalog.contains("soundtrack")){result.music=Verify(Fetch(result.catalog["soundtrack"].get<std::string>(),cancel,fixtures_));Manifest(result.music,"soundtrack");result.musicAvailable=result.music.at("build").get<uint64_t>()>state.value("highestMusicBuild",uint64_t(0));std::map<std::string,json> old;if(state.contains("music"))for(auto& f:state["music"]["manifest"]["files"])old[f["path"].get<std::string>()]=f;for(auto& f:result.music["files"]){auto key=f["path"].get<std::string>();auto path=SafePath(ManagedMusic(),key);if(!fs::exists(path)||Hash(path)!=f["sha256"]){result.musicBytes+=f["bytes"].get<uint64_t>();if(old.count(key))result.changed++;else result.added++;}old.erase(key);}result.removed=(int)old.size();}return result;}
void Store::InstallGame(const json& m){Manifest(m,"game");RequireIdle();Need(m["build"].get<uint64_t>()>(state.contains("game")?state["game"]["manifest"]["build"].get<uint64_t>():0)&&m["build"].get<uint64_t>()>=state.value("highestGameBuild",uint64_t(0)),"Game release is not newer");cancel=false;auto id=Id(),relative="versions/"+std::to_string(m["build"].get<uint64_t>());auto target=SafePath(root,relative),stage=SafePath(root,"staging/"+id);if(fs::exists(target)){CheckInventory(target,m["files"]);BackupSaves(id);auto retired=state.value("previousGame",json());auto next=state;if(state.contains("game"))next["previousGame"]=state["game"];next["game"]={{"directory",relative},{"manifest",m}};next["highestGameBuild"]=m["build"];SaveState(next);Prune(retired);Log("Reused verified retained game version");return;}Space(m["package"]["bytes"].get<uint64_t>()+Bytes(m));fs::create_directories(stage);Download(m["package"]["url"],stage/L"game.zip",m["package"]["bytes"],m["package"]["sha256"],cancel,progress,fixtures_);Extract(stage/L"game.zip",stage/L"runtime",m["files"]);Need(fs::is_regular_file(stage/L"runtime"/L"Racer.exe"),"Release has no Racer.exe");Need(!cancel,"Cancelled before activation");RequireIdle();BackupSaves(id);auto retired=state.value("previousGame",json());auto next=state;if(state.contains("game"))next["previousGame"]=state["game"];next["game"]={{"directory",relative},{"manifest",m}};next["highestGameBuild"]=m["build"];Journal({{"phase","prepared"},{"kind","game"},{"transaction",id},{"target",relative}});fs::create_directories(target.parent_path());fs::rename(stage/L"runtime",target);SaveState(next);Journal({{"phase","complete"},{"transaction",id}});Log("Game activated "+m["version"].get<std::string>());Prune(retired);fs::remove(stage/L"game.zip");fs::remove(stage);}
void Store::InstallMusic(const json& m){Manifest(m,"soundtrack");RequireIdle();Need(m["build"].get<uint64_t>()>state.value("highestMusicBuild",uint64_t(0)),"Soundtrack release is not newer");cancel=false;auto id=Id(),relative="shared/soundtracks/"+std::to_string(m["build"].get<uint64_t>());auto target=SafePath(root,relative),stage=SafePath(root,"staging/music-"+id);Need(!fs::exists(target),"Soundtrack directory already exists; preserved for recovery");Space(Bytes(m));fs::create_directories(stage);auto oldRoot=ManagedMusic();std::map<std::string,json> owned; if(state.contains("music"))for(auto& f:state["music"]["manifest"]["files"])owned[f["path"].get<std::string>()]=f;
 // Preserve every unowned or modified old file before selecting the replacement collection.
 if(fs::exists(oldRoot))for(auto& e:fs::recursive_directory_iterator(oldRoot)){CheckNoLinks(e.path());if(!e.is_regular_file())continue;auto rel=PathText(fs::relative(e.path(),oldRoot));auto h=Hash(e.path());if(owned.count(rel)&&h==owned[rel]["sha256"])continue;auto personal=SafePath(PersonalMusic(),rel);if(fs::exists(personal)){if(Hash(personal)==h)continue;personal=personal.parent_path()/(personal.stem().wstring()+L"-preserved-"+Wide(h)+personal.extension().wstring());}if(!fs::exists(personal))Copy(e.path(),personal);Log("Preserved personal/modified track: "+rel);}
 for(auto& f:m["files"]){Need(!cancel,"Soundtrack download cancelled");auto rel=f["path"].get<std::string>();auto from=SafePath(oldRoot,rel),to=SafePath(stage,rel);if(fs::is_regular_file(from)&&fs::file_size(from)==f["bytes"].get<uint64_t>()&&Hash(from)==f["sha256"])Copy(from,to);else Download(f["url"],to,f["bytes"],f["sha256"],cancel,progress,fixtures_);}
 CheckInventory(stage,m["files"]);Need(!cancel,"Cancelled before soundtrack activation");RequireIdle();auto retired=state.value("previousMusic",json());auto next=state;if(state.contains("music"))next["previousMusic"]=state["music"];next["music"]={{"directory",relative},{"manifest",m}};next["highestMusicBuild"]=m["build"];Journal({{"phase","prepared"},{"kind","soundtrack"},{"transaction",id},{"target",relative}});fs::create_directories(target.parent_path());fs::rename(stage,target);SaveState(next);Journal({{"phase","complete"},{"transaction",id}});Log("Soundtrack activated independently of game");Prune(retired);}
void Store::Rollback(){RequireIdle();Need(state.contains("previousGame"),"No previous game version is available");auto old=state["previousGame"];CheckInventory(SafePath(root,old["directory"]),old["manifest"]["files"]);BackupSaves("rollback-"+Id());suppressedBuild=state["game"]["manifest"]["build"].get<uint64_t>();auto next=state;next["previousGame"]=state["game"];next["game"]=old;SaveState(next);Log("Previous game selected; newer save data retained unchanged");}
void Store::Seed(const fs::path& game,const json& gm,const fs::path& music,const json& mm){Need(!Installed(),"Starter installation already initialized");Manifest(gm,"game");Manifest(mm,"soundtrack");CheckInventory(game,gm["files"]);CheckInventory(music,mm["files"]);Space(Bytes(gm)+Bytes(mm));auto g="versions/"+std::to_string(gm["build"].get<uint64_t>()),m="shared/soundtracks/"+std::to_string(mm["build"].get<uint64_t>());for(auto& f:gm["files"])Copy(SafePath(game,f["path"]),SafePath(root,g+"/"+f["path"].get<std::string>()));for(auto& f:mm["files"])Copy(SafePath(music,f["path"]),SafePath(root,m+"/"+f["path"].get<std::string>()));SaveState({{"schema",1},{"game",{{"directory",g},{"manifest",gm}}},{"music",{{"directory",m},{"manifest",mm}}},{"highestGameBuild",gm["build"]},{"highestMusicBuild",mm["build"]}});Log("Complete starter game and soundtrack verified");}
}
