using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using System.Reflection;using UnityEngine;
namespace Racer {
// Explicit bounded local checks; never attached by ordinary gameplay.
public sealed class CaveRestoreAiChecks:MonoBehaviour {
 public static string Output="Docs/CaveRestore/ai";public string Only="";
 RaceDirector race;ArcadeVehicle car;readonly List<string> checks=new();int resets;
 void Check(bool ok,string message){checks.Add((ok?"PASS ":"FAIL ")+message);File.WriteAllLines(Output+"/driving-results.txt",checks);}
 public static void Launch(){new GameObject("Local reverse shortcut verification").AddComponent<CaveRestoreAiChecks>();}
 IEnumerator Start(){AudioListener.volume=0;Application.runInBackground=true;race=FindAnyObjectByType<RaceDirector>();yield return null;yield return null;
 #if UNITY_EDITOR
 race.Flow.UseValidationSave(Path.GetFullPath("Temp/CaveRestoreSave"));
 #endif
 race.Flow.OpenGarage();race.Flow.SelectVehicle("moto");race.Flow.CloseGarage();race.opponents=race.traffic=false;race.laps=1;race.Flow.StartRace();while(race.Flow.State!=RaceFlow.Stage.Racing){AudioListener.volume=0;yield return null;}car=race.vehicle;car.GetComponent<VehicleInput>().enabled=false;car.enabled=false;car.GetComponent<VehicleRespawn>().Respawned+=()=>resets++;
 foreach(string profile in new[]{"atv"})foreach(var b in race.Branches)if(b.title=="Echo Cave"){car.GetComponent<VehicleConfiguration>().Apply(profile);yield return Place(b);yield return Drive(b,"AI-"+profile,true);}
 car.Body.isKinematic=true;race.Flow.Pause();File.WriteAllLines(Output+"/driving-done.txt",checks);
 }
 IEnumerator Place(WoodlandRoute b){race.Racers[0].Branch.Clear();race.Progress.Restart();race.Progress.Cross(0,true,race.Clock);for(int i=1;i<race.gates.Length;i++)if(race.road.Project(race.gates[i].transform.position,out _)<b.entryRoad-1)race.Progress.Cross(i,true,race.Clock);var p=b.At(0,out var f);car.Body.isKinematic=false;car.Body.position=p+Vector3.up*.6f;car.Body.rotation=Quaternion.LookRotation(Vector3.ProjectOnPlane(f,Vector3.up));car.transform.SetPositionAndRotation(car.Body.position,car.Body.rotation);car.Body.linearVelocity=car.Body.angularVelocity=Vector3.zero;car.ClearSteering();Physics.SyncTransforms();for(int i=0;i<30;i++){car.Simulate(0,0,0,Time.fixedDeltaTime);yield return new WaitForFixedUpdate();}race.Racers[0].Branch.Clear();race.Progress.Restart();race.Progress.Cross(0,true,race.Clock);for(int i=1;i<race.gates.Length;i++)if(race.road.Project(race.gates[i].transform.position,out _)<b.entryRoad-1)race.Progress.Cross(i,true,race.Clock);car.Body.linearVelocity=f*22;race.ResetSampling(car.Body.position,race.Clock);if(b.title=="Echo Cave")race.Racers[0].Branch.Begin(b);}
 IEnumerator Drive(WoodlandRoute b,string profile,bool ai){var guide=b.GetComponent<ReverseShortcutGuidance>();RoadDriver pilot=null;if(ai){pilot=car.gameObject.AddComponent<RoadDriver>();pilot.Initialize(race,car,true,1,1);pilot.Racer=race.Racers[0];if(b.title=="Echo Cave")race.Racers[0].Branch.Clear();var planned=typeof(RoadDriver).GetField("plannedBranch",BindingFlags.Instance|BindingFlags.NonPublic);var choose=typeof(RoadDriver).GetMethod("DecideShortcut",BindingFlags.Instance|BindingFlags.NonPublic);for(int seed=0;seed<32&&planned.GetValue(pilot)==null;seed++){pilot.Shortcuts.Initialize(seed);choose.Invoke(pilot,new object[]{b.entryRoad-30});}Check((WoodlandRoute)planned.GetValue(pilot)==b,b.title+": existing probabilistic AI selection reaches this branch");if(planned.GetValue(pilot)==null)planned.SetValue(pilot,b);if(b.title=="Echo Cave")race.Racers[0].Branch.Begin(b);}float start=Time.time,best=0,air=0,maxAir=0,maxSide=0;bool entered=false,complete=false;int before=resets;string tag=profile+"-"+b.title.Replace(' ','-').Replace('/','-');using(var log=new StreamWriter(Output+"/"+tag+".csv")){log.WriteLine("time,s,lateral,x,y,z,speed,wheels,target,obstacle,resets");while(Time.time-start<75){AudioListener.volume=0;float s=b.Project(car.Body.position,out float lateral);best=Mathf.Max(best,s);maxSide=Mathf.Max(maxSide,lateral);if(s>(b.Length-4)&&lateral<7&&car.GroundedWheels>=2){complete=true;break;}if(resets>before)break;if(!ai){float look=guide.lookAhead;var target=guide.Target(b,car.Body.position,s,look);var delta=Quaternion.Inverse(Quaternion.LookRotation(Vector3.ProjectOnPlane(car.transform.forward,Vector3.up)))*(target-car.Body.position);float angle=Mathf.Atan2(delta.x,delta.z);float speed=car.ForwardSpeed;float steer=Mathf.Clamp(Mathf.Atan(2*car.wheelbase*Mathf.Sin(angle)/look)/(Mathf.Lerp(car.slowSteerAngle,car.fastSteerAngle,Mathf.Clamp01(speed/car.topSpeed))*Mathf.Deg2Rad),-1,1);float desired=b.SpeedAt(s);for(float ahead=0;ahead<50;ahead+=6){b.At(s+ahead,out var f0);b.At(s+ahead+6,out var f1);float curve=Vector3.Angle(Vector3.ProjectOnPlane(f0,Vector3.up),Vector3.ProjectOnPlane(f1,Vector3.up))*Mathf.Deg2Rad/6;float safe=Mathf.Sqrt(car.maxGripAcceleration*.65f/Mathf.Max(.0001f,curve));desired=Mathf.Min(desired,Mathf.Sqrt(safe*safe+2*car.braking*.8f*Mathf.Max(0,ahead-8)));}car.Simulate(speed<desired?1:0,speed>desired+.5f?Mathf.Clamp01((speed-desired)*.3f):0,steer,Time.fixedDeltaTime);}yield return new WaitForFixedUpdate();entered|=race.Racers[0].Branch.Route==b;if(car.GroundedWheels==0){air+=Time.fixedDeltaTime;maxAir=Mathf.Max(maxAir,air);}else air=0;var p=car.Body.position;log.WriteLine($"{Time.time-start:F2},{s:F2},{lateral:F2},{p.x:F3},{p.y:F3},{p.z:F3},{car.ForwardSpeed:F2},{car.GroundedWheels},{(pilot?pilot.TargetSpeed:0):F2},{(pilot?pilot.LastObstacle:"")},{resets-before}");}}
 Check(complete&&entered&&resets==before&&(!pilot||pilot.RecoveryCount==0),$"{tag}: entered={entered}; completed={complete}; station={best:F1}/{b.Length:F1}; air={maxAir:F2}s; lateralMax={maxSide:F2}; resets={resets-before}; AI recoveries={(pilot?pilot.RecoveryCount:0)}");var rats=FindAnyObjectByType<UndergroundLife>();if(b.title.StartsWith("Storm")&&rats)Check(rats.Encounters>0&&rats.Sounds>0,"Rat encounter and localized audio triggered; encounters="+rats.Encounters+" sounds="+rats.Sounds);if(pilot){pilot.enabled=false;Destroy(pilot);yield return null;}}
 }
}


