using System;
using System.IO;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
namespace Racer
{
    // Explicit isolated CR105–111 checks. No ordinary-player execution or ghost assertions.
    public sealed class CR105Validation:MonoBehaviour
    {
        static string Arg(string key,string fallback=""){var a=Environment.GetCommandLineArgs();int i=Array.IndexOf(a,key);return i>=0&&i+1<a.Length?a[i+1]:fallback;}
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)] static void Boot(){if(Arg("-cr105Check")==""||Arg("-racerTestSave")==""||FindAnyObjectByType<CR105Validation>())return;var g=new GameObject("CR105 isolated targeted validation");DontDestroyOnLoad(g);g.AddComponent<CR105Validation>();}
        string dir;RaceDirector race;RaceFlow flow;ArcadeVehicle car;readonly List<string> checks=new();
        void Check(bool pass,string name){checks.Add((pass?"PASS ":"FAIL ")+name);File.WriteAllLines(dir+"/checks.txt",checks);}
        void Bind(){race=FindAnyObjectByType<RaceDirector>();flow=race.Flow;car=race.vehicle;}
        IEnumerator Load(string scene){if(UnityEngine.SceneManagement.SceneManager.GetActiveScene().name!=scene)UnityEngine.SceneManagement.SceneManager.LoadScene(scene);yield return null;yield return null;Bind();}
        IEnumerator Start(){Application.runInBackground=true;dir=Arg("-evidence");Directory.CreateDirectory(dir);yield return Load(Arg("-course","StreetLoopGreybox"));string mode=Arg("-cr105Check");
            if(mode=="local"){yield return Features();yield return Views();yield return Traffic();yield return Turkeys();}
            else if(mode=="final-local"){yield return Views();yield return Turkeys();}else if(mode=="features")yield return Features();else if(mode=="views")yield return Views();else if(mode=="playlist")yield return Playlist();else if(mode=="race"||mode=="unlimited")yield return RaceRun(mode=="unlimited"?0:int.Parse(Arg("-laps","1")),Arg("-vehicle","atv"),false);else if(mode=="traffic")yield return Traffic();else if(mode=="turkey")yield return Turkeys();else if(mode=="startup"){Check(flow.State==RaceFlow.Stage.Ready,"Portable menu startup");ThreeFeatureValidation.CaptureUi(dir+"/startup.png");}
            if(mode=="final-local")yield return CompatibleRoster();
            if(mode=="reverse-playlist")yield return ReversePlaylistRetest();
            if(mode=="moved-gate")yield return MovedGate();
            File.WriteAllText(dir+"/done.txt","Targeted checks complete. Read checks.txt for failures. Normal motor-input automation; no physical controller or subjective acceptance.");Application.Quit();}
        IEnumerator CompatibleRoster(){race.opponents=true;flow.Save.Settings.opponents=true;flow.Save.Settings.vehicleId="original";flow.Save.Settings.opponentRoster=new[]{"original","moto","atv"};var d=new RacePlaylists.Definition{name="Compatibility choice",entries=new(){new(){course=4,laps=1}}};flow.Playlists.Definitions.Add(d);flow.Playlists.Save();flow.StartPlaylist(d);Check(flow.State==RaceFlow.Stage.PlaylistVehicle&&flow.Save.Settings.vehicleId=="original"&&flow.Save.Settings.opponentRoster[0]=="original","Incompatible player and roster unchanged before explicit choice");ThreeFeatureValidation.CaptureUi(dir+"/compatible-roster-choice.png");flow.ChoosePlaylistVehicle("atv");yield return null;yield return null;Bind();Check(car.GetComponent<VehicleConfiguration>().profileId=="atv"&&race.opponentRoster.SequenceEqual(new[]{"atv","moto","atv"}),"Explicit compatible choice changes only incompatible roster entries");flow.CancelPlaylist();Check(flow.State==RaceFlow.Stage.Ready&&RacePlaylists.Active==null,"Cancel compatibility playlist returns driving setup");}
        IEnumerator ReversePlaylistRetest(){flow.Save.Settings.opponents=true;flow.Save.Settings.traffic=false;flow.Save.Settings.vehicleId="moto";flow.Save.Settings.opponentRoster=new[]{"moto","atv","moto"};flow.Save.SaveSettings();var d=new RacePlaylists.Definition{name="Mountain review trio",entries=new(){new(){course=4,laps=1},new(){course=5,laps=1},new(){course=4,laps=5}}};flow.Playlists.Definitions.Add(d);flow.Playlists.Save();RacePlaylists.Begin(d);RacePlaylists.Advance();RacePlaylists.PendingStart=true;yield return Load("MountainLoopReverse");yield return RaceRun(1,"moto",true);Check(flow.State==RaceFlow.Stage.Results&&RacePlaylists.Position==1,"Corrected reverse entry reaches playlist results");flow.NextPlaylistRace();yield return null;yield return null;Bind();Check(RacePlaylists.Position==2&&race.laps==5,"Next from corrected reverse results loads final 5-lap entry");flow.CancelPlaylist();Check(RacePlaylists.Active==null&&new RacePlaylists(flow.Save.DirectoryPath).Definitions.Any(p=>p.name==d.name),"Quit after next preserves playlist definition");}
        IEnumerator MovedGate(){race.opponents=race.traffic=false;race.laps=1;car.GetComponent<VehicleConfiguration>().Apply("moto");flow.StartRace();while(flow.State==RaceFlow.Stage.Countdown)yield return null;var pilot=car.gameObject.AddComponent<RoadDriver>();pilot.Initialize(race,car,true,1,1);pilot.Racer=race.Racers[0];car.GetComponent<VehicleInput>().enabled=false;pilot.Place(900,0);race.Progress.Cross(0,true,race.Clock);for(int i=1;i<race.gates.Length-1;i++)race.Progress.Cross(i,true,race.Clock);float until=Time.time+15;while(race.Progress.NextGate>0&&Time.time<until)yield return new WaitForFixedUpdate();Check(race.Progress.NextGate==0&&race.Progress.MissedGates==0,"Local moved downhill checkpoint accepted under normal input; prior gates are fixture setup");ThreeFeatureValidation.CaptureUi(dir+"/moved-gate.png");}
        IEnumerator Features()
        {
            race.opponents=true;race.laps=1;for(int i=0;i<5;i++){Check(race.laps==i+1,"AI selector "+(i+1));flow.CycleLaps();}Check(race.laps==1,"AI wraps to 1");flow.ToggleOpponents();race.laps=5;flow.CycleLaps();Check(race.laps==0,"Solo enables Unlimited");flow.Save.Settings.lastFiniteLaps=5;flow.ToggleOpponents();Check(race.laps==5,"Enabling AI restores remembered 5");flow.ToggleOpponents();flow.CycleLaps();var reload=new RacerSave(flow.Save.DirectoryPath,race.Category);Check(reload.Settings.laps==0&&reload.Settings.lastFiniteLaps==5,"Unlimited preference and last finite reload");
            flow.OpenPlaylists();var library=flow.Playlists.Definitions;library.Add(new RacePlaylists.Definition{name="Targeted trio"});var d=library[^1];d.entries.Add(new(){course=4,laps=1});d.entries.Add(new(){course=5,laps=5});d.entries.Add(new(){course=4,laps=2});var entry=d.entries[2];d.entries.RemoveAt(2);d.entries.Insert(0,entry);d.entries.RemoveAt(0);d.entries.Add(new(){course=4,laps=2});Check(flow.Playlists.Save(),"Save edited three-entry playlist");var saved=new RacePlaylists(flow.Save.DirectoryPath);Check(saved.Definitions.Last().entries.Select(e=>e.laps).SequenceEqual(new[]{1,5,2}),"Playlist order/laps definition reload");Check(RacePlaylists.Scenes.Distinct().Count()==6&&RacePlaylists.Scenes[4]=="MountainLoop"&&RacePlaylists.Scenes[5]=="MountainLoopReverse","Six selector identities including mountain directions");
            flow.Save.Settings.vehicleId="original";flow.StartPlaylist(d);Check(flow.State==RaceFlow.Stage.PlaylistVehicle&&flow.Save.Settings.vehicleId=="original","Incompatible playlist vehicle requests explicit choice");ThreeFeatureValidation.CaptureUi(dir+"/compatible-choice.png");flow.CancelPlaylist();Check(RacePlaylists.Active==null&&flow.Playlists.Definitions.Contains(d),"Quit retains definition");
            flow.StartFreeRoam();var map=race.GetComponent<ExplorationMap>();int index=Array.FindIndex(map.destinations,x=>x.id=="summit-homeward");map.Reveal(map.destinations[index].position);map.Open();var before=car.Body.position;map.RequestTravel(index);Check(map.Confirming&&Vector3.Distance(before,car.Body.position)<.001f,"Named confirmation before any travel");ThreeFeatureValidation.CaptureUi(dir+"/travel-question.png");map.CancelTravel();Check(map.Opened&&!map.Confirming&&Vector3.Distance(before,car.Body.position)<.001f,"No leaves map/player unchanged");map.RequestTravel(index);bool traveled=map.ConfirmTravel();Check(traveled&&!map.Opened&&!map.Confirming&&flow.State==RaceFlow.Stage.Racing&&flow.Notice=="Arrived at "+map.destinations[index].title,"Yes arrives, closes overlays and resumes driving");var after=car.Body.position;Check(!map.ConfirmTravel()&&Vector3.Distance(after,car.Body.position)<.001f,"Confirmation consumed / no second teleport");yield return null;map.Open();map.RequestTravel(index);race.FreeRoam=false;Check(!map.ConfirmTravel()&&map.Opened&&map.TravelMessage.Contains("free roam"),"Unavailable at confirmation remains in map with reason");race.FreeRoam=true;map.Close();flow.Pause();flow.QuitRace();
            Check(RecordBoards.LapCategory("mountain-forward-v1-moto-solo-clear-laps1")==RecordBoards.LapCategory("mountain-forward-v1-moto-solo-clear-laps5"),"Lap category retained across finite counts");Check("mountain-forward-v1-moto-solo-clear-laps1"!="mountain-forward-v1-moto-solo-clear-laps5","Finite total categories separate");
        }
        IEnumerator RaceRun(int laps,string vehicle,bool alreadyStarted)
        {
            if(!alreadyStarted){race.opponents=false;race.traffic=false;race.laps=laps;car.GetComponent<VehicleConfiguration>().Apply(vehicle);flow.StartRace();}
            while(flow.State==RaceFlow.Stage.Countdown)yield return null;
            var pilot=car.gameObject.AddComponent<RoadDriver>();pilot.Initialize(race,car,true,1,1);pilot.Racer=race.Racers[0];car.GetComponent<VehicleInput>().enabled=false;
            // The narrow ridge alternate is exercised by the reference driver on each new direction.
            var ridge=race.Branches.FirstOrDefault(b=>b.title.Contains("Ridge Cut"));if(ridge)ridge.aiValidated=true;
            float begin=Time.time;bool branchSeen=false;int target=laps==0?6:laps;using(var log=new StreamWriter(dir+"/"+race.gameObject.scene.name+"-"+vehicle+"-laps"+laps+".csv")){
                log.WriteLine("time,x,y,z,speed,throttle,brake,lap,next,branch,recoveries");float next=0;while(!race.ClassificationFinal&&race.Progress.CompletedLaps<target&&Time.time-begin<Mathf.Max(240,target*220)){
                    yield return new WaitForFixedUpdate();branchSeen|=race.Racers[0].Branch.Route==ridge&&ridge;if(Time.time>next){next=Time.time+.2f;var p=car.Body.position;log.WriteLine($"{Time.time-begin},{p.x},{p.y},{p.z},{car.ForwardSpeed},{pilot.LastThrottle},{pilot.LastBrake},{race.Progress.CompletedLaps},{race.Progress.NextGate},{race.Racers[0].Branch.Route?.title},{pilot.RecoveryCount}");}}
            }
            Check(race.Progress.CompletedLaps==target,$"Normal-input {race.courseName} {vehicle} completed {target} laps; actual={race.Progress.CompletedLaps} misses={race.Progress.MissedGates} recovery={pilot.RecoveryCount}");Check(branchSeen,"Narrow ridge alternate exercised "+race.courseName);File.WriteAllLines(dir+"/"+race.gameObject.scene.name+"-"+vehicle+"-penalties.txt",race.Progress.Penalties);
            if(laps==0){Check(!race.Progress.Finished&&!race.ClassificationFinal&&flow.Save.Best.race==0,"Unlimited beyond five laps has no race finish or total record");flow.Pause();flow.QuitRace();Check(flow.State==RaceFlow.Stage.Ready,"Unlimited exit to menu");}
            else{float end=Time.realtimeSinceStartup+100;while(!race.ClassificationFinal&&Time.realtimeSinceStartup<end)yield return null;Check(race.Progress.Finished&&race.Category.EndsWith("laps"+laps),"Finite finish/category "+laps);if(race.opponents)Check(race.Racers.Skip(1).All(r=>r.Progress.Finished),"New direction AI finishes "+race.courseName);}
            if(pilot){pilot.enabled=false;Destroy(pilot);}ThreeFeatureValidation.CaptureUi(dir+"/"+race.gameObject.scene.name+"-"+vehicle+"-result.png");
        }
        IEnumerator Playlist()
        {
            race.opponents=true;race.traffic=false;flow.Save.Settings.opponents=true;flow.Save.Settings.traffic=false;flow.Save.Settings.vehicleId="moto";flow.Save.Settings.difficulty=1;flow.Save.Settings.opponentRoster=new[]{"moto","atv","moto"};flow.Save.SaveSettings();
            var d=new RacePlaylists.Definition{name="Mountain review trio",entries=new(){new(){course=4,laps=1},new(){course=5,laps=1},new(){course=4,laps=5}}};flow.Playlists.Definitions.Add(d);flow.Playlists.Save();flow.StartPlaylist(d);yield return null;yield return null;Bind();
            flow.StartRace();Check(RacePlaylists.Position==0&&race.laps==1,"Playlist restart repeats current entry");yield return RaceRun(1,"moto",true);
            flow.NextPlaylistRace();yield return null;yield return null;Bind();Check(RacePlaylists.Position==1&&race.reverseCourse,"Next event loads reverse at position 2/3");yield return RaceRun(1,"moto",true);
            flow.Save.Settings.vehicleId="atv";flow.NextPlaylistRace();yield return null;yield return null;Bind();yield return RaceRun(5,"atv",true);Check(!RacePlaylists.HasNext&&RacePlaylists.Position==2,"Last event completes playlist");flow.QuitRace();Check(RacePlaylists.Active==null&&new RacePlaylists(flow.Save.DirectoryPath).Definitions.Any(p=>p.name==d.name),"Playlist quit and saved definition reload");
        }
        void Shot(string name,Vector3 p,Vector3 target){var camera=Camera.main;var op=camera.transform.position;var oq=camera.transform.rotation;camera.transform.SetPositionAndRotation(p,Quaternion.LookRotation(target-p));ThreeFeatureValidation.CaptureUi(dir+"/"+name+".png");camera.transform.SetPositionAndRotation(op,oq);}
        IEnumerator Views(){flow.StartFreeRoam();yield return null;foreach(var mailbox in FindObjectsByType<Transform>().Where(t=>t.name.StartsWith("Mailbox -")&&!t.name.Contains("Friend")&&(Arg("-mailbox")==""||t.name.Contains(Arg("-mailbox"))))){Shot(mailbox.name,mailbox.position+Vector3.up*10+mailbox.forward*15,mailbox.position+Vector3.up);yield return null;}flow.OpenPlaylists();ThreeFeatureValidation.CaptureUi(dir+"/playlist-editor.png");}
        IEnumerator Traffic(){race.traffic=true;flow.StartFreeRoam();var driver=race.Drivers.First(d=>d.HighwayTraffic&&d.Direction>0);var p=race.throughRoad.At(race.throughRoad.Project(new Vector3(290,8,561),out _)-75,out _);driver.Place(race.throughRoad.Project(p,out _),6.15f);float start=Time.time;while(Time.time-start<18)yield return new WaitForFixedUpdate();Check(driver.transform.position.x>400&&driver.transform.position.z>545,"Highway eastbound passes Cherokee junction straight");foreach(var b in FindObjectsByType<CircuitBoundary>()){Check(!b.GetComponentsInChildren<Collider>().Any(c=>c.name.Contains("Closure")||c.name=="Solid race closure"),"No road closure collision "+b.name);Check(!b.Outside(b.transform.TransformPoint(new Vector3(0,0,30))),"Continuation point open "+b.name);}ThreeFeatureValidation.CaptureUi(dir+"/junction.png");flow.Pause();}
        IEnumerator Turkeys(){race.traffic=false;flow.StartFreeRoam();var wildlife=race.GetComponent<Wildlife>();var sites=wildlife.habitats.Where(h=>h.species==Wildlife.Species.Turkey).ToArray();if(Arg("-idleOnly")!="yes")Check(sites.Length==3,"Three Kyle woodland turkey habitats");var animals=wildlife.GetComponentsInChildren<Transform>(true).Where(t=>t.name=="Wildlife Turkey").ToArray();var chaseView=FindAnyObjectByType<ChaseCamera>();if(chaseView)chaseView.enabled=false;Camera.main.transform.SetPositionAndRotation(sites[1].position+Vector3.up*10,Quaternion.LookRotation(Vector3.up));bool present=false,absent=false;for(int seed=1;seed<=25&&(!present||!absent);seed++){AmbientLife.ForcedSeed=seed;wildlife.SelectPopulation();yield return new WaitForSeconds(.04f);int count=animals.Count(t=>t.gameObject.activeSelf);present|=count>0;absent|=count==0;}AmbientLife.ForcedSeed=0;if(Arg("-idleOnly")!="yes")Check(present&&absent,"Occasional present and absent turkey states");for(int seed=1;seed<=25;seed++){AmbientLife.ForcedSeed=seed;wildlife.SelectPopulation();yield return new WaitForSeconds(.08f);if(animals.Any(t=>t.gameObject.activeSelf))break;}AmbientLife.ForcedSeed=0;car.Body.position=sites[1].position+Vector3.up+new Vector3(0,0,25);car.Body.linearVelocity=Vector3.zero;var before=animals.Select(t=>t.position).ToArray();float until=Time.time+22;while(Time.time<until&&!animals.Where((t,i)=>Vector3.Distance(t.position,before[i])>.05f).Any())yield return null;Check(animals.Where((t,i)=>Vector3.Distance(t.position,before[i])>.05f).Any(),"Turkey idle walk movement over one idle cycle");if(Arg("-idleOnly")=="yes"){Shot("turkeys-idle",sites[1].position+new Vector3(5,3,6),sites[1].position+Vector3.up*.7f);yield break;}before=animals.Select(t=>t.position).ToArray();car.Body.position=sites[1].position+Vector3.up+new Vector3(0,0,6);car.Body.linearVelocity=Vector3.right*4;yield return new WaitForSeconds(1);Check(animals.Where((t,i)=>Vector3.Distance(t.position,before[i])>2).Any(),"Turkey startle escape movement");Shot("turkeys",sites[1].position+new Vector3(5,3,6),sites[1].position+Vector3.up*.7f);Check(animals.All(t=>t.GetComponentsInChildren<Collider>().Length==0),"Turkeys are nonblocking");
            if(Arg("-turkeyAudible")=="yes"){
                var sources=FindObjectsByType<AudioSource>();var muted=sources.Select(s=>s.mute).ToArray();foreach(var source in sources)source.mute=source!=wildlife.Voice;wildlife.enabled=false;var camera=Camera.main;var chase=FindAnyObjectByType<ChaseCamera>();if(chase)chase.enabled=false;camera.transform.position=sites[1].position+Vector3.up*2;wildlife.Voice.transform.position=sites[1].position;wildlife.Voice.volume=.6f*flow.Save.Settings.ambience;wildlife.Voice.clip=TurkeyVoice.Create();wildlife.Voice.Play();TestAudioMute.BriefAudibleCheck(1.2f);yield return new WaitForSecondsRealtime(1.3f);wildlife.Voice.Stop();TestAudioMute.BriefAudibleCheck(0);yield return null;Check(AudioListener.volume==0,"Brief turkey audio check automatically remuted");for(int i=0;i<sources.Length;i++)if(sources[i])sources[i].mute=muted[i];
            }yield return new WaitForSeconds(.3f);}
    }
}
