using System;
using System.IO;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
namespace Racer
{
    // Explicit, isolated CR101–104 checks. Never runs in ordinary play.
    public sealed class CR110Validation : MonoBehaviour
    {
        static string Arg(string k,string fallback=""){var a=Environment.GetCommandLineArgs();int i=Array.IndexOf(a,k);return i>=0&&i+1<a.Length?a[i+1]:fallback;}
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)] static void Boot(){if(Arg("-cr110Check")==""||Arg("-racerTestSave")=="")return;var g=new GameObject("CR110 targeted checks");DontDestroyOnLoad(g);g.AddComponent<CR110Validation>();}
        string dir;RaceDirector race;ArcadeVehicle car;RaceFlow flow;readonly List<string> checks=new();
        void Check(bool pass,string message){checks.Add((pass?"PASS ":"FAIL ")+message);File.WriteAllLines(dir+"/checks.txt",checks);}
        static float Ground(Vector3 p){var h=Physics.RaycastAll(new(p.x,400,p.z),Vector3.down,800).Where(h=>h.collider.name.StartsWith("Ground_")).OrderBy(h=>h.distance).ToArray();return h.Length>0?h[0].point.y:-999;}
        void Place(Vector3 p,Vector3 f){p.y=Ground(p)+car.suspensionLength-.12f;car.Body.position=p;car.Body.rotation=Quaternion.LookRotation(Vector3.ProjectOnPlane(f,Vector3.up));car.transform.SetPositionAndRotation(p,car.Body.rotation);car.Body.linearVelocity=car.Body.angularVelocity=Vector3.zero;car.ClearSteering();Physics.SyncTransforms();race.ResetSampling(p,Time.timeAsDouble);FindAnyObjectByType<ChaseCamera>()?.Snap();}
        IEnumerator Start(){Application.runInBackground=true;dir=Arg("-evidence");Directory.CreateDirectory(dir);if(Arg("-course")!=""&&UnityEngine.SceneManagement.SceneManager.GetActiveScene().name!=Arg("-course"))UnityEngine.SceneManagement.SceneManager.LoadScene(Arg("-course"));yield return null;yield return null;race=FindAnyObjectByType<RaceDirector>();flow=race.Flow;car=race.vehicle;race.opponents=race.traffic=false;if(Arg("-cr110Check")=="startup"){Check(flow.State==RaceFlow.Stage.Ready&&Resources.Load<AudioClip>("Title/Voice")!=null,"Extracted package loads menu and embedded speech");ThreeFeatureValidation.CaptureUi(dir+"/startup.png");File.WriteAllText(dir+"/done.txt","Single extracted-package startup check");Application.Quit();yield break;}flow.StartFreeRoam();car.enabled=false;car.GetComponent<VehicleInput>().enabled=false;
            if(Arg("-cr110Check")=="baseline"){car.GetComponent<VehicleConfiguration>().Apply("moto");var points=GameObject.Find("Summit approach and safe return").GetComponent<RaceRoad>().points.Take(5).ToArray();yield return Drive(points,"baseline-motorcycle-natural-approach",12,70);}
            else if(Arg("-cr110Check")=="flight")yield return Flights();
            else if(Arg("-cr110Check")=="branches")yield return MountainBranches();
            else if(Arg("-cr110Check")=="local-drive")yield return LocalDrive();
            File.WriteAllText(dir+"/done.txt","Targeted checks finished; read failures. Automated normal motor inputs; no physical controller or human validation.");Application.Quit();}
        IEnumerator Drive(Vector3[] points,string id,float desired,float limit){Place(points[0],points[1]-points[0]);int target=1;float start=Time.time,minUp=1;using(var w=new StreamWriter(dir+"/"+id+".csv")){w.WriteLine("time,x,y,z,speed,wheels,target,throttle,brake,steer");while(Time.time-start<limit&&target<points.Length){var local=car.transform.InverseTransformPoint(points[target]);float steer=Mathf.Clamp(Mathf.Atan2(local.x,local.z)*2,-1,1),throttle=Mathf.Clamp01((desired-car.ForwardSpeed)*.7f),brake=car.ForwardSpeed>desired+1?.3f:0;car.Simulate(throttle,brake,steer,Time.fixedDeltaTime);yield return new WaitForFixedUpdate();var p=car.Body.position;minUp=Mathf.Min(minUp,car.transform.up.y);w.WriteLine($"{Time.time-start},{p.x},{p.y},{p.z},{car.ForwardSpeed},{car.GroundedWheels},{target},{throttle},{brake},{steer}");if(Vector3.ProjectOnPlane(p-points[target],Vector3.up).magnitude<5)target++;} }
            ThreeFeatureValidation.CaptureUi(dir+"/"+id+".png");Check(target==points.Length&&minUp>.65f,id+" reached="+target+"/"+points.Length+" minUp="+minUp);}
        IEnumerator Flights(){var root=GameObject.Find(Arg("-launchRoot","CR094 summit launch")).transform;float lip=float.Parse(Arg("-lip","220"));var home=GameObject.Find("Dan - blue X").transform.position;File.WriteAllText(dir+"/flights.csv","vehicle,line,startX,startY,startZ,runup,launchX,launchY,launchZ,speed,landingX,landingY,landingZ,minClearance,air,headingDot,minUp\n");
            foreach(var profile in race.EligibleVehicles.Where(p=>Arg("-vehicle")==""||Arg("-vehicle")==p.Id))foreach(float line in Arg("-line")!=""?new[]{float.Parse(Arg("-line"))}:Arg("-center")=="yes"?new[]{0f}:new[]{0f,3f}){car.GetComponent<VehicleConfiguration>().Apply(profile.Id);Place(root.TransformPoint(new Vector3(line,0,5)),root.forward);var start=car.Body.position;flow.Activities.NewSession();int awardsBefore=flow.Activities.Awards;string id=profile.Id+"-"+line;float began=Time.time,air=0,minClear=999,minUp=1,minSurfaceUp=1;bool launched=false,landed=false,touchedMountain=false;Vector3 launch=default,landing=default;float speed=0,landedAt=0;int stable=0;
                using(var w=new StreamWriter(dir+"/"+id+".csv")){w.WriteLine("time,x,y,z,vx,vy,vz,speed,wheels,up,s,clearance,throttle,brake,steer");while(Time.time-began<40){var local=root.InverseTransformPoint(car.Body.position);float yaw=Vector3.SignedAngle(Vector3.ProjectOnPlane(car.transform.forward,Vector3.up),root.forward,Vector3.up);float steer=Mathf.Clamp(yaw*.045f+(line-local.x)*.1f,-.35f,.35f);float throttle=landed?Mathf.Clamp01((10-car.ForwardSpeed)*.6f):1,brake=landed&&car.ForwardSpeed>12?.5f:0;if(landed&&Arg("-settleBrake")=="yes"&&Time.time-landedAt<.8f){throttle=.25f;brake=0;}car.Simulate(throttle,brake,steer,Time.fixedDeltaTime);yield return new WaitForFixedUpdate();var p=car.Body.position;local=root.InverseTransformPoint(p);var v=car.Body.linearVelocity;minUp=Mathf.Min(minUp,car.transform.up.y);if(car.GroundedWheels>=2){Vector3 supportNormal=Vector3.zero;int supports=0;foreach(var wheel in car.suspensionPoints)if(Physics.Raycast(car.transform.TransformPoint(wheel),-car.transform.up,out var support,car.suspensionLength,car.groundMask,QueryTriggerInteraction.Ignore)&&Vector3.Dot(support.normal,Vector3.up)>.35f){supportNormal+=support.normal;supports++;}if(supports>=2&&(!landed||Time.time-landedAt>=.5f)){float alignment=Vector3.Dot(car.transform.up,supportNormal.normalized);if(alignment<minSurfaceUp){minSurfaceUp=alignment;File.AppendAllText(dir+"/"+id+"-alignment.txt",$"time={Time.time-began} station={local.z} supports={supports} aligned={alignment} landed={landed} normal={supportNormal.normalized} up={car.transform.up}\n");}}}float clearance=999;var bounds=car.GetComponent<Collider>().bounds;foreach(float x in new[]{bounds.min.x,bounds.center.x,bounds.max.x})foreach(float z in new[]{bounds.min.z,bounds.center.z,bounds.max.z})clearance=Mathf.Min(clearance,bounds.min.y-Ground(new(x,0,z)));
                    if(launched&&local.z>lip+5&&local.z<330&&(car.GroundedWheels>=2||clearance<=0))touchedMountain=true;
                    if(!launched&&local.z>lip-2&&car.GroundedWheels<2){launched=true;launch=p;speed=v.magnitude;ThreeFeatureValidation.CaptureUi(dir+"/"+id+"-chase.png");}
                    if(launched&&!landed){air+=Time.fixedDeltaTime;if(air>2&&air<2+Time.fixedDeltaTime*1.1f)Shot(id+"-side",p+root.right*75+Vector3.up*25,p);if(local.z>lip+5&&car.GroundedWheels<2&&clearance>.15f)minClear=Mathf.Min(minClear,clearance);if(air>1&&(car.GroundedWheels>=2||clearance<=.15f)){landed=true;landedAt=Time.time;landing=p;ThreeFeatureValidation.CaptureUi(dir+"/"+id+"-landing.png");}}
                    w.WriteLine($"{Time.time-began},{p.x},{p.y},{p.z},{v.x},{v.y},{v.z},{car.ForwardSpeed},{car.GroundedWheels},{car.transform.up.y},{local.z},{clearance},{throttle},{brake},{steer}");if(landed&&car.GroundedWheels>=2&&car.transform.up.y>.7f)stable++;else stable=0;if(stable>65)break;if(Mathf.Abs(local.x)>35)break;}}
                float heading=Vector3.Dot(Vector3.ProjectOnPlane(landing-launch,Vector3.up).normalized,Vector3.ProjectOnPlane(home-launch,Vector3.up).normalized);File.AppendAllText(dir+"/flights.csv",$"{profile.Id},{line},{start.x},{start.y},{start.z},{lip-5},{launch.x},{launch.y},{launch.z},{speed},{landing.x},{landing.y},{landing.z},{minClear},{air},{heading},{minUp}\n");File.AppendAllText(dir+"/local-jump-results.txt",id+" awards="+flow.Activities.Awards+" diagnostic="+flow.Activities.LastJumpDiagnostic+Environment.NewLine);if(Arg("-score")=="yes")Check(flow.Activities.Awards>awardsBefore,id+" settled summit landing awarded");Check(launched&&landed&&!touchedMountain&&stable>65&&minClear>0&&root.InverseTransformPoint(landing).z>=330&&Vector3.Dot(Vector3.ProjectOnPlane(landing-launch,Vector3.up).normalized,root.forward)>.99f&&minUp>.35f&&minSurfaceUp>.8f,id+" supported from rest, terrain clearance, directional landing; clearance="+minClear+" air="+air+" stable="+stable+" worldUp="+minUp+" surfaceUp="+minSurfaceUp);}
        }
        IEnumerator MountainBranches(){var root=GameObject.Find(Arg("-launchRoot","CR094 summit launch")).transform;var branch=race.Branches.Single(b=>b.title.Contains("Flight"));var points=branch.points;int start=Enumerable.Range(0,points.Length).OrderBy(i=>Vector3.Distance(points[i],root.position)).First();int end=Enumerable.Range(0,points.Length).Where(i=>root.InverseTransformPoint(points[i]).z>=440).OrderBy(i=>Mathf.Abs(root.InverseTransformPoint(points[i]).z-445)).First();foreach(var profile in race.EligibleVehicles){car.GetComponent<VehicleConfiguration>().Apply(profile.Id);yield return Drive(points.Take(start+1).ToArray(),profile.Id+"-summit-entry",7,180);yield return Drive(points.Skip(end).ToArray(),profile.Id+"-summit-return",7,180);}Place(root.TransformPoint(new Vector3(2,0,45)),root.forward);bool recovered=car.GetComponent<VehicleRespawn>().TryRecoverLocal();yield return new WaitForFixedUpdate();Check(recovered&&Mathf.Abs(car.Body.position.y-Ground(car.Body.position))<3,"One supported local recovery in "+race.courseName);}
        void Shot(string name,Vector3 position,Vector3 target){var c=Camera.main;var oldP=c.transform.position;var oldR=c.transform.rotation;c.transform.SetPositionAndRotation(position,Quaternion.LookRotation(target-position,name=="property-top"?-GameObject.Find("Dan - blue X").transform.forward:Vector3.up));ThreeFeatureValidation.CaptureUi(dir+"/"+name+".png");c.transform.SetPositionAndRotation(oldP,oldR);}
        IEnumerator LocalDrive(){car.GetComponent<VehicleConfiguration>().Apply("moto");var home=GameObject.Find("Dan - blue X").transform;var driveway=new[]{40f,30f,20f,9f,4f,-1f,-6f,-11f,-16f,-21f}.Select(z=>home.TransformPoint(new Vector3(-22,0,z))).ToArray();if(Arg("-localPart")=="")yield return Drive(driveway,"changed-driveway1",5,45);var root=GameObject.Find(Arg("-launchRoot","CR094 summit launch")).transform;var route=root.GetComponentInChildren<RaceRoad>().points;int end=Array.FindIndex(route,p=>Vector3.Distance(p,root.position)<.1f);if(Arg("-localPart")!="return")yield return Drive(route.Take(end+1).ToArray(),"natural-runup-connection",7,100);if(Arg("-localPart")=="connection")yield break;var destination=race.GetComponent<ExplorationMap>().destinations.Single(d=>d.id=="summit-homeward");Check(Mathf.Abs(destination.position.y-Ground(destination.position))<.25f&&Vector3.Distance(destination.position,root.TransformPoint(new Vector3(0,0,5)))<.25f,"Moved summit destination is supported at run-up");Check(Vector3.Distance(root.GetComponentInChildren<ActivitySite>().transform.position,root.TransformPoint(new Vector3(0,25.92f,220)))<.1f,"Local jump activity follows new lip");if(Arg("-localPart")!="return"){Place(root.TransformPoint(new Vector3(3,0,60)),root.forward);bool reset=car.GetComponent<VehicleRespawn>().TryRecoverLocal();yield return new WaitForFixedUpdate();Check(reset&&Mathf.Abs(car.Body.position.y-Ground(car.Body.position))<3,"Single aborted approach reset is supported");}var landingStart=root.TransformPoint(new Vector3(0,0,445));var returnPoints=new[]{landingStart}.Concat(route.Skip(Array.FindIndex(route,p=>root.InverseTransformPoint(p).z>=450))).ToArray();yield return Drive(returnPoints,"landing-return",7,100);}
        IEnumerator Views(){yield return null;car.Body.isKinematic=true;var home=GameObject.Find("Dan - blue X").transform;Shot("property-top",home.TransformPoint(new Vector3(-12,105,-4)),home.TransformPoint(new Vector3(-12,0,-4)));Shot("driveway1-ground",home.TransformPoint(new Vector3(-22,3,8)),home.TransformPoint(new Vector3(-22,-2,-16)));yield return null;
            foreach(var text in GameObject.Find("CR102 summit signs").GetComponentsInChildren<TextMesh>()){var t=text.transform;var root=t.parent;var p=root.position-root.forward*13; p.y=Ground(p)+2;Shot(root.name+"-approach",p,t.position);p=root.position+root.forward*10;p.y=Ground(p)+2;Shot(root.name+"-rear",p,t.position);var b=text.GetComponent<Renderer>().localBounds;Check(b.size.x*t.lossyScale.x<=6.4f&&b.size.y*t.lossyScale.y<=2,"Contained "+root.name);yield return null;}}
    }
}
