#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using System.Reflection;using UnityEngine;using UnityEngine.InputSystem;using UnityEngine.InputSystem.LowLevel;
namespace Racer {
public sealed class MountainPolishUiChecks:MonoBehaviour {
 const string Output="Docs/MountainPolish";readonly List<string> checks=new();Gamepad pad;Keyboard keyboard;RaceFlow flow;InputSettings.BackgroundBehavior oldBackground;InputSettings.EditorInputBehaviorInPlayMode oldInput;
 void Check(bool good,string text){checks.Add((good?"PASS ":"FAIL ")+text);File.WriteAllLines(Output+"/ui-checks.txt",checks);}
 void Update(){AudioListener.volume=0;}
 IEnumerator Press(GamepadButton button){while(MenuInput.Blocked)yield return null;InputSystem.QueueStateEvent(pad,new GamepadState().WithButton(button));yield return null;yield return null;InputSystem.QueueStateEvent(pad,new GamepadState());yield return null;yield return null;}
 IEnumerator Start(){Application.runInBackground=true;oldBackground=InputSystem.settings.backgroundBehavior;oldInput=InputSystem.settings.editorInputBehaviorInPlayMode;InputSystem.settings.backgroundBehavior=InputSettings.BackgroundBehavior.IgnoreFocus;InputSystem.settings.editorInputBehaviorInPlayMode=InputSettings.EditorInputBehaviorInPlayMode.AllDeviceInputAlwaysGoesToGameView;pad=InputSystem.AddDevice<Gamepad>();keyboard=InputSystem.AddDevice<Keyboard>();yield return null;yield return null;flow=FindAnyObjectByType<RaceFlow>();var title=FindAnyObjectByType<StartupTitle>();float deadline=Time.realtimeSinceStartup+20;while(title&&!title.Armed&&Time.realtimeSinceStartup<deadline)yield return null;Check(flow.State==RaceFlow.Stage.Title&&title,"Normal title remains the startup presentation");yield return Press(GamepadButton.South);deadline=Time.realtimeSinceStartup+15;while(flow.State!=RaceFlow.Stage.Racing&&Time.realtimeSinceStartup<deadline)yield return null;yield return null;Check(flow.State==RaceFlow.Stage.Racing&&flow.Race.FreeRoam&&flow.Race.vehicle.GetComponent<VehicleInput>().enabled,"Title dismissal starts driveable Free Roam");var initial=flow.Race.vehicle.Body.position;InputSystem.QueueStateEvent(pad,new GamepadState{rightTrigger=1});yield return new WaitForSecondsRealtime(1);InputSystem.QueueStateEvent(pad,new GamepadState());yield return null;Check(Vector3.Distance(initial,flow.Race.vehicle.Body.position)>1,"Controller throttle moves the vehicle");var glyph=FindObjectsByType<MenuGlyph>().FirstOrDefault(g=>g.name=="Menu button");Check(glyph&&glyph.Path=="<Gamepad>/start"&&MenuGlyph.Label(glyph.Path)=="","Temporary prompt uses the existing shaped Menu glyph");ThreeFeatureValidation.CaptureUi(Output+"/startup-roam.png");yield return Press(GamepadButton.Start);Check(flow.State==RaceFlow.Stage.Ready&&flow.RoamMenu,"Start opens existing main menu");foreach(string id in new[]{"race","garage","records","exploration","settings"})Check(FindObjectsByType<UnityEngine.UI.Button>().Any(b=>b.name==id&&b.gameObject.activeInHierarchy),"Existing menu destination: "+id);Check(flow.RoamMenuHintUntil==0,"Opening menu dismisses temporary hint");ThreeFeatureValidation.CaptureUi(Output+"/roam-menu.png");yield return Press(GamepadButton.East);Check(flow.State==RaceFlow.Stage.Racing,"B resumes Free Roam from main menu");InputSystem.QueueStateEvent(keyboard,new KeyboardState(Key.Escape));yield return null;yield return null;InputSystem.QueueStateEvent(keyboard,new KeyboardState());yield return null;yield return null;Check(flow.State==RaceFlow.Stage.Ready&&flow.RoamMenu,"Keyboard Escape opens the same menu");
 var flags=BindingFlags.NonPublic|BindingFlags.Instance;typeof(RaceFlow).GetMethod("SetStage",flags).Invoke(flow,new object[]{RaceFlow.Stage.Results});yield return null;yield return null;Check(!FindObjectsByType<MenuGlyph>().Any(g=>g.transform.parent.name=="Back"&&g.gameObject.activeInHierarchy),"Results root does not advertise ineffective Back");flow.OpenSettings();yield return null;yield return null;Check(FindObjectsByType<MenuGlyph>().Any(g=>g.transform.parent.name=="Back"&&g.gameObject.activeInHierarchy),"Results Settings retains valid Back");yield return Press(GamepadButton.East);Check(flow.State==RaceFlow.Stage.Results,"Results Settings B returns to results");ThreeFeatureValidation.CaptureUi(Output+"/results.png");File.WriteAllText(Output+"/ui-done.txt",$"{checks.Count(c=>c.StartsWith("PASS"))}/{checks.Count} passed");UnityEditor.EditorApplication.isPlaying=false;}
 void OnDestroy(){if(pad!=null)InputSystem.RemoveDevice(pad);if(keyboard!=null)InputSystem.RemoveDevice(keyboard);InputSystem.settings.backgroundBehavior=oldBackground;InputSystem.settings.editorInputBehaviorInPlayMode=oldInput;}
}
}
#endif
