#if UNITY_EDITOR
using System;using System.Collections;using System.Collections.Generic;using System.IO;using System.IO.Compression;using System.Linq;using System.Reflection;using UnityEngine;using UnityEngine.EventSystems;using UnityEngine.InputSystem;using UnityEngine.InputSystem.LowLevel;
namespace Racer {
public sealed class ReportMenuChecks:MonoBehaviour {
 const string Out="Docs/ReportCleanup";readonly List<string> results=new();Keyboard keys;Gamepad pad;Mouse mouse;DeveloperLocationHud hud;RaceDirector race;InputSettings.BackgroundBehavior oldBackground;InputSettings.EditorInputBehaviorInPlayMode oldEditorInput;
 void Check(bool ok,string message){results.Add((ok?"PASS ":"FAIL ")+message);File.WriteAllLines(Out+"/ui-checks.txt",results);}
 IEnumerator KeyPress(Key key){InputSystem.QueueStateEvent(keys,new KeyboardState(key));yield return new WaitForSecondsRealtime(.08f);InputSystem.QueueStateEvent(keys,new KeyboardState());yield return new WaitForSecondsRealtime(.12f);}
 IEnumerator Pad(GamepadButton button){InputSystem.QueueStateEvent(pad,new GamepadState().WithButton(button));yield return new WaitForSecondsRealtime(.08f);InputSystem.QueueStateEvent(pad,new GamepadState());yield return new WaitForSecondsRealtime(.12f);}
 UnityEngine.UI.Button Find(string name)=>hud.GetComponentsInChildren<UnityEngine.UI.Button>(true).Single(b=>b.name==name);
 IEnumerator Select(string name,bool gamepad){for(int i=0;i<12&&EventSystem.current.currentSelectedGameObject!=Find(name).gameObject;i++){if(gamepad)yield return Pad(GamepadButton.DpadDown);else yield return KeyPress(Key.DownArrow);}Check(EventSystem.current.currentSelectedGameObject==Find(name).gameObject,"Navigation reaches "+name);}
 IEnumerator Click(string name){Canvas.ForceUpdateCanvases();var button=Find(name);var r=(RectTransform)button.transform;Vector2 pos=RectTransformUtility.WorldToScreenPoint(null,r.TransformPoint(r.rect.center));InputSystem.QueueStateEvent(mouse,new MouseState{position=pos});yield return new WaitForSecondsRealtime(.12f);Check(EventSystem.current.IsPointerOverGameObject(mouse.deviceId),"Mouse hover raycasts "+name);InputSystem.QueueStateEvent(mouse,new MouseState{position=pos}.WithButton(MouseButton.Left));yield return new WaitForSecondsRealtime(.08f);InputSystem.QueueStateEvent(mouse,new MouseState{position=pos});yield return new WaitForSecondsRealtime(.15f);}
 IEnumerator Start(){oldBackground=InputSystem.settings.backgroundBehavior;oldEditorInput=InputSystem.settings.editorInputBehaviorInPlayMode;InputSystem.settings.backgroundBehavior=InputSettings.BackgroundBehavior.IgnoreFocus;InputSystem.settings.editorInputBehaviorInPlayMode=InputSettings.EditorInputBehaviorInPlayMode.AllDeviceInputAlwaysGoesToGameView;Directory.CreateDirectory(Out);AudioListener.volume=0;Application.runInBackground=true;keys=InputSystem.AddDevice<Keyboard>();pad=InputSystem.AddDevice<Gamepad>();mouse=InputSystem.AddDevice<Mouse>();race=FindAnyObjectByType<RaceDirector>();yield return null;yield return null;
 var title=FindAnyObjectByType<StartupTitle>();if(title)Destroy(title.gameObject);typeof(StartupTitle).GetField("completed",BindingFlags.Static|BindingFlags.NonPublic).SetValue(null,true);race.Flow.UseValidationSave(Path.GetFullPath("Temp/ReportCleanupMenuSave"));race.Flow.EnterMenuAfterTitle();race.Flow.StartFreeRoam();yield return new WaitForSecondsRealtime(.2f);hud=DeveloperLocationHud.Instance;
 yield return KeyPress(Key.F3);yield return KeyPress(Key.F6);Check(DeveloperLocationHud.Interactive&&EventSystem.current.GetComponent<UnityEngine.InputSystem.UI.InputSystemUIInputModule>().enabled&&EventSystem.current.sendNavigationEvents,"Debug owns gameplay while shared UI remains active");Check(!Find("Return to Vehicle").interactable&&!Find("Export Bug Report ZIP").interactable,"Inapplicable return/export actions disabled");
 yield return KeyPress(Key.DownArrow);Check(EventSystem.current.currentSelectedGameObject==Find("Capture Bug  F4").gameObject,"Keyboard arrows navigate debug actions");yield return KeyPress(Key.Enter);float until=Time.realtimeSinceStartup+5;while(!hud.CommentOpen&&Time.realtimeSinceStartup<until)yield return null;Check(hud.CommentOpen,"Enter activates in-game Capture Bug");foreach(char c in "Menu interaction export verification")InputSystem.QueueTextEvent(keys,c);yield return null;yield return KeyPress(Key.Enter);Check(DeveloperLocationHud.Session?.Count==1&&!hud.CommentOpen,"Comment saved through keyboard");
 yield return Pad(GamepadButton.Start);yield return Select("Export Bug Report ZIP",true);yield return Pad(GamepadButton.South);Check(File.Exists(hud.LastExport),"Controller A activates in-game ZIP export");if(File.Exists(hud.LastExport)){using(var zip=ZipFile.OpenRead(hud.LastExport)){var root=zip.Entries.Single(e=>e.FullName.EndsWith("/BUG_REPORT.md")).FullName.Replace("BUG_REPORT.md","");var names=zip.Entries.Select(e=>e.FullName.Substring(root.Length)).ToArray();Check(names.Contains("BUG_REPORT.md")&&names.Contains("bugs.json")&&names.Contains("Screenshots/BUG-001.png"),"Opened exported ZIP: Markdown, JSON and referenced PNG present");using(var reader=new StreamReader(zip.GetEntry(root+"BUG_REPORT.md").Open()))Check(reader.ReadToEnd().Contains("Screenshots/BUG-001.png"),"Markdown screenshot resolves inside ZIP");}File.WriteAllText(Out+"/test-export.txt",hud.LastExport);}
 yield return Select("Debug Fly / Inspection",true);yield return Pad(GamepadButton.South);Check(hud.Flying&&!DeveloperLocationHud.Interactive,"Controller activates Debug Fly");yield return Pad(GamepadButton.Start);Check(!Find("Debug Fly / Inspection").interactable&&Find("Return to Vehicle").interactable,"Fly/return applicability reverses while flying");
 InputSystem.QueueStateEvent(pad,new GamepadState{leftStick=new Vector2(0,-1)});yield return new WaitForSecondsRealtime(.1f);InputSystem.QueueStateEvent(pad,new GamepadState());yield return new WaitForSecondsRealtime(.15f);Check(EventSystem.current.currentSelectedGameObject!=Find("Resume").gameObject,"Left stick navigates debug menu");
 yield return Click("Return to Vehicle");Check(!hud.Flying&&!DeveloperLocationHud.Interactive,"Mouse returns to vehicle");yield return KeyPress(Key.F6);yield return Click("Open Debug Report Folder");Check(hud.LastOpenedFolder==DeveloperLocationHud.Session.DirectoryPath,"Mouse activates report-folder action");
 yield return Click("Toggle Debug HUD");Check(!(bool)typeof(DeveloperLocationHud).GetField("hudVisible",BindingFlags.NonPublic|BindingFlags.Instance).GetValue(hud),"Mouse toggles Debug HUD");yield return Pad(GamepadButton.East);Check(!DeveloperLocationHud.Interactive,"Controller B closes menu");yield return KeyPress(Key.F6);yield return KeyPress(Key.Escape);Check(!DeveloperLocationHud.Interactive,"Escape closes menu");yield return KeyPress(Key.F6);yield return Click("Resume");Check(!DeveloperLocationHud.Interactive&&Time.timeScale==1,"Mouse Resume restores game");yield return KeyPress(Key.F6);yield return Select("Exit Debug Mode  F3",false);yield return KeyPress(Key.Enter);Check(!hud.Visible&&!DeveloperLocationHud.OwnsInput,"Enter exits Debug Mode without leaking to Pause");
 // Short, isolated one-lap event. Feed ordered timing gates so this test focuses
 // on the production finish/Results UI rather than repeating a full route drive.
 race.opponents=race.traffic=false;race.laps=1;race.Flow.StartRace();while(race.Flow.State!=RaceFlow.Stage.Racing)yield return null;
 race.Progress.Cross(0,true,race.Clock);for(int gate=1;gate<=race.Progress.CheckpointCount;gate++){yield return new WaitForSecondsRealtime(.15f);race.Progress.Cross(gate,true,race.Clock);}yield return new WaitForSecondsRealtime(.2f);race.Progress.Cross(0,true,race.Clock);yield return new WaitForSecondsRealtime(.4f);
 Check(race.Progress.Finished&&race.Flow.State==RaceFlow.Stage.Results,"Short ordered-gate race completes through production Results flow");var menus=race.GetComponent<RaceMenus>();yield return Pad(GamepadButton.RightShoulder);Check((int)typeof(RaceMenus).GetField("resultTab",BindingFlags.NonPublic|BindingFlags.Instance).GetValue(menus)==1,"Controller switches Results to Lap Times");
 ThreeFeatureValidation.CaptureUi(Out+"/results-lap-times-controller.png");yield return Pad(GamepadButton.East);Check(race.Flow.State==RaceFlow.Stage.Ready,"B returns directly from alternate Results tab to Main Menu");
 File.WriteAllLines(Out+"/ui-done.txt",results);
 }
 void OnDestroy(){InputSystem.settings.backgroundBehavior=oldBackground;InputSystem.settings.editorInputBehaviorInPlayMode=oldEditorInput;if(keys!=null)InputSystem.RemoveDevice(keys);if(pad!=null)InputSystem.RemoveDevice(pad);if(mouse!=null)InputSystem.RemoveDevice(mouse);}
}}
#endif




