using System;
using System.IO;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
namespace Racer {
// Explicit local-segment fixture. Never enabled in ordinary gameplay.
public sealed class ShortcutRevisionFollowupChecks:MonoBehaviour {
 public string Only=""; public static string Output="Docs/ShortcutRevision/followup";
 readonly List<string> checks=new();RaceDirector race;ArcadeVehicle car;int resets;float lastTime; public float EntrySpeed=26; float groundOffset; bool groundRun;readonly Dictionary<string,float> times=new();
 void Check(bool ok,string message){checks.Add((ok?"PASS ":"FAIL ")+message);File.WriteAllLines(Output+"/checks.txt",checks);}
 public static void Launch(){var g=new GameObject("Bounded shortcut checks");DontDestroyOnLoad(g);g.AddComponent<ShortcutRevisionFollowupChecks>();}
 void OnEnable()=>SceneManager.sceneLoaded+=Loaded;
 void OnDisable()=>SceneManager.sceneLoaded-=Loaded;
 void Loaded(Scene scene,LoadSceneMode mode){foreach(var t in FindObjectsByType<ContinuationTraffic>())t.enabled=false;}
 [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Boot(){var a=Environment.GetCommandLineArgs();int i=Array.IndexOf(a,"-shortcutRevisionCheck");if(i>=0&&Array.IndexOf(a,"-racerTestSave")>=0){Output=a[i+1];Launch();}}
 IEnumerator Start(){Directory.CreateDirectory(Output);AudioListener.volume=0;Application.runInBackground=true;yield return null;yield return null;race=FindAnyObjectByType<RaceDirector>();
 #if UNITY_EDITOR
 race.Flow.UseValidationSave(Path.GetFullPath("Temp/ShortcutRevisionSave"));
 #endif
 race.Flow.OpenGarage();race.Flow.SelectVehicle("moto");race.Flow.CloseGarage();race.opponents=race.traffic=false;race.laps=1;race.Flow.StartRace();while(race.Flow.State!=RaceFlow.Stage.Racing){AudioListener.volume=0;yield return null;}car=race.vehicle;car.GetComponent<VehicleInput>().enabled=false;car.enabled=false;car.GetComponent<VehicleRespawn>().Respawned+=()=>resets++;
 var tree=race.Branches.First(b=>b.title=="Tree-Top Trail");EntrySpeed=26;yield return Place(tree,false);yield return Drive(tree,false);times[tree.title+" main"]=lastTime;
 yield return Place(tree,true);yield return Drive(tree,true);Check(lastTime<times[tree.title+" main"]-.2f,$"Tree clean {lastTime:F2}s faster than main {times[tree.title+" main"]:F2}s");
 EntrySpeed=19;yield return Place(tree,true);yield return Drive(tree,true);EntrySpeed=26;
 times["Abandoned Cabin Jump main"]=5.06f;
 foreach(var branch in race.Branches)foreach(float offset in branch==tree?new[]{5f}:new[]{-5f,5f}){groundOffset=offset;yield return PlannedGround(branch);}
 File.WriteAllLines(Output+"/done.txt",checks);car.Body.isKinematic=true;race.Flow.Pause();
 }
 IEnumerator Place(WoodlandRoute b,bool branch){race.Progress.Restart();race.Racers[0].Branch.Clear();race.Progress.Cross(0,true,race.Clock);for(int i=1;i<race.gates.Length;i++)if(race.road.Project(race.gates[i].transform.position,out _)<b.entryRoad-1)race.Progress.Cross(i,true,race.Clock);var p=race.road.At(b.entryRoad,out var f);if(branch){p=b.At(0,out f);}if(groundRun){p+=Vector3.Cross(Vector3.up,f).normalized*groundOffset;p.y=Ground(p);}car.enabled=false;car.GetComponent<VehicleInput>().enabled=false;car.Body.isKinematic=false;car.Body.position=p+Vector3.up*.55f;car.Body.rotation=Quaternion.LookRotation(Vector3.ProjectOnPlane(f,Vector3.up));car.transform.SetPositionAndRotation(car.Body.position,car.Body.rotation);car.Body.linearVelocity=car.Body.angularVelocity=Vector3.zero;car.ClearSteering();Physics.SyncTransforms();for(int i=0;i<30;i++){car.Simulate(0,0,0,Time.fixedDeltaTime);yield return new WaitForFixedUpdate();}race.Progress.Restart();race.Progress.Cross(0,true,race.Clock);for(int i=1;i<race.gates.Length;i++)if(race.road.Project(race.gates[i].transform.position,out _)<b.entryRoad-1)race.Progress.Cross(i,true,race.Clock);car.Body.linearVelocity=f.normalized*EntrySpeed;race.ResetSampling(car.Body.position,race.Clock);}
 float Steer(Vector3 target){var local=Quaternion.Inverse(Quaternion.LookRotation(Vector3.ProjectOnPlane(car.transform.forward,Vector3.up)))*(target-car.Body.position);float look=Math.Max(3,new Vector2(local.x,local.z).magnitude);return Mathf.Clamp(Mathf.Atan(2*car.wheelbase*Mathf.Sin(Mathf.Atan2(local.x,local.z))/look)/(Mathf.Lerp(car.slowSteerAngle,car.fastSteerAngle,Mathf.Clamp01(car.ForwardSpeed/car.topSpeed))*Mathf.Deg2Rad),-1,1);}
 IEnumerator Drive(WoodlandRoute b,bool branch){string name=(branch?"shortcut-":"main-")+b.title.Replace(' ','-')+"-"+EntrySpeed;float start=Time.time,air=0,maxAir=0,best=0;bool reached=false,entered=false;int before=resets,deckFrames=0;float firstDeck=-1;using(var log=new StreamWriter(Output+"/"+name+".csv")){log.WriteLine("time,x,y,z,speed,station,lateral,wheels,nextGate,branch");while(Time.time-start<22){float s=branch?b.Project(car.Body.position,out _):race.road.Project(car.Body.position,out _)-b.entryRoad;best=Math.Max(best,s);float length=branch?b.Length:b.exitRoad-b.entryRoad;Vector3 target=branch?b.At(s+9,out _):race.road.At(b.entryRoad+s+10,out _);if(s>=length-3){reached=true;break;}float speed=car.ForwardSpeed,desired=branch?Mathf.Min(EntrySpeed<20&&s<48?EntrySpeed:32,b.SpeedAt(s)):32;for(float ahead=0;ahead<50;ahead+=6){Vector3 f0,f1;if(branch){b.At(s+ahead,out f0);b.At(s+ahead+6,out f1);}else{race.road.At(b.entryRoad+s+ahead,out f0);race.road.At(b.entryRoad+s+ahead+6,out f1);}float curve=Vector3.Angle(Vector3.ProjectOnPlane(f0,Vector3.up),Vector3.ProjectOnPlane(f1,Vector3.up))*Mathf.Deg2Rad/6;float safe=Mathf.Sqrt(car.maxGripAcceleration*.5f/Mathf.Max(.0001f,curve));desired=Mathf.Min(desired,Mathf.Sqrt(safe*safe+2*car.braking*.8f*Mathf.Max(0,ahead-8)));}car.Simulate(speed<desired?1:0,speed>desired+.5f?Mathf.Clamp01((speed-desired)*.3f):0,Steer(target),Time.fixedDeltaTime);yield return new WaitForFixedUpdate();AudioListener.volume=0;if(car.GroundedWheels==0){air+=Time.fixedDeltaTime;maxAir=Math.Max(maxAir,air);}else air=0;if(branch&&b.title=="Tree-Top Trail"&&s>33&&s<98&&car.GroundedWheels>=2&&Mathf.Abs(car.Body.position.y-b.At(s,out _).y)<1.3f){deckFrames++;if(firstDeck<0)firstDeck=s;}entered|=race.Racers[0].Branch.Route==b;var p=car.Body.position;b.Project(p,out var lateral);log.WriteLine($"{Time.time-start:F2},{p.x:F3},{p.y:F3},{p.z:F3},{car.ForwardSpeed:F2},{s:F2},{lateral:F2},{car.GroundedWheels},{race.Progress.NextGate},{race.Racers[0].Branch.Route==b}");}}
 lastTime=Time.time-start;Check(reached&&resets==before,$"{name}: physical normal-input traverse {lastTime:F2}s, progress={best:F1}m, maxAir={maxAir:F2}s, resets={resets-before}");if(branch){if(b.title=="Tree-Top Trail")Check(firstDeck>=33&&firstDeck<43,$"Tree first touchdown {firstDeck:F2}m; first platform33..48, entry cap{EntrySpeed}");Check(deckFrames>20,$"Tree-top receiving trail physically driven on elevated support: {deckFrames} frames");Check(entered&&race.Progress.MissedGates==0&&race.Progress.NextGate>b.bypassedGates.Max(),$"{b.title}: actual entrance/bypass entitlement, nextGate={race.Progress.NextGate}, misses={race.Progress.MissedGates}, entered={entered}");Check(maxAir>(b.title=="Tree-Top Trail"?.25f:.75f),$"{b.title}: substantial intentional airtime {maxAir:F2}s");}}
 float Ground(Vector3 p)=>Physics.RaycastAll(p+Vector3.up*150,Vector3.down,300,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).OrderBy(h=>h.distance).First().point.y;
 IEnumerator GroundDrive(WoodlandRoute b){float start=Time.time;int before=resets;bool reached=false;using(var log=new StreamWriter(Output+"/ground-"+b.title.Replace(' ','-')+groundOffset+".csv")){log.WriteLine("time,station,speed,lateral,wheels");while(Time.time-start<65){float s=b.Project(car.Body.position,out var lateral);if(s>b.Length-5){reached=true;break;}var target=b.At(s+5,out var f)+Vector3.Cross(Vector3.up,f).normalized*groundOffset;target.y=Ground(target);car.Simulate(1,0,Steer(target),Time.fixedDeltaTime);yield return new WaitForFixedUpdate();AudioListener.volume=0;log.WriteLine($"{Time.time-start:F2},{s:F2},{car.ForwardSpeed:F2},{lateral:F2},{car.GroundedWheels}");}}lastTime=Time.time-start;Check(reached&&resets==before,$"{b.title}: traversable ground recovery offset={groundOffset} reached={reached} resets={resets-before} time={lastTime:F2}");}

 IEnumerator PlannedGround(WoodlandRoute b){
 float begin=b.title=="Tree-Top Trail"?36:44,end=b.Length-6;int count=Mathf.CeilToInt((end-begin)/2)+1;const int lanes=9;var points=new Vector3[count,lanes];var costs=new float[count,lanes];var prev=new int[count,lanes];float sign=Mathf.Sign(groundOffset);
 bool Clear(Vector3 p,Quaternion rot)=>!Physics.OverlapBox(p+Vector3.up*.85f,new Vector3(.72f,.48f,1.15f),rot,1,QueryTriggerInteraction.Ignore).Any(c=>!c.name.StartsWith("Ground_")&&c.attachedRigidbody!=car.Body);
 for(int i=0;i<count;i++)for(int j=0;j<lanes;j++){float station=Mathf.Lerp(begin,end,(float)i/(count-1));var p=b.At(station,out var f)+Vector3.Cross(Vector3.up,f).normalized*sign*(3+j);p.y=Ground(p);points[i,j]=p;costs[i,j]=1e9f;prev[i,j]=-1;if(!Clear(p,Quaternion.LookRotation(Vector3.ProjectOnPlane(f,Vector3.up))))continue;if(i==0){costs[i,j]=Mathf.Abs(j-2)*2;continue;}for(int k=Mathf.Max(0,j-1);k<=Mathf.Min(lanes-1,j+1);k++){float c=costs[i-1,k]+Vector3.Distance(points[i-1,k],p)+Mathf.Abs(j-2)*.05f;if(c<costs[i,j]){costs[i,j]=c;prev[i,j]=k;}}}
 int lane=Enumerable.Range(0,lanes).OrderBy(j=>costs[count-1,j]).First();if(costs[count-1,lane]>1e8f){Check(false,b.title+" no passable local ground path for "+groundOffset);yield break;}var path=new Vector3[count];for(int i=count-1;i>=0;i--){path[i]=points[i,lane];lane=prev[i,lane];}
 File.WriteAllText(Output+"/ground-path-"+b.title+groundOffset+".json",Newtonsoft.Json.JsonConvert.SerializeObject(path.Select(p=>new {p.x,p.y,p.z})));
 car.Body.isKinematic=false;car.Body.position=path[0]+Vector3.up*.55f;car.Body.rotation=Quaternion.LookRotation(Vector3.ProjectOnPlane(path[1]-path[0],Vector3.up));car.transform.SetPositionAndRotation(car.Body.position,car.Body.rotation);car.Body.linearVelocity=car.Body.angularVelocity=Vector3.zero;car.ClearSteering();Physics.SyncTransforms();for(int i=0;i<25;i++){car.Simulate(0,0,0,Time.fixedDeltaTime);yield return new WaitForFixedUpdate();}car.Body.linearVelocity=car.transform.forward*18;float start=Time.time;int before=resets;int next=1;float stalled=0,reverseUntil=0;using(var log=new StreamWriter(Output+"/ground-"+b.title.Replace(' ','-')+groundOffset+".csv")){log.WriteLine("time,station,speed,wheels,next");while(Time.time-start<50&&next<count){var p=car.Body.position;while(next<count-1&&Vector3.Dot(p-path[next],path[next+1]-path[next])>0)next++;if(next==count-1&&Vector2.Distance(new(p.x,p.z),new(path[^1].x,path[^1].z))<3)break;var target=path[Mathf.Min(count-1,next+1)];if(car.ForwardSpeed<.3f)stalled+=Time.fixedDeltaTime;else stalled=0;if(stalled>1.2f){reverseUntil=Time.time+1.2f;stalled=0;}bool reverse=Time.time<reverseUntil;car.Simulate(reverse?0:1,reverse?1:0,reverse?-sign:Steer(target),Time.fixedDeltaTime);yield return new WaitForFixedUpdate();AudioListener.volume=0;log.WriteLine($"{Time.time-start:F2},{b.Project(car.Body.position,out _):F2},{car.ForwardSpeed:F2},{car.GroundedWheels},{next}");}}
 float elapsed=Time.time-start;bool reached=next>=count-2;Check(reached&&resets==before,$"{b.title} ground {groundOffset}: traversed {begin:F0}..{end:F0} in {elapsed:F2}s, reached={reached}, resets={resets-before}");Check(reached&&elapsed>times[b.title+" main"]+1,$"{b.title} bush section alone {elapsed:F2}s slower than full main {times[b.title+" main"]:F2}s");
 }

}
}







