using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Object=UnityEngine.Object;
namespace Racer.Editor {
public static partial class BackyardReverseAuthoring {
static Vector3[] Curve(Vector3[] knots){var points=new List<Vector3>();for(int i=0;i<knots.Length;i++){var a=knots[(i+knots.Length-1)%knots.Length];var b=knots[i];var c=knots[(i+1)%knots.Length];var d=knots[(i+2)%knots.Length];int n=Mathf.Max(2,Mathf.CeilToInt(Vector3.Distance(b,c)/.8f));for(int j=0;j<n;j++){float t=j/(float)n;points.Add(.5f*(2*b+(-a+c)*t+(2*a-5*b+4*c-d)*t*t+(-a+3*b-3*c+d)*t*t*t));}}return points.ToArray();}
static void ResetRoad(RaceRoad r){typeof(RaceRoad).GetField("distance",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).SetValue(r,null);r.Initialize();}
public static void Reverse(){
if(Application.isPlaying||UnityEngine.SceneManagement.SceneManager.GetActiveScene().isDirty)throw new Exception("Saved edit mode required");if(File.Exists("Assets/Scenes/DansBackyardReverse.unity"))throw new Exception("Reverse already exists; inspect before regenerating");
Directory.CreateDirectory(Folder);Directory.CreateDirectory(Evidence);report.Clear();EditorSceneManager.OpenScene(BackyardForwardAuthoring.ScenePath);EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene(),"Assets/Scenes/DansBackyardReverse.unity");
var race=Object.FindAnyObjectByType<RaceDirector>();var forward=race.road;forward.Initialize();var forwardPoints=forward.points.ToArray();var street=race.ambientRoad;street.Initialize();
var root=new GameObject("Backyard Reverse main route").transform;var oldGates=race.gates.ToArray();var course=race.GetComponent<BackyardForwardCourse>();
foreach(var b in Object.FindObjectsByType<WoodlandRoute>())Object.DestroyImmediate(b);foreach(var f in Object.FindObjectsByType<ForestLayout>())Object.DestroyImmediate(f);
foreach(string n in new[]{"Forward teal navigation - no colliders","Forward shortcut guidance"}){var go=GameObject.Find(n);if(go)go.SetActive(false);}
// Existing physical Forward stunts remain. Only their directional guidance is hidden in Reverse.
foreach(var t in Object.FindObjectsByType<Transform>().Where(t=>t.name.Contains("shortcut arrow")||t.name.Contains("Shortcut arrow")).ToArray())t.gameObject.SetActive(false);
var knots=new List<Vector3>{new(441,0,8.5f),new(459.6f,0,8.1f),new(473,0,9)};
float end=street.Project(new(474,79,14),out _),join=street.Project(new(468,80,63),out _);for(float s=end;s>=join;s-=4)knots.Add(street.At(s,out _));
knots.AddRange(new Vector3[]{new(466,0,66),new(456.4f,0,67.4f),new(428,0,83),new(398,0,80),new(362,0,62),new(325,0,72),new(304,0,103),new(269,0,123),new(224,0,112),new(186,0,80),new(160,0,80.7f),new(145,0,80.7f),new(128,0,80.7f),new(80,0,80.7f),new(60,0,71),new(48,0,49),new(36,0,19),new(47,0,-16),new(27,0,-47),new(25,0,-72),new(43,0,-94.1f),new(56,0,-94.1f),new(72.4f,0,-94.1f),new(128,0,-94.1f),new(151,0,-96),new(183,0,-95),new(221,0,-76),new(236,0,-46),new(231.4f,0,-25.6f),new(257,0,-24),new(287,0,-22),new(316,0,-16),new(332,0,-10),new(345.6f,0,-8.8f),new(350,0,-16),new(358,0,-20.1f),new(371,0,-13.6f),new(378.6f,0,-9.8f),new(383,0,-7.6f),new(425,0,13.4f),new(435,0,10)});
var path=Curve(knots.ToArray());for(int i=0;i<path.Length;i++)path[i].y=Ground(path[i]);var road=new GameObject("Reverse navigation only - no pavement").AddComponent<RaceRoad>();road.transform.SetParent(root);road.forestTrail=true;road.points=path;road.Initialize();
var lips=new[]{new Vector3(128,0,80.7f),new Vector3(72.4f,0,-94.1f),new Vector3(383,0,-7.6f)};var lands=new[]{new Vector3(80,0,80.7f),new Vector3(128,0,-94.1f),new Vector3(425,0,13.4f)};var axes=new[]{Vector3.left,Vector3.right,new Vector3(2,0,1).normalized};var launchS=lips.Select(p=>{p.y=Ground(p);return road.Project(p,out _);}).ToArray();var landS=lands.Select(p=>{p.y=Ground(p);return road.Project(p,out _);}).ToArray();var run=new[]{32f,32f,28f};var rise=new[]{5.8f,6.6f,4.2f};
var stations=new float[path.Length];for(int i=1;i<path.Length;i++)stations[i]=stations[i-1]+Vector3.Distance(path[i-1],path[i]);
for(int j=0;j<3;j++){lips[j].y=Ground(lips[j])+rise[j];lands[j].y=Ground(lands[j]);for(int i=0;i<path.Length;i++){float q=stations[i]-launchS[j];if(q>=-run[j]&&q<=0)path[i].y+=rise[j]*Mathf.Pow((q+run[j])/run[j],2);else if(q>0&&stations[i]<landS[j])path[i].y=Mathf.Lerp(lips[j].y,lands[j].y,Mathf.InverseLerp(launchS[j],landS[j],stations[i]));}}
bool Air(float s)=>Enumerable.Range(0,3).Any(j=>s>launchS[j]+.2f&&s<landS[j]-1);
bool NewGround(Vector3 p){if(p.x>=390||p.x<=15||p.z<=-103||p.z>=96)return false;float d=Near(p,path,out _,out int index);return d<=5.3f&&!Air(stations[index])&&Near(p,forwardPoints,out _,out _)>=5.5f;}
Sculpt(NewGround,p=>{float d=Near(p,path,out var at,out _);p.y=Mathf.Lerp(p.y,at.y,1-Smooth(2.65f,5.3f,d));return p;},"reverse-trail");
// Ground route data against final surfaces; airborne guidance spans takeoff to receiving bank.
for(int i=0;i<path.Length;i++)if(!Air(stations[i]))path[i].y=Ground(path[i]);road.points=path;ResetRoad(road);for(int j=0;j<3;j++){lips[j].y=Ground(lips[j]);launchS[j]=road.Project(lips[j],out _);landS[j]=road.Project(lands[j],out _);}
race.road=road;race.courseId="backyard-reverse-v1-main";race.courseName="Dan's Backyard Loop - Reverse";race.reverseCourse=true;race.opponentRoster=new[]{"moto","atv","moto"};course.anchors=new[]{new Vector3(441,Ground(new(441,0,8.5f)),8.5f),new(128,55.9f,80.7f),new(72.4f,38.1f,-94.1f),new(231.4f,61.2f,-25.6f),new(345.6f,81.1f,-8.8f),new(378.6f,78.8f,-9.8f)};course.launchStations=launchS;course.landingStations=landS;course.flightStarts=lips;course.flightDirections=axes;
var layout=root.gameObject.AddComponent<ForestLayout>();layout.jumpStarts=launchS;layout.jumpEnds=landS;layout.jumpNames=new[]{"Reverse north gully","Reverse south gully","Pool-house flight"};layout.approachLead=32;
var gates=new List<RaceGate>();var targets=new[]{new Vector3(441,0,8.5f),new(398,0,80),new(186,0,80),new(36,0,19),new(36,0,-89),new(170,0,-95),new(266,0,-24),new(330,0,-11)};
for(int i=0;i<targets.Length;i++){var p=targets[i];p.y=Ground(p);p=road.At(road.Project(p,out _),out var f);p.y=Ground(p);var g=Object.Instantiate(i==0?oldGates[0]:oldGates[1],root);g.name=i==0?"Reverse START FINISH":"Reverse blue CP "+i;g.transform.SetPositionAndRotation(p+Vector3.up*1.5f,Quaternion.LookRotation(Vector3.ProjectOnPlane(f,Vector3.up)));g.halfWidth=i==0?2.6f:3.3f;g.upperHeight=18;gates.Add(g);}
foreach(var g in oldGates)Object.DestroyImmediate(g.gameObject);race.gates=gates.ToArray();var spawn=race.vehicle.GetComponent<VehicleRespawn>().spawnPoint;var start=road.At(road.Project(gates[0].transform.position,out _)-7,out var startF);spawn.SetPositionAndRotation(start+Vector3.up*.55f,Quaternion.LookRotation(Vector3.ProjectOnPlane(startF,Vector3.up)));race.vehicle.transform.SetPositionAndRotation(spawn.position,spawn.rotation);
Trees(c=>{var p=c.bounds.center;float d=Near(p,path,out var at,out _);return d<6.2f&&c.bounds.max.y>at.y-10&&c.bounds.min.y<at.y+5;},c=>NewGround(c.bounds.center));
PaintTrail(root,road,forwardPoints,launchS,landS);Navigation(root,road,launchS,landS);Separators(root,road,forward);
foreach(var u in Object.FindObjectsByType<ShortcutUndergrowth>())u.protectedMain=road;
EditorUtility.SetDirty(race);EditorUtility.SetDirty(course);EditorBuildSettings.scenes=EditorBuildSettings.scenes.Append(new EditorBuildSettingsScene("Assets/Scenes/DansBackyardReverse.unity",true)).ToArray();Save();ExportReverse();File.WriteAllLines(Evidence+"/reverse-changes.txt",report);
}
static void PaintTrail(Transform root,RaceRoad road,Vector3[] forward,float[] starts,float[] ends){var v=new List<Vector3>();var tris=new List<int>();for(float s=1;s<road.Length-1;s+=1){if(Enumerable.Range(0,3).Any(j=>s>starts[j]-.4f&&s<ends[j]+.5f))continue;var p=road.At(s,out var f);if(p.x>390||Near(p,forward,out _,out _)<5.5f)continue;var side=Vector3.Cross(Vector3.up,f).normalized;int b=v.Count;foreach(float step in new[]{0f,1f}){var at=road.At(s+step,out var direction);var right=Vector3.Cross(Vector3.up,direction).normalized;foreach(float t in new[]{-2.65f,2.65f}){var q=at+right*t;q.y=Ground(q)+.018f;v.Add(q);}}tris.AddRange(new[]{b,b+2,b+1,b+1,b+2,b+3});}var mesh=new Mesh{indexFormat=UnityEngine.Rendering.IndexFormat.UInt32};mesh.SetVertices(v);mesh.SetTriangles(tris,0);mesh.RecalculateNormals();mesh.RecalculateBounds();var go=new GameObject("Narrow worn-earth Reverse trail",typeof(MeshFilter),typeof(MeshRenderer));go.transform.SetParent(root);go.GetComponent<MeshFilter>().sharedMesh=Store(mesh,"trail-color");var mat=new Material(Shader.Find("Universal Render Pipeline/Lit")){color=new(.36f,.29f,.18f)};AssetDatabase.CreateAsset(mat,Folder+"/Reverse worn earth.mat");go.GetComponent<Renderer>().sharedMaterial=mat;}
static void Navigation(Transform root,RaceRoad road,float[] starts,float[] ends){var mat=AssetDatabase.LoadAssetAtPath<Material>(AssetDatabase.FindAssets("CR117 main teal t:Material").Select(AssetDatabase.GUIDToAssetPath).First());for(float s=12;s<road.Length;s+=30){if(Enumerable.Range(0,3).Any(j=>s>starts[j]-5&&s<ends[j]+10))continue;var p=road.At(s,out var f);var go=new GameObject("Reverse teal ground arrow",typeof(MeshFilter),typeof(MeshRenderer));go.transform.SetParent(root);go.transform.SetPositionAndRotation(p,Quaternion.LookRotation(Vector3.ProjectOnPlane(f,Vector3.up)));float w=.65f;var v=new[]{new Vector3(-w*.4f,0,-1.7f),new(w*.4f,0,-1.7f),new(w*.4f,0,0),new(w,0,0),new(0,0,1.7f),new(-w,0,0),new(-w*.4f,0,0)};for(int i=0;i<v.Length;i++){var q=go.transform.TransformPoint(v[i]);q.y=Ground(q)+.03f;v[i]=go.transform.InverseTransformPoint(q);}var m=new Mesh{vertices=v,triangles=new[]{0,6,1,1,6,2,6,5,4,6,4,2,2,4,3}};m.RecalculateNormals();m.RecalculateBounds();go.GetComponent<MeshFilter>().sharedMesh=Store(m,"arrow");go.GetComponent<Renderer>().sharedMaterial=mat;}}
static void Separators(Transform root,RaceRoad road,RaceRoad forward){var mat=AssetDatabase.LoadAssetAtPath<Material>("Assets/Vegetation/Phase6/Forest.mat");var shape=AssetDatabase.LoadAssetAtPath<Mesh>("Assets/Vegetation/Phase6/IrregularCrown.asset");var centres=new List<Vector3>();var combine=new List<CombineInstance>();var random=new System.Random(46000);for(float s=0;s<road.Length;s+=5){var p=road.At(s,out var f);if(p.x<220||p.x>365||p.z>12||p.z<-35)continue;foreach(int sign in new[]{-1,1}){var at=p+Vector3.Cross(Vector3.up,f).normalized*(7+sign*.4f)*sign;at.y=Ground(at);if(Near(at,forward.points,out _,out _)<5||Near(at,road.points,out _,out _)<5)continue;centres.Add(at);for(int i=0;i<4;i++){var q=at+new Vector3((float)random.NextDouble()*3-1.5f,0,(float)random.NextDouble()*3-1.5f);q.y=Ground(q);combine.Add(new(){mesh=shape,transform=Matrix4x4.TRS(q,Quaternion.Euler(0,random.Next(360),0),new(1.4f,1.1f,1.4f))});}}}var m=new Mesh{indexFormat=UnityEngine.Rendering.IndexFormat.UInt32};m.CombineMeshes(combine.ToArray());var go=new GameObject("Reverse corridor traversable undergrowth",typeof(MeshFilter),typeof(MeshRenderer));go.transform.SetParent(root);go.GetComponent<MeshFilter>().sharedMesh=Store(m,"separator-bushes");go.GetComponent<Renderer>().sharedMaterial=mat;var u=go.AddComponent<ShortcutUndergrowth>();u.centres=centres.ToArray();u.radius=4;u.protectedMain=road;report.Add("Natural traversable bush clusters "+centres.Count+"; no rigid barriers");}
public static void ExportReverse(){var race=Object.FindAnyObjectByType<RaceDirector>();var c=race.GetComponent<BackyardForwardCourse>();File.WriteAllText(Evidence+"/geometry.json",Newtonsoft.Json.JsonConvert.SerializeObject(new{race.courseName,race.courseId,length=race.road.Length,route=race.road.points.Select(P),gates=race.gates.Select(g=>new{g.name,position=P(g.transform.position),g.halfWidth}),launches=c.flightStarts.Select(P),directions=c.flightDirections.Select(P),landings=c.landingStations.Select(s=>P(race.road.At(s,out _))),c.launchStations,c.landingStations},Newtonsoft.Json.Formatting.Indented));}
}
}

