using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;
using UnityEditor.SceneManagement;
using Object=UnityEngine.Object;
namespace Racer.Editor
{
    public static partial class DiscoveryAuthoring
    {
        public static void CR101CloseRemainingFence(){foreach(var scene in ReverseReviewRelease.Scenes){EditorSceneManager.OpenScene(scene);owner=Object.FindAnyObjectByType<RaceDirector>();var home=GameObject.Find("Dan - blue X").transform;worldRoot=GameObject.Find("CR101 local boundary extension").transform;piece=2200;if(worldRoot.Find("Rear final closure"))continue;RunFence(home.TransformPoint(new Vector3(-20,0,-27)),home.TransformPoint(new Vector3(-17.3f,0,-27)),false);new GameObject("Rear final closure").transform.SetParent(worldRoot,false);Save();}}
        public static void CR101CloseFence(){foreach(var scene in ReverseReviewRelease.Scenes){EditorSceneManager.OpenScene(scene);owner=Object.FindAnyObjectByType<RaceDirector>();var home=GameObject.Find("Dan - blue X").transform;worldRoot=GameObject.Find("CR101 local boundary extension").transform;piece=2100;if(worldRoot.Find("Rear closure applied"))continue;RunFence(home.TransformPoint(new Vector3(-29,0,-27)),home.TransformPoint(new Vector3(-20,0,-27)),false);new GameObject("Rear closure applied").transform.SetParent(worldRoot,false);Save();}}
        public static float HomewardHeight(float s){if(s<=160)return 152;float d=s-160;return 152+.0072f*d*d;}
        static float LandingHeight(float s){if(s<390)return 181.5f-(s-340)*.75f;if(s<=510){float d=s-390;return 144-.75f*d+.0025f*d*d;}return 90-(s-510)*.05f;}
        public static void CR103Return(){foreach(var scene in ReverseReviewRelease.Scenes){EditorSceneManager.OpenScene(scene);owner=Object.FindAnyObjectByType<RaceDirector>();var root=GameObject.Find("CR094 summit launch").transform;Vector3 P(float s,float x=0){var p=root.TransformPoint(new Vector3(x,0,s));p.y=LandingHeight(s);return p;}var route=root.GetComponentInChildren<RaceRoad>();var path=Curve(new[]{P(475),P(492,12),P(510,35),new Vector3(750,100,90),new(795,113,75),new(820,115,66)});int cut=Array.FindIndex(route.points,p=>root.InverseTransformPoint(p).z>474);route.points=route.points.Take(cut).Concat(path).ToArray();route.Initialize();Terrain("cr103-supported-return",p=>{float d=Near(p,path,out var at);if(d<18)p.y=Mathf.Lerp(p.y,at.y,1-Smooth(7,18,d));return p;});var old=root.Find("Ground_CR103 supported return");if(old)Object.DestroyImmediate(old.gameObject);var o=new GameObject("Ground_CR103 supported return",typeof(MeshFilter),typeof(MeshRenderer),typeof(MeshCollider));o.transform.SetParent(root,false);var v=new List<Vector3>();var triangles=new List<int>();for(int i=0;i<path.Length;i++){var side=Vector3.Cross(Vector3.up,path[Math.Min(i+1,path.Length-1)]-path[Math.Max(0,i-1)]).normalized*7;v.Add(root.InverseTransformPoint(path[i]-side+Vector3.up*.035f));v.Add(root.InverseTransformPoint(path[i]+side+Vector3.up*.035f));if(i<path.Length-1){int n=i*2;triangles.AddRange(new[]{n,n+2,n+1,n+1,n+2,n+3});}}var mesh=new Mesh();mesh.SetVertices(v);mesh.SetTriangles(triangles,0);mesh.RecalculateNormals();mesh.RecalculateBounds();o.GetComponent<MeshFilter>().sharedMesh=MeshAsset(mesh,"cr103-return");o.GetComponent<MeshCollider>().sharedMesh=o.GetComponent<MeshFilter>().sharedMesh;o.GetComponent<Renderer>().sharedMaterial=Mat("Summit packed earth",new(.43f,.31f,.17f));Save();}}
        public static void CR103Connection(){foreach(var scene in ReverseReviewRelease.Scenes){EditorSceneManager.OpenScene(scene);owner=Object.FindAnyObjectByType<RaceDirector>();var root=GameObject.Find("CR094 summit launch").transform;var route=root.GetComponentInChildren<RaceRoad>();int end=Array.FindIndex(route.points,p=>Vector3.Distance(p,root.position)<.1f);if(end<0)throw new Exception("No run-up entry");var curve=Curve(new[]{new Vector3(990,164,115),new(1040,153,130),new(1100,152,135),new(1160,152,150),new(1182,152,170),new(1190,152,188),root.position,root.TransformPoint(new Vector3(0,0,20))});var path=curve.Take(Array.FindIndex(curve,p=>Vector3.Distance(p,root.position)<.1f)+1).ToArray();route.points=path.Concat(route.points.Skip(end+1)).ToArray();route.Initialize();Terrain("cr103-inward-connection",p=>{float distance=Near(p,path,out var at);if(distance<16)p.y=Mathf.Lerp(p.y,at.y,1-Smooth(6,16,distance));return p;});var old=root.Find("Ground_CR103 supported connection");if(old)Object.DestroyImmediate(old.gameObject);var o=new GameObject("Ground_CR103 supported connection",typeof(MeshFilter),typeof(MeshRenderer),typeof(MeshCollider));o.transform.SetParent(root,false);var v=new List<Vector3>();var tris=new List<int>();for(int i=0;i<path.Length;i++){var side=Vector3.Cross(Vector3.up,path[Math.Min(path.Length-1,i+1)]-path[Math.Max(0,i-1)]).normalized*6;v.Add(root.InverseTransformPoint(path[i]-side+Vector3.up*.035f));v.Add(root.InverseTransformPoint(path[i]+side+Vector3.up*.035f));if(i<path.Length-1){int n=i*2;tris.AddRange(new[]{n,n+2,n+1,n+1,n+2,n+3});}}var mesh=new Mesh();mesh.SetVertices(v);mesh.SetTriangles(tris,0);mesh.RecalculateNormals();mesh.RecalculateBounds();o.GetComponent<MeshFilter>().sharedMesh=MeshAsset(mesh,"cr103-entry");o.GetComponent<MeshCollider>().sharedMesh=o.GetComponent<MeshFilter>().sharedMesh;o.GetComponent<Renderer>().sharedMaterial=Mat("Summit packed earth",new(.43f,.31f,.17f));Save();}}
        public static void CR103Landing(){foreach(var scene in ReverseReviewRelease.Scenes){EditorSceneManager.OpenScene(scene);owner=Object.FindAnyObjectByType<RaceDirector>();var root=GameObject.Find("CR094 summit launch").transform;
            Terrain("cr103-catch-landing",p=>{var q=root.InverseTransformPoint(p);if(q.z>320&&q.z<540&&Mathf.Abs(q.x)<43){float blend=Smooth(320,340,q.z)*(1-Smooth(515,540,q.z))*(1-Smooth(24,43,Mathf.Abs(q.x)));p.y=Mathf.Lerp(p.y,LandingHeight(q.z)-.06f,blend);}return p;});
            var old=root.Find("Ground_CR103 smooth landing");if(old)Object.DestroyImmediate(old.gameObject);var o=new GameObject("Ground_CR103 smooth landing",typeof(MeshFilter),typeof(MeshRenderer),typeof(MeshCollider));o.transform.SetParent(root,false);var v=new List<Vector3>();var tris=new List<int>();for(int i=0;i<=370;i++){float s=330+i*.5f;v.Add(new(-24,LandingHeight(s)-152,s));v.Add(new(24,LandingHeight(s)-152,s));if(i<370){int n=i*2;tris.AddRange(new[]{n,n+2,n+1,n+1,n+2,n+3});}}var m=new Mesh();m.SetVertices(v);m.SetTriangles(tris,0);m.RecalculateNormals();m.RecalculateBounds();o.GetComponent<MeshFilter>().sharedMesh=MeshAsset(m,"cr103-catch-landing");o.GetComponent<MeshCollider>().sharedMesh=o.GetComponent<MeshFilter>().sharedMesh;o.GetComponent<Renderer>().sharedMaterial=Mat("Summit packed earth",new(.43f,.31f,.17f));var route=root.GetComponentInChildren<RaceRoad>();for(int i=0;i<route.points.Length;i++){var q=root.InverseTransformPoint(route.points[i]);if(Mathf.Abs(q.x)<1&&q.z>=330&&q.z<500){var p=route.points[i];p.y=LandingHeight(q.z);route.points[i]=p;}}route.Initialize();Save();}}
        public static void CR101Property(){foreach(var scene in ReverseReviewRelease.Scenes){EditorSceneManager.OpenScene(scene);owner=Object.FindAnyObjectByType<RaceDirector>();var home=GameObject.Find("Dan - blue X").transform;var art=home.Find("Reference architecture");if(art.Find("CR101 layout applied"))continue;
            // The house faces the road: drawing-right is house-local negative X.
            foreach(var mf in art.GetComponentsInChildren<MeshFilter>()){var mesh=Object.Instantiate(mf.sharedMesh);var v=mesh.vertices;bool changed=false;for(int i=0;i<v.Length;i++){var q=home.InverseTransformPoint(mf.transform.TransformPoint(v[i]));if(q.z<-28&&q.x>-8&&q.x<14){q+=new Vector3(-40,1,19);changed=true;}else if(q.z<-28&&q.x>=-18&&q.x<=-10){q+=new Vector3(2,1.2f,15);changed=true;}else continue;v[i]=mf.transform.InverseTransformPoint(home.TransformPoint(q));}if(changed){mesh.vertices=v;mesh.RecalculateBounds();mesh.RecalculateNormals();mf.sharedMesh=MeshAsset(mesh,owner.gameObject.scene.name+"-cr101-"+mf.name);}else Object.DestroyImmediate(mesh);}
            art.Find("Separate downhill garage kennel").localPosition=new(-37,-4.5f,-18);art.Find("Smaller pool house left of garage").localPosition=new(-12,-4.3f,-19);
            var path=Enumerable.Range(0,35).Select(i=>home.TransformPoint(new Vector3(-22,Mathf.Lerp(-.8f,-4.5f,i/34f),9-i))).ToArray();
            Terrain("cr101-property",p=>{var q=home.InverseTransformPoint(p);if(q.x<-26&&q.x>-50&&q.z<-10&&q.z>-26){float blend=(1-Smooth(9,13,Mathf.Abs(q.x+37)))*(1-Smooth(5.8f,9,Mathf.Abs(q.z+18)));p.y=Mathf.Lerp(p.y,home.position.y-4.5f,blend);}float d=Near(p,path,out var at);if(d<6)p.y=Mathf.Lerp(p.y,at.y,1-Smooth(4,6,d));return p;});
            // Move only the side boundary crossed by the enlarged local property layout.
            worldRoot=new GameObject("CR101 local boundary extension").transform;piece=2000;foreach(var fence in Object.FindObjectsByType<BreakableProp>().Where(b=>b.GetComponentInChildren<Transform>()&&b.name.Contains("Grounded")).ToArray()){var q=home.InverseTransformPoint(fence.transform.position);if(q.x<-20&&q.x>-31&&q.z<8&&q.z>-28)Object.DestroyImmediate(fence.gameObject);}
            RunFence(home.TransformPoint(new(-29,0,8)),home.TransformPoint(new(-49,0,-8)),false);RunFence(home.TransformPoint(new(-49,0,-8)),home.TransformPoint(new(-49,0,-27)),false);RunFence(home.TransformPoint(new(-49,0,-27)),home.TransformPoint(new(-29,0,-27)),false);
            ClearTrees(p=>{var q=home.InverseTransformPoint(p);return q.x<-17&&q.x>-48&&q.z<9&&q.z>-26;});new GameObject("CR101 layout applied").transform.SetParent(art,false);Save();}}
        public static void CR103Geometry()
        {
            Directory.CreateDirectory("Docs/CR101-104");
            foreach(var scene in ReverseReviewRelease.Scenes){EditorSceneManager.OpenScene(scene);owner=Object.FindAnyObjectByType<RaceDirector>();var collection=owner.GetComponent<ExplorationCollection>();var home=GameObject.Find("Dan - blue X").transform.position;var center=new Vector3(990,0,150);var f=Vector3.ProjectOnPlane(home-center,Vector3.up).normalized;var root=GameObject.Find("CR094 summit launch").transform;root.SetPositionAndRotation(center-f*210+Vector3.up*152,Quaternion.LookRotation(f));
                Vector3 P(float s,float y,float x=0){var p=root.TransformPoint(new Vector3(x,0,s));p.y=y;return p;}
                var entry=Curve(new[]{new Vector3(990,164,115),new(1040,153,130),new(1100,152,135),new(1160,152,140),P(-24,152),P(0,152)});
                var exit=Curve(new[]{P(485,LandingHeight(485)),P(510,90,35),new Vector3(820,115,66)});
                Terrain("cr103-homeward",p=>{var q=root.InverseTransformPoint(p);float side=Mathf.Abs(q.x);if(q.z>=-25&&q.z<=221&&side<36)p.y=Mathf.Lerp(p.y,HomewardHeight(Mathf.Clamp(q.z,0,220))-.06f,(1-Smooth(14,36,side))*Smooth(-25,-10,q.z));if(q.z>=325&&q.z<500&&side<42)p.y=Mathf.Lerp(p.y,LandingHeight(q.z),(1-Smooth(23,42,side))*Smooth(325,345,q.z)*(1-Smooth(480,500,q.z)));foreach(var path in new[]{entry,exit}){float d=Near(p,path,out var at);if(d<16)p.y=Mathf.Lerp(p.y,at.y,1-Smooth(6,16,d));}return p;});
                var surface=root.GetComponentsInChildren<MeshFilter>().Single(m=>m.name=="Ground_Summit authored launch");var vertices=new List<Vector3>();var triangles=new List<int>();for(int i=0;i<=440;i++){float s=i*.5f;vertices.Add(new(-14,HomewardHeight(s)-152,s));vertices.Add(new(14,HomewardHeight(s)-152,s));if(i<440){int n=i*2;triangles.AddRange(new[]{n,n+2,n+1,n+1,n+2,n+3});}}var mesh=new Mesh();mesh.SetVertices(vertices);mesh.SetTriangles(triangles,0);mesh.RecalculateNormals();mesh.RecalculateBounds();surface.sharedMesh=MeshAsset(mesh,"cr103-runup");surface.GetComponent<MeshCollider>().sharedMesh=null;surface.GetComponent<MeshCollider>().sharedMesh=surface.sharedMesh;
                var site=root.GetComponentInChildren<ActivitySite>();site.transform.position=P(220,HomewardHeight(220));site.forward=f;
                var route=collection.routes.Single(r=>r.name=="Summit approach and safe return");route.points=entry.Concat(Enumerable.Range(1,22).Select(i=>P(i*10,HomewardHeight(i*10)))).Concat(Enumerable.Range(0,15).Select(i=>P(345+i*10,LandingHeight(345+i*10)))).Concat(exit.Skip(1)).ToArray();route.Initialize();
                var map=owner.GetComponent<ExplorationMap>();var destination=map.destinations.Single(d=>d.id=="summit-homeward");destination.position=P(5,152);destination.yaw=root.eulerAngles.y;destination.title="Summit Homeward Flight / run-up";
                ClearTrees(p=>{var q=root.InverseTransformPoint(p);return q.z>-25&&q.z<500&&Mathf.Abs(q.x)<32||Near(p,entry,out _)<10||Near(p,exit,out _)<10;});
                File.WriteAllText("Docs/CR101-104/geometry-"+owner.gameObject.scene.name+".txt",$"House {home:F3}; summit reference {center:F3}; heading {f:F6}; origin {root.position:F3}; lip {site.transform.position:F3}; 220m runway / stationary start at s5; no motor changes.\n");Save();}
        }
        public static void CR102Signs(){foreach(var scene in ReverseReviewRelease.Scenes){EditorSceneManager.OpenScene(scene);owner=Object.FindAnyObjectByType<RaceDirector>();var launch=GameObject.Find("CR094 summit launch").transform;var old=GameObject.Find("CR098 summit guidance");if(old)Object.DestroyImmediate(old);old=GameObject.Find("CR102 summit signs");if(old)Object.DestroyImmediate(old);worldRoot=new GameObject("CR102 summit signs").transform;
            var font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");var mat=AssetDatabase.LoadAssetAtPath<Material>(Folder+"/CR102 lettering.mat");if(!mat){mat=new Material(Shader.Find("Racer/SummitText"));mat.mainTexture=font.material.mainTexture;AssetDatabase.CreateAsset(mat,Folder+"/CR102 lettering.mat");}
            void Sign(string id,Vector3 p,Vector3 f,string value){var r=new GameObject(id).transform;r.SetParent(worldRoot);r.SetPositionAndRotation(Ground(p),Quaternion.LookRotation(f));var wood=Mat("Sign timber",new(.22f,.14f,.07f));Part(r,"Post",new(0,1.65f,0),new(.2f,3.3f,.2f),wood);Part(r,"Backing",new(0,2.7f,0),new(7,2.3f,.22f),wood);var t=new GameObject("Contained front lettering").AddComponent<TextMesh>();t.transform.SetParent(r,false);t.transform.localPosition=new(0,2.7f,-.125f);t.font=font;t.fontSize=64;t.characterSize=.1f;t.anchor=TextAnchor.MiddleCenter;t.alignment=TextAlignment.Center;t.color=new(1,.94f,.74f);t.text=value;font.RequestCharactersInTexture(value,64);var renderer=t.GetComponent<Renderer>();renderer.sharedMaterial=mat;var b=renderer.localBounds;float fit=Mathf.Min(6.3f/Mathf.Max(.01f,b.size.x),1.8f/Mathf.Max(.01f,b.size.y));t.transform.localScale=Vector3.one*fit;r.gameObject.AddComponent<PhysicalSign>();}
            Sign("01 approach",new(1040,0,134),new Vector3(50,0,15),"SUMMIT JUMP\nFOLLOW THE RUN-UP");
            Sign("02 run-up",launch.TransformPoint(new Vector3(10,0,18)),launch.forward,"HOMEWARD JUMP\nSTRAIGHT / FULL THROTTLE");
            Sign("03 launch",launch.TransformPoint(new Vector3(10,0,175)),launch.forward,"CLEAR THE SUMMIT\nLAND STRAIGHT");
            Sign("04 landing",launch.TransformPoint(new Vector3(20,0,395)),launch.forward,"LANDING\nBRAKE AFTER TOUCHDOWN");
            Sign("05 return",launch.TransformPoint(new Vector3(20,0,465)),launch.forward,"RIDGE RETURN\nBEAR RIGHT");Save();}}
    }
}


