using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;
using UnityEditor.SceneManagement;
using Object=UnityEngine.Object;
namespace Racer.Editor {
public static class ReverseShortcutsAuthoring {
 const string F="Assets/Track/ReverseShortcuts",D="Docs/ReverseShortcuts";
 static Transform root;static Material earth,concrete,wood,gold,metal,water;static RaceDirector race;
 static readonly List<string> report=new();static int asset;
 static float Flat(Vector3 a,Vector3 b)=>Vector2.Distance(new(a.x,a.z),new(b.x,b.z));
 static float Ground(Vector3 p)=>Physics.RaycastAll(new(p.x,300,p.z),Vector3.down,600,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).OrderBy(h=>h.distance).First().point.y;
 static object P(Vector3 p)=>new{x=p.x,y=p.y,z=p.z};
 static Material Mat(string n,Color c){var prior=AssetDatabase.LoadAssetAtPath<Material>(F+"/"+n+".mat");if(prior)return prior;var m=new Material(Shader.Find("Universal Render Pipeline/Lit")){name=n,color=c};AssetDatabase.CreateAsset(m,F+"/"+n+".mat");return m;}
 static Mesh Store(Mesh m,string n){m.RecalculateNormals();m.RecalculateBounds();string path=F+"/"+n+"-"+(asset++)+".asset";var prior=AssetDatabase.LoadAssetAtPath<Mesh>(path);if(prior){EditorUtility.CopySerialized(m,prior);Object.DestroyImmediate(m);return prior;}AssetDatabase.CreateAsset(m,path);return m;}
 static GameObject MeshPart(string n,List<Vector3> v,List<int> t,Material mat,bool solid=true){var m=new Mesh{indexFormat=UnityEngine.Rendering.IndexFormat.UInt32};m.SetVertices(v);m.SetTriangles(t,0);var uv=v.Select(p=>new Vector2(p.x,p.z)*.2f).ToArray();m.uv=uv;m=Store(m,n);var g=new GameObject(n,typeof(MeshFilter),typeof(MeshRenderer));g.transform.SetParent(root);g.GetComponent<MeshFilter>().sharedMesh=m;g.GetComponent<Renderer>().sharedMaterial=mat;if(solid)g.AddComponent<MeshCollider>().sharedMesh=m;return g;}
 static GameObject Box(string n,Vector3 p,Vector3 size,Quaternion q,Material mat,bool solid=true){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=n;g.transform.SetParent(root);g.transform.SetPositionAndRotation(p,q);g.transform.localScale=size;g.GetComponent<Renderer>().sharedMaterial=mat;if(!solid)Object.DestroyImmediate(g.GetComponent<Collider>());return g;}
 static Vector3[] Curve(Vector3[] k){var p=new List<Vector3>();for(int i=0;i<k.Length-1;i++){var a=k[Math.Max(0,i-1)];var b=k[i];var c=k[i+1];var d=k[Math.Min(k.Length-1,i+2)];int n=Mathf.CeilToInt(Flat(b,c)/.65f);for(int j=0;j<n;j++){float t=j/(float)n;p.Add(.5f*(2*b+(-a+c)*t+(2*a-5*b+4*c-d)*t*t+(-a+3*b-3*c+d)*t*t*t));}}p.Add(k[^1]);return p.ToArray();}
 static WoodlandRoute Branch(string title,Vector3[] points,int[] gates){var g=new GameObject(title);g.transform.SetParent(root);var b=g.AddComponent<WoodlandRoute>();b.title=title;b.points=points;b.halfWidth=2.7f;b.entryMargin=1;b.entryInset=4;b.entryRoad=race.road.Project(points[0],out _);b.exitRoad=race.road.Project(points[^1],out _);b.bypassedGates=gates;b.aiValidated=false;return b;}
 static void Strip(string n,WoodlandRoute b,float start,float end,float half,Material mat,bool skirts){var v=new List<Vector3>();var t=new List<int>();int rows=Mathf.CeilToInt((end-start)/.5f);int cols=skirts?4:2;for(int i=0;i<=rows;i++){var p=b.At(Mathf.Lerp(start,end,i/(float)rows),out var f);var r=Vector3.Cross(Vector3.up,f).normalized;foreach(float w in skirts?new[]{-half-1.8f,-half,half,half+1.8f}:new[]{-half,half}){var q=p+r*w;if(Math.Abs(w)>half)q.y=Ground(q)-.025f;v.Add(q);}if(i>0)for(int j=0;j<cols-1;j++){int a=(i-1)*cols+j;t.AddRange(new[]{a,a+cols,a+1,a+1,a+cols,a+cols+1});}}MeshPart(n,v,t,mat);}
 static void Arrow(WoodlandRoute b,float s){var p=b.At(s,out var f);var r=Vector3.Cross(Vector3.up,f).normalized;foreach(int sign in new[]{-1,1}){var a=p-f*.8f+r*.6f*sign;var z=p+f*.45f;Box("Gold optional shortcut arrow",(a+z)*.5f+Vector3.up*.045f,new(.13f,.035f,Vector3.Distance(a,z)),Quaternion.LookRotation(z-a),gold,false);}}
 static void Sign(string label,Vector3 p,Vector3 forward){p.y=Ground(p);var q=Quaternion.LookRotation(forward);Box("Grounded shortcut sign post",p+Vector3.up*1.1f,new(.14f,2.2f,.14f),q,wood);Box(label+" sign",p+Vector3.up*2,new(4.4f,.8f,.12f),q,wood,false);var g=new GameObject(label,typeof(TextMesh));g.transform.SetParent(root);g.transform.SetPositionAndRotation(p+Vector3.up*2-forward*.08f,q*Quaternion.Euler(0,180,0));var text=g.GetComponent<TextMesh>();text.text=label;text.anchor=TextAnchor.MiddleCenter;text.alignment=TextAlignment.Center;text.fontSize=56;text.characterSize=.085f;text.color=new(1,.76f,.25f);var m=new Material(text.GetComponent<Renderer>().sharedMaterial){shader=Shader.Find("Racer/SummitText")};AssetDatabase.CreateAsset(m,F+"/sign-"+(asset++)+".mat");text.GetComponent<Renderer>().sharedMaterial=m;}
 static void Ridge(){
 var knots=new[]{new Vector3(394.1f,0,79.4f),new(382,0,83),new(368,0,91),new(352,0,98),new(335,0,105),new(316,0,115),new(297,0,123),new(281.3f,0,124.9f),new(273,0,122)};
 var trees=Object.FindObjectsByType<Collider>().Where(c=>c.name.IndexOf("tree",StringComparison.OrdinalIgnoreCase)>=0||c.name.IndexOf("trunk",StringComparison.OrdinalIgnoreCase)>=0).ToArray();
 // Move the trail's intermediate anchors around complete existing trees; never
 // clear a straight corridor or touch any original tree/crown asset.
 for(int i=1;i<knots.Length-2;i++){var tangent=(knots[i+1]-knots[i-1]).normalized;var side=Vector3.Cross(Vector3.up,tangent);float best=float.MinValue;var chosen=knots[i];for(float offset=-6;offset<=6;offset+=.5f){var p=knots[i]+side*offset;float clearance=trees.Min(c=>Flat(c.bounds.center,p)-Mathf.Max(c.bounds.extents.x,c.bounds.extents.z));float score=Mathf.Min(clearance,7)-Math.Abs(offset)*.12f;if(score>best){best=score;chosen=p;}}knots[i]=chosen;}
 var points=Curve(knots);float len=0;var s=new float[points.Length];for(int i=1;i<points.Length;i++)s[i]=s[i-1]+Flat(points[i],points[i-1]);len=s[^1];var unshifted=points.ToArray();
 for(int i=0;i<points.Length;i++){float e=Mathf.SmoothStep(0,1,Mathf.Clamp01(s[i]/18))*Mathf.SmoothStep(0,1,Mathf.Clamp01((len-s[i])/32));points[i].y=Ground(points[i])+.035f+e*(1.25f+.22f*Mathf.Sin(s[i]*.16f));}
 var b=Branch("Abandoned Logging Ridge",points,Array.Empty<int>());b.halfWidth=2;b.entryInset=3;Strip("Ground_Abandoned logging earth ridge",b,0,b.Length,2,earth,true);Physics.SyncTransforms();
 foreach(float at in new[]{10f,35f,61f,88f,110f}){if(at>=b.Length)continue;Arrow(b,at);var p=b.At(at,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;var q=p+side*6.5f;q.y=Ground(q);Box("Weathered fallen logging timber",q+Vector3.up*.24f,new(.48f,.48f,3.3f),Quaternion.LookRotation(f+side*.3f),wood);}
 Sign("LOGGING RIDGE",points[0]+new Vector3(0,0,4),points[1]-points[0]);report.Add("Logging ridge length="+b.Length+" entry="+points[0]+" rejoin="+points[^1]+" AI disabled; original forest preserved");
 }
 static WoodlandRoute drain;static float tunnelEnd,jumpStart,jumpLip,land;
 static void Drain(){
 var k=new[]{new Vector3(179,0,80.7f),new(170,0,75),new(166.8f,62.7f,73),new(151,55.0f,72),new(140,48.0f,61),new(128,42.5f,45),new(117,39.8f,32),new(111,38.6f,25),new(107.9f,38.35f,21.1f),new(104.3f,36.95f,3),new(99.3f,37.3f,-13),new(95.8f,41.9f,-24),new(80.5f,40,-66),new(64,0,-67),new(45,0,-61),new(26,0,-50)};
 k[0].y=Ground(k[0])+.03f;k[1].y=Ground(k[1])+.03f;for(int i=13;i<k.Length;i++)k[i].y=Ground(k[i])+.035f;
 drain=Branch("Storm Drain / Gully Jump",Curve(k),new[]{3});drain.entryInset=15;drain.halfWidth=3.3f;
 tunnelEnd=drain.Project(k[8],out _);jumpStart=drain.Project(k[9],out _);jumpLip=drain.Project(k[11],out _);land=drain.Project(k[12],out _);
 // Smooth supported ramp to an intentional rising lip; flight has no collider.
 for(int i=0;i<drain.points.Length;i++){float s=drain.Project(drain.points[i],out _);if(s>=tunnelEnd&&s<jumpStart)drain.points[i].y=Ground(drain.points[i])+.25f;else if(s>=jumpStart&&s<=jumpLip){float u=(s-jumpStart)/(jumpLip-jumpStart);drain.points[i].y=36.95f-1.2f*u+6.15f*u*u;}}
 Strip("Culvert continuous floor",drain,0,tunnelEnd+1,4.5f,concrete,false);
 Strip("Ground_Gully straight launch",drain,tunnelEnd,jumpLip,3.4f,earth,true);
 Strip("Ground_Gully western landing and rejoin",drain,land,drain.Length,3.8f,earth,true);
 float entrance=drain.Project(k[2],out _);
 drain.undergroundStart=entrance;drain.undergroundEnd=tunnelEnd;
 // Welded side walls and roof form the bore; terrain above is preserved.
 var v=new List<Vector3>();var t=new List<int>();int count=Mathf.CeilToInt(tunnelEnd-entrance);
 for(int i=0;i<=count;i++){float s=Mathf.Lerp(entrance,tunnelEnd,i/(float)count);var p=drain.At(s,out var f);var r=Vector3.Cross(Vector3.up,f).normalized;foreach(var q in new[]{p-r*4.6f,p-r*4.6f+Vector3.up*6.5f,p+r*4.6f+Vector3.up*6.5f,p+r*4.6f})v.Add(q);if(i>0)for(int j=0;j<3;j++){int a=(i-1)*4+j;t.AddRange(new[]{a,a+1,a+4,a+1,a+5,a+4,a,a+4,a+1,a+1,a+4,a+5});}}
 var inward=new List<int>();for(int i=0;i<t.Count;i+=12)inward.AddRange(t.Skip(i).Take(6));concrete.SetFloat("_Cull",0);MeshPart("Storm culvert walls and roof",v,inward,concrete);
 foreach(float s in new[]{entrance,tunnelEnd}){var p=drain.At(s,out var f);f=Vector3.ProjectOnPlane(f,Vector3.up).normalized;var r=Vector3.Cross(Vector3.up,f);var q=Quaternion.LookRotation(f);foreach(int sign in new[]{-1,1})Box("Concrete culvert portal pier",p+r*5.0f*sign+Vector3.up*3.25f,new(.75f,7,.9f),q,concrete);Box("Concrete portal lintel",p+Vector3.up*6.8f,new(10.7f,.7f,.9f),q,concrete);}
 var ep=drain.At(entrance,out var ef);ef=Vector3.ProjectOnPlane(ef,Vector3.up).normalized;var er=Vector3.Cross(Vector3.up,ef);var grate=new GameObject("Forward closed drainage grate");grate.transform.SetParent(root);for(float x=-4.4f;x<=4.41f;x+=.55f){var bar=Box("Visible steel grate bar",ep+er*x+Vector3.up*3.2f,new(.15f,6.4f,.25f),Quaternion.LookRotation(ef),metal);bar.transform.SetParent(grate.transform);}var manager=root.gameObject.AddComponent<ReverseShortcutWorldState>();manager.grate=grate;manager.Refresh();
 for(float s=entrance+7;s<tunnelEnd-5;s+=12){var p=drain.At(s,out var f);var r=Vector3.Cross(Vector3.up,f).normalized;Box("Recessed drain edge channel",p+r*3.15f+Vector3.up*.02f,new(.25f,.02f,5),Quaternion.LookRotation(f),water,false);Box("Damp concrete joint",p+Vector3.up*5.35f,new(6.9f,.06f,.12f),Quaternion.LookRotation(f),metal,false);var lamp=new GameObject("Culvert maintenance light");lamp.transform.SetParent(root);lamp.transform.position=p+Vector3.up*4.9f;var light=lamp.AddComponent<Light>();light.type=LightType.Point;light.range=12;light.intensity=1.25f;light.color=new(.72f,.8f,.68f);}
 foreach(float s in new[]{5f,entrance+3,tunnelEnd+5,jumpStart+2,land+8})Arrow(drain,s);
 Sign("STORM DRAIN",k[0]+new Vector3(0,0,-5),k[1]-k[0]);Sign("GULLY JUMP",drain.At(jumpStart,out var dir)+Vector3.Cross(Vector3.up,dir).normalized*5,dir);
 report.Add($"Drain entrance station={entrance} exit={tunnelEnd} jumpStart={jumpStart} lip={jumpLip} landing={land}; branch length={drain.Length}; bypass CP3 only; AI disabled");
 }
 static void Portals(){
 // Remove only the terrain intersecting the open bore at its mouths. Triangles
 // over the underground section and every existing route support stay intact.
 var protectedRoads=Object.FindObjectsByType<RaceRoad>();
 bool Cut(Vector3 p){if(p.x<100||p.x>179||p.z<17||p.z>81)return false;float s=drain.Project(p,out float d);if(d>4.65f||s<8||s>tunnelEnd+1)return false;var floor=drain.At(s,out _);if(p.y<floor.y-.25f||p.y>floor.y+6.55f)return false;foreach(var road in protectedRoads){road.Project(p,out float lateral);if(lateral<3.8f)return false;}return true;}
 foreach(var mf in Object.FindObjectsByType<MeshFilter>().Where(m=>m.name.StartsWith("Ground_")&&m.GetComponent<MeshCollider>()&&!m.transform.IsChildOf(root)).ToArray()){
 var src=mf.sharedMesh;var vs=src.vertices;var ts=src.triangles;if(!vs.Any(p=>Cut(mf.transform.TransformPoint(p))))continue;
 var cs=src.colors;var uv=src.uv;var uv1=new List<Vector4>();src.GetUVs(1,uv1);var verts=new List<Vector3>();var colors=new List<Color>();var tex=new List<Vector2>();var tex1=new List<Vector4>();var inds=new List<int>();int removed=0;
 for(int a=0;a<ts.Length;a+=3){int ia=ts[a],ib=ts[a+1],ic=ts[a+2];var pa=mf.transform.TransformPoint(vs[ia]);var pb=mf.transform.TransformPoint(vs[ib]);var pc=mf.transform.TransformPoint(vs[ic]);bool near=Cut(pa)||Cut(pb)||Cut(pc)||Cut((pa+pb+pc)/3);int n=near?Mathf.Clamp(Mathf.CeilToInt(Mathf.Max(Vector3.Distance(pa,pb),Vector3.Distance(pa,pc))/.35f),1,24):1;
 void Triangle(Vector2 a,Vector2 b,Vector2 c){Vector3 At(Vector2 q)=>pa+(pb-pa)*q.x+(pc-pa)*q.y;var center=(At(a)+At(b)+At(c))/3;if(Cut(center)){removed++;return;}foreach(var q in new[]{a,b,c}){inds.Add(verts.Count);verts.Add(mf.transform.InverseTransformPoint(At(q)));colors.Add(cs.Length==vs.Length?cs[ia]+(cs[ib]-cs[ia])*q.x+(cs[ic]-cs[ia])*q.y:Color.white);tex.Add(uv.Length==vs.Length?uv[ia]+(uv[ib]-uv[ia])*q.x+(uv[ic]-uv[ia])*q.y:Vector2.zero);tex1.Add(uv1.Count==vs.Length?uv1[ia]+(uv1[ib]-uv1[ia])*q.x+(uv1[ic]-uv1[ia])*q.y:Vector4.zero);}}
 for(int j=0;j<n;j++)for(int k=0;k<n-j;k++){Triangle(new(j/(float)n,k/(float)n),new((j+1)/(float)n,k/(float)n),new(j/(float)n,(k+1)/(float)n));if(j+k<n-1)Triangle(new((j+1)/(float)n,k/(float)n),new((j+1)/(float)n,(k+1)/(float)n),new(j/(float)n,(k+1)/(float)n));}}
 if(removed==0)continue;var mesh=new Mesh{indexFormat=UnityEngine.Rendering.IndexFormat.UInt32};mesh.SetVertices(verts);mesh.SetTriangles(inds,0);mesh.SetColors(colors);mesh.SetUVs(0,tex);mesh.SetUVs(1,tex1);mesh=Store(mesh,"Portal terrain "+mf.name);mf.sharedMesh=mesh;mf.GetComponent<MeshCollider>().sharedMesh=mesh;report.Add("Portal cut "+mf.name+" triangles="+removed);
 }Physics.SyncTransforms();
 }
 public static void Build(){
 if(Application.isPlaying||UnityEngine.SceneManagement.SceneManager.GetActiveScene().isDirty)throw new Exception("Saved edit mode required");
 if(AssetDatabase.IsValidFolder(F))throw new Exception("Already authored; inspect before rerun");Directory.CreateDirectory(F);Directory.CreateDirectory(D);AssetDatabase.Refresh();report.Clear();asset=0;
 EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");Physics.SyncTransforms();race=Object.FindAnyObjectByType<RaceDirector>();root=new GameObject("Reverse optional forest shortcuts").transform;
 earth=Mat("Old logging earth",new(.35f,.26f,.15f));concrete=Mat("Damp storm concrete",new(.34f,.37f,.34f));wood=Mat("Old logging timber",new(.23f,.16f,.08f));gold=Mat("Optional route gold",new(1,.69f,.14f));metal=Mat("Dark weathered steel",new(.13f,.17f,.16f));water=Mat("Shallow edge drainage",new(.12f,.22f,.23f));
 Ridge();Drain();Portals();EditorSceneManager.MarkSceneDirty(root.gameObject.scene);EditorSceneManager.SaveScene(root.gameObject.scene);AssetDatabase.SaveAssets();
 File.WriteAllLines(D+"/authoring.txt",report);Export();
 }
 public static void Export(){var branches=Object.FindObjectsByType<WoodlandRoute>();File.WriteAllText(D+"/geometry.json",Newtonsoft.Json.JsonConvert.SerializeObject(new{branches=branches.Select(b=>new{b.title,b.entryRoad,b.exitRoad,b.Length,b.halfWidth,b.entryInset,b.bypassedGates,b.aiValidated,points=b.points.Select(P)}),tunnelEnd,jumpStart,jumpLip,land},Newtonsoft.Json.Formatting.Indented));}
 public static void RebuildCandidate(){
 EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");var old=GameObject.Find("Reverse optional forest shortcuts");if(old)Object.DestroyImmediate(old);
 var terrain=Newtonsoft.Json.Linq.JArray.Parse(File.ReadAllText(D+"/original-terrain.json"));foreach(var row in terrain){var g=GameObject.Find((string)row["name"]);if(!g)continue;var mf=g.GetComponent<MeshFilter>();if(!mf)continue;var m=AssetDatabase.LoadAssetAtPath<Mesh>(AssetDatabase.GUIDToAssetPath((string)row["guid"]));if(m){mf.sharedMesh=m;if(g.GetComponent<MeshCollider>())g.GetComponent<MeshCollider>().sharedMesh=m;}}
 Physics.SyncTransforms();race=Object.FindAnyObjectByType<RaceDirector>();root=new GameObject("Reverse optional forest shortcuts").transform;asset=200;report.Clear();earth=Mat("Old logging earth",new(.35f,.26f,.15f));concrete=Mat("Damp storm concrete",new(.34f,.37f,.34f));wood=Mat("Old logging timber",new(.23f,.16f,.08f));gold=Mat("Optional route gold",new(1,.69f,.14f));metal=Mat("Dark weathered steel",new(.13f,.17f,.16f));water=Mat("Shallow edge drainage",new(.12f,.22f,.23f));Ridge();Drain();Portals();foreach(var text in root.GetComponentsInChildren<TextMesh>())text.transform.rotation*=Quaternion.Euler(0,180,0);EditorSceneManager.MarkSceneDirty(root.gameObject.scene);EditorSceneManager.SaveScene(root.gameObject.scene);AssetDatabase.SaveAssets();Export();File.WriteAllLines(D+"/revised-authoring.txt",report);
 }
 public static void RebuildRidge(){
 EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");root=GameObject.Find("Reverse optional forest shortcuts").transform;race=Object.FindAnyObjectByType<RaceDirector>();asset=300;earth=Mat("Old logging earth",new(.35f,.26f,.15f));wood=Mat("Old logging timber",new(.23f,.16f,.08f));gold=Mat("Optional route gold",new(1,.69f,.14f));
 foreach(var t in root.Cast<Transform>().Where(t=>t.name.Contains("logging")||t.name=="Abandoned Logging Ridge"||t.name.Contains("LOGGING")||t.name=="Gold optional shortcut arrow"||t.name=="Grounded shortcut sign post"&&t.position.x>275).ToArray())Object.DestroyImmediate(t.gameObject);
 Physics.SyncTransforms();Ridge();drain=root.GetComponentsInChildren<WoodlandRoute>().First(b=>b.title.StartsWith("Storm"));foreach(float s in new[]{5f,18f,103f,119f,197f})Arrow(drain,s); var branch=root.GetComponentsInChildren<WoodlandRoute>().First(b=>b.title.StartsWith("Abandoned"));
 Func<Collider,bool> clear=c=>{var p=c.bounds.center;branch.Project(p,out float rd);float ds=drain.Project(p,out float dd);return (rd<2.8f||dd<3.4f&&ds>84&&ds<101)&&c.bounds.max.y>Math.Min(branch.At(branch.Project(p,out _),out _).y,drain.At(ds,out _).y)&&c.bounds.min.y<Math.Max(branch.At(branch.Project(p,out _),out _).y,drain.At(ds,out _).y)+5;};
 var trees=typeof(BackyardReverseAuthoring).GetMethod("Trees",System.Reflection.BindingFlags.Static|System.Reflection.BindingFlags.NonPublic);trees.Invoke(null,new object[]{clear,(Func<Collider,bool>)(c=>{branch.Project(c.bounds.center,out float d);return d<4;})});foreach(var text in root.GetComponentsInChildren<TextMesh>().Where(t=>t.text=="LOGGING RIDGE"))text.transform.rotation*=Quaternion.Euler(0,180,0);EditorSceneManager.MarkSceneDirty(root.gameObject.scene);EditorSceneManager.SaveScene(root.gameObject.scene);AssetDatabase.SaveAssets();File.WriteAllLines(D+"/ridge-repair.txt",report);
 }
 public static void FinishCorridors(){
 EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");root=GameObject.Find("Reverse optional forest shortcuts").transform;race=Object.FindAnyObjectByType<RaceDirector>();asset=500;drain=root.GetComponentsInChildren<WoodlandRoute>().First(b=>b.title.StartsWith("Storm"));var ridge=root.GetComponentsInChildren<WoodlandRoute>().First(b=>b.title.StartsWith("Abandoned"));var roads=Object.FindObjectsByType<RaceRoad>();float lip=drain.Project(new(95.8f,0,-24),out _),landing=drain.Project(new(80.5f,0,-66),out _);
 bool Protected(Vector3 p){foreach(var road in roads){road.Project(p,out float d);if(d<3.8f)return true;}return false;}
 Func<Collider,bool> clear=c=>{var p=c.bounds.center;if(Protected(p))return false;ridge.Project(p,out float rd);float s=drain.Project(p,out float dd);return rd<3.2f||dd<4.1f&&(s>drain.undergroundEnd-15&&s<lip||s>landing-12);};
 int removed=Object.FindObjectsByType<Collider>().Count(c=>(c.name.ToLower().Contains("tree")||c.name.ToLower().Contains("trunk"))&&clear(c));
 typeof(BackyardReverseAuthoring).GetMethod("Trees",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Static).Invoke(null,new object[]{clear,(Func<Collider,bool>)(c=>{ridge.Project(c.bounds.center,out float d);return d<4&&!Protected(c.bounds.center);})});
 var centres=new List<Vector3>();for(float s=16;s<ridge.Length-24;s+=5){var p=ridge.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;foreach(int sign in new[]{-1,1}){var q=p+side*6.2f*sign;if(!Protected(q)){q.y=Ground(q);centres.Add(q);}}}for(float s=lip+7;s<landing-4;s+=5){var p=drain.At(s,out _);if(!Protected(p)){p.y=Ground(p);centres.Add(p);}}
 var go=new GameObject("Slow recoverable shortcut edge brush");go.transform.SetParent(root);var brush=go.AddComponent<ShortcutUndergrowth>();brush.centres=centres.ToArray();brush.radius=3.7f;brush.protectedMain=race.road;var sphere=GameObject.CreatePrimitive(PrimitiveType.Sphere);var shape=sphere.GetComponent<MeshFilter>().sharedMesh;var combined=new List<CombineInstance>();foreach(var p in centres)for(int j=0;j<3;j++){var q=p+new Vector3(Mathf.Sin(j*2.1f)*1.5f,0,Mathf.Cos(j*2.1f)*1.5f);q.y=Ground(q);combined.Add(new(){mesh=shape,transform=Matrix4x4.TRS(q+Vector3.up*.6f,Quaternion.Euler(0,j*43,0),new Vector3(2.7f,1.2f,2.7f))});}var mesh=new Mesh{indexFormat=UnityEngine.Rendering.IndexFormat.UInt32};mesh.CombineMeshes(combined.ToArray());mesh=Store(mesh,"Shortcut recovery brush");go.AddComponent<MeshFilter>().sharedMesh=mesh;go.AddComponent<MeshRenderer>().sharedMaterial=Mat("Dense logging brush",new(.18f,.27f,.10f));Object.DestroyImmediate(sphere);
 Physics.SyncTransforms();EditorSceneManager.MarkSceneDirty(root.gameObject.scene);EditorSceneManager.SaveScene(root.gameObject.scene);AssetDatabase.SaveAssets();File.WriteAllText(D+"/corridor-support.txt",$"Additional complete trees cleared only from driving/landing line: {removed}; brush clusters: {centres.Count}; main-route clearance protected. No reset trigger or invisible wall.");
 }
 public static void ShareWorld(){
 EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");root=GameObject.Find("Reverse optional forest shortcuts").transform;race=Object.FindAnyObjectByType<RaceDirector>();var branches=root.GetComponentsInChildren<WoodlandRoute>();drain=branches.First(b=>b.title.StartsWith("Storm"));var ridge=branches.First(b=>b.title.StartsWith("Abandoned"));drain.entryInset=30;drain.entryHeightAbove=3.2f;drain.entryHeightBelow=1.5f;drain.entryMargin=.5f;wood=Mat("Old logging timber",new(.23f,.16f,.08f));
 var p=ridge.At(14,out var f);var gate=Box("Forward closed logging trail gate",p+Vector3.up*.85f,new(5.0f,1.7f,.35f),Quaternion.LookRotation(Vector3.ProjectOnPlane(f,Vector3.up)),wood);root.GetComponent<ReverseShortcutWorldState>().ridgeGate=gate;root.GetComponent<ReverseShortcutWorldState>().Refresh();
 foreach(var b in root.GetComponentsInChildren<ShortcutUndergrowth>())b.protectedMain=null;
 var prefab=PrefabUtility.SaveAsPrefabAssetAndConnect(root.gameObject,F+"/Reverse optional shortcuts.prefab",InteractionMode.AutomatedAction);
 foreach(var b in root.GetComponentsInChildren<ShortcutUndergrowth>())b.protectedMain=race.road;
 race.courseId="backyard-reverse-v2-forest-shortcuts";EditorUtility.SetDirty(race);EditorSceneManager.MarkSceneDirty(root.gameObject.scene);EditorSceneManager.SaveScene(root.gameObject.scene);
 var finalGeometry=branches.Select(b=>new{b.title,b.entryRoad,b.exitRoad,b.Length,b.halfWidth,b.entryInset,b.entryHeightAbove,b.bypassedGates,b.aiValidated,b.undergroundStart,b.undergroundEnd,points=b.points.Select(P)}).ToArray();File.WriteAllText(D+"/geometry.json",Newtonsoft.Json.JsonConvert.SerializeObject(new{branches=finalGeometry,tunnelEnd=drain.undergroundEnd,jumpStart=drain.Project(new(104.3f,0,3),out _),jumpLip=drain.Project(new(95.8f,0,-24),out _),land=drain.Project(new(80.5f,0,-66),out _)},Newtonsoft.Json.Formatting.Indented));
 EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardForward.unity");race=Object.FindAnyObjectByType<RaceDirector>();root=((GameObject)PrefabUtility.InstantiatePrefab(prefab)).transform;root.name="Reverse optional forest shortcuts";drain=root.GetComponentsInChildren<WoodlandRoute>().First(b=>b.title.StartsWith("Storm"));ridge=root.GetComponentsInChildren<WoodlandRoute>().First(b=>b.title.StartsWith("Abandoned"));tunnelEnd=drain.undergroundEnd;asset=700;Physics.SyncTransforms();Portals();
 var roads=Object.FindObjectsByType<RaceRoad>();bool Protected(Vector3 v){foreach(var road in roads){road.Project(v,out float d);if(d<3.8f)return true;}return false;}
 Func<Collider,bool> clear=c=>{if(Protected(c.bounds.center))return false;ridge.Project(c.bounds.center,out float rd);float s=drain.Project(c.bounds.center,out float dd);return rd<3.2f||dd<4.1f&&(s>drain.undergroundEnd-15&&s<145||s>177);};
 typeof(BackyardReverseAuthoring).GetMethod("Trees",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Static).Invoke(null,new object[]{clear,(Func<Collider,bool>)(c=>{ridge.Project(c.bounds.center,out float d);return d<4&&!Protected(c.bounds.center);})});
 foreach(var b in root.GetComponentsInChildren<ShortcutUndergrowth>())b.protectedMain=race.road;
 foreach(var b in root.GetComponentsInChildren<WoodlandRoute>())Object.DestroyImmediate(b);
 root.GetComponent<ReverseShortcutWorldState>().Refresh();EditorSceneManager.MarkSceneDirty(root.gameObject.scene);EditorSceneManager.SaveScene(root.gameObject.scene);AssetDatabase.SaveAssets();File.WriteAllText(D+"/world-state.txt","Single shared prefab in both Backyard scenes; Forward removes only new branch metadata and closes grate/logging gate. Reverse opens both. Free roam opens both. Existing Forward branches unchanged. Reverse record identity v2; historical records retained.");EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");
 } public static void CorrectCandidate(){
 EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");Physics.SyncTransforms();root=GameObject.Find("Reverse optional forest shortcuts").transform;race=Object.FindAnyObjectByType<RaceDirector>();asset=100;earth=AssetDatabase.LoadAssetAtPath<Material>(F+"/Old logging earth.mat");concrete=AssetDatabase.LoadAssetAtPath<Material>(F+"/Damp storm concrete.mat");gold=AssetDatabase.LoadAssetAtPath<Material>(F+"/Optional route gold.mat");
 float OriginalGround(Vector3 p)=>Physics.RaycastAll(new(p.x,300,p.z),Vector3.down,600,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")&&!h.collider.transform.IsChildOf(root)).OrderBy(h=>h.distance).Select(h=>h.point.y).DefaultIfEmpty(p.y-.18f).First();
 var ridge=root.GetComponentsInChildren<WoodlandRoute>().First(b=>b.title.StartsWith("Abandoned"));drain=root.GetComponentsInChildren<WoodlandRoute>().First(b=>b.title.StartsWith("Storm"));
 var rp=ridge.points.ToArray();for(int i=0;i<rp.Length;i++){float s=ridge.Project(rp[i],out _);if(s>60&&s<96){ridge.At(s,out var f);rp[i]+=Vector3.Cross(Vector3.up,f).normalized*(3.5f*Mathf.Pow(Mathf.Sin(Mathf.PI*(s-60)/36),2));}}
 ridge.points=rp;typeof(WoodlandRoute).GetField("lengths",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance).SetValue(ridge,null);
 Object.DestroyImmediate(GameObject.Find("Ground_Abandoned logging earth ridge"));Strip("Ground_Logging ridge corrected around existing tree",ridge,0,ridge.Length,2,earth,true);
 var dp=drain.points.ToArray();for(int i=0;i<dp.Length;i++){float s=drain.Project(dp[i],out _);if(s>=91&&s<115){float h=OriginalGround(dp[i])+.18f;dp[i].y=Mathf.Lerp(dp[i].y,h,Mathf.SmoothStep(0,1,Mathf.InverseLerp(91,98,s)));}else if(s>=115&&s<=142.4681f){float u=(s-115)/(142.4681f-115);dp[i].y=36.95f-1.2f*u+6.15f*u*u;}}
 drain.points=dp;tunnelEnd=95.68018f;jumpStart=115;jumpLip=142.4681f;land=187.2764f;
 Object.DestroyImmediate(GameObject.Find("Ground_Gully straight launch"));Object.DestroyImmediate(GameObject.Find("Culvert continuous floor"));Strip("Culvert continuous floor",drain,0,tunnelEnd+1,4.5f,concrete,false);Strip("Ground_Gully straight launch",drain,tunnelEnd,jumpLip,3.4f,earth,true);
 // Keep inward-facing collision triangles. Opposite duplicate faces cancelled
 // normals and produced visible black bands on the first candidate.
 var wall=GameObject.Find("Storm culvert walls and roof").GetComponent<MeshFilter>();var mesh=Object.Instantiate(wall.sharedMesh);var old=mesh.triangles;var tri=new List<int>();for(int i=0;i<old.Length;i+=12)tri.AddRange(old.Skip(i).Take(6));mesh.triangles=tri.ToArray();Store(mesh,"Culvert inward faces");wall.sharedMesh=mesh;wall.GetComponent<MeshCollider>().sharedMesh=mesh;concrete.SetFloat("_Cull",0);EditorUtility.SetDirty(concrete);
 foreach(var text in root.GetComponentsInChildren<TextMesh>())text.transform.rotation*=Quaternion.Euler(0,180,0);
 foreach(var arrow in root.Cast<Transform>().Where(t=>t.name=="Gold optional shortcut arrow").ToArray())Object.DestroyImmediate(arrow.gameObject);
 foreach(float s in new[]{10f,35f,61f,88f,110f})Arrow(ridge,s);foreach(float s in new[]{5f,18f,101f,117f,195f})Arrow(drain,s);
 Physics.SyncTransforms();EditorUtility.SetDirty(ridge);EditorUtility.SetDirty(drain);EditorSceneManager.MarkSceneDirty(root.gameObject.scene);EditorSceneManager.SaveScene(root.gameObject.scene);AssetDatabase.SaveAssets();Export();File.WriteAllText(D+"/correction.txt","One tree avoided by local ridge shift; gully run matched to actual floor; tunnel normals repaired; sign fronts corrected.");
 }
}
}
