var dir="Docs/Phase6Environment";var rows=new System.Collections.Generic.List<string>();var ambience=UnityEngine.Object.FindAnyObjectByType<Racer.WoodlandAmbience>();var sources=ambience.GetComponentsInChildren<AudioSource>();var wind=sources.Single(s=>s.loop);var bird=sources.Single(s=>!s.loop);var race=UnityEngine.Object.FindAnyObjectByType<Racer.RaceDirector>();
void Check(bool ok,string message){rows.Add((ok?"PASS ":"FAIL ")+message);}
foreach(var clip in new[]{ambience.wind}.Concat(ambience.birds)){var data=new float[clip.samples*clip.channels];clip.GetData(data,0);double sum=0;float peak=0,maxDelta=0;for(int i=0;i<data.Length;i++){sum+=data[i]*data[i];peak=Mathf.Max(peak,Mathf.Abs(data[i]));if(i>0)maxDelta=Mathf.Max(maxDelta,Mathf.Abs(data[i]-data[i-1]));}float seam=Mathf.Abs(data[0]-data[data.Length-1]);Check(peak<.99f,clip.name+": duration="+clip.length+"s peak="+peak+" RMS="+Math.Sqrt(sum/data.Length)+" loop seam="+seam+" max adjacent="+maxDelta);}
int sample=wind.timeSamples;race.RestartRace();Check(wind.isPlaying&&wind.timeSamples==sample&&ambience.GetComponentsInChildren<AudioSource>().Length==2,"Race restart preserves wind playback position and two sources");UnityEngine.Object.FindAnyObjectByType<Racer.VehicleRespawn>().ResetVehicle();Check(wind.isPlaying&&wind.timeSamples==sample,"Vehicle reset preserves ambient playback");
var camera=Camera.main;var chase=camera.GetComponent<Racer.ChaseCamera>();chase.enabled=false;var position=camera.transform.position;camera.transform.position=new Vector3(0,15,550);float started=Time.realtimeSinceStartup,lastVolume=wind.volume,maxStep=0,peakOutput=0;int lastSample=wind.timeSamples,wraps=0,birdStarts=0;bool wasBird=bird.isPlaying;var buffer=new float[1024];int frame=Time.frameCount;
UnityEditor.EditorApplication.CallbackFunction tick=null;
tick=()=>{if(Time.frameCount==frame)return;frame=Time.frameCount;float elapsed=Time.realtimeSinceStartup-started;maxStep=Mathf.Max(maxStep,Mathf.Abs(wind.volume-lastVolume));lastVolume=wind.volume;if(wind.timeSamples<lastSample)wraps++;lastSample=wind.timeSamples;wind.GetOutputData(buffer,0);foreach(float x in buffer)peakOutput=Mathf.Max(peakOutput,Mathf.Abs(x));if(bird.isPlaying&&!wasBird)birdStarts++;wasBird=bird.isPlaying;if(elapsed>12)camera.transform.position=new Vector3(470,85,30);if(elapsed<38)return;UnityEditor.EditorApplication.update-=tick;Check(wraps>=1&&wind.isPlaying,"31-second wind loop continues; observed wraps="+wraps);Check(maxStep<.015f,"Smooth commercial/woodland gain transition; largest frame step="+maxStep);Check(peakOutput>0&&peakOutput<.2f,"Measured source output peak="+peakOutput);Check(ambience.GetComponentsInChildren<AudioSource>().Length==2,"Still two sources after restarts and transitions; bird starts observed="+birdStarts);rows.Add("Objective audio checks only; speaker/headphone listening balance requires Dan. No physical controller.");System.IO.File.WriteAllLines(dir+"/audio.txt",rows);camera.transform.position=position;chase.enabled=true;chase.Snap();};
UnityEditor.EditorApplication.update+=tick;
return "38-second audio observation started";
