var dir="Docs/Phase6Environment";var rows=new System.Collections.Generic.List<string>();int fail=0;
void Check(bool ok,string s){rows.Add((ok?"PASS ":"FAIL ")+s);if(!ok)fail++;}
var sites=GameObject.Find(Racer.Editor.Phase6Review.Root).transform.Cast<Transform>().ToArray();var now=sites.Select(t=>t.name+"|"+t.position.ToString("F6")+"|"+t.rotation.ToString("F6")).ToArray();Check(now.SequenceEqual(System.IO.File.ReadAllLines(dir+"/sites-before.txt")),"All 47 building positions and rotations match checkpoint");Check(!GameObject.Find("Original house 1"),"House 1 remains absent");
int floating=0,buried=0;foreach(var t in sites){var f=t.Find("Foundation");float floor=t.position.y+t.Find("Phase 6 architecture").localPosition.y;foreach(float x in new[]{-.5f,.5f})foreach(float z in new[]{-.5f,.5f}){var p=f.TransformPoint(new Vector3(x,-.5f,z));float y=Racer.Editor.Phase6Buildings.Ground(p);if(p.y-y>.05f)floating++;if(y>floor+.05f)buried++;}}Check(floating==0&&buried==0,"Foundation corners: floating="+floating+", above floor="+buried+"; no foundation adjustment necessary");
var coords=new System.Collections.Generic.Dictionary<Vector2,Vector3>();var colors=new System.Collections.Generic.Dictionary<Vector2,Color>();var uvs=new System.Collections.Generic.Dictionary<Vector2,Vector4>();int seams=0,colorSeams=0,uvSeams=0;var ground=GameObject.Find("Memory loop - north is +Z");
foreach(var f in ground.GetComponentsInChildren<MeshFilter>()){var m=f.sharedMesh;var v=m.vertices;var n=m.normals;var c=m.colors;var uv=new System.Collections.Generic.List<Vector4>();m.GetUVs(1,uv);for(int i=0;i<v.Length;i++){var k=new Vector2(v[i].x,v[i].z);var d=new Vector3(v[i].y,n[i].x,n[i].z);if(coords.TryGetValue(k,out var old)&&Vector3.Distance(old,d)>.00001f)seams++;coords[k]=d;if(colors.TryGetValue(k,out var oldColor)&&Vector4.Distance(oldColor,c[i])>.001f)colorSeams++;colors[k]=c[i];if(uv.Count==v.Length&&Mathf.Abs(uv[i].x)<5&&uv[i].z>.9f){if(uvs.TryGetValue(k,out var oldUv)&&Vector4.Distance(oldUv,uv[i])>.01f)uvSeams++;uvs[k]=uv[i];}}}
Check(seams==0,"Terrain boundary height/normal mismatches="+seams);Check(colorSeams==0,"Terrain boundary color mismatches="+colorSeams);Check(uvSeams==0,"Road paint UV boundary mismatches="+uvSeams);Check(ground.GetComponentsInChildren<MeshFilter>().All(f=>f.sharedMesh==f.GetComponent<MeshCollider>().sharedMesh),"Every visible terrain mesh is also its collision mesh");
Check(GameObject.Find("Woods replacing later subdivisions").GetComponentsInChildren<BoxCollider>().Length==11995,"11995 solid trees retained");Check(Mathf.Abs(Mathf.PI*Racer.Editor.CompactYard.Radius*Racer.Editor.CompactYard.Radius-2250.869f)<.01f,"Compact yard boundary unchanged");Check(UnityEngine.Object.FindObjectsByType<Racer.BreakableProp>().Length==18,"18 breakable props retained");Check(UnityEngine.Object.FindObjectsByType<Light>().Length==1,"One daytime directional light");Check(UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.Rendering.Universal.UniversalRendererData>("Assets/Settings/PC_Renderer.asset").rendererFeatures.Count==0,"No enabled or dormant PC renderer features requiring build-only stripping");
rows.Add("RESULT failures="+fail);System.IO.File.WriteAllLines(dir+"/geometry.txt",rows);return rows;
