using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class ApplyWorldCleanup {
 const string Out="Docs/WorldCleanup",Folder="Assets/Vegetation/WorldCleanup";
 static float Near(Vector3 p,Vector3[] pts){float best=float.MaxValue;for(int i=1;i<pts.Length;i++){var a=pts[i-1];var v=pts[i]-a;v.y=0;var q=p-a;q.y=0;float t=Mathf.Clamp01(Vector3.Dot(q,v)/Mathf.Max(.001f,v.sqrMagnitude));best=Mathf.Min(best,(q-v*t).sqrMagnitude);}return Mathf.Sqrt(best);}
 static Vector3 Ground(Vector3 p){var hits=Physics.RaycastAll(p+Vector3.up*500,Vector3.down,1000,~0,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).OrderBy(h=>h.distance).ToArray();if(hits.Length==0)throw new Exception("No terrain at "+p);return hits[0].point;}
 static object P(Vector3 p)=>new{x=p.x,y=p.y,z=p.z};
 public static string Main(){if(Application.isPlaying||UnityEngine.SceneManagement.SceneManager.GetActiveScene().isDirty)throw new Exception("Saved edit mode required");Directory.CreateDirectory(Out);Directory.CreateDirectory(Folder);AssetDatabase.Refresh();EditorApplication.delayCall+=Run;return "Scoped world cleanup scheduled";}
 static void Run(){var original=UnityEngine.SceneManagement.SceneManager.GetActiveScene().path;try{var report=new List<object>();foreach(var sceneName in RacePlaylists.Scenes){File.AppendAllText(Out+"/apply-progress.txt",sceneName+" starting\n");var scene=EditorSceneManager.OpenScene("Assets/Scenes/"+sceneName+".unity");Physics.SyncTransforms();var race=Object.FindAnyObjectByType<RaceDirector>();var map=race.GetComponent<ExplorationMap>();
 var marker=GameObject.Find("TEMPORARY Backyard anchor validation - no route");int removed=marker?marker.GetComponentsInChildren<Renderer>().Length:0;if(marker)Object.DestroyImmediate(marker);
 race.courseName=RacePlaylists.Titles[Array.IndexOf(RacePlaylists.Scenes,sceneName)];EditorUtility.SetDirty(race);
 var names=new[]{"Dan - blue X","Original house 2","Original house 3","Friend across street - blue circle"};var titles=new[]{"Moll's","Roger's","McFadden's","Anderson's"};var ids=new[]{"home","property-roger","property-mcfadden","property-anderson"};var homes=names.Select(n=>GameObject.Find(n).transform).ToArray();var destinations=map.destinations.ToList();
 for(int i=0;i<4;i++){var d=destinations.FirstOrDefault(d=>d.id==ids[i]);if(d==null){d=new ExplorationMap.Destination{id=ids[i]};destinations.Add(d);}d.title=titles[i];d.position=Ground(homes[i].position+homes[i].forward*18);d.yaw=Quaternion.LookRotation(homes[i].forward).eulerAngles.y;}
 map.destinations=destinations.ToArray();EditorUtility.SetDirty(map);
 foreach(var text in Object.FindObjectsByType<TextMesh>())if(text.text.Contains("KYLE'S WOODED DRIVE")){text.text=text.text.Replace("KYLE'S WOODED DRIVE","ANDERSON'S");EditorUtility.SetDirty(text);}
 var collection=race.GetComponent<ExplorationCollection>();foreach(var s in collection.sites){if(s.title=="Kyle's turning")s.title="Anderson's";if(s.title=="House 2 approach")s.title="Roger's approach";}EditorUtility.SetDirty(collection);
 if(GameObject.Find("World cleanup additional woodland"))throw new Exception("Already applied; inspect before rerunning");var root=new GameObject("World cleanup additional woodland").transform;
 var roads=Object.FindObjectsByType<RaceRoad>().Where(r=>r.points!=null&&r.points.Length>1).ToArray();var branches=Object.FindObjectsByType<WoodlandRoute>();var shrubs=Object.FindObjectsByType<ShortcutUndergrowth>().Select(s=>s.GetComponent<Renderer>().bounds).ToArray();var gates=race.gates.Select(g=>g.transform.position).ToArray();
 var shapes=new[]{"BroadCrown","IrregularCrown","UprightCrown"}.Select(n=>AssetDatabase.LoadAssetAtPath<Mesh>("Assets/Vegetation/Phase6/"+n+".asset")).ToArray();var trunk=AssetDatabase.LoadAssetAtPath<Mesh>("Assets/Vegetation/Phase6/Trunk.asset");var material=AssetDatabase.LoadAssetAtPath<Material>("Assets/Vegetation/Phase6/Forest.mat");
 var pieces=new Dictionary<Vector2Int,List<CombineInstance>>();var temps=new List<Mesh>();var positions=new List<Vector3>();var random=new System.Random(45000);float R(float a,float b)=>Mathf.Lerp(a,b,(float)random.NextDouble());
 var existing=Object.FindObjectsByType<BoxCollider>().Where(c=>c.name.Contains("Tree")||c.name.Contains("Trunk")||c.name.Contains("trunk")).Select(c=>c.bounds.center).ToArray();var solid=Object.FindObjectsByType<Collider>().Where(c=>!c.isTrigger&&!c.name.StartsWith("Ground_")&&!(c is TerrainCollider)&&!c.GetComponentInParent<ArcadeVehicle>()).ToArray();int screen=0;
 for(int candidate=0;candidate<15000&&positions.Count<720;candidate++){
 bool screening=candidate<1500;Vector3 p;if(screening){var house=homes[3];p=house.position+house.forward*R(11,42)+house.right*R(-38,38);}else{var road=roads[candidate%roads.Length];int ix=random.Next(road.points.Length-1);var f=Vector3.ProjectOnPlane(road.points[ix+1]-road.points[ix],Vector3.up).normalized;p=road.points[ix]+Vector3.Cross(Vector3.up,f)*R(17,62)*(candidate%2==0?1:-1)+f*R(-12,12);}
 // The accepted Backyard stunts, dump, ravine and slow ground-recovery field are untouched.
 if(p.x>0&&p.x<345&&p.z>-190&&p.z<155)continue;
 if(homes.Any(h=>{var q=h.InverseTransformPoint(p);return Mathf.Abs(q.x)<(h==homes[3]?13:23)&&q.z>-(h==homes[3]?15:30)&&q.z<(h==homes[3]?11:18);}))continue;
 if(roads.Any(r=>Near(p,r.points)<(r.name.Contains("drive")||r.name.Contains("Drive")?9:r.forestTrail?11:14)))continue;
 if(branches.Any(b=>Near(p,b.points)<b.halfWidth+7)||gates.Any(g=>Vector2.Distance(new(p.x,p.z),new(g.x,g.z))<20))continue;
 if(shrubs.Any(b=>p.x>b.min.x-7&&p.x<b.max.x+7&&p.z>b.min.z-7&&p.z<b.max.z+7))continue;
 if(collection.sites.Any(s=>Near(p,new[]{s.access,s.position})<7))continue;
 if(existing.Any(q=>Vector2.Distance(new(p.x,p.z),new(q.x,q.z))<4)||positions.Any(q=>Vector2.Distance(new(p.x,p.z),new(q.x,q.z))<(screening?5.5f:7)))continue;
 var hits=Physics.RaycastAll(new(p.x,500,p.z),Vector3.down,900,~0,QueryTriggerInteraction.Ignore).OrderBy(h=>h.distance).ToArray();if(hits.Length==0||!hits[0].collider.name.StartsWith("Ground_")||hits[0].normal.y<.82f)continue;p=hits[0].point;
 if(solid.Any(c=>{var b=c.bounds;b.Expand(new Vector3(8,0,8));return b.Contains(p+Vector3.up*2);}))continue;
 float height=screening?R(14,20):R(10,18),radius=height*R(.25f,.32f);var key=new Vector2Int(Mathf.FloorToInt(p.x/160),Mathf.FloorToInt(p.z/160));if(!pieces.TryGetValue(key,out var batch))pieces[key]=batch=new();
 var crown=Object.Instantiate(shapes[random.Next(3)]);var tint=Color.Lerp(new(.24f,.34f,.19f),new(.39f,.46f,.25f),R(0,1));crown.colors=Enumerable.Repeat(tint,crown.vertexCount).ToArray();temps.Add(crown);batch.Add(new(){mesh=crown,transform=Matrix4x4.TRS(p+Vector3.up*height*.34f,Quaternion.Euler(0,R(0,360),0),new(radius,height*.69f,radius))});
 var bark=Object.Instantiate(trunk);bark.colors=Enumerable.Repeat(new Color(.25f,.20f,.145f),bark.vertexCount).ToArray();temps.Add(bark);var size=new Vector3(.6f,height*.62f,.6f);var center=p+Vector3.up*size.y*.5f;batch.Add(new(){mesh=bark,transform=Matrix4x4.TRS(center,Quaternion.identity,size)});var collider=new GameObject(screening?"Anderson woodland trunk":"Roadside woodland trunk").AddComponent<BoxCollider>();collider.transform.SetParent(root);collider.transform.position=center;collider.size=size;positions.Add(p);if(screening)screen++;
 }
 foreach(var pair in pieces){var mesh=new Mesh{indexFormat=UnityEngine.Rendering.IndexFormat.UInt32};mesh.CombineMeshes(pair.Value.ToArray());AssetDatabase.CreateAsset(mesh,Folder+"/"+sceneName+"-"+pair.Key.x+"-"+pair.Key.y+".asset");var go=new GameObject("Additional woodland canopy",typeof(MeshFilter),typeof(MeshRenderer));go.transform.SetParent(root);go.GetComponent<MeshFilter>().sharedMesh=mesh;go.GetComponent<MeshRenderer>().sharedMaterial=material;}foreach(var m in temps)Object.DestroyImmediate(m);
 Physics.SyncTransforms();report.Add(new{scene=sceneName,removedMarkerRenderers=removed,trees=positions.Count,andersonTrees=screen,positions=positions.Select(P).ToArray(),destinations=map.destinations.Select(d=>new{d.id,d.title,position=P(d.position)}).ToArray()});EditorSceneManager.MarkSceneDirty(scene);EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();File.AppendAllText(Out+"/apply-progress.txt",sceneName+" saved trees="+positions.Count+" Anderson="+screen+"\n");}
 File.WriteAllText(Out+"/implementation.json",Newtonsoft.Json.JsonConvert.SerializeObject(report,Newtonsoft.Json.Formatting.Indented));PlayerSettings.bundleVersion="0.45.0-review1";AssetDatabase.SaveAssets();File.WriteAllText(Out+"/apply-done.txt","Completed scoped scene changes");}catch(Exception e){File.WriteAllText(Out+"/apply-error.txt",e.ToString());}finally{EditorSceneManager.OpenScene(original);}}
}
