using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class AuditWorldCleanup {
 static object P(Vector3 p)=>new{x=p.x,y=p.y,z=p.z};
 public static string Main(){if(Application.isPlaying||UnityEngine.SceneManagement.SceneManager.GetActiveScene().isDirty)throw new Exception("Saved edit mode required");Directory.CreateDirectory("Docs/WorldCleanup");EditorApplication.delayCall+=Run;return "Audit scheduled";}
 static void Run(){string original=UnityEngine.SceneManagement.SceneManager.GetActiveScene().path;try{var rows=new List<object>();foreach(var scene in RacePlaylists.Scenes){EditorSceneManager.OpenScene("Assets/Scenes/"+scene+".unity");Physics.SyncTransforms();var race=Object.FindAnyObjectByType<RaceDirector>();var collection=race.GetComponent<ExplorationCollection>();
 var homes=new[]{"Dan - blue X","Original house 2","Original house 3","Friend across street - blue circle"}.Select(n=>{var t=GameObject.Find(n).transform;return new{name=n,position=P(t.position),forward=P(t.forward)};}).ToArray();
 var sites=collection.sites.Where(s=>s.approach=="Western gullies").Select(s=>new{s.id,s.title,s.approach,position=P(s.position),access=P(s.access),ground=Physics.RaycastAll(s.position+Vector3.up*250,Vector3.down,500).Where(h=>h.collider.name.StartsWith("Ground_")).Select(h=>new{h.collider.name,point=P(h.point)}).ToArray()}).ToArray();
 rows.Add(new{scene,race.courseName,homes,destinations=race.GetComponent<ExplorationMap>().destinations.Select(d=>new{d.id,d.title,position=P(d.position),d.yaw}).ToArray(),sites,roads=Object.FindObjectsByType<RaceRoad>().Select(r=>new{r.name,r.forestTrail,count=r.points.Length,points=r.points.Select(P).ToArray()}).ToArray(),branches=Object.FindObjectsByType<WoodlandRoute>().Select(r=>new{r.name,r.title,points=r.points.Select(P).ToArray()}).ToArray(),markers=Object.FindObjectsByType<Transform>().Where(t=>t.name.Contains("anchor validation")).Select(t=>t.name).ToArray()});}
 File.WriteAllText("Docs/WorldCleanup/audit.json",Newtonsoft.Json.JsonConvert.SerializeObject(rows,Newtonsoft.Json.Formatting.Indented));}catch(Exception e){File.WriteAllText("Docs/WorldCleanup/audit-error.txt",e.ToString());}finally{EditorSceneManager.OpenScene(original);}}
}
