using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class AuditReverseCorrections {
 public static string Main(){if(Application.isPlaying||UnityEngine.SceneManagement.SceneManager.GetActiveScene().isDirty)throw new Exception("Saved edit mode required");EditorApplication.delayCall+=Run;return "Inspect saved Reverse surfaces, divergences and local collision";}
 static object P(Vector3 p)=>new{x=p.x,y=p.y,z=p.z};
 static void Run(){const string folder="Docs/BackyardReverseCorrections";Directory.CreateDirectory(folder);try{EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");Physics.SyncTransforms();var race=Object.FindAnyObjectByType<RaceDirector>();race.road.Initialize();var forward=Object.FindObjectsByType<RaceRoad>().First(r=>r.name=="Forward navigation only - no road mesh");forward.Initialize();
 var centres=new[]{new Vector3(230.2f,60.1f,-32.9f),new(188,69,82.5f),new(15.8f,37.4f,-61.8f),new(48.6f,42.8f,82.2f),new(130.4f,42.9f,-92.4f),new(326,78.1f,-11.7f),new(416.6f,84.7f,82.1f),new(172.2f,46.3f,-98.9f),new(235,60.7f,-31.3f)};
 var rows=new List<object>();var camGo=new GameObject("Temporary inspection camera");var cam=camGo.AddComponent<Camera>();cam.CopyFrom(Camera.main);cam.enabled=false;cam.nearClipPlane=.1f;cam.farClipPlane=1000;
 for(int i=0;i<centres.Length;i++){var p=centres[i];float station=race.road.Project(p,out _);var samples=new List<object>();for(float d=-35;d<=35;d+=.5f){var q=race.road.At(station+d,out var f);var hits=Physics.RaycastAll(new(q.x,250,q.z),Vector3.down,500,~0,QueryTriggerInteraction.Ignore).OrderBy(h=>h.distance).Select(h=>new{name=h.collider.name,y=h.point.y,normal=P(h.normal),type=h.collider.GetType().Name}).ToArray();samples.Add(new{d,p=P(q),hits});}
 var near=Object.FindObjectsByType<Collider>().Where(c=>Vector2.Distance(new(c.bounds.ClosestPoint(p).x,c.bounds.ClosestPoint(p).z),new(p.x,p.z))<16).Select(c=>new{c.name,type=c.GetType().Name,min=P(c.bounds.min),max=P(c.bounds.max),trigger=c.isTrigger}).ToArray();
 rows.Add(new{i,reference=P(p),station,forwardStation=forward.Project(p,out _),samples,near});
 cam.transform.SetPositionAndRotation(p+new Vector3(0,65,-24),Quaternion.LookRotation(new Vector3(0,-65,24)));var rt=new RenderTexture(1200,900,24);cam.targetTexture=rt;cam.Render();var old=RenderTexture.active;RenderTexture.active=rt;var tex=new Texture2D(1200,900,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,1200,900),0,0);tex.Apply();File.WriteAllBytes(folder+"/after-"+i+".png",tex.EncodeToPNG());RenderTexture.active=old;cam.targetTexture=null;rt.Release();Object.DestroyImmediate(tex);Object.DestroyImmediate(rt);
 }Object.DestroyImmediate(camGo);
 var trail=GameObject.Find("Narrow worn-earth Reverse trail");var mat=trail?trail.GetComponent<Renderer>().sharedMaterial:null;
 File.WriteAllText(folder+"/after-audit.json",Newtonsoft.Json.JsonConvert.SerializeObject(new{race.courseId,branches=Object.FindObjectsByType<WoodlandRoute>().Select(b=>b.name),route=race.road.points.Select(P),forward=forward.points.Select(P),trail=new{material=mat?AssetDatabase.GetAssetPath(mat):"removed",shader=mat?mat.shader.name:"terrain",color=mat?mat.color.ToString():"established dirt",vertices=trail?trail.GetComponent<MeshFilter>().sharedMesh.vertexCount:0},rows},Newtonsoft.Json.Formatting.Indented));File.WriteAllText(folder+"/after-audit-done.txt","Saved geometry audit complete");}catch(Exception e){File.WriteAllText(folder+"/after-audit-error.txt",e.ToString());}}
}

