UnityEditor.EditorApplication.delayCall+=()=>{try{
UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");Physics.SyncTransforms();
var ridge=UnityEngine.Object.FindObjectsByType<Racer.WoodlandRoute>().First(b=>b.title.StartsWith("Abandoned Logging"));var drain=UnityEngine.Object.FindObjectsByType<Racer.WoodlandRoute>().First(b=>b.title.StartsWith("Storm"));
var mf=GameObject.Find("Ground_Gully straight launch").GetComponent<MeshFilter>();
var rows=new List<string>();foreach(var b in new[]{ridge,drain})for(float s=1;s<b.Length-1;s+=1){if(b==drain&&s>drain.Project(new Vector3(95.8f,0,-24),out _)&&s<drain.Project(new Vector3(80.5f,0,-66),out _))continue;var p=b.At(s,out var f);var hits=Physics.OverlapBox(p+Vector3.up*1.1f,new Vector3(.95f,.55f,.6f),Quaternion.LookRotation(Vector3.ProjectOnPlane(f,Vector3.up)),1,QueryTriggerInteraction.Ignore).Where(c=>c!=null&&!c.GetComponentInParent<Racer.ArcadeVehicle>()&&!c.name.Contains("floor")&&!c.name.Contains("ridge")&&!c.name.Contains("launch")&&!c.name.Contains("landing"));foreach(var c in hits)rows.Add(b.title+" s="+s+" p="+p+" obstacle="+c.name);}
System.IO.File.WriteAllLines("Docs/ReverseShortcuts/clearance.txt",rows);
var go=new GameObject("Temporary shortcut camera");var cam=go.AddComponent<Camera>();cam.CopyFrom(Camera.main);cam.enabled=false;bool fog=RenderSettings.fog;RenderSettings.fog=false;
void Shot(string name,Vector3 eye,Vector3 target,float size){cam.orthographic=size>0;cam.orthographicSize=Mathf.Max(1,size);cam.fieldOfView=65;cam.transform.SetPositionAndRotation(eye,Quaternion.LookRotation(target-eye));var rt=new RenderTexture(1500,1000,24);var prior=RenderTexture.active;cam.targetTexture=rt;cam.Render();RenderTexture.active=rt;var tex=new Texture2D(1500,1000,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,1500,1000),0,0);tex.Apply();System.IO.File.WriteAllBytes("Docs/ReverseShortcuts/"+name+".png",tex.EncodeToPNG());RenderTexture.active=prior;cam.targetTexture=null;rt.Release();UnityEngine.Object.DestroyImmediate(rt);UnityEngine.Object.DestroyImmediate(tex);}
Shot("ridge-candidate",new Vector3(360,160,150),new Vector3(340,78,103),60);Shot("entrance-candidate",new Vector3(185,70,86),new Vector3(157,58,69),0);Shot("gully-candidate",new Vector3(50,80,-10),new Vector3(104,37,-5),48);Shot("tunnel-candidate",drain.At(40,out _)+Vector3.up*2,drain.At(53,out _)+Vector3.up*2,0);
RenderSettings.fog=fog;UnityEngine.Object.DestroyImmediate(go);UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(mf.gameObject.scene);UnityEditor.SceneManagement.EditorSceneManager.SaveScene(mf.gameObject.scene);UnityEditor.AssetDatabase.SaveAssets();System.IO.File.WriteAllText("Docs/ReverseShortcuts/audit-done.txt","Clearance findings="+rows.Count);
}catch(Exception e){System.IO.File.WriteAllText("Docs/ReverseShortcuts/audit-error.txt",e.ToString());}};return "Scheduled targeted clearance and visual audit";
