using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
// Local saved-scene repair. Route/navigation/checkpoint transforms are never changed.
public static class ReportCleanup {
 const string Folder="Assets/Track/ReportCleanup";
 struct V {public Vector3 p;public Color c;public V(Vector3 p,Color c){this.p=p;this.c=c;}public static V Lerp(V a,V b,float t)=>new V(Vector3.Lerp(a.p,b.p,t),Color.Lerp(a.c,b.c,t));}
 class Face {public List<V> v;public Face(params V[] a){v=a.ToList();}}
 static Color Earth=new(.39f,.48f,.29f),Rock=new(.34f,.36f,.29f);
 static V E(Vector3 p)=>new(p,Earth);static V R(Vector3 p)=>new(p,Rock);
 static List<V> Clip(List<V> poly,Plane plane,bool inside){var result=new List<V>();for(int i=0;i<poly.Count;i++){var a=poly[i];var b=poly[(i+1)%poly.Count];float da=plane.GetDistanceToPoint(a.p),db=plane.GetDistanceToPoint(b.p);bool ia=inside?da>=-.00001f:da<=.00001f,ib=inside?db>=-.00001f:db<=.00001f;if(ia)result.Add(a);if(ia!=ib)result.Add(V.Lerp(a,b,da/(da-db)));}return result;}
 static IEnumerable<Face> Subtract(Face f,Plane[] planes){foreach(var plane in planes)if(f.v.All(v=>plane.GetDistanceToPoint(v.p)<-.00001f))return new[]{f};var intersection=f.v;foreach(var p in planes){intersection=Clip(intersection,p,true);if(intersection.Count<3)return new[]{f};}var outside=new List<Face>();var rest=f.v;foreach(var p in planes){var part=Clip(rest,p,false);if(part.Count>=3)outside.Add(new Face(part.ToArray()));rest=Clip(rest,p,true);if(rest.Count<3)break;}return outside;}
 static Plane[] Box(Vector3 a,Vector3 b,float width,float bottom,float top){var f=Vector3.ProjectOnPlane(b-a,Vector3.up).normalized;var right=Vector3.Cross(Vector3.up,f);var up=Vector3.Cross(b-a,right).normalized;if(up.y<0)up=-up;return new[]{new Plane(f,a-f*.15f),new Plane(-f,b+f*.15f),new Plane(right,a-right*width),new Plane(-right,a+right*width),new Plane(up,a+Vector3.up*bottom),new Plane(-up,a+Vector3.up*top)};}
 static List<Face> Read(MeshFilter mf){var m=mf.sharedMesh;var v=m.vertices;var c=m.colors;var t=m.triangles;return Enumerable.Range(0,t.Length/3).Select(i=>new Face(Enumerable.Range(0,3).Select(j=>{int k=t[i*3+j];return new V(mf.transform.TransformPoint(v[k]),c.Length==v.Length?c[k]:Earth);}).ToArray())).ToList();}
 static Mesh Store(string name,List<Face> faces){var vs=new List<Vector3>();var cs=new List<Color>();var ix=new List<int>();foreach(var face in faces)for(int j=1;j+1<face.v.Count;j++){var a=face.v[0];var b=face.v[j];var c=face.v[j+1];if(Vector3.Cross(b.p-a.p,c.p-a.p).sqrMagnitude<.00000001f)continue;int k=vs.Count;vs.AddRange(new[]{a.p,b.p,c.p});cs.AddRange(new[]{a.c,b.c,c.c});ix.AddRange(new[]{k,k+1,k+2});}var mesh=new Mesh{indexFormat=UnityEngine.Rendering.IndexFormat.UInt32};mesh.SetVertices(vs);mesh.SetColors(cs);mesh.SetTriangles(ix,0);mesh.RecalculateNormals();mesh.RecalculateBounds();string path=Folder+"/"+name+".asset";var old=AssetDatabase.LoadAssetAtPath<Mesh>(path);if(old){EditorUtility.CopySerialized(mesh,old);Object.DestroyImmediate(mesh);return old;}AssetDatabase.CreateAsset(mesh,path);return mesh;}
 static void Assign(MeshFilter mf,string name,List<Face> faces){var mesh=Store(name,faces);mf.transform.SetPositionAndRotation(Vector3.zero,Quaternion.identity);mf.transform.localScale=Vector3.one;mf.sharedMesh=mesh;if(mf.TryGetComponent<MeshCollider>(out var mc)){mc.sharedMesh=null;mc.sharedMesh=mesh;}}
 static void Quad(List<Face> f,Vector3 a,Vector3 b,Vector3 c,Vector3 d,bool rock=false,bool doubleSide=false){var col=rock?Rock:Earth;f.Add(new Face(new(a,col),new(b,col),new(c,col)));f.Add(new Face(new(a,col),new(c,col),new(d,col)));if(doubleSide){f.Add(new Face(new(c,col),new(b,col),new(a,col)));f.Add(new Face(new(d,col),new(c,col),new(a,col)));}}
 static bool Local(Vector3 p)=>p.x>855&&p.x<1060&&p.z>-112&&p.z<185;
 static GameObject Make(string name,List<Face> fs,Material mat){var g=new GameObject("Ground_"+name,typeof(MeshFilter),typeof(MeshRenderer),typeof(MeshCollider));g.GetComponent<MeshRenderer>().sharedMaterial=mat;Assign(g.GetComponent<MeshFilter>(),name,fs);return g;}
 static void Save(){var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene();EditorSceneManager.MarkSceneDirty(scene);EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();}
 public static string Signs(){
 if(Application.isPlaying)throw new Exception("Edit mode required");var notes=new List<string>();
 foreach(var path in EditorBuildSettings.scenes.Select(s=>s.path).Concat(new[]{"Assets/Scenes/MountainLoop.unity","Assets/Scenes/MountainLoopReverse.unity"}).Distinct()){
 EditorSceneManager.OpenScene(path);int removed=0;
 foreach(var sign in Object.FindObjectsByType<PhysicalSign>()){
 string text=string.Join(" / ",sign.GetComponentsInChildren<TextMesh>().Select(t=>t.text.Replace('\n',' ').ToUpperInvariant()));
 bool redundant=text.Contains("FOLLOW TEAL")||text.Contains("FOLLOW AMBER BOARDS")||text.Contains("BIG FLIGHT AHEAD")||text.Contains("SUMMIT JUMP")||text.Contains("HOMEWARD JUMP")||text.Contains("CLEAR THE SUMMIT")||text.Contains("BRAKE AFTER TOUCHDOWN")||text.Contains("TWO BIG FLIGHTS")||text.Contains("HOMEWARD SUMMIT FLIGHT")||text.Contains("LEFT FORK")&&text.Contains("SUMMIT TRAVERSE");
 if(!redundant)continue;notes.Add(path+" | REMOVE "+sign.name+" | "+text+" | "+sign.transform.position);Object.DestroyImmediate(sign.gameObject);removed++;
 }Save();notes.Add(path+" removed="+removed+"; named landmarks, optional-route labels and nonobvious hazard signs retained");File.WriteAllLines("Docs/ReportCleanup/sign-dispositions.txt",notes);
 }return "Conservative sign audit saved";
 }
 static void SeatTrees(Func<Collider,bool> affected,MeshCollider driving){
 bool Supported(Collider c)=>Physics.RaycastAll(new(c.bounds.center.x,500,c.bounds.center.z),Vector3.down,1000,1,QueryTriggerInteraction.Ignore).Any(h=>h.collider.name.StartsWith("Ground_"));
 typeof(Racer.Editor.BackyardReverseAuthoring).GetMethod("Trees",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Static).Invoke(null,new object[]{(Func<Collider,bool>)(c=>affected(c)&&(!Supported(c)||driving.Raycast(new Ray(new(c.bounds.center.x,230,c.bounds.center.z),Vector3.down),out _,260))),(Func<Collider,bool>)(c=>affected(c)&&Supported(c))});
 }
 public static string FinishForwardDependencies(){Physics.SyncTransforms();bool Area(Vector3 p)=>(p.x>=1168&&p.x<=1412&&p.z>=-336&&p.z<=-198)||(p.x>=1198&&p.x<=1342&&p.z>=154&&p.z<=284)||(p.x>=726&&p.x<=1082&&p.z>=32&&p.z<=164);SeatTrees(c=>Area(c.bounds.center),GameObject.Find("Ground_CR133 mountain driving surface").GetComponent<MeshCollider>());Save();return "Forward complete tree assemblies grounded; landing corridor trees removed";}
 public static string AllDetails(){Props();return SeatDetails();}
 public static string FinishReverseFinalDependencies(){Physics.SyncTransforms();SeatTrees(c=>c.bounds.center.x>=740&&c.bounds.center.x<=1100&&c.bounds.center.z>=-212&&c.bounds.center.z<=356,GameObject.Find("Ground_CR133 mountain driving surface").GetComponent<MeshCollider>());Save();return "Final Reverse tree grounding complete";}
 public static string Props(){var notes=new List<string>();foreach(var t in Object.FindObjectsByType<Transform>().Where(t=>t.name.StartsWith("Acorn clue /")&&t.position.x>=740&&t.position.x<=1412&&t.position.z>=-336&&t.position.z<=356)){var renderers=t.GetComponentsInChildren<Renderer>();if(renderers.Length==0)continue;float foot=renderers.Min(r=>r.bounds.min.y);var p=t.position;var hits=Physics.RaycastAll(new(p.x,foot+20,p.z),Vector3.down,70,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).OrderBy(h=>Mathf.Abs(h.point.y-foot)).ToArray();if(hits.Length>0){t.position+=Vector3.up*(hits[0].point.y-foot);notes.Add("Grounded landmark cairn "+t.name+" "+t.position);}}Save();File.WriteAllLines("Docs/ReportCleanup/"+UnityEngine.SceneManagement.SceneManager.GetActiveScene().name+"-props.txt",notes);return "Grounded dependent landmark props="+notes.Count;}
 public static string Details(){
 var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene().name;bool reverse=scene.EndsWith("Reverse");var driving=GameObject.Find("Ground_CR133 mountain driving surface").GetComponent<MeshCollider>();var road=Object.FindAnyObjectByType<RaceDirector>().road;var branch=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title=="Summit Traverse");branch.Initialize();road.Initialize();var mat=GameObject.Find("Ground_CR133 mountain earth banks").GetComponent<Renderer>().sharedMaterial;int stones=0,arrows=0;
 void Stone(Vector3 q,float width,float length,float height){
 var hits=Physics.RaycastAll(q+Vector3.up*4,Vector3.down,14,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).OrderBy(h=>Mathf.Abs(h.point.y-q.y)).ToArray();if(hits.Length==0)return;q.y=hits[0].point.y-.3f;
 // Reject placements on either nearby driving layer.
 float bs=branch.Project(q,out float bd);if(bd<branch.halfWidth+1&&Mathf.Abs(branch.At(bs,out _).y-q.y)<4)return;float rs=road.Project(q,out float rd);if(rd<8.3f&&Mathf.Abs(road.At(rs,out _).y-q.y)<4)return;
 var faces=new List<Face>();Vector3 Ring(int ring,int i){float a=i*Mathf.PI/4+.11f*ring;float r=(ring==0?1: ring==1?1.04f:ring==2?.74f:.30f)*(1+.11f*Mathf.Sin(i*3.1f+stones));return q+new Vector3(Mathf.Cos(a)*width*.5f*r,ring*height/3+Mathf.Sin(i*2+ring)*height*.08f,Mathf.Sin(a)*length*.5f*r);}
 for(int r=0;r<3;r++)for(int i=0;i<8;i++)Quad(faces,Ring(r,i),Ring(r,(i+1)%8),Ring(r+1,(i+1)%8),Ring(r+1,i),true);for(int i=0;i<8;i++)faces.Add(new Face(R(Ring(3,i)),R(Ring(3,(i+1)%8)),R(q+Vector3.up*(height+height*.05f))));foreach(var face in faces)face.v.Reverse();Make("ReportCleanup "+scene+" natural edge "+stones++,faces,mat);
 }
 if(reverse){foreach(float s in new[]{18f,34f,50f}){var p=branch.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;Stone(p+side*9.8f,5.2f,7,2.6f);Stone(p-side*10.4f,5.2f,7,2.6f);}foreach(float s in new[]{178f,186f,194f,202f}){var p=branch.At(s,out var f);Stone(p-Vector3.Cross(Vector3.up,f).normalized*10,5.4f,7,3.1f);}}
 else {foreach(var p in new[]{new Vector3(1003,160,114),new Vector3(1009,160,116),new Vector3(997,160,110)})Stone(p,5.8f,5.2f,2.8f);}
 foreach(var mf in Object.FindObjectsByType<MeshFilter>().Where(m=>m.sharedMesh&&(m.name.IndexOf("arrow",StringComparison.OrdinalIgnoreCase)>=0||m.name.Contains("Main teal")||m.name.Contains("gold"))).ToArray()){
 var vertices=mf.sharedMesh.vertices;bool changed=false;for(int i=0;i<vertices.Length;i++){var p=mf.transform.TransformPoint(vertices[i]);if(p.x<830||p.x>1075||p.z<-142||p.z>170)continue;if(driving.Raycast(new Ray(p+Vector3.up*4,Vector3.down),out var hit,8)){p.y=hit.point.y+.10f;vertices[i]=mf.transform.InverseTransformPoint(p);changed=true;}}
 if(!changed)continue;var mesh=Object.Instantiate(mf.sharedMesh);mesh.vertices=vertices;mesh.RecalculateNormals();mesh.RecalculateBounds();string path=Folder+"/"+scene+"-seated-marking-"+arrows+++".asset";AssetDatabase.CreateAsset(mesh,path);mf.sharedMesh=mesh;}
 Physics.SyncTransforms();Save();File.WriteAllText("Docs/ReportCleanup/"+scene+"-details.txt","Natural outcrops="+stones+"; seated marking meshes="+arrows+". Both road layers checked before barrier placement.");return "Natural edge outcrops="+stones+" markings="+arrows;
 }
 public static string SeatDetails(){var rows=new List<string>();Physics.SyncTransforms();foreach(var stone in Object.FindObjectsByType<MeshFilter>().Where(m=>m.name.Contains("ReportCleanup")&&m.name.Contains("natural edge"))){var mesh=Object.Instantiate(stone.sharedMesh);var ix=mesh.triangles;var vs=mesh.vertices;float orientation=0;for(int i=0;i<ix.Length;i+=3){var a=vs[ix[i]];var b=vs[ix[i+1]];var c=vs[ix[i+2]];orientation+=Vector3.Dot(Vector3.Cross(b-a,c-a),(a+b+c)/3-mesh.bounds.center);}if(orientation<0)for(int i=0;i<ix.Length;i+=3)(ix[i],ix[i+1])=(ix[i+1],ix[i]);mesh.triangles=ix;mesh.RecalculateNormals();var old=stone.sharedMesh;EditorUtility.CopySerialized(mesh,old);Object.DestroyImmediate(mesh);stone.GetComponent<MeshCollider>().sharedMesh=null;stone.GetComponent<MeshCollider>().sharedMesh=old;var bounds=stone.GetComponent<Renderer>().bounds;var footing=Physics.RaycastAll(new(bounds.center.x,bounds.min.y+20,bounds.center.z),Vector3.down,70,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")&&!h.collider.name.Contains("natural edge")).OrderBy(h=>Mathf.Abs(h.point.y-bounds.min.y)).ToArray();if(footing.Length>0)stone.transform.position+=Vector3.up*(footing[0].point.y-bounds.min.y-.18f);rows.Add("Grounded outward solid collision "+stone.name);}
 foreach(var sign in Object.FindObjectsByType<PhysicalSign>()){string label=string.Join(" ",sign.GetComponentsInChildren<TextMesh>().Select(t=>t.text));if(label.Contains("MAIN ROUTE")&&label.Contains("BIG JUMP")){rows.Add("Remove repeated tutorial "+label);Object.DestroyImmediate(sign.gameObject);continue;}var p=sign.transform.position;if(p.x<740||p.x>1412||p.z<-336||p.z>356)continue;var posts=sign.GetComponentsInChildren<Renderer>().Where(r=>r.name.IndexOf("post",StringComparison.OrdinalIgnoreCase)>=0).ToArray();if(posts.Length==0)continue;float foot=posts.Min(r=>r.bounds.min.y);var hits=Physics.RaycastAll(new(p.x,foot+20,p.z),Vector3.down,80,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).OrderBy(h=>Mathf.Abs(h.point.y-foot)).ToArray();if(hits.Length>0){sign.transform.position+=Vector3.up*(hits[0].point.y-foot);rows.Add("Grounded "+sign.name);}}
 Save();File.WriteAllLines("Docs/ReportCleanup/"+UnityEngine.SceneManagement.SceneManager.GetActiveScene().name+"-final-details.txt",rows);return "Details finalized";}
 public static string ForwardBend(){
 if(Application.isPlaying)throw new Exception("Edit mode required");EditorSceneManager.OpenScene("Assets/Scenes/MountainLoop.unity");var road=Object.FindAnyObjectByType<RaceDirector>().road;road.Initialize();var mf=GameObject.Find("Ground_CR133 mountain driving surface").GetComponent<MeshFilter>();var pavement=mf.GetComponent<MeshCollider>();const float start=710,end=790;var a=road.At(start,out var fa);var b=road.At(end,out var fb);
 float Sample(float s){var p=road.At(s,out _);return pavement.Raycast(new Ray(p+Vector3.up*4,Vector3.down),out var hit,8)?hit.point.y:p.y+.04f;}float ya=Sample(start),yb=Sample(end),ma=(Sample(start+1)-Sample(start-1))*.5f,mb=(Sample(end+1)-Sample(end-1))*.5f;
 float Height(float s){float t=(s-start)/(end-start),t2=t*t,t3=t2*t;return (2*t3-3*t2+1)*ya+(t3-2*t2+t)*ma*(end-start)+(-2*t3+3*t2)*yb+(t3-t2)*mb*(end-start);}
 var mesh=Object.Instantiate(mf.sharedMesh);var vertices=mesh.vertices;int changed=0;float maxDelta=0;
 for(int i=0;i<vertices.Length;i++){var p=mf.transform.TransformPoint(vertices[i]);if(p.x<1305||p.x>1405||p.z<-300||p.z>-208)continue;float best=float.MaxValue,station=0;for(float s=start-2;s<end+2;s+=1){var u=road.At(s,out _);var v=road.At(s+1,out _);var d=new Vector2(v.x-u.x,v.z-u.z);var q=new Vector2(p.x-u.x,p.z-u.z);float t=Mathf.Clamp01(Vector2.Dot(q,d)/d.sqrMagnitude);float distance=(q-d*t).magnitude;if(distance<best){best=distance;station=s+t;}}
 if(station<start||station>end||best>10||Mathf.Abs(p.y-road.At(station,out _).y)>4)continue;float target=Height(station);float blend=1-Mathf.SmoothStep(0,1,(best-7)/3);float y=Mathf.Lerp(p.y,target,blend);maxDelta=Mathf.Max(maxDelta,Mathf.Abs(y-p.y));p.y=y;vertices[i]=mf.transform.InverseTransformPoint(p);changed++;}
 mesh.vertices=vertices;mesh.RecalculateNormals();mesh.RecalculateBounds();AssetDatabase.CreateAsset(mesh,Folder+"/forward-bend-continuous-grade.asset");mf.sharedMesh=mesh;pavement.sharedMesh=mesh;Physics.SyncTransforms();Save();File.WriteAllText("Docs/ReportCleanup/BUG-015-grade.txt",$"Existing paved bend refitted with endpoint-height/grade continuity, stations {start}-{end}. Vertices={changed}, maximum local vertical correction={maxDelta:F3}m; route points and X/Z road footprint unchanged.");return "Forward bend vertices="+changed+" max correction="+maxDelta;
 }
 public static string ReverseJoin(){
 if(Application.isPlaying)throw new Exception("Edit mode required");Directory.CreateDirectory(Folder);EditorSceneManager.OpenScene("Assets/Scenes/MountainLoopReverse.unity");var branch=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title=="Summit Traverse");branch.Initialize();var mf=GameObject.Find("Ground_CR133 mountain driving surface").GetComponent<MeshFilter>();var mesh=Object.Instantiate(mf.sharedMesh);var vertices=mesh.vertices;int corrected=0;
 // The prior remesh ended at X=940 and faded to a mismatched old grade.
 // Restore the branch cross-section through that join; leave its route untouched.
 for(int i=0;i<vertices.Length;i++){var p=mf.transform.TransformPoint(vertices[i]);if(p.x<908||p.x>968||p.z<-75||p.z>-27||p.y<115||p.y>134)continue;float s=branch.Project(p,out float d);if(s<265||s>327||d>9)continue;var target=branch.At(s,out _);float fade=Mathf.SmoothStep(0,1,Mathf.Min(s-265,327-s)/12)*Mathf.SmoothStep(0,1,(9-d)/2);p.y=Mathf.Lerp(p.y,target.y+.04f,fade);vertices[i]=mf.transform.InverseTransformPoint(p);corrected++;}
 mesh.vertices=vertices;mesh.RecalculateNormals();mesh.RecalculateBounds();string asset=Folder+"/reverse-branch-join.asset";var existing=AssetDatabase.LoadAssetAtPath<Mesh>(asset);if(existing){EditorUtility.CopySerialized(mesh,existing);Object.DestroyImmediate(mesh);mesh=existing;}else AssetDatabase.CreateAsset(mesh,asset);mf.sharedMesh=mesh;mf.GetComponent<MeshCollider>().sharedMesh=mesh;Physics.SyncTransforms();Save();File.WriteAllText("Docs/ReportCleanup/BUG-001-road.txt","Corrected "+corrected+" existing pavement vertices across the previous X=940 remesh boundary. Route points, width, progression and driving physics unchanged.");return "Branch join vertices="+corrected;
 }
}








