using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
// Local saved-scene repair. Route/navigation/checkpoint transforms are never changed.
public static class MountainCleanup {
 const string Folder="Assets/Track/MountainCleanup";
 struct V {public Vector3 p;public Color c;public V(Vector3 p,Color c){this.p=p;this.c=c;}public static V Lerp(V a,V b,float t)=>new V(Vector3.Lerp(a.p,b.p,t),Color.Lerp(a.c,b.c,t));}
 class Face {public List<V> v;public Face(params V[] a){v=a.ToList();}}
 static Color Earth=new(.39f,.48f,.29f),Rock=new(.34f,.36f,.29f);
 static V E(Vector3 p)=>new(p,Earth);static V R(Vector3 p)=>new(p,Rock);
 static List<V> Clip(List<V> poly,Plane plane,bool inside){var result=new List<V>();for(int i=0;i<poly.Count;i++){var a=poly[i];var b=poly[(i+1)%poly.Count];float da=plane.GetDistanceToPoint(a.p),db=plane.GetDistanceToPoint(b.p);bool ia=inside?da>=-.00001f:da<=.00001f,ib=inside?db>=-.00001f:db<=.00001f;if(ia)result.Add(a);if(ia!=ib)result.Add(V.Lerp(a,b,da/(da-db)));}return result;}
 static IEnumerable<Face> Subtract(Face f,Plane[] planes){foreach(var plane in planes)if(f.v.All(v=>plane.GetDistanceToPoint(v.p)<-.00001f))return new[]{f};var intersection=f.v;foreach(var p in planes){intersection=Clip(intersection,p,true);if(intersection.Count<3)return new[]{f};}var outside=new List<Face>();var rest=f.v;foreach(var p in planes){var part=Clip(rest,p,false);if(part.Count>=3)outside.Add(new Face(part.ToArray()));rest=Clip(rest,p,true);if(rest.Count<3)break;}return outside;}
 static Plane[] Box(Vector3 a,Vector3 b,float width,float bottom,float top){var f=Vector3.ProjectOnPlane(b-a,Vector3.up).normalized;var right=Vector3.Cross(Vector3.up,f);var up=Vector3.Cross(b-a,right).normalized;if(up.y<0)up=-up;return new[]{new Plane(f,a-f*.15f),new Plane(-f,b+f*.15f),new Plane(right,a-right*width),new Plane(-right,a+right*width),new Plane(up,a+Vector3.up*bottom),new Plane(-up,a+Vector3.up*top)};}
 static List<Face> Read(MeshFilter mf){var m=mf.sharedMesh;var v=m.vertices;var c=m.colors;var t=m.triangles;return Enumerable.Range(0,t.Length/3).Select(i=>new Face(Enumerable.Range(0,3).Select(j=>{int k=t[i*3+j];return new V(mf.transform.TransformPoint(v[k]),c.Length==v.Length?c[k]:Earth);}).ToArray())).ToList();}
 static Mesh Store(string name,List<Face> faces){var vs=new List<Vector3>();var cs=new List<Color>();var ix=new List<int>();foreach(var face in faces)for(int j=1;j+1<face.v.Count;j++){var a=face.v[0];var b=face.v[j];var c=face.v[j+1];if(Vector3.Cross(b.p-a.p,c.p-a.p).sqrMagnitude<.00000001f)continue;int k=vs.Count;vs.AddRange(new[]{a.p,b.p,c.p});cs.AddRange(new[]{a.c,b.c,c.c});ix.AddRange(new[]{k,k+1,k+2});}var mesh=new Mesh{indexFormat=UnityEngine.Rendering.IndexFormat.UInt32};mesh.SetVertices(vs);mesh.SetColors(cs);mesh.SetTriangles(ix,0);mesh.RecalculateNormals();mesh.RecalculateBounds();string path=Folder+"/"+name+".asset";var old=AssetDatabase.LoadAssetAtPath<Mesh>(path);if(old){EditorUtility.CopySerialized(mesh,old);Object.DestroyImmediate(mesh);return old;}AssetDatabase.CreateAsset(mesh,path);return mesh;}
 static void Assign(MeshFilter mf,string name,List<Face> faces){var mesh=Store(name,faces);mf.transform.SetPositionAndRotation(Vector3.zero,Quaternion.identity);mf.transform.localScale=Vector3.one;mf.sharedMesh=mesh;if(mf.TryGetComponent<MeshCollider>(out var mc)){mc.sharedMesh=null;mc.sharedMesh=mesh;}}
 static void Quad(List<Face> f,Vector3 a,Vector3 b,Vector3 c,Vector3 d,bool rock=false,bool doubleSide=false){var col=rock?Rock:Earth;f.Add(new Face(new(a,col),new(b,col),new(c,col)));f.Add(new Face(new(a,col),new(c,col),new(d,col)));if(doubleSide){f.Add(new Face(new(c,col),new(b,col),new(a,col)));f.Add(new Face(new(d,col),new(c,col),new(a,col)));}}
 static bool Local(Vector3 p)=>p.x>855&&p.x<1060&&p.z>-112&&p.z<185;
 static GameObject Make(string name,List<Face> fs,Material mat){var g=new GameObject("Ground_"+name,typeof(MeshFilter),typeof(MeshRenderer),typeof(MeshCollider));g.GetComponent<MeshRenderer>().sharedMaterial=mat;Assign(g.GetComponent<MeshFilter>(),name,fs);return g;}
 static void Save(){var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene();EditorSceneManager.MarkSceneDirty(scene);EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();}
 public static string Barriers(){
 Directory.CreateDirectory(Folder);var report=new List<string>();Physics.SyncTransforms();var mat=GameObject.Find("Ground_MountainCut rock vault").GetComponent<Renderer>().sharedMaterial;
 var blocks=Object.FindObjectsByType<BoxCollider>().Where(c=>c.name.StartsWith("CR121 closed late cut barrier")||c.name=="Far-side shortcut separator"||c.name.StartsWith("Summit side-entry timber screen")).ToArray();
 var groups=blocks.GroupBy(c=>c.name.StartsWith("Summit")?"Summit-"+c.name.Split(' ').Last().Split('-')[0]:c.GetEntityId().ToString()).ToArray();int n=0;
 foreach(var group in groups){var box=group.First();var p=box.bounds.center;float y=group.Min(c=>c.bounds.min.y);bool summit=box.name.StartsWith("Summit");if(summit){var hits=Physics.RaycastAll(new Ray(new Vector3(p.x,180,p.z),Vector3.down),60,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).ToArray();if(hits.Length>0)y=hits.Max(h=>h.point.y);}
 float length=summit?6.4f:(box.name.StartsWith("CR121")?5.6f:3.65f);float width=summit?3.2f:(box.name.StartsWith("CR121")?2.9f:1.6f);float height=summit?4.0f:3.3f;
 var fs=new List<Face>();var center=new Vector3(p.x,y-.45f,p.z);var rot=box.transform.rotation;Vector3 P(int ring,int j){float a=j*Mathf.PI*2/9;float radius=new[]{.92f,1f,.75f,.33f}[ring];float yy=new[]{0,.65f,height*.70f,height}[ring];float irregular=1+.09f*Mathf.Sin(j*2.7f+n*1.9f+ring*.8f);return center+rot*new Vector3(Mathf.Cos(a)*width*.5f*radius*irregular,yy+.12f*Mathf.Sin(j*1.7f+n),Mathf.Sin(a)*length*.5f*radius*irregular);}
 for(int ring=0;ring<3;ring++)for(int j=0;j<9;j++)Quad(fs,P(ring,j),P(ring,j+1),P(ring+1,j+1),P(ring+1,j),true,true);for(int j=0;j<9;j++)fs.Add(new Face(R(P(3,j)),R(P(3,j+1)),R(center+Vector3.up*(height+.06f))));
 Make("MountainCleanup natural outcrop "+n,fs,mat);report.Add($"{box.name}: {group.Count()} slabs replaced at {center}, height={height}");n++;
 }
 foreach(var block in blocks)Object.DestroyImmediate(block.gameObject);Physics.SyncTransforms();Save();File.WriteAllLines("Docs/MountainCleanup/barriers.txt",report);return $"Replaced {blocks.Length} slabs with {n} irregular colliding rock outcrops";
 }
 public static string ClearSupport(){Directory.CreateDirectory(Folder);var race=Object.FindAnyObjectByType<RaceDirector>();var road=race.road;var b=Object.FindObjectsByType<WoodlandRoute>().Single(x=>x.title=="Summit Traverse");var vols=new List<Plane[]>();
 // Cut only erroneous secondary support, leaving established pavement and route data exact.
 for(float s=0;s<48;s+=2)vols.Add(Box(b.At(s,out _),b.At(s+2,out _),7,-1.25f,8));
 for(float s=315;s<b.Length;s+=2)vols.Add(Box(b.At(s,out _),b.At(Mathf.Min(s+2,b.Length),out _),7,-1.25f,8));
 for(float s=1565;s<1675;s+=2)vols.Add(Box(road.At(s,out _),road.At(s+2,out _),7.5f,-1.25f,12));
 var report=new List<string>();foreach(var mf in Object.FindObjectsByType<MeshFilter>().Where(m=>m.sharedMesh&&m.name.StartsWith("Ground_")&&!m.name.Contains("driving surface")&&m.GetComponent<Renderer>()&&(m.GetComponent<Renderer>().bounds.Intersects(new Bounds(new Vector3(890,115,-75),new Vector3(170,100,170)))||m.GetComponent<Renderer>().bounds.Intersects(new Bounds(new Vector3(1000,161,110),new Vector3(90,20,80)))))){var before=Read(mf);var fs=before;foreach(var vol in vols)fs=fs.SelectMany(f=>Subtract(f,vol)).ToList();if(fs.Count!=before.Count||!fs.SequenceEqual(before)){Assign(mf,"cleared-"+mf.name,fs);report.Add(mf.name+": "+before.Count+" -> "+fs.Count);}}
 Physics.SyncTransforms();Save();File.WriteAllLines("Docs/MountainCleanup/support-clearance.txt",report);return string.Join("\n",report);
 }
 static Plane[] Rect(float x0,float x1,float z0,float z1)=>new[]{new Plane(Vector3.right,new Vector3(x0,0,0)),new Plane(Vector3.left,new Vector3(x1,0,0)),new Plane(Vector3.forward,new Vector3(0,0,z0)),new Plane(Vector3.back,new Vector3(0,0,z1))};
 public static string ShoulderContact(){var b=Object.FindObjectsByType<WoodlandRoute>().Single(x=>x.title=="Summit Traverse");var q=b.At(404,out var f)+Vector3.Cross(Vector3.up,f).normalized*4;var mf=GameObject.Find("Ground_MountainCleanup connected mountain shoulder").GetComponent<MeshFilter>();var fs=Read(mf);foreach(var face in fs)for(int i=0;i<face.v.Count;i++){var v=face.v[i];float d=Vector2.Distance(new(v.p.x,v.p.z),new(q.x,q.z));if(d<4)v.p.y-=1.6f*(1-Mathf.SmoothStep(0,1,d/4));face.v[i]=v;}Assign(mf,"final-shoulder-contact",fs);Physics.SyncTransforms();Save();return "Small shoulder interpolation contact recessed beneath existing pavement";}
 public static string FinalSeat(){var road=GameObject.Find("Ground_CR133 mountain driving surface").GetComponent<Collider>();var mf=GameObject.Find("Ground_MountainCleanup connected mountain shoulder").GetComponent<MeshFilter>();var fs=Read(mf);foreach(var face in fs)for(int i=0;i<face.v.Count;i++){var v=face.v[i];if(road.Raycast(new Ray(v.p+Vector3.up*15,Vector3.down),out var h,30))v.p.y=Mathf.Min(v.p.y,h.point.y-1.3f);face.v[i]=v;}Assign(mf,"final-connected-subgrade",fs);int n=0;
 foreach(var arrow in Object.FindObjectsByType<MeshFilter>().Where(m=>m.sharedMesh&&(m.name.Contains("arrow")||m.name.Contains("Main teal")||m.name.Contains("gold")))){var rr=arrow.GetComponent<Renderer>();if(!rr||!rr.bounds.Intersects(new Bounds(new(885,112,-85),new(116,50,116))))continue;var faces=Read(arrow);foreach(var face in faces)for(int i=0;i<face.v.Count;i++){var v=face.v[i];if(road.Raycast(new Ray(v.p+Vector3.up*12,Vector3.down),out var h,24))v.p.y=h.point.y+.075f;face.v[i]=v;}Assign(arrow,"final-arrow-"+n++,faces);}
 Physics.SyncTransforms();Save();return "Final local subgrade and "+n+" route markings seated";}
 public static string FirstBump(){var road=Object.FindAnyObjectByType<RaceDirector>().road;var mf=GameObject.Find("Ground_CR133 mountain driving surface").GetComponent<MeshFilter>();var mesh=Object.Instantiate(mf.sharedMesh);var vs=mesh.vertices;var a=road.At(175,out var fa);var b=road.At(255,out var fb);float Y(float s){float t=Mathf.Clamp01((s-175)/80),t2=t*t,t3=t2*t;return (2*t3-3*t2+1)*a.y+(t3-2*t2+t)*fa.y*80+(-2*t3+3*t2)*b.y+(t3-t2)*fb.y*80+.04f;}float Station(Vector3 p,out float d){float best=float.MaxValue,at=0;for(float s=171;s<259;s+=.5f){var u=road.At(s,out _);var v=road.At(s+.5f,out _);var f=new Vector2(v.x-u.x,v.z-u.z);var q=new Vector2(p.x-u.x,p.z-u.z);float t=Mathf.Clamp01(Vector2.Dot(q,f)/f.sqrMagnitude);float dd=(q-f*t).sqrMagnitude;if(dd<best){best=dd;at=s+t*.5f;}}d=Mathf.Sqrt(best);return at;}
 for(int i=0;i<vs.Length;i++){var p=mf.transform.TransformPoint(vs[i]);if(p.x<775||p.x>845||p.z<40||p.z>130)continue;float s=Station(p,out float d);if(s<175||s>255||d>15||Math.Abs(p.y-road.At(s,out _).y)>5)continue;p.y=Y(s);vs[i]=mf.transform.InverseTransformPoint(p);}mesh.vertices=vs;mesh.RecalculateNormals();mesh.RecalculateBounds();AssetDatabase.CreateAsset(mesh,Folder+"/first-bump-surface.asset");mf.sharedMesh=mesh;mf.GetComponent<MeshCollider>().sharedMesh=mesh;
 var vols=new List<Plane[]>();for(float s=176;s<254;s+=2){var u=road.At(s,out _);var v=road.At(s+2,out _);u.y=Y(s);v.y=Y(s+2);vols.Add(Box(u,v,7.3f,-3,7));}int changed=0;
 foreach(var ground in Object.FindObjectsByType<MeshFilter>().Where(m=>m!=mf&&m.sharedMesh&&m.name.StartsWith("Ground_")&&m.GetComponent<Renderer>()&&m.GetComponent<Renderer>().bounds.Intersects(new Bounds(new(810,116,86),new(80,35,95))))){var orig=Read(ground);var fs=orig;foreach(var vol in vols)fs=fs.SelectMany(f=>Subtract(f,vol)).ToList();if(!fs.SequenceEqual(orig)){Assign(ground,"first-bump-clear-"+ground.name,fs);changed++;}}
 Physics.SyncTransforms();Save();return "First bump continuous surface and buried support contacts cleared in "+changed+" meshes";}
 public static string RetessellateBump(){var road=Object.FindAnyObjectByType<RaceDirector>().road;var mf=GameObject.Find("Ground_CR133 mountain driving surface").GetComponent<MeshFilter>();var mc=mf.GetComponent<Collider>();var a=road.At(175,out var fa);var b=road.At(255,out var fb);var cache=new Dictionary<Vector2,(Vector3 p,bool hit)>();
 (Vector3 p,bool hit) P(float x,float z){var key=new Vector2(x,z);if(cache.TryGetValue(key,out var old))return old;float best=float.MaxValue,station=0;for(float s=155;s<276;s+=.5f){var u=road.At(s,out _);var v=road.At(s+.5f,out _);var d=new Vector2(v.x-u.x,v.z-u.z);float t=Mathf.Clamp01(Vector2.Dot(key-new Vector2(u.x,u.z),d)/d.sqrMagnitude);float sq=(key-new Vector2(u.x,u.z)-d*t).sqrMagnitude;if(sq<best){best=sq;station=s+t*.5f;}}bool hit=mc.Raycast(new Ray(new(x,145,z),Vector3.down),out var h,60);var p=h.point;if(hit&&station>=175&&station<=255&&best<225){float t=(station-175)/80,t2=t*t,t3=t2*t;p.y=(2*t3-3*t2+1)*a.y+(t3-2*t2+t)*fa.y*80+(-2*t3+3*t2)*b.y+(t3-t2)*fb.y*80+.04f;}return cache[key]=(new(x,p.y,z),hit);}
 var fs=Read(mf).SelectMany(f=>Subtract(f,Rect(775,845,40,130))).ToList();for(float x=775;x<845;x+=.5f)for(float z=40;z<130;z+=.5f){var a0=P(x,z);var b0=P(x,z+.5f);var c0=P(x+.5f,z+.5f);var d0=P(x+.5f,z);if(a0.hit&&b0.hit&&c0.hit)fs.Add(new Face(new(a0.p,Color.white),new(b0.p,Color.white),new(c0.p,Color.white)));if(a0.hit&&c0.hit&&d0.hit)fs.Add(new Face(new(a0.p,Color.white),new(c0.p,Color.white),new(d0.p,Color.white)));}Assign(mf,"retessellated-first-climb",fs);Physics.SyncTransforms();Save();return "First climb overlapping fans replaced with sampled continuous pavement";}
 public static string RebuildJoin(){var road=Object.FindAnyObjectByType<RaceDirector>().road;var branch=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title=="Summit Traverse");var mf=GameObject.Find("Ground_CR133 mountain driving surface").GetComponent<MeshFilter>();var mc=mf.GetComponent<MeshCollider>();var savedBack=Physics.queriesHitBackfaces;Physics.queriesHitBackfaces=true;
 var samples=new List<(Vector3 a,Vector3 b,bool branch)>();for(float s=1520;s<1710;s+=.5f)samples.Add((road.At(s,out _),road.At(s+.5f,out _),false));for(float s=270;s<branch.Length;s+=.5f)samples.Add((branch.At(s,out _),branch.At(Mathf.Min(s+.5f,branch.Length),out _),true));
 var cache=new Dictionary<Vector2,(Vector3 p,bool inside)>();(Vector3 p,bool inside) P(float x,float z){var key=new Vector2(x,z);if(cache.TryGetValue(key,out var old))return old;float rd=float.MaxValue,bd=float.MaxValue,ry=0,by=0;foreach(var seg in samples){var d=new Vector2(seg.b.x-seg.a.x,seg.b.z-seg.a.z);var q=key-new Vector2(seg.a.x,seg.a.z);float t=Mathf.Clamp01(Vector2.Dot(q,d)/Mathf.Max(.00001f,d.sqrMagnitude));float distance=(q-d*t).magnitude;if(seg.branch&&distance<bd){bd=distance;by=Mathf.Lerp(seg.a.y,seg.b.y,t);}if(!seg.branch&&distance<rd){rd=distance;ry=Mathf.Lerp(seg.a.y,seg.b.y,t);}}if(x>847.02f&&x<893.63f){float t=(x-847.02f)/46.61f,t2=t*t,t3=t2*t;ry=(2*t3-3*t2+1)*101.59f+(t3-2*t2+t)*.112f*46.61f+(-2*t3+3*t2)*116.14f+(t3-t2)*.183f*46.61f;}float blend=Mathf.SmoothStep(0,1,(rd-7)/18);float y=Mathf.Lerp(ry,by,blend)+.04f;bool found=mc.Raycast(new Ray(new(x,140,z),Vector3.down),out var hit,45);bool inside=found||rd<=7||bd<=6;float edge=Mathf.Min(x-830,940-x,z+140,-30-z);if(found)y=Mathf.Lerp(hit.point.y,y,Mathf.SmoothStep(0,1,edge/5));return cache[key]=(new(x,y,z),inside);}
 var fs=Read(mf).SelectMany(f=>Subtract(f,Rect(830,940,-140,-30))).ToList();int added=0;void Add((Vector3 p,bool inside) a,(Vector3 p,bool inside) b,(Vector3 p,bool inside) c){var src=new[]{a,b,c};var poly=new List<Vector3>();for(int j=0;j<3;j++){var u=src[j];var v=src[(j+1)%3];if(u.inside)poly.Add(u.p);if(u.inside!=v.inside)poly.Add(Vector3.Lerp(u.p,v.p,.5f));}for(int j=1;j+1<poly.Count;j++){fs.Add(new Face(new(poly[0],Color.white),new(poly[j],Color.white),new(poly[j+1],Color.white)));added++;}}
 for(float x=830;x<940;x+=.5f)for(float z=-140;z<-30;z+=.5f){var a=P(x,z);var b=P(x,z+.5f);var c=P(x+.5f,z+.5f);var d=P(x+.5f,z);Add(a,b,c);Add(a,c,d);}Assign(mf,"single-surface-rejoin",fs);Physics.queriesHitBackfaces=savedBack;Physics.SyncTransforms();Save();File.WriteAllText("Docs/MountainCleanup/rejoin-remesh.txt",$"Removed overlapping triangulation inside the existing local footprint and retessellated at 0.5m spacing; {added} faces. Main/branch coordinates, endpoints and final tangent unchanged.");return "Existing overlap retessellated: "+added;}
 public static string FinishSurfaces(){var pavement=GameObject.Find("Ground_CR133 mountain driving surface").GetComponent<Collider>();var land=GameObject.Find("Ground_MountainCleanup connected mountain shoulder").GetComponent<MeshFilter>();var original=AssetDatabase.LoadAssetAtPath<Mesh>(Folder+"/MountainCleanup connected mountain shoulder.asset");var mesh=Object.Instantiate(original);var vs=mesh.vertices;for(int i=0;i<vs.Length;i++){var p=vs[i];if(pavement.Raycast(new Ray(p+Vector3.up*10,Vector3.down),out var h,20))p.y=Mathf.Min(p.y,h.point.y-.4f);vs[i]=p;}mesh.vertices=vs;mesh.RecalculateNormals();mesh.RecalculateBounds();AssetDatabase.CreateAsset(mesh,Folder+"/continuous-subgrade.asset");land.sharedMesh=mesh;land.GetComponent<MeshCollider>().sharedMesh=mesh;
 int arrows=0;foreach(var mf in Object.FindObjectsByType<MeshFilter>().Where(m=>m.sharedMesh&&(m.name.Contains("arrow")||m.name.Contains("Main teal")||m.name.Contains("gold")))){var rr=mf.GetComponent<Renderer>();if(!rr||!rr.bounds.Intersects(new Bounds(new(886,112,-95),new(78,35,45))))continue;var v=mf.sharedMesh.vertices;bool changed=false;for(int i=0;i<v.Length;i++){var p=mf.transform.TransformPoint(v[i]);if(p.x<848||p.x>924||p.z<-115||p.z>-76)continue;if(pavement.Raycast(new Ray(p+Vector3.up*8,Vector3.down),out var h,16)){p.y=h.point.y+.065f;v[i]=mf.transform.InverseTransformPoint(p);changed=true;}}if(changed){var m=Object.Instantiate(mf.sharedMesh);m.vertices=v;m.RecalculateNormals();m.RecalculateBounds();AssetDatabase.CreateAsset(m,Folder+"/seated-arrow-"+arrows+++".asset");mf.sharedMesh=m;}}
 var receiving=GameObject.Find("Ground_MountainCleanup landing rock shoulder").GetComponent<MeshFilter>();var faces=Read(receiving);faces=faces.Where(f=>!f.v.All(v=>Mathf.Abs(v.p.x-905)<.01f)).ToList();var originalGround=GameObject.Find("Ground_CR117 outer ravine").GetComponent<Collider>();Vector3 Top(float z){var q=new Vector3(905,160,z);var mc=receiving.GetComponent<Collider>();return mc.Raycast(new Ray(q,Vector3.down),out var h,150)?h.point:new Vector3(905,45,z);}Vector3 Lower(float z,int ring){var t=Top(z);float x=905+ring*4.5f+Mathf.Sin(z*.16f)*ring*.65f;float floor=originalGround.Raycast(new Ray(new(x,160,z),Vector3.down),out var hit,200)?hit.point.y:45;float y=Mathf.Lerp(t.y,floor,ring/3f);return new(x,y+(ring<3?Mathf.Sin(z*.3f)*1.3f:0),z);}
 for(float z=-354;z<-246;z+=3)for(int r=0;r<3;r++)Quad(faces,r==0?Top(z):Lower(z,r),r==0?Top(z+3):Lower(z+3,r),Lower(z+3,r+1),Lower(z,r+1),true,true);Assign(receiving,"irregular-landing-rock-face",faces);Physics.SyncTransforms();Save();return "Continuous subgrade, seated arrows="+arrows+", irregular receiving rock slope";}
 public static string RejoinFaces(){var road=Object.FindAnyObjectByType<RaceDirector>().road;var branch=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title=="Summit Traverse");var mf=GameObject.Find("Ground_CR133 mountain driving surface").GetComponent<MeshFilter>();var mesh=Object.Instantiate(mf.sharedMesh);var vs=mesh.vertices;int count=0;
 Vector3 Near(Vector3 p,Func<float,Vector3> at,float a,float b,out float distance){var best=Vector3.zero;float min=float.MaxValue;for(float s=a;s<b;s+=1){var u=at(s);var v=at(s+1);var d=new Vector2(v.x-u.x,v.z-u.z);var q=new Vector2(p.x-u.x,p.z-u.z);float t=Mathf.Clamp01(Vector2.Dot(q,d)/Mathf.Max(.001f,d.sqrMagnitude));float sq=(q-d*t).sqrMagnitude;if(sq<min){min=sq;best=Vector3.Lerp(u,v,t);}}distance=Mathf.Sqrt(min);return best;}
 float Y(Vector3 p){var r=Near(p,s=>road.At(s,out _),1580,1675,out float rd);var b=Near(p,s=>branch.At(s,out _),385,branch.Length,out float bd);float blend=Mathf.SmoothStep(0,1,rd/Mathf.Max(.001f,rd+bd));return Mathf.Lerp(r.y,b.y,blend)+.04f;}
 for(int i=0;i<vs.Length;i++){var p=mf.transform.TransformPoint(vs[i]);if(p.x<850||p.x>922||p.z<-113||p.z>-78||p.y<98||p.y>126)continue;float edge=Mathf.Min(p.x-850,922-p.x,p.z+113,-78-p.z);p.y=Mathf.Lerp(p.y,Y(p),Mathf.SmoothStep(0,1,edge/6));vs[i]=mf.transform.InverseTransformPoint(p);count++;}
 mesh.vertices=vs;mesh.RecalculateNormals();mesh.RecalculateBounds();AssetDatabase.CreateAsset(mesh,Folder+"/coherent-rejoin.asset");mf.sharedMesh=mesh;mf.GetComponent<MeshCollider>().sharedMesh=null;mf.GetComponent<MeshCollider>().sharedMesh=mesh;Physics.SyncTransforms();Save();File.WriteAllText("Docs/MountainCleanup/rejoin-faces.txt",$"Corrected {count} vertices in existing overlapping-ribbon join. Deterministic continuous height blend between unchanged route centre lines; existing X/Z footprint and final rejoin unchanged.");return "Local driving fan vertices corrected="+count;}
 public static string Bumps(){Directory.CreateDirectory(Folder);var road=Object.FindAnyObjectByType<RaceDirector>().road;var driving=GameObject.Find("Ground_CR133 mountain driving surface").GetComponent<MeshFilter>();var report=new List<string>();
 foreach(var span in new[]{new Vector2(175,255),new Vector2(2140,2215)}){var a=road.At(span.x,out var fa);var b=road.At(span.y,out var fb);float length=span.y-span.x;float Height(float s){float t=Mathf.Clamp01((s-span.x)/length),t2=t*t,t3=t2*t;return (2*t3-3*t2+1)*a.y+(t3-2*t2+t)*fa.y*length+(-2*t3+3*t2)*b.y+(t3-t2)*fb.y*length+.04f;}
 float Station(Vector3 p,out float d){float best=float.MaxValue,at=span.x;for(float s=span.x-4;s<span.y+4;s+=1){var u=road.At(s,out _);var v=road.At(s+1,out _);var flat=new Vector2(v.x-u.x,v.z-u.z);var q=new Vector2(p.x-u.x,p.z-u.z);float t=Mathf.Clamp01(Vector2.Dot(q,flat)/flat.sqrMagnitude);float dist=(q-flat*t).sqrMagnitude;if(dist<best){best=dist;at=s+t;}}d=Mathf.Sqrt(best);return at;}
 int count=0;foreach(var mf in Object.FindObjectsByType<MeshFilter>().Where(m=>m.sharedMesh&&(m==driving||m.name.StartsWith("Ground_")||m.name.Contains("arrow")||m.name.Contains("Main teal")))){var vs=mf.sharedMesh.vertices;bool changed=false;for(int i=0;i<vs.Length;i++){var p=mf.transform.TransformPoint(vs[i]);if(Vector3.Distance(p,(a+b)*.5f)>length*.8f+20)continue;float s=Station(p,out float d);if(s<span.x||s>span.y||d>20)continue;float old=road.At(s,out _).y+.04f;if(Mathf.Abs(p.y-old)>3)continue;float delta=Height(s)-old;float blend=1-Mathf.SmoothStep(0,1,(d-7)/10);p.y+=delta*blend;vs[i]=mf.transform.InverseTransformPoint(p);changed=true;count++;}if(changed){var mesh=Object.Instantiate(mf.sharedMesh);mesh.vertices=vs;mesh.RecalculateNormals();mesh.RecalculateBounds();string path=Folder+"/bump-"+span.x+"-"+mf.name.Replace('/','-')+".asset";AssetDatabase.CreateAsset(mesh,path);mf.sharedMesh=mesh;if(mf.TryGetComponent<MeshCollider>(out var mc)){mc.sharedMesh=null;mc.sharedMesh=mesh;}}}report.Add($"{span}: {count} vertices refitted with endpoint-tangent continuity");}
 Physics.SyncTransforms();Save();File.WriteAllLines("Docs/MountainCleanup/bumps.txt",report);return string.Join("\n",report);}
 public static string Dependencies(){Physics.SyncTransforms();var road=Object.FindAnyObjectByType<RaceDirector>().road;bool Area(Vector3 p)=> (p.x>=815&&p.x<=905&&p.z>=-354&&p.z<=-246)||(p.x>775&&p.x<850&&p.z>45&&p.z<130)||(p.x>1240&&p.x<1305&&p.z>-320&&p.z<-240)||(p.x>=830&&p.x<=930&&p.z>=-130&&p.z<=-20);
 var rows=new List<string>();var pavement=GameObject.Find("Ground_CR133 mountain driving surface").GetComponent<Collider>();bool Cut(Collider c){if(!Area(c.bounds.center)||c.bounds.center.z>-246||c.bounds.center.x>905)return false;var p=c.bounds.center;return pavement.Raycast(new Ray(new(p.x,180,p.z),Vector3.down),out var h,150)&&h.point.y>c.bounds.min.y+3;}
 foreach(var c in Object.FindObjectsByType<Collider>().Where(c=>c.name.IndexOf("trunk",StringComparison.OrdinalIgnoreCase)>=0&&Area(c.bounds.center)))rows.Add($"Tree {c.bounds.center} foot={c.bounds.min.y} remove-under-landing={Cut(c)}");
 typeof(Racer.Editor.BackyardReverseAuthoring).GetMethod("Trees",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Static).Invoke(null,new object[]{(Func<Collider,bool>)Cut,(Func<Collider,bool>)(c=>Area(c.bounds.center))});
 foreach(var t in Object.FindObjectsByType<Transform>().Where(t=>Area(t.position)&&(t.GetComponent<PhysicalSign>()||t.name.StartsWith("Acorn clue /")))){var rs=t.GetComponentsInChildren<Renderer>();var posts=rs.Where(r=>r.name.IndexOf("post",StringComparison.OrdinalIgnoreCase)>=0).ToArray();if(t.GetComponent<PhysicalSign>()&&posts.Length==0)continue;var rr=posts.Length>0?posts:rs;if(rr.Length==0)continue;float foot=rr.Min(r=>r.bounds.min.y);var p=t.position;var hits=Physics.RaycastAll(new(p.x,foot+30,p.z),Vector3.down,70,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).ToArray();if(hits.Length>0){float dy=hits.OrderBy(h=>Math.Abs(h.point.y-foot)).First().point.y-foot;t.position+=Vector3.up*dy;rows.Add(t.name+" grounded delta="+dy);}}
 Save();File.WriteAllLines("Docs/MountainCleanup/dependencies-after.txt",rows);return "Targeted tree/sign/cairn dependencies reseated; "+rows.Count+" records";}
 public static string Terrain(){
 Directory.CreateDirectory(Folder);Physics.SyncTransforms();var road=Object.FindAnyObjectByType<RaceDirector>().road;var branch=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title=="Summit Traverse");var grounds=Object.FindObjectsByType<MeshCollider>().Where(c=>c.name.StartsWith("Ground_")).ToArray();var pavement=grounds.Single(c=>c.name.Contains("driving surface"));var mat=GameObject.Find("Ground_MountainCut rock vault").GetComponent<Renderer>().sharedMaterial;var report=new List<string>();
 bool InPatch(Vector3 p)=>p.x>=830&&p.x<=930&&p.z>=-130&&p.z<=-20;
 var dependencies=Object.FindObjectsByType<Transform>().Where(t=>InPatch(t.position)&&(t.GetComponent<PhysicalSign>()||t.name.StartsWith("Acorn clue /"))).ToArray();File.WriteAllLines("Docs/MountainCleanup/dependencies-before.txt",dependencies.Select(t=>t.name+" "+t.position));
 var originals=grounds.Where(c=>!c.name.Contains("driving surface")&&!c.name.Contains("earth banks")&&!c.name.Contains("MountainPolish")&&!c.name.Contains("MountainCut")).ToArray();
 float Original(float x,float z){var p=new Vector3(x,220,z);var ys=originals.Select(c=>c.Raycast(new Ray(p,Vector3.down),out var h,240)?h.point.y:float.NegativeInfinity).Where(y=>!float.IsNegativeInfinity(y));return ys.Any()?ys.Max():45;}
 var terrain=new List<Face>();var cache=new Dictionary<Vector2,Vector3>();
 Vector3 Point(float x,float z){var key=new Vector2(x,z);if(cache.TryGetValue(key,out var v))return v;float original=Original(x,z);var p=new Vector3(x,112,z);float rs=road.Project(p,out _);var rp=road.At(rs,out _);float bs=branch.Project(p,out _);var bp=branch.At(bs,out _);float rd=Vector2.Distance(new(x,z),new(rp.x,rp.z)),bd=Vector2.Distance(new(x,z),new(bp.x,bp.z));var near=rd<bd?rp:bp;float d=Mathf.Min(rd,bd),width=rd<bd?7:6;float y=near.y-.5f-Mathf.Max(0,d-width)*.70f;
 // A continuous sampled landform replaces triangle-edge curtains. Roads stay fixed.
 if(d>width+14)y=Mathf.Lerp(y,original,Mathf.SmoothStep(0,1,(d-width-14)/12));float edge=Mathf.Min(x-830,930-x,z+130,-20-z);y=Mathf.Lerp(original,y,Mathf.SmoothStep(0,1,edge/8));
 if(pavement.Raycast(new Ray(new(x,near.y+3,z),Vector3.down),out var hit,6))y=Mathf.Min(y,hit.point.y-.5f);
 return cache[key]=new Vector3(x,y,z);}
 for(float x=830;x<930;x+=2)for(float z=-130;z<-20;z+=2)Quad(terrain,Point(x,z),Point(x,z+2),Point(x+2,z+2),Point(x+2,z));
 var cut=Rect(830,930,-130,-20);foreach(var mf in grounds.Select(c=>c.GetComponent<MeshFilter>()).Where(m=>m&&m.gameObject!=pavement.gameObject&&m.GetComponent<Renderer>().bounds.Intersects(new Bounds(new(880,115,-75),new(100,220,110))))){var before=Read(mf);var after=before.SelectMany(f=>Subtract(f,cut)).ToList();Assign(mf,"terrain-retained-"+mf.name,after);report.Add("Replaced patch inside "+mf.name);}
 Make("MountainCleanup connected mountain shoulder",terrain,mat);
 // Support the receiving road only: the authored 100m westbound flight gap stays open.
 var landing=new List<Face>();var lip=new List<(Vector3 top,Vector3 bottom)>();
 Vector3 Landing(float x,float z){float original=Original(x,z);float y=original;var q=new Vector3(x,124,z);if(pavement.Raycast(new Ray(q+Vector3.up*25,Vector3.down),out var h,65))y=Mathf.Max(original,h.point.y-.4f);else {float s=road.Project(new Vector3(x,120,-300),out _);float roadY=road.At(s,out _).y;float lateral=Mathf.Abs(z+300);y=Mathf.Max(original,roadY-.4f-Mathf.Max(0,lateral-23)*1.5f);}float fade=Mathf.SmoothStep(0,1,(x-815)/18)*Mathf.SmoothStep(0,1,(54-Mathf.Abs(z+300))/16);y=Mathf.Lerp(original,y,fade);return new(x,y,z);}
 for(float x=815;x<905;x+=3)for(float z=-354;z<-246;z+=3)Quad(landing,Landing(x,z),Landing(x,z+3),Landing(x+3,z+3),Landing(x+3,z));
 for(float z=-354;z<-246;z+=3){var a=Landing(905,z);var b=Landing(905,z+3);Quad(landing,a,b,new Vector3(905,Original(905,z+3)-.3f,z+3),new Vector3(905,Original(905,z)-.3f,z),true,true);}
 Make("MountainCleanup landing rock shoulder",landing,mat);Physics.SyncTransforms();
 foreach(var t in dependencies){var rs=t.GetComponentsInChildren<Renderer>();var posts=rs.Where(r=>r.name.IndexOf("post",StringComparison.OrdinalIgnoreCase)>=0).ToArray();if(t.GetComponent<PhysicalSign>()&&posts.Length==0)continue;var supports=posts.Length>0?posts:rs;if(supports.Length==0)continue;var p=t.position;float foot=supports.Min(r=>r.bounds.min.y);var hits=Physics.RaycastAll(new(p.x,foot+30,p.z),Vector3.down,90,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).ToArray();if(hits.Length>0){float delta=hits.Max(h=>h.point.y)-foot;t.position+=Vector3.up*delta;report.Add("Grounded "+t.name+" by "+delta);}}
 typeof(Racer.Editor.BackyardReverseAuthoring).GetMethod("Trees",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Static).Invoke(null,new object[]{(Func<Collider,bool>)(c=>false),(Func<Collider,bool>)(c=>InPatch(c.bounds.center))});
 Save();File.WriteAllLines("Docs/MountainCleanup/terrain.txt",report);return "Rebuilt bounded shoulder terrain and supported existing receiving road; flight gap unchanged";
 }
}





