using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
// Local saved-scene repair. Route/navigation/checkpoint transforms are never changed.
public static class SolidReportTerrain {
 const string Folder="Assets/Track/ReportCleanup";
 struct V {public Vector3 p;public Color c;public V(Vector3 p,Color c){this.p=p;this.c=c;}public static V Lerp(V a,V b,float t)=>new V(Vector3.Lerp(a.p,b.p,t),Color.Lerp(a.c,b.c,t));}
 class Face {public List<V> v;public Face(params V[] a){v=a.ToList();}}
 static Color Earth=new(.39f,.48f,.29f),Rock=new(.34f,.36f,.29f);
 static V E(Vector3 p)=>new(p,Earth);static V R(Vector3 p)=>new(p,Rock);
 static List<V> Clip(List<V> poly,Plane plane,bool inside){var result=new List<V>();for(int i=0;i<poly.Count;i++){var a=poly[i];var b=poly[(i+1)%poly.Count];float da=plane.GetDistanceToPoint(a.p),db=plane.GetDistanceToPoint(b.p);bool ia=inside?da>=-.00001f:da<=.00001f,ib=inside?db>=-.00001f:db<=.00001f;if(ia)result.Add(a);if(ia!=ib)result.Add(V.Lerp(a,b,da/(da-db)));}return result;}
 static IEnumerable<Face> Subtract(Face f,Plane[] planes){foreach(var plane in planes)if(f.v.All(v=>plane.GetDistanceToPoint(v.p)<-.00001f))return new[]{f};var intersection=f.v;foreach(var p in planes){intersection=Clip(intersection,p,true);if(intersection.Count<3)return new[]{f};}var outside=new List<Face>();var rest=f.v;foreach(var p in planes){var part=Clip(rest,p,false);if(part.Count>=3)outside.Add(new Face(part.ToArray()));rest=Clip(rest,p,true);if(rest.Count<3)break;}return outside;}
 static Plane[] Box(Vector3 a,Vector3 b,float width,float bottom,float top){var f=Vector3.ProjectOnPlane(b-a,Vector3.up).normalized;var right=Vector3.Cross(Vector3.up,f);var up=Vector3.Cross(b-a,right).normalized;if(up.y<0)up=-up;return new[]{new Plane(f,a-f*.15f),new Plane(-f,b+f*.15f),new Plane(right,a-right*width),new Plane(-right,a+right*width),new Plane(up,a+Vector3.up*bottom),new Plane(-up,a+Vector3.up*top)};}
 static List<Face> Read(MeshFilter mf){var m=mf.sharedMesh;var v=m.vertices;var c=m.colors;var t=m.triangles;return Enumerable.Range(0,t.Length/3).Select(i=>new Face(Enumerable.Range(0,3).Select(j=>{int k=t[i*3+j];return new V(mf.transform.TransformPoint(v[k]),c.Length==v.Length?c[k]:Earth);}).ToArray())).ToList();}
 static Mesh Store(string name,List<Face> faces){var vs=new List<Vector3>();var cs=new List<Color>();var ix=new List<int>();foreach(var face in faces)for(int j=1;j+1<face.v.Count;j++){var a=face.v[0];var b=face.v[j];var c=face.v[j+1];if(Vector3.Cross(b.p-a.p,c.p-a.p).sqrMagnitude<.00000001f)continue;int k=vs.Count;vs.AddRange(new[]{a.p,b.p,c.p});cs.AddRange(new[]{a.c,b.c,c.c});ix.AddRange(new[]{k,k+1,k+2});}var mesh=new Mesh{indexFormat=UnityEngine.Rendering.IndexFormat.UInt32};mesh.SetVertices(vs);mesh.SetColors(cs);mesh.SetTriangles(ix,0);mesh.RecalculateNormals();mesh.RecalculateBounds();string path=Folder+"/"+name+".asset";var old=AssetDatabase.LoadAssetAtPath<Mesh>(path);if(old){EditorUtility.CopySerialized(mesh,old);Object.DestroyImmediate(mesh);return old;}AssetDatabase.CreateAsset(mesh,path);return mesh;}
 static void Assign(MeshFilter mf,string name,List<Face> faces){var mesh=Store(name,faces);mf.transform.SetPositionAndRotation(Vector3.zero,Quaternion.identity);mf.transform.localScale=Vector3.one;mf.sharedMesh=mesh;if(mf.TryGetComponent<MeshCollider>(out var mc)){mc.sharedMesh=null;mc.sharedMesh=mesh;}}
 static void Quad(List<Face> f,Vector3 a,Vector3 b,Vector3 c,Vector3 d,bool rock=false,bool doubleSide=false){var col=rock?Rock:Earth;f.Add(new Face(new(a,col),new(b,col),new(c,col)));f.Add(new Face(new(a,col),new(c,col),new(d,col)));if(doubleSide){f.Add(new Face(new(c,col),new(b,col),new(a,col)));f.Add(new Face(new(d,col),new(c,col),new(a,col)));}}
 static bool Local(Vector3 p)=>p.x>855&&p.x<1060&&p.z>-112&&p.z<185;
 static GameObject Make(string name,List<Face> fs,Material mat){var g=new GameObject("Ground_"+name,typeof(MeshFilter),typeof(MeshRenderer),typeof(MeshCollider));g.GetComponent<MeshRenderer>().sharedMaterial=mat;Assign(g.GetComponent<MeshFilter>(),name,fs);return g;}
 static void Save(){var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene();EditorSceneManager.MarkSceneDirty(scene);EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();}
 public static string Reverse()=>Run(true);
 public static string Forward()=>Run(false);
 struct Cut {public Vector3 a,b;public float width,bottom,top;public Cut(Vector3 a,Vector3 b,float w,float lo,float hi){this.a=a;this.b=b;width=w;bottom=lo;top=hi;}}
 static string Run(bool reverse){
 if(Application.isPlaying)throw new Exception("Edit mode required");Directory.CreateDirectory(Folder);string scene="MountainLoop"+(reverse?"Reverse":"");EditorSceneManager.OpenScene("Assets/Scenes/"+scene+".unity");Physics.SyncTransforms();var race=Object.FindAnyObjectByType<RaceDirector>();race.road.Initialize();var driving=GameObject.Find("Ground_CR133 mountain driving surface").GetComponent<MeshCollider>();var mat=GameObject.Find("Ground_CR133 mountain earth banks").GetComponent<Renderer>().sharedMaterial;var notes=new List<string>();
 var areas=reverse?new[]{(830f,1100f,-144f,356f),(740f,840f,20f,124f),(950f,1050f,-212f,-84f)}:new[]{(1168f,1412f,-336f,-198f),(1198f,1342f,154f,284f),(726f,1082f,32f,164f)};
 var branches=Object.FindObjectsByType<WoodlandRoute>();foreach(var b in branches)b.Initialize();var cuts=new List<Cut>();if(reverse)for(float s=798;s<964;s+=3)cuts.Add(new(race.road.At(s,out _),race.road.At(s+3,out _),9.8f,-.15f,8.6f));foreach(var b in branches.Where(b=>b.title=="Summit Traverse"))for(float s=0;s<b.Length;s+=3)cuts.Add(new(b.At(s,out _),b.At(Mathf.Min(b.Length,s+3),out _),b.halfWidth+1.5f,-.15f,8.6f));
 var starts=Resources.FindObjectsOfTypeAll<MeshFilter>().Where(m=>m.gameObject.scene==UnityEngine.SceneManagement.SceneManager.GetActiveScene()&&m.name.StartsWith("Ground_CR122 main section")).Select(m=>m.transform.TransformPoint((m.sharedMesh.vertices[0]+m.sharedMesh.vertices[1])*.5f)).ToArray();foreach(var f in race.GetComponent<MountainFlights>().flights){var end=starts.Where(p=>Vector3.Dot(p-f.lip,f.forward)>35&&Vector3.Cross(Vector3.ProjectOnPlane(p-f.lip,Vector3.up),f.forward).magnitude<8).OrderBy(p=>Vector3.Dot(p-f.lip,f.forward)).First();cuts.Add(new(f.lip+f.forward*.3f,end-f.forward*.6f,25,-4,150));}
 int index=0;foreach(var area in areas){float x0=area.Item1,x1=area.Item2,z0=area.Item3,z1=area.Item4;const float step=2;int nx=Mathf.CeilToInt((x1-x0)/step),nz=Mathf.CeilToInt((z1-z0)/step);var bounds=new Bounds(new((x0+x1)/2,120,(z0+z1)/2),new(x1-x0,260,z1-z0));var grounds=Object.FindObjectsByType<MeshCollider>().Where(c=>c!=driving&&c.name.StartsWith("Ground_")&&c.bounds.Intersects(bounds)&&!c.name.Contains("natural edge")).ToArray();
 var bins=new Dictionary<Vector2Int,List<Vector3>>();for(float x=x0-48;x<=x1+48;x+=2)for(float z=z0-48;z<=z1+48;z+=2){float top=230;for(int layer=0;layer<3;layer++){if(!driving.Raycast(new Ray(new(x,top,z),Vector3.down),out var h,260))break;var k=new Vector2Int(Mathf.FloorToInt(x/8),Mathf.FloorToInt(z/8));if(!bins.TryGetValue(k,out var list))bins[k]=list=new();list.Add(h.point);top=h.point.y-.15f;}}
 var heights=new float[nx+1,nz+1];var columns=new List<(float floor,float side,float bottom,float top)>[nx+1,nz+1];
 for(int i=0;i<=nx;i++)for(int j=0;j<=nz;j++){float x=Mathf.Min(x1,x0+i*step),z=Mathf.Min(z1,z0+j*step),target=float.NegativeInfinity;var key=new Vector2Int(Mathf.FloorToInt(x/8),Mathf.FloorToInt(z/8));for(int dx=-6;dx<=6;dx++)for(int dz=-6;dz<=6;dz++)if(bins.TryGetValue(key+new Vector2Int(dx,dz),out var ps))foreach(var p in ps){float d=Vector2.Distance(new(x,z),new(p.x,p.z));if(d<48)target=Mathf.Max(target,p.y-.22f-d*.72f);}
 float old=45;foreach(var g in grounds)if(g.Raycast(new Ray(new(x,220,z),Vector3.down),out var hit,260))old=Mathf.Max(old,hit.point.y);if(float.IsNegativeInfinity(target))target=old;
 foreach(var cut in cuts.Where(c=>c.top<100)){var cd=new Vector2(cut.b.x-cut.a.x,cut.b.z-cut.a.z);var cq=new Vector2(x-cut.a.x,z-cut.a.z);float ct=Mathf.Clamp01(Vector2.Dot(cq,cd)/Mathf.Max(.0001f,cd.sqrMagnitude));float lateral=(cq-cd*ct).magnitude;if(lateral<cut.width+18)target=Mathf.Min(target,Mathf.Lerp(cut.a.y,cut.b.y,ct)-.12f+Mathf.Max(0,lateral-cut.width)*2.2f);}if(driving.Raycast(new Ray(new(x,220,z),Vector3.down),out var floor,260))target=floor.point.y-.10f;float edge=Mathf.Min(x-x0,x1-x,z-z0,z1-z);heights[i,j]=Mathf.Lerp(old,target,Mathf.SmoothStep(0,1,edge/12));
 var col=columns[i,j]=new();foreach(var cut in cuts){var d=new Vector2(cut.b.x-cut.a.x,cut.b.z-cut.a.z);var q=new Vector2(x-cut.a.x,z-cut.a.z);float t=Vector2.Dot(q,d)/Mathf.Max(.0001f,d.sqrMagnitude);if(cut.top>100&&(t<0||t>1))continue;t=Mathf.Clamp01(t);float side=cut.width-(q-d*t).magnitude;if(side> -4)col.Add((Mathf.Lerp(cut.a.y,cut.b.y,t),side,cut.bottom,cut.top));}
 }
 float Field(int x,int z,float y){float d=heights[x,z]-y;foreach(var c in columns[x,z])d=Mathf.Min(d,-Mathf.Min(c.side,y-c.floor-c.bottom,c.floor+c.top-y));return d;}
 var faces=new List<Face>();int[][] tets={new[]{0,5,1,6},new[]{0,1,2,6},new[]{0,2,3,6},new[]{0,3,7,6},new[]{0,7,4,6},new[]{0,4,5,6}};int[] ox={0,1,1,0,0,1,1,0},oz={0,0,1,1,0,0,1,1};
 void Emit(Vector3 a,Vector3 b,Vector3 c,Vector3 outward){if(Vector3.Dot(Vector3.Cross(b-a,c-a),outward)<0)(b,c)=(c,b);faces.Add(new Face(E(a),E(b),E(c)));}
 for(int i=0;i<nx;i++)for(int j=0;j<nz;j++){float highest=Mathf.Max(heights[i,j],heights[i+1,j],heights[i,j+1],heights[i+1,j+1]);for(float y=40;y<=highest+2;y+=2){var p=new Vector3[8];var d=new float[8];bool pos=false,neg=false;for(int k=0;k<8;k++){p[k]=new(Mathf.Min(x1,x0+(i+ox[k])*step),y+(k>=4?2:0),Mathf.Min(z1,z0+(j+oz[k])*step));d[k]=Field(i+ox[k],j+oz[k],p[k].y);pos|=d[k]>=0;neg|=d[k]<0;}if(!pos||!neg)continue;
 foreach(var tet in tets){var inside=tet.Where(k=>d[k]>=0).ToArray();var outside=tet.Where(k=>d[k]<0).ToArray();if(inside.Length==0||outside.Length==0)continue;Vector3 At(int a,int b)=>Vector3.Lerp(p[a],p[b],d[a]/(d[a]-d[b]));var normal=outside.Select(k=>p[k]).Aggregate(Vector3.zero,(a,b)=>a+b)/outside.Length-inside.Select(k=>p[k]).Aggregate(Vector3.zero,(a,b)=>a+b)/inside.Length;
 if(inside.Length==1)Emit(At(inside[0],outside[0]),At(inside[0],outside[1]),At(inside[0],outside[2]),normal);else if(outside.Length==1)Emit(At(outside[0],inside[0]),At(outside[0],inside[1]),At(outside[0],inside[2]),normal);else {var a=At(inside[0],outside[0]);var b=At(inside[0],outside[1]);var c=At(inside[1],outside[0]);var e=At(inside[1],outside[1]);Emit(a,b,c,normal);Emit(b,e,c,normal);}}
 }}
 var planes=new[]{new Plane(Vector3.right,new Vector3(x0,0,0)),new Plane(Vector3.left,new Vector3(x1,0,0)),new Plane(Vector3.forward,new Vector3(0,0,z0)),new Plane(Vector3.back,new Vector3(0,0,z1))};
 foreach(var g in grounds){if(g.name.Contains("rock vault")||g.name.Contains("portal outcrops")||g.name.Contains("mountain cap"))continue;var mf=g.GetComponent<MeshFilter>();if(mf)Assign(mf,scene+"-solid-retained-"+index+"-"+g.GetEntityId().ToString().Replace(':','-'),Read(mf).SelectMany(f=>Subtract(f,planes)).ToList());}
 Make("ReportCleanup "+scene+" continuous solid "+index++,faces,mat);notes.Add(area+" solid surface triangles="+faces.Count);Physics.SyncTransforms();
 }
 Save();File.WriteAllLines("Docs/ReportCleanup/"+scene+"-solid-terrain.txt",notes);return "Continuous terrain solid saved; dependencies require final seating";
 }
}





