using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class AuthorUndergroundPolish {
 const string F="Assets/Track/UndergroundPolish",D="Docs/UndergroundPolish";
 static Transform root;static int serial;static List<string> log=new();
 static Material Mat(string name,Color color,bool underground=false,bool natural=false){var m=new Material(Shader.Find(underground?"Racer/UndergroundSurface":"Universal Render Pipeline/Lit")){name=name,color=color};if(underground)m.SetFloat("_Natural",natural?1:0);AssetDatabase.CreateAsset(m,F+"/"+name+".mat");return m;}
 static GameObject Part(string name,Vector3 p,Vector3 size,Quaternion q,Material mat,PrimitiveType type=PrimitiveType.Cube){var g=GameObject.CreatePrimitive(type);g.name=name;g.transform.SetParent(root);g.transform.SetPositionAndRotation(p,q);g.transform.localScale=size;g.GetComponent<Renderer>().sharedMaterial=mat;Object.DestroyImmediate(g.GetComponent<Collider>());return g;}
 static void Surface(MeshFilter mf,WoodlandRoute b,Material mat,float begin,float end,bool lift=false){var mesh=Object.Instantiate(mf.sharedMesh);mesh.name=mf.name+" atmosphere";var v=mesh.vertices;var colors=new Color[v.Length];for(int i=0;i<v.Length;i++){var p=mf.transform.TransformPoint(v[i]);float s=b.Project(p,out _);if(lift&&(i%4==1||i%4==2)){p.y+=.9f*(1-Mathf.SmoothStep(0,1,(s-begin)/28));v[i]=mf.transform.InverseTransformPoint(p);}float portal=Mathf.Max(1-Mathf.Clamp01((s-begin)/20),1-Mathf.Clamp01((end-s)/26));float pocket=Mathf.Pow(Mathf.Max(0,Mathf.Cos((s-begin)*Mathf.PI/24)),12)*.17f;float value=Mathf.Lerp(.34f+pocket,1,portal);colors[i]=new(value,value,value,1);}mesh.vertices=v;mesh.colors=colors;mesh.RecalculateBounds();mesh.RecalculateNormals();AssetDatabase.CreateAsset(mesh,F+"/surface-"+(serial++)+".asset");mf.sharedMesh=mesh;mf.GetComponent<Renderer>().sharedMaterial=mat;var c=mf.GetComponent<MeshCollider>();if(c)c.sharedMesh=mesh;}
 public static string Main(){if(Application.isPlaying||UnityEngine.SceneManagement.SceneManager.GetActiveScene().isDirty)throw new Exception("Saved edit mode required");Directory.CreateDirectory(F);AssetDatabase.Refresh();
 EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");Physics.SyncTransforms();
 // The only atlas arrow by the supplied driveway exit sits off the accepted main line.
 var stray=Object.FindObjectsByType<Renderer>().Single(r=>r.name=="Main teal / reassurance"&&Vector3.Distance(r.bounds.center,new(464.6f,82.2f,-2.1f))<12);log.Add("Removed "+stray.name+" at bounds "+stray.bounds.center+" (atlas mesh stored at world origin)");Object.DestroyImmediate(stray.gameObject);
 var b=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title.StartsWith("Storm"));var ridge=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title.StartsWith("Abandoned"));
 root=new GameObject("Storm Drain atmosphere").transform;var concrete=Mat("Dark stained concrete",new(.42f,.46f,.43f),true);var wet=Mat("Wet drain edges",new(.07f,.14f,.15f));wet.SetFloat("_Smoothness",.94f);wet.SetFloat("_Metallic",.35f);var wood=Mat("Storm washed wood",new(.19f,.125f,.07f));var trash=Mat("Weathered pale litter",new(.34f,.32f,.23f));var rust=Mat("Rusted drainage iron",new(.19f,.12f,.065f));var stain=Mat("Drain mineral stains",new(.035f,.065f,.043f));
 var shell=GameObject.Find("Long storm culvert walls and ceiling").GetComponent<MeshFilter>();Surface(shell,b,concrete,b.undergroundStart,b.undergroundEnd,true);Surface(GameObject.Find("Ground_Culvert seamless floor").GetComponent<MeshFilter>(),b,concrete,b.undergroundStart,b.undergroundEnd);
 var mouth=b.At(b.undergroundStart,out _);foreach(var t in Object.FindObjectsByType<Transform>().Where(t=>Vector3.Distance(t.position,mouth)<11)){if(t.name=="Culvert mouth lintel")t.position+=Vector3.up*.9f;if(t.name=="Supported culvert mouth pier"){t.position+=Vector3.up*.45f;t.localScale+=Vector3.up*.9f;}}
 foreach(var t in Object.FindObjectsByType<Transform>().Where(t=>t.name=="Culvert overhead expansion joint")){float s=b.Project(t.position,out _);t.position+=Vector3.up*(.9f*(1-Mathf.SmoothStep(0,1,(s-b.undergroundStart)/28)));}
 int lamp=0;foreach(var l in Object.FindObjectsByType<Light>().Where(l=>l.name=="Low maintenance tunnel light")){l.intensity=(lamp++%3==0)?.25f:0;l.range=9;}
 var rng=new System.Random(56000);for(float s=b.undergroundStart+6;s<b.undergroundEnd-5;s+=3.2f){var p=b.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;var q=Quaternion.LookRotation(f);int sign=((int)(s*10)%2==0)?1:-1;foreach(int edge in new[]{-1,1}){
 float offset=3.55f+(float)rng.NextDouble()*.55f;var foot=p+side*offset*edge;
 Part("Storm washed branch or board",foot+Vector3.up*.10f,new(.13f,.13f,.5f+(float)rng.NextDouble()*.9f),q*Quaternion.Euler(0,rng.Next(-35,35),0),wood);
 Part("Water edge litter",foot+f*.65f+Vector3.up*.06f,new(.27f,.05f,.38f),q*Quaternion.Euler(0,rng.Next(180),0),trash);
 Part("Damp sediment and leaf cluster",foot-f*.4f+Vector3.up*.035f,new(.7f,.05f,.65f),q,stain,PrimitiveType.Sphere);
 if((int)s%3==0)Part("Drain wall mineral streak",p+side*(4.53f+.2f*Mathf.Sin(s*.045f))*edge+Vector3.up*1.8f,new(.035f,2.9f,.5f),q,stain);
 }
 if((int)s%5==0)Part("Broken rusted pipe section",p+side*3.95f*sign+Vector3.up*.2f,new(.4f,.5f,.4f),q*Quaternion.Euler(90,0,0),rust,PrimitiveType.Cylinder);
 }
 // Four recognizable rats, pooled once and animated into side recesses.
 var encounter=new GameObject("Drain entrance rat encounter").AddComponent<UndergroundLife>();encounter.transform.SetParent(root);encounter.entrance=b.At(b.undergroundStart+9,out var entryForward);encounter.forward=Vector3.ProjectOnPlane(entryForward,Vector3.up).normalized;encounter.rats=new Transform[4];encounter.refuges=new Vector3[4];var fur=Mat("Rat brown grey fur",new(.23f,.20f,.17f));var pink=Mat("Rat ears and tails",new(.33f,.22f,.2f));var black=Mat("Rat eyes",new(.012f,.009f,.008f));
 for(int i=0;i<4;i++){var p=b.At(b.undergroundStart+10+i*1.8f,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;int edge=i%2==0?1:-1;var rat=new GameObject("Scurrying drain rat "+(i+1)).transform;rat.SetParent(encounter.transform);rat.position=p+side*edge*(1.1f+i*.24f)+Vector3.up*.14f;rat.rotation=Quaternion.LookRotation(f);var save=root;root=rat;
 void Body(string n,Vector3 local,Vector3 size,Material mat){var g=Part(n,rat.TransformPoint(local),size,rat.rotation,mat,PrimitiveType.Sphere);}
 Body("Rat body",Vector3.zero,new(.24f,.21f,.46f),fur);Body("Rat pointed muzzle",new(0,.005f,.26f),new(.14f,.14f,.23f),fur);foreach(int a in new[]{-1,1}){Body("Rat ear",new(a*.09f,.10f,.18f),new(.09f,.10f,.05f),pink);Body("Rat eye",new(a*.065f,.04f,.29f),new(.025f,.025f,.025f),black);}
 Part("Rat tail",rat.TransformPoint(new(.035f,-.04f,-.37f)),new(.026f,.026f,.42f),rat.rotation*Quaternion.Euler(0,-12,0),pink);root=save;encounter.rats[i]=rat;encounter.refuges[i]=p+f*4+side*edge*4.65f+Vector3.up*.13f;
 Part("Rat refuge dark recess",encounter.refuges[i]+Vector3.up*.1f,new(.08f,.65f,.85f),Quaternion.LookRotation(f),stain);
 }
 // Previous rebuilding removed the label. Use the established one-sided, depth-tested font style.
 var signP=ridge.At(5,out var rf);rf=Vector3.ProjectOnPlane(rf,Vector3.up).normalized;signP+=Vector3.Cross(Vector3.up,rf)*3.7f;var hit=Physics.RaycastAll(signP+Vector3.up*8,Vector3.down,16,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).OrderBy(h=>Mathf.Abs(h.point.y-signP.y)).First();signP.y=hit.point.y;
 var signQ=Quaternion.LookRotation(rf);Part("Logging Ridge grounded sign post",signP+Vector3.up*1.2f,new(.15f,2.4f,.15f),signQ,wood);Part("Logging Ridge sign board",signP+Vector3.up*2.1f,new(4.4f,.85f,.13f),signQ,wood);
 var letters=new GameObject("LOGGING RIDGE",typeof(TextMesh));letters.transform.SetParent(root);letters.transform.SetPositionAndRotation(signP+Vector3.up*2.1f-rf*.08f,signQ);var text=letters.GetComponent<TextMesh>();text.text="LOGGING RIDGE";text.fontSize=56;text.characterSize=.09f;text.anchor=TextAnchor.MiddleCenter;text.alignment=TextAlignment.Center;text.color=new(1,.78f,.32f);var fontMat=new Material(text.GetComponent<Renderer>().sharedMaterial){shader=Shader.Find("Racer/SummitText")};AssetDatabase.CreateAsset(fontMat,F+"/Logging Ridge font.mat");text.GetComponent<Renderer>().sharedMaterial=fontMat;
 log.Add("Drain: entrance ceiling/lintel +0.9m taper over 28m, piers extended with bases preserved; floor vertices unchanged. Four non-colliding rats and local audio; 300+ edge details; restrained lights; grounded sign.");
 Save();
 EditorSceneManager.OpenScene("Assets/Scenes/ForestLoopReverse.unity");Physics.SyncTransforms();root=new GameObject("Forest Reverse natural cave atmosphere").transform;
 var caveShell=GameObject.Find("Echo Cave enclosed rock").GetComponent<MeshFilter>();b=Object.FindObjectsByType<WoodlandRoute>().OrderBy(b=>{b.Project(caveShell.sharedMesh.vertices[caveShell.sharedMesh.vertexCount/2],out float d);return d;}).First();
 var shellVertices=caveShell.sharedMesh.vertices.Select(caveShell.transform.TransformPoint).ToArray();float begin=shellVertices.Min(p=>b.Project(p,out _)),end=shellVertices.Max(p=>b.Project(p,out _));var rock=Mat("Dark damp cave stone",new(.43f,.39f,.33f),true,true);Surface(caveShell,b,rock,begin,end);var stone=Mat("Fallen cave stone",new(.17f,.16f,.125f));var roots=Mat("Cave exposed roots",new(.15f,.10f,.055f));var damp=Mat("Cave damp patches",new(.055f,.075f,.064f));damp.SetFloat("_Smoothness",.85f);
 foreach(var l in Object.FindObjectsByType<Light>().Where(l=>l.name=="Cave warm wayfinding")){l.intensity=.22f;l.range=12;l.color=new(.52f,.63f,.61f);}
 for(float s=begin+12;s<end-12;s+=7){var p=b.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;var q=Quaternion.LookRotation(f);foreach(int edge in new[]{-1,1}){
 var foot=p+side*edge*4.7f;var ground=Physics.RaycastAll(foot+Vector3.up*3,Vector3.down,7,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).OrderBy(h=>Mathf.Abs(h.point.y-foot.y)).ToArray();if(ground.Length==0)continue;foot.y=ground[0].point.y;
 Part("Cave fallen angular stone",foot+Vector3.up*.18f,new(.7f,.36f,.95f),q*Quaternion.Euler(0,s*7,12),stone,PrimitiveType.Cube);
 Part("Damp cave gravel patch",foot+Vector3.up*.035f,new(1.3f,.045f,1.8f),q,damp,PrimitiveType.Sphere);
 var crown=Physics.RaycastAll(p+side*edge*3.8f+Vector3.up*3,Vector3.up,25,1,QueryTriggerInteraction.Ignore).FirstOrDefault(h=>h.collider==caveShell.GetComponent<MeshCollider>());if(crown.collider){float drop=1.1f+Mathf.PingPong(s*.1f,1);Part("Natural ceiling formation",crown.point-Vector3.up*drop*.32f,new(.65f,drop,.8f),q*Quaternion.Euler(0,s,8),stone,PrimitiveType.Sphere);Part("Exposed ceiling root",crown.point-Vector3.up*.3f,new(.09f,.09f,2.6f),q*Quaternion.Euler(20,s,15),roots);}
 }
 }
 foreach(float s in new[]{begin+45,(begin+end)*.5f,end-40}){var drip=new GameObject("Quiet localized cave drips").AddComponent<UndergroundLife>();drip.transform.SetParent(root);drip.cave=true;drip.rats=Array.Empty<Transform>();drip.refuges=Array.Empty<Vector3>();drip.entrance=b.At(s,out _)+Vector3.up*2;}
 log.Add($"Forest cave route preserved: {b.title}, decoration span {begin:F1}-{end:F1}; no detail colliders, daylight ends, natural stone/roots/dampness and three sparse localized drip sources.");Save();AssetDatabase.SaveAssets();File.WriteAllLines(D+"/authoring.txt",log);EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");return string.Join("\n",log);
 }
 static void Save(){EditorSceneManager.MarkSceneDirty(root.gameObject.scene);EditorSceneManager.SaveScene(root.gameObject.scene);AssetDatabase.SaveAssets();}
}
