using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
// Local saved-scene repair. Route/navigation/checkpoint transforms are never changed.
public static class MountainCut {
 const string Folder="Assets/Track/MountainCut";
 struct V {public Vector3 p;public Color c;public V(Vector3 p,Color c){this.p=p;this.c=c;}public static V Lerp(V a,V b,float t)=>new V(Vector3.Lerp(a.p,b.p,t),Color.Lerp(a.c,b.c,t));}
 class Face {public List<V> v;public Face(params V[] a){v=a.ToList();}}
 static Color Earth=new(.39f,.48f,.29f),Rock=new(.34f,.36f,.29f);
 static V E(Vector3 p)=>new(p,Earth);static V R(Vector3 p)=>new(p,Rock);
 static List<V> Clip(List<V> poly,Plane plane,bool inside){var result=new List<V>();for(int i=0;i<poly.Count;i++){var a=poly[i];var b=poly[(i+1)%poly.Count];float da=plane.GetDistanceToPoint(a.p),db=plane.GetDistanceToPoint(b.p);bool ia=inside?da>=-.00001f:da<=.00001f,ib=inside?db>=-.00001f:db<=.00001f;if(ia)result.Add(a);if(ia!=ib)result.Add(V.Lerp(a,b,da/(da-db)));}return result;}
 static IEnumerable<Face> Subtract(Face f,Plane[] planes){var intersection=f.v;foreach(var p in planes){intersection=Clip(intersection,p,true);if(intersection.Count<3)return new[]{f};}var outside=new List<Face>();var rest=f.v;foreach(var p in planes){var part=Clip(rest,p,false);if(part.Count>=3)outside.Add(new Face(part.ToArray()));rest=Clip(rest,p,true);if(rest.Count<3)break;}return outside;}
 static Plane[] Box(Vector3 a,Vector3 b,float width,float bottom,float top){var f=Vector3.ProjectOnPlane(b-a,Vector3.up).normalized;var right=Vector3.Cross(Vector3.up,f);var up=Vector3.Cross(b-a,right).normalized;if(up.y<0)up=-up;return new[]{new Plane(f,a-f*.15f),new Plane(-f,b+f*.15f),new Plane(right,a-right*width),new Plane(-right,a+right*width),new Plane(up,a+Vector3.up*bottom),new Plane(-up,a+Vector3.up*top)};}
 static List<Face> Read(MeshFilter mf){var m=mf.sharedMesh;var v=m.vertices;var c=m.colors;var t=m.triangles;return Enumerable.Range(0,t.Length/3).Select(i=>new Face(Enumerable.Range(0,3).Select(j=>{int k=t[i*3+j];return new V(mf.transform.TransformPoint(v[k]),c.Length==v.Length?c[k]:Earth);}).ToArray())).ToList();}
 static Mesh Store(string name,List<Face> faces){var vs=new List<Vector3>();var cs=new List<Color>();var ix=new List<int>();foreach(var face in faces)for(int j=1;j+1<face.v.Count;j++){var a=face.v[0];var b=face.v[j];var c=face.v[j+1];if(Vector3.Cross(b.p-a.p,c.p-a.p).sqrMagnitude<.00000001f)continue;int k=vs.Count;vs.AddRange(new[]{a.p,b.p,c.p});cs.AddRange(new[]{a.c,b.c,c.c});ix.AddRange(new[]{k,k+1,k+2});}var mesh=new Mesh{indexFormat=UnityEngine.Rendering.IndexFormat.UInt32};mesh.SetVertices(vs);mesh.SetColors(cs);mesh.SetTriangles(ix,0);mesh.RecalculateNormals();mesh.RecalculateBounds();string path=Folder+"/"+name+".asset";var old=AssetDatabase.LoadAssetAtPath<Mesh>(path);if(old){EditorUtility.CopySerialized(mesh,old);Object.DestroyImmediate(mesh);return old;}AssetDatabase.CreateAsset(mesh,path);return mesh;}
 static void Assign(MeshFilter mf,string name,List<Face> faces){var mesh=Store(name,faces);mf.transform.SetPositionAndRotation(Vector3.zero,Quaternion.identity);mf.transform.localScale=Vector3.one;mf.sharedMesh=mesh;if(mf.TryGetComponent<MeshCollider>(out var mc)){mc.sharedMesh=null;mc.sharedMesh=mesh;}}
 static void Quad(List<Face> f,Vector3 a,Vector3 b,Vector3 c,Vector3 d,bool rock=false,bool doubleSide=false){var col=rock?Rock:Earth;f.Add(new Face(new(a,col),new(b,col),new(c,col)));f.Add(new Face(new(a,col),new(c,col),new(d,col)));if(doubleSide){f.Add(new Face(new(c,col),new(b,col),new(a,col)));f.Add(new Face(new(d,col),new(c,col),new(a,col)));}}
 static bool Local(Vector3 p)=>p.x>855&&p.x<1060&&p.z>-112&&p.z<185;
 static GameObject Make(string name,List<Face> fs,Material mat){var g=new GameObject("Ground_"+name,typeof(MeshFilter),typeof(MeshRenderer),typeof(MeshCollider));g.GetComponent<MeshRenderer>().sharedMaterial=mat;Assign(g.GetComponent<MeshFilter>(),name,fs);return g;}
 public static string Main(){if(Application.isPlaying)throw new Exception("Edit mode required");Directory.CreateDirectory(Folder);Directory.CreateDirectory("Docs/MountainCut");EditorSceneManager.OpenScene("Assets/Scenes/MountainLoopReverse.unity");Physics.SyncTransforms();var race=Object.FindAnyObjectByType<RaceDirector>();var road=race.road;road.Initialize();var branch=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title=="Summit Traverse");branch.Initialize();var driving=GameObject.Find("Ground_CR133 mountain driving surface").GetComponent<MeshCollider>();var support=GameObject.Find("Ground_MountainPolish supported shoulders").GetComponent<MeshFilter>();var mat=support.GetComponent<Renderer>().sharedMaterial;var notes=new List<string>();
 // Dependency inventory before modifying supporting meshes.
 var signs=Object.FindObjectsByType<PhysicalSign>().Where(s=>Local(s.transform.position)).ToArray();var props=Object.FindObjectsByType<Transform>().Where(t=>t.name.StartsWith("Acorn clue /")&&Local(t.position)).ToArray();File.WriteAllLines("Docs/MountainCut/dependencies-before.txt",signs.Select(s=>s.name+" "+s.transform.position).Concat(props.Select(p=>p.name+" "+p.position)));
 var baseGround=Object.FindObjectsByType<Collider>().Where(c=>c.name.StartsWith("Ground_")&&c!=driving&&c!=support.GetComponent<Collider>()).ToArray();
 float Ground(Vector3 p){var ys=baseGround.Select(c=>c.Raycast(new Ray(p+Vector3.up*.05f,Vector3.down),out var h,170)?h.point.y:float.NegativeInfinity).Where(y=>!float.IsNegativeInfinity(y)).ToArray();return ys.Length>0?ys.Max():p.y-15;}
 // Retain support elsewhere; replace only junction support, avoiding unmatched internal-edge fins.
 var old=Read(support);var keep=old.Where(f=>!f.v.Any(v=>Local(v.p))).ToList();notes.Add("Retired local support faces="+(old.Count-keep.Count));Assign(support,"retained-shoulders",keep);Physics.SyncTransforms();
 var banks=new List<Face>();
 void Skirts(Func<float,Vector3> at,float start,float end){foreach(int side in new[]{-1,1}){Vector3 previous=default,previousOuter=default,previousToe=default;bool valid=false;for(float s=start;s<=end+.1f;s+=1){var p=at(s);var f=(at(s+.25f)-at(s-.25f)).normalized;var right=Vector3.Cross(Vector3.up,f).normalized;Vector3 edge=default;bool found=false;for(float w=3;w<=15;w+=.25f){var q=p+right*(w*side);if(driving.Raycast(new Ray(q+Vector3.up*1.5f,Vector3.down),out var h,3)){edge=h.point;found=true;}else if(found)break;}if(!found){valid=false;continue;}edge.y-=.06f;var outer=edge+right*(side*1.3f);outer.y-=.25f;var toe=outer+right*(side*Mathf.Clamp((outer.y-Ground(outer))*1.3f,4,22));toe.y=Mathf.Min(outer.y-.15f,Ground(toe));if(valid){if(side==1){Quad(banks,previous,edge,outer,previousOuter);Quad(banks,previousOuter,outer,toe,previousToe);}else{Quad(banks,edge,previous,previousOuter,outer);Quad(banks,outer,previousOuter,previousToe,toe);}}previous=edge;previousOuter=outer;previousToe=toe;valid=true;}}}
 Skirts(s=>road.At(s,out _),390,520);Skirts(s=>branch.At(s,out _),0,branch.Length-18);
 // Reserve each route layer's full clearance, not a single crossing hole.
 var volumes=new List<Plane[]>();for(float s=800;s<962;s+=2)volumes.Add(Box(road.At(s,out _),road.At(s+2,out _),9,-.12f,7.3f));
 for(float s=390;s<520;s+=3)volumes.Add(Box(road.At(s,out _),road.At(s+3,out _),6.9f,-.12f,7));
 for(float s=0;s<branch.Length;s+=3)volumes.Add(Box(branch.At(s,out _),branch.At(Mathf.Min(s+3,branch.Length),out _),6.2f,-.12f,7));
 List<Face> Carve(List<Face> input){foreach(var volume in volumes){var next=new List<Face>();foreach(var f in input)next.AddRange(Subtract(f,volume));input=next;}return input;}
 banks=Carve(banks);Make("MountainCut natural embankments",banks,mat);notes.Add("Replacement embankment faces="+banks.Count);
 // Remove remaining original support intrusions in the lower-road envelope only.
 foreach(var mf in Object.FindObjectsByType<MeshFilter>().Where(m=>m.sharedMesh&&m.name.StartsWith("Ground_")&&m.gameObject!=driving.gameObject&&m!=support&&!m.name.Contains("MountainCut")).ToArray()){
 var fs=Read(mf);bool changed=false;for(float s=830;s<950;s+=2){var vol=Box(road.At(s,out _),road.At(s+2,out _),9,-.1f,7.3f);var next=new List<Face>();foreach(var f in fs){if(!f.v.Any(v=>v.p.x>970&&v.p.x<1010&&v.p.z>100&&v.p.z<215)){next.Add(f);continue;}var pieces=Subtract(f,vol).ToArray();if(pieces.Length!=1||pieces[0]!=f)changed=true;next.AddRange(pieces);}fs=next;}if(changed){Assign(mf,"cut-"+mf.name.Replace('/','-'),fs);notes.Add("Carved lower clearance in "+mf.name);}}
 // Rock vault under the upper road: 18m opening, 7.8m minimum headroom.
 // Portals and side rock slope outward into the mountain, never a floor or a route change.
 var shell=new List<Face>();for(int z=112;z<144;z+=2){float floor(float zz)=>road.At(road.Project(new Vector3(990,152,zz),out _),out _).y;Vector3[] Section(float zz){float y=floor(zz);return new[]{new Vector3(977,y-2,zz),new Vector3(980,y+5.2f,zz),new Vector3(982,y+7.8f,zz),new Vector3(990,y+8.4f,zz),new Vector3(998,y+7.8f,zz),new Vector3(1000,y+5.2f,zz),new Vector3(1003,y-2,zz)};}var a=Section(z);var b=Section(z+2);for(int i=0;i<a.Length-1;i++)Quad(shell,a[i],b[i],b[i+1],a[i+1],true,true);}
 // Vault upper skin meets the actual upper-road underside and adjacent banks.
 foreach(float z in new[]{112f,144f}){float y=road.At(road.Project(new Vector3(990,152,z),out _),out _).y;var inner=new[]{new Vector3(977,y-2,z),new Vector3(980,y+5.2f,z),new Vector3(982,y+7.8f,z),new Vector3(990,y+8.4f,z),new Vector3(998,y+7.8f,z),new Vector3(1000,y+5.2f,z),new Vector3(1003,y-2,z)};for(int i=0;i<inner.Length-1;i++){var a=inner[i];var b=inner[i+1];var aa=a;var bb=b;aa.x=990+(aa.x-990)*1.4f;bb.x=990+(bb.x-990)*1.4f;aa.y=Mathf.Min(163.6f,a.y+3.2f);bb.y=Mathf.Min(163.6f,b.y+3.2f);Quad(shell,a,b,bb,aa,true,true);}}
 shell=Carve(shell);Make("MountainCut rock vault",shell,mat);Physics.SyncTransforms();
 // Natural visible colliding boulders protect selected exposed upper shoulders.
 var stones=new List<string>();foreach(float s in new[]{54f,72f,92f,118f,142f,170f,198f,222f}){var p=branch.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;var q=p+side*8.1f;if(Physics.Raycast(new Ray(q+Vector3.up*3,Vector3.down),out var hit,20,1,QueryTriggerInteraction.Ignore)&&hit.collider.name.StartsWith("Ground_")){var g=GameObject.CreatePrimitive(PrimitiveType.Sphere);g.name="Summit natural edge boulder";g.transform.position=hit.point+Vector3.up*.55f;g.transform.localScale=new Vector3(2.7f,1.9f,2.5f);g.GetComponent<Renderer>().sharedMaterial=mat;var mesh=Object.Instantiate(g.GetComponent<MeshFilter>().sharedMesh);mesh.colors=Enumerable.Repeat(Rock,mesh.vertexCount).ToArray();AssetDatabase.CreateAsset(mesh,Folder+"/boulder-"+s+".asset");g.GetComponent<MeshFilter>().sharedMesh=mesh;stones.Add(g.transform.position.ToString());}}
 // Gate visuals only. Preserve trigger transform, dimensions, order and progression.
 var gate=race.gates[1];foreach(var r in gate.GetComponentsInChildren<Renderer>()){if(r.bounds.size.y<1)r.transform.position+=Vector3.up*3.5f;else{var sc=r.transform.localScale;sc.y*=1.875f;r.transform.localScale=sc;r.transform.position+=Vector3.up*1.75f;}}notes.Add("Raised CP1 visual crossbar 3.5m; checkpoint data unchanged");
 Physics.SyncTransforms();foreach(var sign in signs){var rs=sign.GetComponentsInChildren<Renderer>();var posts=rs.Where(r=>r.name.IndexOf("post",StringComparison.OrdinalIgnoreCase)>=0).ToArray();if(posts.Length==0)continue;float foot=posts.Min(r=>r.bounds.min.y);var p=sign.transform.position;var hits=Physics.RaycastAll(new(p.x,foot+25,p.z),Vector3.down,90,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).ToArray();if(hits.Length==0)continue;float ground=hits.Max(h=>h.point.y);sign.transform.position+=Vector3.up*(ground-foot+.03f);notes.Add("Grounded sign "+sign.name+" delta="+(ground-foot));}
 foreach(var t in props){var rs=t.GetComponentsInChildren<Renderer>();if(rs.Length==0)continue;var p=rs[0].bounds.center;float foot=rs.Min(r=>r.bounds.min.y);var hits=Physics.RaycastAll(new(p.x,foot+20,p.z),Vector3.down,70,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).ToArray();if(hits.Length>0)t.position+=Vector3.up*(hits.Max(h=>h.point.y)-foot);}
 // Reuse established complete-tree grounding so batched crowns follow their trunks.
 typeof(Racer.Editor.BackyardReverseAuthoring).GetMethod("Trees",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Static).Invoke(null,new object[]{(Func<Collider,bool>)(c=>false),(Func<Collider,bool>)(c=>Local(c.bounds.center))});
 EditorSceneManager.MarkSceneDirty(race.gameObject.scene);EditorSceneManager.SaveScene(race.gameObject.scene);AssetDatabase.SaveAssets();File.WriteAllLines("Docs/MountainCut/authoring.txt",notes);return string.Join("\n",notes);
 }
 public static string RestoreGrade(){
 var race=Object.FindAnyObjectByType<RaceDirector>();var road=race.road;var branch=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title=="Summit Traverse");var oldMesh=AssetDatabase.LoadAssetAtPath<Mesh>("Assets/Track/LocalRecovery/Surgical-second-arrow-Ground_CR133 mountain driving surface.asset");var temp=new GameObject("Temporary original grade",typeof(MeshCollider));var mc=temp.GetComponent<MeshCollider>();mc.sharedMesh=oldMesh;Physics.SyncTransforms();
 float Height(Vector3 p){return mc.Raycast(new Ray(new(p.x,185,p.z),Vector3.down),out var h,45)?h.point.y:p.y;}
 int moved=0;foreach(var mf in Object.FindObjectsByType<MeshFilter>().Where(m=>m.sharedMesh&&(m.name.Contains("driving surface")||m.name.Contains("arrow")||m.name.Contains("Main teal")))){var vs=mf.sharedMesh.vertices;bool changed=false;for(int i=0;i<vs.Length;i++){var p=mf.transform.TransformPoint(vs[i]);if(p.x<981||p.x>999||p.z<72||p.z>110||p.y<145||p.y>180)continue;float y=Height(p);bool marking=mf.name.Contains("arrow")||mf.name.Contains("Main teal");float target=y+(marking?.075f:0);if(Math.Abs(p.y-target)<.001f)continue;p.y=target;vs[i]=mf.transform.InverseTransformPoint(p);changed=true;moved++;}if(!changed)continue;var mesh=Object.Instantiate(mf.sharedMesh);mesh.vertices=vs;mesh.RecalculateNormals();mesh.RecalculateBounds();var path=Folder+"/restored-"+mf.name.Replace('/','-')+".asset";AssetDatabase.CreateAsset(mesh,path);mf.sharedMesh=mesh;if(mf.TryGetComponent<MeshCollider>(out var c))c.sharedMesh=mesh;}
 // Same X/Z route, original physical run-up elevation. Cache is refreshed, not re-routed.
 int rp=0;for(int i=0;i<road.points.Length;i++){var p=road.points[i];if(Math.Abs(p.x-990)>.1f||p.z<72||p.z>110)continue;road.points[i]=new(p.x,Height(p)-.04f,p.z);rp++;}typeof(RaceRoad).GetField("distance",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance).SetValue(road,null);road.Initialize();EditorUtility.SetDirty(road);Object.DestroyImmediate(temp);
 // Remove the former side-entry screen's tiny intrusion at the restored road edge.
 foreach(var t in Object.FindObjectsByType<Transform>().Where(t=>t.name.StartsWith("Summit side-entry timber screen")&&t.position.z>95&&t.position.z<116&&t.position.x<985))t.position+=Vector3.left*2;
 // Build one uninterrupted vault; its roof stays clear of all driving surfaces.
 var vault=GameObject.Find("Ground_MountainCut rock vault").GetComponent<MeshFilter>();var fs=new List<Face>();
 Vector3[] Ring(float z){float y=152+Mathf.Pow(Mathf.Max(0,125-z)/60,2)*25;return new[]{new Vector3(977,y-2,z),new Vector3(980,y+5.2f,z),new Vector3(982,y+7.8f,z),new Vector3(990,y+8.4f,z),new Vector3(998,y+7.8f,z),new Vector3(1000,y+5.2f,z),new Vector3(1003,y-2,z)};}
 for(int z=112;z<144;z+=2){var a=Ring(z);var b=Ring(z+2);for(int i=0;i<a.Length-1;i++)Quad(fs,a[i],b[i],b[i+1],a[i+1],true,true);}
 // Close the rock mass over/alongside the opening rather than leaving cut-face cracks.
 for(int z=112;z<144;z+=2){var a=Ring(z);var b=Ring(z+2);for(int i=0;i<a.Length-1;i++){var aa=a[i];var ab=a[i+1];var ba=b[i];var bb=b[i+1];aa.y=Mathf.Max(aa.y,163.3f);ab.y=Mathf.Max(ab.y,163.3f);ba.y=Mathf.Max(ba.y,163.3f);bb.y=Mathf.Max(bb.y,163.3f);Quad(fs,aa,ba,bb,ab,true,true);}}
 foreach(float z in new[]{112f,144f}){var a=Ring(z);for(int i=0;i<a.Length-1;i++){var aa=a[i];var bb=a[i+1];aa.y=Mathf.Max(aa.y,163.3f);bb.y=Mathf.Max(bb.y,163.3f);Quad(fs,a[i],a[i+1],bb,aa,true,true);}}
 Assign(vault,"MountainCut rock vault",fs);
 // Smooth only the exposed local fin vertices on the cut's adjacent earth skin.
 foreach(var mf in Object.FindObjectsByType<MeshFilter>().Where(m=>m.sharedMesh&&m.name.StartsWith("Ground_")&&!m.name.Contains("driving surface")&&!m.name.Contains("rock vault"))){var vs=mf.sharedMesh.vertices;bool changed=false;for(int i=0;i<vs.Length;i++){var p=mf.transform.TransformPoint(vs[i]);float s=branch.Project(p,out float d);var q=branch.At(s,out _);if(s<25||s>285||d>22||p.y<q.y+1||p.y>q.y+14)continue;float horizontal=Vector2.Distance(new(p.x,p.z),new(q.x,q.z));if(horizontal>14)continue;p.y=q.y-.15f+Mathf.Max(0,horizontal-8)*.5f;vs[i]=mf.transform.InverseTransformPoint(p);changed=true;}if(!changed)continue;var mesh=Object.Instantiate(mf.sharedMesh);mesh.vertices=vs;mesh.RecalculateNormals();mesh.RecalculateBounds();AssetDatabase.CreateAsset(mesh,AssetDatabase.GenerateUniqueAssetPath(Folder+"/local-seam-"+mf.name+".asset"));mf.sharedMesh=mesh;if(mf.TryGetComponent<MeshCollider>(out var c))c.sharedMesh=mesh;}
 Physics.SyncTransforms();EditorSceneManager.MarkSceneDirty(race.gameObject.scene);EditorSceneManager.SaveScene(race.gameObject.scene);AssetDatabase.SaveAssets();var result=$"Restored original lower road grade: mesh/marking vertices={moved}, navigation points={rp}; X/Z line, branch and gates retained";File.WriteAllText("Docs/MountainCut/grade-restoration.txt",result);return result;
 }
 public static string Finish(){
 var race=Object.FindAnyObjectByType<RaceDirector>();var road=race.road;var branch=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title=="Summit Traverse");var before=Newtonsoft.Json.Linq.JObject.Parse(File.ReadAllText("Docs/MountainCut/routes-before.json"));road.points=before["road"].Select(t=>new Vector3((float)t[0],(float)t[1],(float)t[2])).ToArray();void Refresh(){typeof(RaceRoad).GetField("distance",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance).SetValue(road,null);road.Initialize();}Refresh();var anchors=Object.FindObjectsByType<WoodlandRoute>().Select(b=>new {b,entry=road.At(b.entryRoad,out _),exit=road.At(b.exitRoad,out _)}).ToArray();
 string temp="Assets/Scenes/MountainCutBaseline.unity";File.Copy("Temp/MountainCutBaseline.unity",temp,true);AssetDatabase.ImportAsset(temp);var baseline=EditorSceneManager.OpenScene(temp,OpenSceneMode.Additive);var oldRoad=baseline.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<RaceDirector>()).First().road;var lower=oldRoad.points.Where(p=>Math.Abs(p.x-990)<.01f&&p.z>=60&&p.z<=120).OrderBy(p=>p.z).ToArray();EditorSceneManager.CloseScene(baseline,true);AssetDatabase.DeleteAsset(temp);
 float Y(float z){for(int i=1;i<lower.Length;i++)if(z<=lower[i].z)return Mathf.Lerp(lower[i-1].y,lower[i].y,Mathf.InverseLerp(lower[i-1].z,lower[i].z,z));return lower.Last().y;}
 var mf=GameObject.Find("Ground_CR133 mountain driving surface").GetComponent<MeshFilter>();var source=AssetDatabase.LoadAssetAtPath<Mesh>("Assets/Track/MountainPolish/grade-Ground_CR133 mountain driving surface.asset");var mesh=Object.Instantiate(source);var vs=mesh.vertices;int changed=0;for(int i=0;i<vs.Length;i++){var p=vs[i];if(p.x<981||p.x>999||p.z<72||p.z>98||p.y<150||p.y>174)continue;float expected=Y(p.z)+.04f;if(Math.Abs(p.y-expected)>6)continue;p.y=expected;vs[i]=p;changed++;}mesh.vertices=vs;mesh.RecalculateNormals();mesh.RecalculateBounds();string path=Folder+"/restored-driving.asset";var oldAsset=AssetDatabase.LoadAssetAtPath<Mesh>(path);if(oldAsset){EditorUtility.CopySerialized(mesh,oldAsset);Object.DestroyImmediate(mesh);mesh=oldAsset;}else AssetDatabase.CreateAsset(mesh,path);mf.sharedMesh=mesh;mf.GetComponent<MeshCollider>().sharedMesh=mesh;
 for(int i=0;i<road.points.Length;i++){var p=road.points[i];if(Math.Abs(p.x-990)<.01f&&p.z>=72&&p.z<=110)road.points[i]=new(p.x,Y(p.z),p.z);}Refresh();EditorUtility.SetDirty(road);foreach(var a in anchors){a.b.entryRoad=road.Project(a.entry,out _);a.b.exitRoad=road.Project(a.exit,out _);EditorUtility.SetDirty(a.b);}
 // Recarve bank material to the restored grade; never touch the actual driving ribbon.
 var bank=GameObject.Find("Ground_MountainCut natural embankments").GetComponent<MeshFilter>();var fs=Read(bank);for(float s=820;s<970;s+=3){var vol=Box(road.At(s,out _),road.At(s+3,out _),8.5f,-.12f,7.1f);fs=fs.SelectMany(f=>Subtract(f,vol)).ToList();}Assign(bank,"MountainCut natural embankments",fs);
 // Close portal perimeter with continuous rock slopes tied into adjacent earth.
 var vault=GameObject.Find("Ground_MountainCut rock vault").GetComponent<MeshFilter>();fs=Read(vault);foreach(float z in new[]{112f,144f}){float floor=z>120?152:Y(z);var inner=new[]{new Vector3(977,floor-2,z),new Vector3(980,floor+5.2f,z),new Vector3(982,floor+7.8f,z),new Vector3(990,floor+8.4f,z),new Vector3(998,floor+7.8f,z),new Vector3(1000,floor+5.2f,z),new Vector3(1003,floor-2,z)};for(int i=0;i<inner.Length-1;i++){var a=inner[i];var b=inner[i+1];var aa=a;var bb=b;aa.x=990+(a.x-990)*1.8f;bb.x=990+(b.x-990)*1.8f;aa.y=i<2||i>3?floor+5:163.7f;bb.y=i<1||i>3?floor+5:163.7f;aa.z+=z==144?6:-5;bb.z=aa.z;Quad(fs,a,b,bb,aa,true,true);}}Assign(vault,"MountainCut rock vault",fs);
 Physics.SyncTransforms();EditorSceneManager.MarkSceneDirty(race.gameObject.scene);EditorSceneManager.SaveScene(race.gameObject.scene);AssetDatabase.SaveAssets();File.WriteAllText("Docs/MountainCut/final-grade.txt",$"Restored {changed} lower vertices against actual historical road samples. Exact X/Z maintained; branch stations reseated to unchanged world-space anchors.");return "Restored original lower layer without sampling upper road; branch anchors preserved";
 }
 public static string CorrectEdges(){
 var race=Object.FindAnyObjectByType<RaceDirector>();var road=race.road;var mf=GameObject.Find("Ground_CR133 mountain driving surface").GetComponent<MeshFilter>();var lower=road.points.Where(p=>Math.Abs(p.x-990)<.01f&&p.z>=60&&p.z<=120).OrderBy(p=>p.z).ToArray();float Y(float z){for(int i=1;i<lower.Length;i++)if(z<=lower[i].z)return Mathf.Lerp(lower[i-1].y,lower[i].y,Mathf.InverseLerp(lower[i-1].z,lower[i].z,z));return lower.Last().y;}
 var mesh=Object.Instantiate(mf.sharedMesh);var vs=mesh.vertices;int count=0;for(int i=0;i<vs.Length;i++){var p=vs[i];if((Math.Abs(p.x-976)<.001f||Math.Abs(p.x-1004)<.001f)&&p.z>=72&&p.z<=98&&p.y>150&&p.y<175){vs[i]=new(p.x,Y(p.z)+.04f,p.z);count++;}}mesh.vertices=vs;mesh.RecalculateNormals();mesh.RecalculateBounds();var old=AssetDatabase.LoadAssetAtPath<Mesh>(Folder+"/restored-driving.asset");EditorUtility.CopySerialized(mesh,old);Object.DestroyImmediate(mesh);mf.sharedMesh=old;mf.GetComponent<MeshCollider>().sharedMesh=null;mf.GetComponent<MeshCollider>().sharedMesh=old;EditorUtility.SetDirty(old);
 Physics.SyncTransforms();EditorSceneManager.MarkSceneDirty(race.gameObject.scene);EditorSceneManager.SaveScene(race.gameObject.scene);AssetDatabase.SaveAssets();File.AppendAllText("Docs/MountainCut/final-grade.txt",$"\nActual 28m-wide lower pavement edges restored: {count} vertices.");return "Restored both actual lower-pavement edges: "+count;
 }
 public static string Dependencies(){var race=Object.FindAnyObjectByType<RaceDirector>();var b=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title=="Summit Traverse");var mf=GameObject.Find("Ground_Mountain_1_2").GetComponent<MeshFilter>();var fs=Read(mf);for(float s=322;s<344;s+=2){var vol=Box(b.At(s,out _),b.At(s+2,out _),6.4f,-.1f,7);fs=fs.SelectMany(f=>Subtract(f,vol)).ToList();}Assign(mf,"upper-shoulder-seam",fs);
 // Remove thin old support curtains immediately around the new vault, retaining terrain beyond it.
 var cut=new[]{new Plane(Vector3.right,new Vector3(973,0,0)),new Plane(Vector3.left,new Vector3(1007,0,0)),new Plane(Vector3.forward,new Vector3(0,0,110)),new Plane(Vector3.back,new Vector3(0,0,149)),new Plane(Vector3.up,new Vector3(0,151.9f,0)),new Plane(Vector3.down,new Vector3(0,164.1f,0))};
 foreach(var m in Object.FindObjectsByType<MeshFilter>().Where(m=>m.sharedMesh&&(m.name.Contains("earth banks")||m.name.Contains("natural embankments")))){var tris=Read(m);var next=tris.SelectMany(f=>Subtract(f,cut)).ToList();Assign(m,"portal-"+m.name,next);}
 // Continuous earth cap above the rock opening seats under the actual upper surface.
 var cap=new List<Face>();var driving=GameObject.Find("Ground_CR133 mountain driving surface").GetComponent<Collider>();Vector3 Top(float x,float z){float y=163.35f-.075f*(x-990)+.02f*(z-125);var p=new Vector3(x,y,z);if(driving.Raycast(new Ray(p+Vector3.up*2,Vector3.down),out var h,4)&&h.point.y>158)p.y=Mathf.Min(p.y,h.point.y-.08f);return p;}
 for(float x=973;x<1007;x+=1)for(float z=110;z<149;z+=1)Quad(cap,Top(x,z),Top(x,z+1),Top(x+1,z+1),Top(x+1,z));
 var vault=GameObject.Find("Ground_MountainCut rock vault").GetComponent<MeshFilter>();var material=vault.GetComponent<Renderer>().sharedMaterial;Make("MountainCut mountain cap",cap,material);
 Physics.SyncTransforms();var trees=Object.FindObjectsByType<Collider>().Where(c=>c.name.IndexOf("trunk",StringComparison.OrdinalIgnoreCase)>=0&&Local(c.bounds.center)).Where(c=>{var p=c.bounds.center;var hits=Physics.RaycastAll(new(p.x,c.bounds.min.y+20,p.z),Vector3.down,80,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).ToArray();return hits.Length>0&&Math.Abs(c.bounds.min.y-hits.Max(h=>h.point.y))>.08f;}).ToArray();if(trees.Length>0)typeof(Racer.Editor.BackyardReverseAuthoring).GetMethod("Trees",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Static).Invoke(null,new object[]{(Func<Collider,bool>)(c=>false),(Func<Collider,bool>)(c=>trees.Contains(c))});
 EditorSceneManager.MarkSceneDirty(race.gameObject.scene);EditorSceneManager.SaveScene(race.gameObject.scene);AssetDatabase.SaveAssets();File.WriteAllText("Docs/MountainCut/dependency-final.txt","Upper shoulder clipped to driving level; portal curtains replaced by continuous cap; complete trees reseated="+trees.Length);return "Local seams and dependencies refitted; trees="+trees.Length;
 }
 public static string RockBanks(){var race=Object.FindAnyObjectByType<RaceDirector>();var road=race.road;var b=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title=="Summit Traverse");var fs=new List<Face>();foreach(float x in new[]{969f,1011f}){Vector3 P(int ring,int i){float a=i*Mathf.PI*2/16;float radius=new[]{.8f,1f,.96f,.75f,.30f}[ring];float y=new[]{137f,145f,153f,160f,163f}[ring];return new Vector3(x+Mathf.Cos(a)*15*radius,y+(ring==0?0:.25f*Mathf.Sin(a*3)),129+Mathf.Sin(a)*28*radius);}for(int r=0;r<4;r++)for(int i=0;i<16;i++)Quad(fs,P(r,i),P(r,i+1),P(r+1,i+1),P(r+1,i),true,true);for(int i=0;i<16;i++)fs.Add(new Face(R(P(4,i)),R(P(4,i+1)),R(new Vector3(x,163.1f,129))));}
 var volumes=new List<Plane[]>();for(float s=810;s<970;s+=3)volumes.Add(Box(road.At(s,out _),road.At(s+3,out _),9,-.15f,7.3f));for(float s=380;s<525;s+=3)volumes.Add(Box(road.At(s,out _),road.At(s+3,out _),8,-.15f,7));for(float s=0;s<75;s+=3)volumes.Add(Box(b.At(s,out _),b.At(s+3,out _),7,-.15f,7));foreach(var vol in volumes)fs=fs.SelectMany(f=>Subtract(f,vol)).ToList();var mat=GameObject.Find("Ground_MountainCut rock vault").GetComponent<Renderer>().sharedMaterial;Make("MountainCut portal outcrops",fs,mat);Physics.SyncTransforms();EditorSceneManager.MarkSceneDirty(race.gameObject.scene);EditorSceneManager.SaveScene(race.gameObject.scene);AssetDatabase.SaveAssets();return "Natural portal outcrops support upper shoulders around the 18m lower opening";}
 public static string ClearBuriedContacts(){var race=Object.FindAnyObjectByType<RaceDirector>();var road=race.road;var vols=new List<Plane[]>();for(float s=815;s<980;s+=3)vols.Add(Box(road.At(s,out _),road.At(s+3,out _),9,-4,7.3f));int count=0;foreach(var mf in Object.FindObjectsByType<MeshFilter>().Where(m=>m.sharedMesh&&m.name.StartsWith("Ground_MountainCut"))){var fs=Read(mf);foreach(var vol in vols)fs=fs.SelectMany(f=>Subtract(f,vol)).ToList();Assign(mf,"clear-"+mf.name,fs);count++;}Physics.SyncTransforms();EditorSceneManager.MarkSceneDirty(race.gameObject.scene);EditorSceneManager.SaveScene(race.gameObject.scene);AssetDatabase.SaveAssets();File.WriteAllText("Docs/MountainCut/buried-contact-fix.txt","Removed secondary support faces through 4m below the lower pavement, preserving the driving surface. These faces were missed by above-floor probes and contacted the vehicle suspension/body. Meshes="+count);return "Cleared buried secondary support collision in "+count+" meshes";}
 public static string TrimUpperOnly(){var b=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title=="Summit Traverse");var mf=GameObject.Find("Ground_Mountain_1_2").GetComponent<MeshFilter>();var fs=Read(mf);for(float s=322;s<344;s+=2){var vol=Box(b.At(s,out _),b.At(s+2,out _),6.4f,-.1f,7);fs=fs.SelectMany(f=>Subtract(f,vol)).ToList();}Assign(mf,"upper-shoulder-seam",fs);EditorSceneManager.MarkSceneDirty(b.gameObject.scene);EditorSceneManager.SaveScene(b.gameObject.scene);AssetDatabase.SaveAssets();return "Only the upper road shoulder intersection is trimmed; native hillside retained";}
}
