using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class AuthorSeven {
 const string F="Assets/Track/SevenCorrections",D="Docs/SevenCorrections";static Transform root;static int serial;static List<string> notes=new();
 static float S(float a,float b,float x)=>Mathf.SmoothStep(0,1,Mathf.InverseLerp(a,b,x));
 static Material Mat(string n,Color c,bool natural=false){var m=new Material(Shader.Find("Racer/UndergroundSurface")){name=n,color=c};m.SetFloat("_Natural",natural?1:0);AssetDatabase.CreateAsset(m,F+"/"+n+".mat");return m;}
 static Mesh SaveMesh(Mesh m,string n){m.RecalculateNormals();m.RecalculateBounds();AssetDatabase.CreateAsset(m,AssetDatabase.GenerateUniqueAssetPath(F+"/"+n+".asset"));return m;}
 static void Replace(MeshFilter mf,Mesh m){mf.sharedMesh=SaveMesh(m,mf.name+"-"+(serial++));if(mf.TryGetComponent<MeshCollider>(out var c)){c.sharedMesh=null;c.sharedMesh=m;}}
 static GameObject Part(string n,Vector3 p,Vector3 size,Quaternion q,Material mat,PrimitiveType type=PrimitiveType.Cube){var g=GameObject.CreatePrimitive(type);g.name=n;g.transform.SetParent(root);g.transform.SetPositionAndRotation(p,q);g.transform.localScale=size;g.GetComponent<Renderer>().sharedMaterial=mat;Object.DestroyImmediate(g.GetComponent<Collider>());return g;}
 static GameObject MeshPart(string n,List<Vector3> vs,List<int> ts,List<Color> cs,Material mat,bool collision){var m=new Mesh{indexFormat=UnityEngine.Rendering.IndexFormat.UInt32};m.SetVertices(vs);m.SetTriangles(ts,0);m.SetColors(cs);m.uv=vs.Select(p=>new Vector2(p.x,p.z)*.2f).ToArray();var g=new GameObject(n,typeof(MeshFilter),typeof(MeshRenderer));g.transform.SetParent(root);g.GetComponent<MeshFilter>().sharedMesh=SaveMesh(m,n);g.GetComponent<Renderer>().sharedMaterial=mat;if(collision)g.AddComponent<MeshCollider>().sharedMesh=m;return g;}
 static void DirtySave(){var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene();EditorSceneManager.MarkSceneDirty(scene);EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();}
 static WoodlandRoute Clone(WoodlandRoute b){var g=new GameObject("Temporary original route"){hideFlags=HideFlags.HideAndDontSave};var copy=g.AddComponent<WoodlandRoute>();copy.points=b.points.ToArray();return copy;}
 static float Hermite(float y0,float y1,float d0,float d1,float length,float u){return (2*u*u*u-3*u*u+1)*y0+(u*u*u-2*u*u+u)*length*d0+(-2*u*u*u+3*u*u)*y1+(u*u*u-u*u)*length*d1;}
 public static string Main(){if(Application.isPlaying||UnityEngine.SceneManagement.SceneManager.GetActiveScene().isDirty)throw new Exception("Saved edit mode required");Directory.CreateDirectory(F);AssetDatabase.Refresh();EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");Physics.SyncTransforms();root=GameObject.Find("Reverse optional forest shortcuts").transform;
 var ridge=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title.StartsWith("Abandoned"));var old=Clone(ridge);float start=82,end=116,y0=old.At(start,out _).y,y1=old.At(end,out _).y;float H(float s)=>s<=start||s>=end?old.At(s,out _).y:Hermite(y0,y1,.035f,-.013f,end-start,(s-start)/(end-start));
 // The crest is visual only; the connected hillside owns wheel collision.
 var crest=GameObject.Find("Ground_Worn logging crest");if(crest.GetComponent<Collider>())Object.DestroyImmediate(crest.GetComponent<Collider>());
 foreach(var mf in root.GetComponentsInChildren<MeshFilter>().Where(m=>m.name=="Ground_Natural rolling ridge"||m.name=="Ground_Worn logging crest"||m.name=="Broken logging wheel paths"||m.name=="Grass intrusion")){var src=mf.sharedMesh;var v=src.vertices;bool changed=false;for(int i=0;i<v.Length;i++){var p=mf.transform.TransformPoint(v[i]);float s=old.Project(p,out var side);if(s<start||s>end)continue;float weight=1-S(3.2f,11,side);float target=H(s);if(mf.name=="Broken logging wheel paths"||mf.name=="Grass intrusion")target+=.035f;if(mf.name=="Ground_Worn logging crest")target+=.008f;p.y=Mathf.Lerp(p.y,target,weight);v[i]=mf.transform.InverseTransformPoint(p);changed=true;}if(changed){var m=Object.Instantiate(src);m.vertices=v;Replace(mf,m);}}
 var rp=ridge.points.ToArray();for(int i=0;i<rp.Length;i++){float s=old.Project(rp[i],out _);rp[i].y=H(s);}ridge.points=rp;EditorUtility.SetDirty(ridge);
 foreach(var t in root.Cast<Transform>().Where(t=>t.name=="Optional gold guidance"&&t.position.x>270)){float s=old.Project(t.position,out _);if(s>start&&s<end){var p=t.position;p.y=H(s)+.06f;t.position=p;}}
 Physics.SyncTransforms();float Ground(Vector3 p)=>Physics.RaycastAll(new(p.x,250,p.z),Vector3.down,500,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).Max(h=>h.point.y);
 foreach(var c in root.GetComponentsInChildren<BoxCollider>().Where(c=>c.name=="Abandoned fallen timber"||c.name=="Weathered stump")){float s=old.Project(c.bounds.center,out _);if(s>start-3&&s<end+3)c.transform.position+=Vector3.up*(Ground(c.bounds.center)-c.bounds.min.y);}
 typeof(Racer.Editor.BackyardReverseAuthoring).GetMethod("Trees",BindingFlags.NonPublic|BindingFlags.Static).Invoke(null,new object[]{(Func<Collider,bool>)(c=>false),(Func<Collider,bool>)(c=>{float s=old.Project(c.bounds.center,out float d);return s>start&&s<end&&d<12;})});
 foreach(var t in root.Cast<Transform>().Where(t=>t.name=="Rough low ridge scrub")){float s=old.Project(t.position,out float d);if(s>start&&s<end&&d<12){var p=t.position;p.y=Ground(p);t.position=p;}}
 foreach(var brush in root.GetComponentsInChildren<ShortcutUndergrowth>())brush.centres=brush.centres.Select(p=>{float s=old.Project(p,out float d);return s>start&&s<end&&d<12?new Vector3(p.x,Ground(p),p.z):p;}).ToArray();Object.DestroyImmediate(old.gameObject);notes.Add("Ridge: one collision skin; final stations 82-116 use continuous Hermite descent, broad level crown, original elevated entry/middle retained; trees/timber/scrub/guidance reseated.");
 Drain();DirtySave();EditorSceneManager.OpenScene("Assets/Scenes/LakeWoods.unity");Cave();DirtySave();File.WriteAllLines(D+"/authoring.txt",notes);EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");return string.Join("\n",notes);
 }
 static void Drain(){var b=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title.StartsWith("Storm"));var old=Clone(b);float end=100,y0=old.At(0,out _).y,y1=old.At(end,out var ef).y;float grade=ef.y/Vector3.ProjectOnPlane(ef,Vector3.up).magnitude;float H(float s)=>s>=end?old.At(s,out _).y:Hermite(y0,y1,-.18f,grade,end,s/end);var bp=b.points.ToArray();for(int i=0;i<bp.Length;i++){float s=old.Project(bp[i],out _);bp[i].y=H(s);}b.points=bp;b.halfWidth=2.65f;EditorUtility.SetDirty(b);
 // Reshape every associated detail to the same floor; pull edge objects inside the smaller chamber.
 var detail=GameObject.Find("Storm Drain atmosphere");foreach(var t in root.Cast<Transform>().Concat(detail.transform.Cast<Transform>()).ToArray()){if(t.GetComponent<WoodlandRoute>()||t.name=="Ground_Culvert seamless floor"||t.name=="Long storm culvert walls and ceiling"||t.name=="Drain entrance rat encounter"||t.name.Contains("Logging"))continue;float s=old.Project(t.position,out float d);if(s<b.undergroundStart||s>b.undergroundEnd||d>7)continue;var center=old.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;float lateral=Vector3.Dot(t.position-center,side);t.position+=Vector3.up*(H(s)-center.y)-side*lateral*.27f;if(t.name=="Culvert overhead expansion joint"){t.localScale=new(6.6f,.1f,.14f);var p=t.position;p.y=H(s)+5.2f;t.position=p;}if(t.name=="Culvert vertical seam"){var p=t.position;p.y=H(s)+2.6f;t.position=p;t.localScale=new(.1f,5.2f,.14f);}if(t.GetComponent<Light>()){t.position=b.At(s,out _)+Vector3.up*4.8f;t.GetComponent<Light>().intensity=((int)s%3==0)?.18f:0;t.GetComponent<Light>().range=7;}}
 // Remove prior water skins and rebuild their visible flow on the new continuous floor.
 foreach(var t in root.Cast<Transform>().Where(t=>t.name=="Shallow storm water").ToArray())Object.DestroyImmediate(t.gameObject);
 Object.DestroyImmediate(GameObject.Find("Ground_Culvert seamless floor"));Object.DestroyImmediate(GameObject.Find("Long storm culvert walls and ceiling"));
 var concrete=Mat("Confined stained culvert",new(.29f,.33f,.30f));var water=Mat("Visible storm flow",new(.12f,.23f,.23f));var sediment=Mat("Culvert sediment",new(.22f,.17f,.085f));var pale=Mat("Washed litter contrast",new(.36f,.33f,.23f));
 float Value(float s)=>Mathf.Lerp(.27f,1,Mathf.Max(1-S(b.undergroundStart,b.undergroundStart+17,s),S(b.undergroundEnd-20,b.undergroundEnd,s)));
 var v=new List<Vector3>();var tr=new List<int>();var colors=new List<Color>();int rows=Mathf.CeilToInt((b.undergroundEnd+.1f)/.5f);for(int i=0;i<=rows;i++){float s=(b.undergroundEnd+.1f)*i/rows;var p=b.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;for(int j=0;j<9;j++){float w=-4.5f+j*1.125f;v.Add(p+side*w);float val=Value(s);colors.Add(new(val,val,val,1));}if(i>0)for(int j=0;j<8;j++){int a=(i-1)*9+j;tr.AddRange(new[]{a,a+9,a+1,a+1,a+9,a+10});}}MeshPart("Ground_Culvert seamless floor",v,tr,colors,concrete,true);
 v=new();tr=new();colors=new();rows=Mathf.CeilToInt(b.undergroundEnd-b.undergroundStart);for(int i=0;i<=rows;i++){float s=Mathf.Lerp(b.undergroundStart,b.undergroundEnd,i/(float)rows);var p=b.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;float h=5.35f+.75f*(1-S(b.undergroundStart,b.undergroundStart+20,s)),w=3.35f+.12f*Mathf.Sin(s*.07f);foreach(var q in new[]{p-side*w,p-side*w+Vector3.up*(h-.6f),p-side*(w-.7f)+Vector3.up*h,p+side*(w-.7f)+Vector3.up*h,p+side*w+Vector3.up*(h-.6f),p+side*w}){v.Add(q);float val=Value(s);colors.Add(new(val,val,val,1));}if(i>0)for(int j=0;j<5;j++){int a=(i-1)*6+j;tr.AddRange(new[]{a,a+1,a+6,a+1,a+7,a+6});}}MeshPart("Long storm culvert walls and ceiling",v,tr,colors,concrete,true);
 // Portal blocks follow the new opening; no crossbar or pier inside the vehicle corridor.
 foreach(var t in root.Cast<Transform>().Where(t=>t.name=="Supported culvert mouth pier"||t.name=="Culvert mouth lintel")){float s=old.Project(t.position,out _);s=s<(b.undergroundStart+b.undergroundEnd)/2?b.undergroundStart:b.undergroundEnd;var p=b.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;if(t.name.Contains("pier")){int sign=Vector3.Dot(t.position-p,side)>0?1:-1;t.position=p+side*3.8f*sign+Vector3.up*2.8f;t.localScale=new(.7f,6.2f,1);}else{t.position=p+Vector3.up*(s==b.undergroundStart?6.35f:5.65f);t.localScale=new(8.3f,.6f,1);}t.rotation=Quaternion.LookRotation(Vector3.ProjectOnPlane(f,Vector3.up));}
 // Remove the obsolete exposed Forward cabin approach overlay only in this Reverse scene.
 var obsolete=GameObject.Find("Cabin wooded approach");if(obsolete){Object.DestroyImmediate(obsolete);notes.Add("Removed obsolete Cabin wooded approach render strip in Reverse near supplied drain coordinate, including any associated collider; Forward scene untouched.");}
 // Match the outside terrain to the first 12m of the floor. Only the existing entrance apron is altered.
 typeof(Racer.Editor.BackyardReverseAuthoring).GetMethod("Sculpt",BindingFlags.NonPublic|BindingFlags.Static).Invoke(null,new object[]{(Func<Vector3,bool>)(p=>{if(p.x<164||p.x>185||p.z<70||p.z>87)return false;float s=old.Project(p,out float d);return s<14&&d<5&&Math.Abs(p.y-old.At(s,out _).y)<4;}),(Func<Vector3,Vector3>)(p=>{float s=old.Project(p,out float d);p.y=Mathf.Lerp(p.y,H(s)-.025f,1-S(3.5f,5,d));return p;}),"Drain continuous entrance apron"});
 for(float s=b.undergroundStart+3;s<b.undergroundEnd-3;s+=1.3f){var p=b.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;var q=Quaternion.LookRotation(f);float width=1.25f+.4f*Mathf.Sin(s*.17f);Part("Continuous shallow storm water",p+Vector3.up*.025f,new(width*2,.015f,1.55f),q,water);if((int)(s*10)%4==0){foreach(int edge in new[]{-1,1}){Part("Visible washed debris accumulation",p+side*2.85f*edge+Vector3.up*.12f,new(.55f,.22f,1.3f),q*Quaternion.Euler(0,s*6,0),sediment);Part("Visible washed paper and leaves",p+side*2.55f*edge+Vector3.up*.04f,new(.45f,.035f,.6f),q*Quaternion.Euler(0,s*12,0),pale);}}}
 // Five rats are staged 24-32m inside, visible ahead while accelerating into the bore.
 var life=Object.FindObjectsByType<UndergroundLife>().First(x=>!x.cave);var template=life.rats[0];var rats=life.rats.ToList();rats.Add(Object.Instantiate(template,template.parent));life.rats=rats.ToArray();life.refuges=new Vector3[5];life.entrance=b.At(b.undergroundStart+16,out var entryF);life.forward=Vector3.ProjectOnPlane(entryF,Vector3.up).normalized;
 for(int i=0;i<5;i++){float s=b.undergroundStart+25+i*2.1f;var p=b.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;int edge=i%2==0?1:-1;var rat=life.rats[i];rat.name="Scurrying drain rat "+(i+1);rat.position=p+side*(.4f+i*.24f)*edge+Vector3.up*.20f;rat.rotation=Quaternion.LookRotation(f);rat.localScale=Vector3.one*1.75f;life.refuges[i]=b.At(s+22,out var ff)+Vector3.Cross(Vector3.up,ff).normalized*3.1f*edge+Vector3.up*.2f;}
 var fur=Mat("Readable brown grey rats",new(.36f,.30f,.23f));foreach(var r in life.GetComponentsInChildren<Renderer>())if(r.name=="Rat body"||r.name=="Rat pointed muzzle")r.sharedMaterial=fur;EditorUtility.SetDirty(life);Object.DestroyImmediate(old.gameObject);notes.Add("Drain: first 100m regraded continuously instead of abrupt 38-degree entrance plunge; 6.7m chamber and chamfered 5.35m ceiling, rapid portal falloff, broad centre flow and visible edge accumulations. Five larger rats staged ahead.");
 }
 static void Cave(){var b=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title=="Echo Cave");var oldShell=GameObject.Find("Echo Cave enclosed rock");root=oldShell.transform.parent;Object.DestroyImmediate(oldShell);foreach(var t in root.Cast<Transform>().Where(t=>t.name=="Cave rock buttress"||t.name=="Cave warm wayfinding").ToArray())Object.DestroyImmediate(t.gameObject);
 var rock=Mat("Natural fractured cave rock",new(.43f,.42f,.36f),true);var gravel=Mat("Cave gravel and stone",new(.26f,.255f,.22f),true);var damp=Mat("Cave damp stone",new(.12f,.17f,.16f),true);var roots=Mat("Cave exposed roots",new(.19f,.13f,.075f),true);
 // Connected faceted rings; clearance expands over the pre-existing cave flight.
 var vs=new List<Vector3>();var ts=new List<int>();var cs=new List<Color>();const int seg=12;float begin=60,end=479;int rows=Mathf.CeilToInt((end-begin)/3);for(int i=0;i<=rows;i++){float s=Mathf.Lerp(begin,end,i/(float)rows);var p=b.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;float w=5.4f+.55f*Mathf.Sin(s*.061f)+.25f*Mathf.Sin(s*.17f);float h=7.6f+.85f*Mathf.Sin(s*.073f)+.45f*Mathf.Cos(s*.17f);if(s>290&&s<385)h=Mathf.Max(h,14*S(290,310,s)*(1-S(365,385,s)));for(int j=0;j<=seg;j++){float a=j*Mathf.PI/seg;float rough=.25f*Mathf.Sin(s*.61f+j*1.9f);var pos=p+side*(Mathf.Cos(a)*(w+rough))+Vector3.up*(-.25f+Mathf.Sin(a)*(h+rough));vs.Add(pos);float portal=Mathf.Max(1-S(begin,begin+25,s),S(end-30,end,s));float val=Mathf.Lerp(.50f,1,portal)*(.86f+.14f*Mathf.Sin(s*.35f+j*2.3f));cs.Add(new(val,val*.98f,val*.94f,1));}if(i>0)for(int j=0;j<seg;j++){int a=(i-1)*(seg+1)+j;ts.AddRange(new[]{a,a+seg+1,a+1,a+1,a+seg+1,a+seg+2});}}
 // Duplicate render vertices by face to retain angular rock normals; collision remains connected in position.
 var flatV=new List<Vector3>();var flatT=new List<int>();var flatC=new List<Color>();foreach(int idx in ts){flatT.Add(flatV.Count);flatV.Add(vs[idx]);flatC.Add(cs[idx]);}MeshPart("Echo Cave enclosed rock",flatV,flatT,flatC,rock,true);
 Physics.SyncTransforms();float Floor(Vector3 p)=>Physics.RaycastAll(p+Vector3.up*2,Vector3.down,12,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).Select(h=>h.point.y).DefaultIfEmpty(p.y).Max();
 var rng=new System.Random(57000);for(float s=begin+4;s<end-4;s+=5){var p=b.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;var q=Quaternion.LookRotation(f);foreach(int edge in new[]{-1,1}){var foot=p+side*(4.35f+.3f*Mathf.Sin(s))*edge;foot.y=Floor(foot);Part("Angular cave wall ledge",foot+Vector3.up*2.2f,new(1.3f,1.3f,3.8f),q*Quaternion.Euler(8,s*3,edge*22),rock);Part("Fallen cave stone",foot+Vector3.up*.16f,new(.8f,.3f,1.1f),q*Quaternion.Euler(9,s*11,8),gravel);if((int)s%3==0){var crown=p+side*3.4f*edge+Vector3.up*6.1f;Part("Hanging angular cave formation",crown,new(.7f,1.15f,1.0f),q*Quaternion.Euler(18,s*3,25),rock);Part("Exposed ceiling root",crown+Vector3.up*.9f,new(.09f,.1f,2.3f),q*Quaternion.Euler(11,s,20),roots);}}
 if(s>288&&s<384)continue;for(int j=0;j<3;j++){var patch=p+side*((float)rng.NextDouble()*5-2.5f)+f*j*.5f;patch.y=Floor(patch)+.017f;Part(j==0?"Shallow cave puddle":"Cave gravel floor patch",patch,new(1.3f+(float)rng.NextDouble(),.015f,2.6f),q*Quaternion.Euler(0,s*7,0),j==0?damp:gravel,PrimitiveType.Cylinder);}
 }
 foreach(float s in new[]{110f,225f,420f}){var drip=new GameObject("Quiet natural cave water").AddComponent<UndergroundLife>();drip.transform.SetParent(root);drip.cave=true;drip.rats=Array.Empty<Transform>();drip.refuges=Array.Empty<Vector3>();drip.entrance=b.At(s,out _)+Vector3.up*2;}
 notes.Add("Forest Forward Echo Cave: replaced 13m smooth vault and repeated oval buttresses with connected irregular faceted 7-9m rock ceiling/walls, flight clearance retained; angular ledges, roots, gravel/damp floor, natural water audio. No Reverse route/gates/arrows/AI changed.");
 }
}
