using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class AuthorCaveHillside{
 const string D="Docs/CaveHillside",F="Assets/Track/CaveHillside";
 [Serializable]public class Line{public Vector3[] points;}
 public static string Main(){if(Application.isPlaying||UnityEngine.SceneManagement.SceneManager.GetActiveScene().isDirty)throw new Exception("Saved edit mode required");Directory.CreateDirectory(F);AssetDatabase.Refresh();var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene();if(scene.name!="LakeWoods")throw new Exception("Forest Forward required");if(GameObject.Find("Ground_Echo wooded hillside"))throw new Exception("Already authored");
 var tmp=new GameObject("Temporary original cave line");var b=tmp.AddComponent<WoodlandRoute>();b.points=JsonUtility.FromJson<Line>(File.ReadAllText("Docs/FinalTwo/original-cave-line.json")).points;var notes=new List<string>();Physics.SyncTransforms();
 float Ground(Vector3 p)=>Physics.RaycastAll(new(p.x,200,p.z),Vector3.down,300,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).Select(h=>h.point.y).DefaultIfEmpty(p.y).Max();
 var deps=Object.FindObjectsByType<Collider>().Where(c=>!c.isTrigger&&(c.name.ToLower().Contains("tree")||c.name.ToLower().Contains("trunk"))).Select(c=>(c,p:c.bounds.center,foot:c.bounds.min.y)).ToArray();
 var shell=GameObject.Find("Echo Cave enclosed rock").GetComponent<MeshFilter>();var rock=shell.GetComponent<Renderer>().sharedMaterial;var verts=shell.sharedMesh.vertices.Select(shell.transform.TransformPoint).ToArray();
 var vs=new List<Vector3>();var ts=new List<int>();var colors=new List<Color>();int rows=140,cols=32;
 // A wide, asymmetric slope bridges the existing excavated trench. Its crest belongs to
 // the adjacent hillside, with broad swells independent of the tunnel's roof profile.
 for(int i=0;i<=rows;i++){float s=Mathf.Lerp(60,479,i/(float)rows);var p=b.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;float left=34+5*Mathf.Sin(s*.018f),right=36+7*Mathf.Sin(s*.024f+1);float gl=Ground(p-side*left),gr=Ground(p+side*right);float roof=verts.Where(v=>Math.Abs(b.Project(v,out _)-s)<4).Select(v=>v.y).DefaultIfEmpty(p.y+9).Max();
 for(int j=0;j<=cols;j++){float u=j/(float)cols,x=Mathf.Lerp(-left,right,u);var q=p+side*x;float baseY=Ground(q);float crown=Mathf.Max(Mathf.Lerp(gl,gr,u)+3.5f*Mathf.Sin(u*Mathf.PI),roof+1.7f);float blend=1-Mathf.SmoothStep(0,1,Mathf.InverseLerp(9,x<0?left:right,Math.Abs(x)));q.y=Mathf.Max(baseY,Mathf.Lerp(baseY,crown,blend))-.025f;vs.Add(q);float c=.9f+.06f*Mathf.Sin(q.x*.11f)*Mathf.Cos(q.z*.09f);colors.Add(new(.38f*c,.46f*c,.30f*c));if(i>0&&j>0){int a=(i-1)*(cols+1)+j-1;ts.AddRange(new[]{a,a+1,a+cols+1,a+1,a+cols+2,a+cols+1});}}
 }
 Material earth=Object.FindObjectsByType<MeshRenderer>().First(r=>r.name.StartsWith("Ground_")).sharedMaterial;
 GameObject MeshPart(string name,List<Vector3> v,List<int> t,List<Color> c,Material mat){var m=new Mesh{indexFormat=UnityEngine.Rendering.IndexFormat.UInt32};m.SetVertices(v);m.SetTriangles(t,0);m.SetColors(c);m.uv=v.Select(p=>new Vector2(p.x,p.z)*.08f).ToArray();m.RecalculateNormals();m.RecalculateBounds();AssetDatabase.CreateAsset(m,F+"/"+name+".asset");var g=new GameObject(name,typeof(MeshFilter),typeof(MeshRenderer),typeof(MeshCollider));g.GetComponent<MeshFilter>().sharedMesh=m;g.GetComponent<MeshRenderer>().sharedMaterial=mat;g.GetComponent<MeshCollider>().sharedMesh=m;return g;}
 var cover=MeshPart("Ground_Echo wooded hillside",vs,ts,colors,earth);
 // Portal faces bridge the broad earth surface to the preserved irregular opening.
 foreach(int row in new[]{0,rows}){float s=row==0?60:479;var p=b.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;var pv=new List<Vector3>();var pt=new List<int>();for(int j=0;j<=cols;j++){var top=vs[row*(cols+1)+j];float x=Vector3.Dot(top-p,side);float w=5.4f+.55f*Mathf.Sin(s*.061f)+.25f*Mathf.Sin(s*.17f);float h=7.6f+.85f*Mathf.Sin(s*.073f)+.45f*Mathf.Cos(s*.17f);float low=Math.Abs(x)<w+.25f?p.y-.25f+Mathf.Sqrt(Mathf.Max(0,1-x*x/((w+.25f)*(w+.25f))))*(h+.25f):Ground(top)-.05f;pv.Add(new(top.x,Mathf.Min(top.y,low),top.z));pv.Add(top);if(j>0){int a=(j-1)*2;pt.AddRange(row==0?new[]{a,a+2,a+1,a+1,a+2,a+3}:new[]{a,a+1,a+2,a+1,a+3,a+2});}}MeshPart("Echo eroded hillside face "+row,pv,pt,pv.Select(v=>new Color(.8f,.79f,.73f)).ToList(),rock);}
 Physics.SyncTransforms();var affected=deps.Where(d=>Ground(d.p)>d.foot+.1f).ToArray();File.WriteAllLines(D+"/affected-trees-before.txt",affected.Select(d=>$"{d.c.name} {d.p:F3} oldFoot={d.foot:F3} finalGround={Ground(d.p):F3}"));
 typeof(Racer.Editor.BackyardReverseAuthoring).GetMethod("Trees",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,new object[]{(Func<Collider,bool>)(c=>false),(Func<Collider,bool>)(c=>affected.Any(d=>d.c==c))});notes.Add("Reseated complete tree render components and colliders: "+affected.Length);
 // Ground nearby individual understory; do not move signs/routes or subterranean details.
 int shrubs=0;foreach(var t in Object.FindObjectsByType<Transform>().Where(t=>t.name.IndexOf("bush",StringComparison.OrdinalIgnoreCase)>=0||t.name.IndexOf("scrub",StringComparison.OrdinalIgnoreCase)>=0).ToArray()){float s=b.Project(t.position,out float d);if(s<60||s>479||d>45)continue;float y=Ground(t.position);if(y>t.position.y+.1f){t.position=new(t.position.x,y,t.position.z);shrubs++;}}notes.Add("Understory reseated="+shrubs);
 var fall=GameObject.Find("Echo Cave partial rockfall");foreach(var t in fall.transform.Cast<Transform>()){float scale=t.name.StartsWith("Wall")?.65f:t.name.StartsWith("Central")?.49f:t.name.StartsWith("Opening")?.52f:.52f;t.localScale=new(1,scale,1);notes.Add(t.name+" height scale="+scale+" visible mesh collider retained");}
 // Existing decorative slabs near the approach were unsupported at eye height.
 int ledges=0;foreach(var t in Object.FindObjectsByType<Transform>().Where(t=>t.name=="Angular cave wall ledge").ToArray()){float s=b.Project(t.position,out _);if(s<155||s>245)continue;var p=b.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;float sign=Mathf.Sign(Vector3.Dot(t.position-p,side));t.rotation=Quaternion.LookRotation(Vector3.ProjectOnPlane(f,Vector3.up))*Quaternion.Euler(0,0,sign*8);t.localScale=new(.9f,.85f,1.6f);t.position=p+side*4.65f*sign;var r=t.GetComponent<Renderer>();t.position+=Vector3.up*(p.y-.08f-r.bounds.min.y);ledges++;}notes.Add("Lower supported side stones replacing eye-line decorative slabs="+ledges);
 Object.DestroyImmediate(tmp);Physics.SyncTransforms();PlayerSettings.bundleVersion="0.59.0-review1";EditorSceneManager.MarkSceneDirty(scene);EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();File.WriteAllLines(D+"/authoring.txt",notes);return string.Join("\n",notes);
 }
}
