EditorApplication.delayCall += () => {try {
void Shot(string name,Vector3 position,Vector3 target){var go=new GameObject("Temporary atlas review camera",typeof(Camera));var camera=go.GetComponent<Camera>();camera.transform.SetPositionAndRotation(position,Quaternion.LookRotation(target-position));camera.fieldOfView=65;camera.farClipPlane=1700;var rt=new RenderTexture(1440,900,24);var tex=new Texture2D(1440,900,TextureFormat.RGB24,false);var old=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;tex.ReadPixels(new Rect(0,0,1440,900),0,0);tex.Apply();System.IO.File.WriteAllBytes("Docs/RouteAtlas/"+name+".png",tex.EncodeToPNG());}finally{RenderTexture.active=old;UnityEngine.Object.DestroyImmediate(tex);UnityEngine.Object.DestroyImmediate(rt);UnityEngine.Object.DestroyImmediate(go);}}
var report=new List<string>();
foreach(var sceneName in new[]{"StreetLoopGreybox","LakeWoods","StreetLoopReverse","ForestLoopReverse","MountainLoop","MountainLoopReverse"}){
UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/"+sceneName+".unity");var race=UnityEngine.Object.FindAnyObjectByType<Racer.RaceDirector>();var root=GameObject.Find("Route atlas direction guidance");if(root.GetComponentsInChildren<Collider>(true).Length>0)throw new Exception("Arrow colliders");int checkedCount=0;float worst=0;
foreach(var mf in root.GetComponentsInChildren<MeshFilter>()){var v=mf.sharedMesh.vertices;var tail=(v[0]+v[1])*.5f;var direction=Vector3.ProjectOnPlane(v[4]-tail,Vector3.up).normalized;float s=race.road.Project(tail,out _);race.road.At(s,out var expected);if(mf.name.StartsWith("Optional gold")){var b=UnityEngine.Object.FindObjectsByType<Racer.WoodlandRoute>().Single(b=>mf.name.EndsWith(b.title));s=b.Project(tail,out _);b.At(s,out expected);}float a=Vector3.Angle(direction,Vector3.ProjectOnPlane(expected,Vector3.up));worst=Math.Max(worst,a);checkedCount++;if(a>70)throw new Exception(sceneName+" arrow direction "+a+" / "+mf.name);}
report.Add($"{sceneName}: {checkedCount} new arrow meshes; 0 arrow colliders; maximum local heading deviation {worst:F1} degrees (surface-conforming meshes). Laurel corridor additions excluded.");
if(sceneName=="ForestLoopReverse"){Shot("House3-property-view",new Vector3(390,111,-200),new Vector3(477,57,-147));var p=race.road.At(111,out var f);Shot("ForestReverse-main-driver-view",p+Vector3.up*3,race.road.At(160,out _));}
if(sceneName=="StreetLoopGreybox"){var p=race.road.At(2160,out var f);Shot("Street-main-fork-view",p+Vector3.up*3,race.road.At(2240,out _));}
if(sceneName=="MountainLoopReverse"){var p=race.road.At(350,out var f);Shot("MountainReverse-guidance-view",p+Vector3.up*3,race.road.At(400,out _));}
}
System.IO.File.WriteAllLines("Docs/RouteAtlas/navigation-inspection.txt",report);
}catch(Exception e){System.IO.File.WriteAllText("Docs/RouteAtlas/capture-error.txt",e.ToString());}};return "Scheduled six direction inspections and four representative views";
