using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class CaptureCleanupWorldMaps {
 const string Output="Docs/WorldMap",Assets="Assets/Resources/WorldMaps";
 static object P(Vector3 p)=>new{x=p.x,y=p.y,z=p.z};
 public static string Main(){if(Application.isPlaying||UnityEngine.SceneManagement.SceneManager.GetActiveScene().isDirty)throw new Exception("Saved edit mode required");Directory.CreateDirectory(Output);Directory.CreateDirectory(Assets);EditorApplication.delayCall+=Run;return "Scheduled saved-geometry world captures; watch Docs/WorldMap/capture-progress.txt";}
 static void Run(){var original=UnityEngine.SceneManagement.SceneManager.GetActiveScene().path;try{foreach(var scene in RacePlaylists.Scenes.Reverse()){
 File.AppendAllText(Output+"/capture-progress.txt",scene+" starting\n");EditorSceneManager.OpenScene("Assets/Scenes/"+scene+".unity");
 var ground=Object.FindObjectsByType<MeshRenderer>().Where(r=>r.enabled&&r.name.StartsWith("Ground_")).ToArray();var b=ground[0].bounds;foreach(var r in ground)b.Encapsulate(r.bounds);
 float x=Mathf.Floor(b.min.x/100)*100-50,z=Mathf.Floor(b.min.z/100)*100-50;var bounds=Rect.MinMaxRect(x,z,Mathf.Ceil(b.max.x/100)*100+50,Mathf.Ceil(b.max.z/100)*100+50);
 var race=Object.FindAnyObjectByType<RaceDirector>();var map=race.GetComponent<ExplorationMap>();
 Physics.SyncTransforms();int checkedTrees=0;float maxError=0;foreach(var name in new[]{"World cleanup additional woodland","Anderson wooded frontage screening"}){var root=GameObject.Find(name);foreach(var box in root.GetComponentsInChildren<BoxCollider>()){var p=box.bounds.center;p.y=box.bounds.min.y;var hits=Physics.RaycastAll(new Vector3(p.x,300,p.z),Vector3.down,600).Where(h=>h.collider.name.StartsWith("Ground_")).OrderBy(h=>h.distance).ToArray();if(hits.Length==0)throw new Exception("Tree without supporting terrain");maxError=Mathf.Max(maxError,Mathf.Abs(p.y-hits[0].point.y));checkedTrees++;}}if(maxError>.04f)throw new Exception("Ungrounded vegetation "+scene+" error="+maxError);File.AppendAllText("Docs/WorldCleanup/grounding-checks.txt",scene+" trees="+checkedTrees+" maxFootError="+maxError+"m\n");
 File.WriteAllText(Output+"/"+scene+".json",Newtonsoft.Json.JsonConvert.SerializeObject(new{scene,bounds=new{x=bounds.x,y=bounds.y,width=bounds.width,height=bounds.height},route=race.road.points.Select(P).ToArray(),branches=Object.FindObjectsByType<WoodlandRoute>().Select(r=>new{r.title,points=r.points.Select(P).ToArray()}).ToArray(),gates=race.gates.Select(g=>new{g.name,position=P(g.transform.position)}).ToArray(),landmarks=map.destinations.Select(d=>new{d.title,position=P(d.position)}).ToArray()},Newtonsoft.Json.Formatting.Indented));
 var go=new GameObject("Temporary world cartography camera"){hideFlags=HideFlags.HideAndDontSave};var cam=go.AddComponent<Camera>();cam.CopyFrom(Camera.main);cam.enabled=false;cam.orthographic=true;cam.orthographicSize=bounds.height/2;cam.aspect=bounds.width/bounds.height;cam.nearClipPlane=.1f;cam.farClipPlane=2400;cam.transform.SetPositionAndRotation(new(bounds.center.x,1100,bounds.center.y),Quaternion.LookRotation(Vector3.down,Vector3.forward));cam.clearFlags=CameraClearFlags.SolidColor;cam.backgroundColor=new(.055f,.085f,.09f);
 // Hide transient cars and course guidance for clean geography. Never save this scene state.
 var hidden=Object.FindObjectsByType<Renderer>().Where(r=>r.GetComponentInParent<ArcadeVehicle>()||r.GetComponentInParent<RaceGate>()).ToArray();foreach(var r in hidden)r.enabled=false;
 bool fog=RenderSettings.fog;RenderSettings.fog=false;float lod=QualitySettings.lodBias;QualitySettings.lodBias=100;
 try{int w=5200,h=Mathf.RoundToInt(w/cam.aspect);Capture(cam,w,h,Assets+"/"+scene+".png");if(scene=="DansBackyardForward"||scene=="LakeWoods"||scene=="MountainLoop")Capture(cam,10400,Mathf.RoundToInt(10400/cam.aspect),Output+"/"+(scene=="DansBackyardForward"?"BACKYARD_BASE":scene=="LakeWoods"?"FOREST_BASE":"MOUNTAIN_BASE")+".png");}
 finally{RenderSettings.fog=fog;QualitySettings.lodBias=lod;Object.DestroyImmediate(go);}
 string path=Assets+"/"+scene+".png";AssetDatabase.ImportAsset(path,ImportAssetOptions.ForceSynchronousImport);var importer=(TextureImporter)AssetImporter.GetAtPath(path);importer.textureType=TextureImporterType.Default;importer.maxTextureSize=8192;importer.npotScale=TextureImporterNPOTScale.None;importer.mipmapEnabled=false;importer.isReadable=true;importer.textureCompression=TextureImporterCompression.Uncompressed;importer.filterMode=FilterMode.Bilinear;importer.wrapMode=TextureWrapMode.Clamp;importer.SaveAndReimport();
 var visual=AssetDatabase.LoadAssetAtPath<WorldMapVisual>(Assets+"/"+scene+".asset");if(!visual){visual=ScriptableObject.CreateInstance<WorldMapVisual>();AssetDatabase.CreateAsset(visual,Assets+"/"+scene+".asset");}visual.bounds=bounds;visual.sourceScene="Assets/Scenes/"+scene+".unity";visual.image=AssetDatabase.LoadAssetAtPath<Texture2D>(path);EditorUtility.SetDirty(visual);AssetDatabase.SaveAssets();File.AppendAllText(Output+"/capture-progress.txt",scene+" captured "+bounds+"\n");
 }File.WriteAllText(Output+"/capture-done.txt","Seven actual saved scenes rendered; no scene saves. +Z up; pixel/world bounds in per-scene JSON and WorldMapVisual assets.");}
 catch(Exception e){File.WriteAllText(Output+"/capture-error.txt",e.ToString());}
 finally{EditorSceneManager.OpenScene(original);}}
 static void Capture(Camera cam,int w,int h,string path){var rt=new RenderTexture(w,h,24);var prior=RenderTexture.active;Texture2D tex=null;try{cam.targetTexture=rt;cam.Render();RenderTexture.active=rt;tex=new Texture2D(w,h,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,w,h),0,0);tex.Apply();var temp=path+".capture-tmp";File.WriteAllBytes(temp,tex.EncodeToPNG());if(File.Exists(path))File.Replace(temp,path,null);else File.Move(temp,path);}finally{RenderTexture.active=prior;cam.targetTexture=null;rt.Release();Object.DestroyImmediate(rt);if(tex)Object.DestroyImmediate(tex);}}
}
