EditorApplication.delayCall+=()=>{var original=UnityEngine.SceneManagement.SceneManager.GetActiveScene().path;try{
if(Application.isPlaying||UnityEngine.SceneManagement.SceneManager.GetActiveScene().isDirty)throw new Exception("Saved edit mode required");
UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/LakeWoods.unity");
var data=Newtonsoft.Json.Linq.JObject.Parse(System.IO.File.ReadAllText("Docs/WorldMap/LakeWoods.json"))["bounds"];var bounds=new Rect((float)data["x"],(float)data["y"],(float)data["width"],(float)data["height"]);int height=Mathf.RoundToInt(10400*bounds.height/bounds.width);
var go=new GameObject("Temporary world extension camera"){hideFlags=HideFlags.HideAndDontSave};var cam=go.AddComponent<Camera>();cam.CopyFrom(Camera.main);cam.enabled=false;cam.orthographic=true;cam.orthographicSize=bounds.height/2;cam.aspect=bounds.width/bounds.height;cam.nearClipPlane=.1f;cam.farClipPlane=2400;cam.transform.SetPositionAndRotation(new Vector3(bounds.center.x,1100,bounds.center.y),Quaternion.LookRotation(Vector3.down,Vector3.forward));cam.clearFlags=CameraClearFlags.SolidColor;cam.backgroundColor=new(.055f,.085f,.09f);
foreach(var r in UnityEngine.Object.FindObjectsByType<Renderer>().Where(r=>r.GetComponentInParent<Racer.ArcadeVehicle>()||r.GetComponentInParent<Racer.RaceGate>()))r.enabled=false;
bool fog=RenderSettings.fog;float lod=QualitySettings.lodBias;RenderSettings.fog=false;QualitySettings.lodBias=100;var rt=new RenderTexture(10400,height,24);var prior=RenderTexture.active;
try{cam.targetTexture=rt;cam.Render();RenderTexture.active=rt;var tex=new Texture2D(10400,height,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,10400,height),0,0);tex.Apply();System.IO.File.WriteAllBytes("Docs/WorldMap/FOREST_BASE.png",tex.EncodeToPNG());UnityEngine.Object.DestroyImmediate(tex);}
finally{RenderTexture.active=prior;cam.targetTexture=null;rt.Release();UnityEngine.Object.DestroyImmediate(rt);UnityEngine.Object.DestroyImmediate(go);RenderSettings.fog=fog;QualitySettings.lodBias=lod;}
System.IO.File.WriteAllText("Docs/WorldMap/forest-done.txt","LakeWoods 10400x6933; X=-1350..1350, Z=-850..950; actual saved geometry");
}catch(Exception e){System.IO.File.WriteAllText("Docs/WorldMap/forest-error.txt",e.ToString());}finally{UnityEditor.SceneManagement.EditorSceneManager.OpenScene(original);}};return "Scheduled high-resolution eastern world extent";
