EditorApplication.delayCall+=()=>{var original=UnityEngine.SceneManagement.SceneManager.GetActiveScene().path;var rows=new List<string>();try{
UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/StreetLoopReverse.unity");var label=UnityEngine.Object.FindObjectsByType<TextMesh>().First(t=>t.text=="Rocky Way Acres");var renderer=label.GetComponent<Renderer>();var p=label.transform.position;var f=label.transform.forward;var go=new GameObject("Temporary sign verification camera");var camera=go.AddComponent<Camera>();camera.CopyFrom(Camera.main);camera.enabled=false;camera.fieldOfView=48;camera.nearClipPlane=.1f;camera.farClipPlane=1500;
byte[] Capture(string name,Vector3 eye,bool visible){renderer.enabled=visible;camera.transform.SetPositionAndRotation(eye,Quaternion.LookRotation(p-eye));var rt=new RenderTexture(960,540,24);var old=RenderTexture.active;camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;var tex=new Texture2D(960,540,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,960,540),0,0);tex.Apply();var pixels=tex.GetRawTextureData().ToArray();if(name!=null)System.IO.File.WriteAllBytes("Docs/BackyardReverse/sign-"+name+".png",tex.EncodeToPNG());RenderTexture.active=old;camera.targetTexture=null;rt.Release();UnityEngine.Object.DestroyImmediate(tex);UnityEngine.Object.DestroyImmediate(rt);return pixels;}
int Changed(byte[] a,byte[] b){int n=0;for(int i=0;i<a.Length;i+=3)if(Math.Abs(a[i]-b[i])+Math.Abs(a[i+1]-b[i+1])+Math.Abs(a[i+2]-b[i+2])>12)n++;return n;}
var front=p-f*18;int frontPixels=Changed(Capture("front",front,true),Capture(null,front,false));rows.Add((frontPixels>25?"PASS ":"FAIL ")+"Front lettering visibly rendered; changed pixels="+frontPixels);
var back=p+f*18;int backPixels=Changed(Capture("back",back,true),Capture(null,back,false));rows.Add((backPixels<4?"PASS ":"FAIL ")+"Back face has no visible lettering; changed pixels="+backPixels);
var blocker=GameObject.CreatePrimitive(PrimitiveType.Cube);blocker.name="Temporary opaque sign blocker";blocker.transform.position=p-f*8;blocker.transform.rotation=label.transform.rotation;blocker.transform.localScale=new(20,10,1);var mat=new Material(Shader.Find("Universal Render Pipeline/Lit")){color=new(.25f,.3f,.2f)};blocker.GetComponent<Renderer>().sharedMaterial=mat;int blockedPixels=Changed(Capture("occluded",front,true),Capture(null,front,false));rows.Add((blockedPixels<4?"PASS ":"FAIL ")+"Opaque world surface fully occludes lettering; changed pixels="+blockedPixels);UnityEngine.Object.DestroyImmediate(blocker);UnityEngine.Object.DestroyImmediate(mat);UnityEngine.Object.DestroyImmediate(go);renderer.enabled=true;
var prop=label.GetComponentInParent<Racer.BreakableProp>();var flags=System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic;typeof(Racer.BreakableProp).GetMethod("Awake",flags).Invoke(prop,null);typeof(Racer.BreakableProp).GetMethod("OnEnable",flags).Invoke(prop,null);var local=label.transform.localPosition;var pos=prop.transform.position;typeof(Racer.BreakableProp).GetMethod("Yield",flags).Invoke(prop,new object[]{Vector3.forward*15});bool attached=prop.IsBroken&&label.transform.localPosition==local;typeof(Racer.BreakableProp).GetMethod("HideDebris",flags).Invoke(prop,null);bool hidden=!renderer.enabled;Racer.BreakableProp.RestoreRace();rows.Add((attached&&hidden&&!prop.IsBroken&&renderer.enabled&&Vector3.Distance(pos,prop.transform.position)<.001f?"PASS ":"FAIL ")+"Break/debris hiding/restoration keeps physical lettering attached; direct component lifecycle fixture");System.IO.File.WriteAllLines("Docs/BackyardReverse/sign-checks.txt",rows);
}catch(Exception e){System.IO.File.WriteAllText("Docs/BackyardReverse/sign-error.txt",e.ToString());}finally{UnityEditor.SceneManagement.EditorSceneManager.OpenScene(original);}};return "Front, back, opaque occlusion and break/restore sign checks scheduled";
