using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using Racer;using Object=UnityEngine.Object;
public static class CheckMountainCut {
 public static string Main(){Physics.SyncTransforms();var race=Object.FindAnyObjectByType<RaceDirector>();var road=race.road;road.Initialize();var b=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title=="Summit Traverse");var report=new List<string>();int count=0,blocked=0,missing=0;var backfaces=Physics.queriesHitBackfaces;Physics.queriesHitBackfaces=true;
 for(float s=820;s<952;s+=1){var p=road.At(s,out var f);var right=Vector3.Cross(Vector3.up,f).normalized;foreach(float lane in new[]{-6f,-3f,0,3f,6f}){var q=p+right*lane;count++;var floor=Physics.RaycastAll(q+Vector3.up*.45f,Vector3.down,1.5f,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).ToArray();if(floor.Length==0){missing++;if(missing<15)report.Add($"MISSING s={s} lane={lane}");}foreach(float height in new[]{1f,3f,6f}){var origin=q+Vector3.up*height;var hits=Physics.RaycastAll(origin,f,1.1f,1,QueryTriggerInteraction.Ignore).Where(h=>!h.collider.name.Contains("arrow")&&!h.collider.name.Contains("marking")).ToArray();if(hits.Length>0){blocked++;if(blocked<40)report.Add($"BLOCK s={s} lane={lane} h={height} "+string.Join(";",hits.Select(h=>h.collider.name)));}}}}
 report.Add($"Lower corridor: {count} floor probes, missing={missing}, forward clearance intersections={blocked}");
 int upperMissing=0,high=0;for(float s=0;s<b.Length;s+=2){var p=b.At(s,out var f);var right=Vector3.Cross(Vector3.up,f).normalized;foreach(float lane in new[]{-4f,0f,4f}){var q=p+right*lane;var hits=Physics.RaycastAll(q+Vector3.up*1.5f,Vector3.down,3,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).ToArray();if(hits.Length==0)upperMissing++;else if(hits.Max(h=>h.point.y)>p.y+.5f){high++;if(high<15)report.Add($"UPPER HIGH s={s} lane={lane} "+string.Join(";",hits.Select(h=>h.collider.name+":"+h.point.y)));}}}report.Add($"Upper: missing={upperMissing}, high={high}");
 b.At(b.Length-1,out var bf);road.At(b.exitRoad,out var rf);report.Add($"Unchanged rejoin tangent angle={Vector3.Angle(bf,rf)}");
 var before=Newtonsoft.Json.Linq.JObject.Parse(File.ReadAllText("Docs/MountainCut/routes-before.json"));var after=Newtonsoft.Json.Linq.JObject.FromObject(new{road=road.points.Select(p=>new[]{p.x,p.y,p.z}),branch=b.points.Select(p=>new[]{p.x,p.y,p.z}),b.entryRoad,b.exitRoad,b.bypassedGates,gates=race.gates.Select(g=>new{name=g.name,p=g.transform.position.ToString("F5")})});bool branchSame=before["branch"].ToString()==after["branch"].ToString();bool gatesSame=before["gates"].ToString()==after["gates"].ToString();bool xzSame=before["road"].Zip(after["road"],(a,c)=>Math.Abs((float)a[0]-(float)c[0])<.0001f&&Math.Abs((float)a[2]-(float)c[2])<.0001f).All(x=>x);report.Add($"Preservation: branch coordinates={branchSame}; gates={gatesSame}; main X/Z={xzSame}; lower Y restored from historical road; station anchors refitted");
 foreach(var sign in Object.FindObjectsByType<PhysicalSign>().Where(s=>s.name.Contains("LEFT TO FULL"))){var rs=sign.GetComponentsInChildren<Renderer>();foreach(var r in rs)report.Add("Main sign "+r.name+" "+r.bounds);}
 foreach(var g in race.gates.Where(g=>g.name=="CR117 CP 1"))report.Add("CP1 visuals "+string.Join(";",g.GetComponentsInChildren<Renderer>().Select(r=>r.name+":"+r.bounds)));
 Physics.queriesHitBackfaces=backfaces;File.WriteAllLines("Docs/MountainCut/geometry-checks.txt",report);return string.Join("\n",report);
 }
}
