using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using Racer;using Object=UnityEngine.Object;
public static class CheckMountainCleanup {
 public static string Main(){var rows=new List<string>();Physics.SyncTransforms();var race=Object.FindAnyObjectByType<RaceDirector>();var road=race.road;var b=Object.FindObjectsByType<WoodlandRoute>().Single(x=>x.title=="Summit Traverse");var pavement=GameObject.Find("Ground_CR133 mountain driving surface").GetComponent<Collider>();int probes=0,bad=0,missingFloor=0;
 foreach(var span in new[]{(1565f,1675f,false),(0f,48f,true),(315f,b.Length,true)})for(float s=span.Item1;s<span.Item2;s+=1){Vector3 p,f;if(span.Item3)p=b.At(s,out f);else p=road.At(s,out f);var right=Vector3.Cross(Vector3.up,f).normalized;foreach(float lane in new[]{-4f,-2f,0,2f,4f}){var q=p+right*lane;if(!pavement.Raycast(new Ray(q+Vector3.up*6,Vector3.down),out var floor,20)){missingFloor++;continue;}probes++;var hits=Physics.RaycastAll(floor.point+Vector3.up*2,Vector3.down,3,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider!=pavement&&h.collider.name.StartsWith("Ground_")&&h.point.y>floor.point.y-.25f).ToArray();if(hits.Length>0){bad++;if(bad<25)rows.Add($"FAIL intrusion s={s} branch={span.Item3} lane={lane}: "+string.Join(";",hits.Select(h=>h.collider.name+" height="+(h.point.y-floor.point.y))));}}}rows.Add($"Driving support clearance probes={probes}, intrusions={bad}, missing-floor={missingFloor}");
 int lowerBad=0;for(float s=820;s<952;s+=2){var p=road.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;foreach(float lane in new[]{-6f,0,6f}){var q=p+side*lane;foreach(float h in new[]{1f,3f,6f}){var hits=Physics.RaycastAll(q+Vector3.up*h,f,2.1f,1,QueryTriggerInteraction.Ignore).Where(t=>!t.collider.name.Contains("arrow")&&!t.collider.name.Contains("marking"));if(hits.Any()){lowerBad++;if(lowerBad<8)rows.Add($"FAIL lower {s}/{lane}/{h}: "+string.Join(";",hits.Select(t=>t.collider.name)));}}}}rows.Add("Lower tunnel clearance failures="+lowerBad);
 b.At(b.Length-1,out var bf);road.At(b.exitRoad,out var rf);rows.Add("Summit rejoin tangent degrees="+Vector3.Angle(bf,rf));
 var old=Newtonsoft.Json.Linq.JObject.Parse(File.ReadAllText("Docs/MountainCleanup/routes-before.json"));var now=Newtonsoft.Json.Linq.JArray.FromObject(road.points.Select(p=>new[]{p.x,p.y,p.z}));rows.Add("Main navigation unchanged="+old["road"].SelectMany(p=>p.Select(v=>(float)v)).SequenceEqual(road.points.SelectMany(p=>new[]{p.x,p.y,p.z})));var oldBranch=old["branches"].Single(x=>(string)x["title"]=="Summit Traverse")["points"];rows.Add("Summit route unchanged="+oldBranch.SelectMany(p=>p.Select(v=>(float)v)).SequenceEqual(b.points.SelectMany(p=>new[]{p.x,p.y,p.z})));
 rows.Add("Old slabs remaining="+Object.FindObjectsByType<Collider>().Count(c=>c.name.StartsWith("CR121 closed late cut barrier")||c.name=="Far-side shortcut separator"||c.name.StartsWith("Summit side-entry timber screen")));
 int missing=0;for(float x=820;x<=904;x+=4)foreach(float z in new[]{-322f,-300f,-278f}){if(!Physics.RaycastAll(new(x,160,z),Vector3.down,120,1,QueryTriggerInteraction.Ignore).Any(h=>h.collider.name=="Ground_MountainCleanup landing rock shoulder"))missing++;}rows.Add("Landing shoulder missing samples="+missing);
 File.WriteAllLines("Docs/MountainCleanup/geometry-checks.txt",rows);return string.Join("\n",rows);}
}



