using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using Racer;using Object=UnityEngine.Object;
public static class CheckCaveHillside{
 public static string Main(){Physics.SyncTransforms();var rows=new List<string>();void Check(bool ok,string s)=>rows.Add((ok?"PASS ":"FAIL ")+s);var hill=GameObject.Find("Ground_Echo wooded hillside").GetComponent<MeshCollider>();var b=Object.FindObjectsByType<WoodlandRoute>().Single(x=>x.title=="Echo Cave");var road=Object.FindAnyObjectByType<RaceDirector>().road;road.Initialize();int blocked=0,samples=0;for(float s=0;s<road.Length;s+=2){var p=road.At(s,out var f);foreach(float x in new[]{-4f,0,4f}){var q=p+Vector3.Cross(Vector3.up,f).normalized*x;samples++;if(hill.Raycast(new Ray(q+Vector3.up*100,Vector3.down),out var hit,200)&&hit.point.y>q.y+.15f){blocked++;rows.Add("road cover s="+s+" at="+q+" cover="+hit.point.y);}}}Check(blocked==0,$"Main route support preserved, probes={samples}, blocked={blocked}");
 int buried=0,trees=0;foreach(var c in Object.FindObjectsByType<Collider>().Where(c=>c.name.ToLower().Contains("tree")||c.name.ToLower().Contains("trunk"))){var p=c.bounds.center;if(!hill.Raycast(new Ray(new(p.x,200,p.z),Vector3.down),out var hit,300))continue;trees++;if(hit.point.y>c.bounds.min.y+.12f){buried++;rows.Add("buried "+c.name+" at="+p+" gap="+(c.bounds.min.y-hit.point.y));}}Check(buried==0,$"Trees on cover={trees}; buried={buried}");
 var fall=GameObject.Find("Echo Cave partial rockfall");foreach(var mf in fall.GetComponentsInChildren<MeshFilter>())Check(mf.sharedMesh==mf.GetComponent<MeshCollider>().sharedMesh,mf.name+" collision matches visible mesh");
 foreach(float s in new[]{180f,192f,200f}){var eye=b.At(s,out _)+Vector3.up*2.3f;var target=b.At(235,out _)+Vector3.up*1.4f;bool hit=Physics.RaycastAll(eye,(target-eye).normalized,(target-eye).magnitude).Any(h=>h.collider.transform.IsChildOf(fall.transform));Check(!hit,"Passage sight line station="+s);}
 var shell=GameObject.Find("Echo Cave enclosed rock").GetComponent<MeshFilter>();int exposed=0,roofCount=0;foreach(var v in shell.sharedMesh.vertices.Where((v,i)=>i%12==0)){var p=shell.transform.TransformPoint(v);float s=b.Project(p,out _);if(s<65||s>474||p.y<b.At(s,out _).y+3)continue;roofCount++;if(!hill.Raycast(new Ray(new(p.x,200,p.z),Vector3.down),out var hit,300)||hit.point.y<p.y-.05f)exposed++;}Check(exposed==0,$"Shell cover probes={roofCount}; exposed={exposed}");
 File.WriteAllLines("Docs/CaveHillside/local-checks.txt",rows);return string.Join("\n",rows);}
}
