UnityEditor.EditorApplication.delayCall+=()=>{var mode=Physics.simulationMode;float volume=AudioListener.volume;try{
UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");AudioListener.volume=0;Physics.simulationMode=SimulationMode.Script;var race=UnityEngine.Object.FindAnyObjectByType<Racer.RaceDirector>();var car=race.vehicle;typeof(Racer.VehicleSurfaceContacts).GetMethod("Reset",System.Reflection.BindingFlags.Static|System.Reflection.BindingFlags.NonPublic).Invoke(null,null);typeof(Racer.ArcadeVehicle).GetMethod("Awake",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(car,null);var configuration=car.GetComponent<Racer.VehicleConfiguration>()??car.gameObject.AddComponent<Racer.VehicleConfiguration>();foreach(var body in UnityEngine.Object.FindObjectsByType<Rigidbody>())if(body!=car.Body)body.gameObject.SetActive(false);var ridge=UnityEngine.Object.FindObjectsByType<Racer.WoodlandRoute>().First(b=>b.title.StartsWith("Abandoned"));var brushes=UnityEngine.Object.FindObjectsByType<Racer.ShortcutUndergrowth>().Where(b=>b.name=="Recoverable rough ridge undergrowth").ToArray();var brushStep=typeof(Racer.ShortcutUndergrowth).GetMethod("FixedUpdate",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance);
float Ground(Vector3 p)=>Physics.RaycastAll(new Vector3(p.x,250,p.z),Vector3.down,500,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).OrderBy(h=>h.distance).First().point.y;
Vector3 Flank(float s){var q=ridge.At(s,out var tangent);return q+Vector3.Cross(Vector3.up,tangent).normalized*6.5f;} var results=new List<string>();foreach(string profile in new[]{"moto","atv"})foreach(bool gully in new[]{false}){configuration.Apply(profile);var p=ridge.At(45,out var f);if(gully){p=new Vector3(96,0,-75);f=Vector3.forward;}else p+=Vector3.Cross(Vector3.up,f).normalized*5.5f;p.y=Ground(p)+2;car.Body.position=p;car.Body.rotation=Quaternion.LookRotation(Vector3.ProjectOnPlane(f,Vector3.up));car.transform.SetPositionAndRotation(p,car.Body.rotation);car.Body.linearVelocity=car.Body.angularVelocity=Vector3.zero;car.Body.isKinematic=false;car.ClearSteering();Physics.SyncTransforms();var targets=gully?new[]{new Vector3(106,0,-36),new Vector3(101,0,-23),new Vector3(101,0,20),new Vector3(102,0,45),new Vector3(105,0,95),new Vector3(112,0,125)}:new[]{Flank(57),new Vector3(333,0,122),new Vector3(320,0,124),new Vector3(306,0,127),new Vector3(296,0,134),new Vector3(282,0,134),ridge.At(ridge.Length,out _)};int target=0,frame=0;bool escaped=false;for(;frame<3000;frame++){var here=car.Body.position;float distance=Vector2.Distance(new Vector2(here.x,here.z),new Vector2(targets[target].x,targets[target].z));if(distance<2.5f){if(target==targets.Length-1&&car.GroundedWheels>=2){escaped=true;break;}if(target<targets.Length-1)target++;}var delta=Quaternion.Inverse(Quaternion.LookRotation(Vector3.ProjectOnPlane(car.transform.forward,Vector3.up)))*(targets[target]-here);float look=Mathf.Max(4,Mathf.Min(12,new Vector2(delta.x,delta.z).magnitude));float angle=Mathf.Atan2(delta.x,delta.z);float speed=car.ForwardSpeed;float steer=Mathf.Clamp(Mathf.Atan(2*car.wheelbase*Mathf.Sin(angle)/look)/(Mathf.Lerp(car.slowSteerAngle,car.fastSteerAngle,Mathf.Clamp01(speed/car.topSpeed))*Mathf.Deg2Rad),-1,1);float desired=Mathf.Abs(angle)>.35f?6:10;car.Simulate(speed<desired?.85f:0,speed>desired+1?.4f:0,steer,.02f);foreach(var brush in brushes)brushStep.Invoke(brush,null);Physics.Simulate(.02f);Physics.SyncTransforms();}results.Add((escaped?"PASS ":"FAIL ")+profile+" "+(gully?"gully undershoot to existing northern shallow exit":"ridge fall to trail rejoin")+$" time={frame*.02f:F2}s final={car.Body.position:F2}; ordinary motor and actual brush resistance");}
System.IO.File.WriteAllLines("Docs/ReverseCorrection/ridge-recovery-checks.txt",results);
}catch(Exception e){System.IO.File.WriteAllText("Docs/ReverseCorrection/recovery-error.txt",e.ToString());}finally{Physics.simulationMode=mode;AudioListener.volume=volume;UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");}};return "Four bounded failed-line recovery checks; no full races";




