using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using Racer;
public static class CheckWorldMapGeometry {
 public static string Main(){var race=UnityEngine.Object.FindAnyObjectByType<RaceDirector>();if(Application.isPlaying||race.gameObject.scene.name!="DansBackyardForward")throw new Exception("Saved Backyard edit mode required");var field=UnityEngine.Object.FindObjectsByType<ShortcutUndergrowth>().Single(f=>f.name.StartsWith("Tree-Top Trail"));var branch=UnityEngine.Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title=="Tree-Top Trail");var checks=new List<string>();void Check(bool ok,string s)=>checks.Add((ok?"PASS ":"FAIL ")+s);
 int tested=0,contacts=0;for(float s=branch.entryRoad;s<branch.exitRoad;s+=.5f){var p=race.road.At(s,out var f);foreach(float offset in new[]{-2f,-1f,0,1,2}){var q=p+Vector3.Cross(Vector3.up,f).normalized*offset+Vector3.up*.75f;tested++;if(field.Coverage(q)>0)contacts++;}}
 Check(contacts==0,$"Main and slightly off-center body positions (0/±1/±2m): {tested-contacts}/{tested} free of slowdown");
 int slow=0,total=0,mainClear=0;var exceptions=new List<object>();for(float s=40;s<=82;s+=3)foreach(float offset in new[]{-10f,-5f,0,5,10}){var p=branch.At(s,out var f)+Vector3.Cross(Vector3.up,f).normalized*offset;p.y=Physics.RaycastAll(new(p.x,250,p.z),Vector3.down,500,1).Where(h=>h.collider.name.StartsWith("Ground_")).OrderBy(h=>h.distance).First().point.y+.6f;total++;if(field.Coverage(p)>.9f)slow++;else{race.road.Project(p,out float lateral);if(lateral<4&&field.Coverage(p)==0)mainClear++;exceptions.Add(new{s,offset,p=p.ToString(),coverage=field.Coverage(p),mainDistance=lateral});}}
 Check(slow+mainClear==total,$"Ground-bypass samples: {slow} dense, {mainClear} correctly excluded inside main-trail clearance, {total} total; no unexplained gaps");
 Check(field.GetComponent<MeshFilter>().sharedMesh.vertexCount==538*44,"538 complete shrub/fern clusters retained; only intruding plants removed");Check(field.GetComponents<Collider>().Length==0,"Undergrowth remains traversable, with no solid bush wall");
 Check(branch.aiValidated&&branch.bypassedGates.SequenceEqual(new[]{2,3}),"Accepted Tree-Top route, AI registration and gate entitlement preserved");
 var visual=Resources.Load<WorldMapVisual>("WorldMaps/DansBackyardForward");Check(visual&&visual.bounds.xMin<=-1251&&visual.bounds.xMax>=1213&&visual.bounds.yMin<=-750&&visual.bounds.yMax>=850,"Visual bounds contain complete saved ground/outer-road extent");
 File.WriteAllText("Docs/WorldMap/bypass-exceptions.json",Newtonsoft.Json.JsonConvert.SerializeObject(exceptions));File.WriteAllLines("Docs/WorldMap/geometry-checks.txt",checks);return string.Join("\n",checks);}
}
