using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class ReportSurfaces {
 public static string Main(){var race=Object.FindAnyObjectByType<RaceDirector>();race.road.Initialize();var road=race.road;bool reverse=race.reverseCourse;var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene().name;var branches=Object.FindObjectsByType<WoodlandRoute>();foreach(var b in branches)b.Initialize();var pavement=GameObject.Find("Ground_CR133 mountain driving surface").GetComponent<MeshCollider>();var rows=new List<string>();Physics.SyncTransforms();int samples=0,intrusions=0,missing=0;
 void Probe(Vector3 p,Vector3 f,float halfWidth,bool support){var right=Vector3.Cross(Vector3.up,f).normalized;foreach(float lane in new[]{-halfWidth,0,halfWidth}){var q=p+right*lane;if(!pavement.Raycast(new Ray(q+Vector3.up*4,Vector3.down),out var floor,10))continue;samples++;var bad=Physics.RaycastAll(floor.point+Vector3.up*2.2f,Vector3.down,2.18f,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider!=pavement&&h.collider.name.StartsWith("Ground_")&&h.point.y>floor.point.y+.025f).ToArray();if(bad.Length>0){intrusions++;if(intrusions<12)rows.Add("FAIL driving intrusion route="+p+" floor="+floor.point+" "+string.Join(";",bad.Select(h=>h.collider.name)));}if(support&&!Physics.RaycastAll(floor.point-Vector3.up*.025f,Vector3.down,.75f,1,QueryTriggerInteraction.Ignore).Any(h=>h.collider!=pavement&&h.collider.name.StartsWith("Ground_"))){missing++;if(missing<16)rows.Add("FAIL missing nearby support "+floor.point);}}}
 var spans=reverse?new[]{new Vector2(140,270),new Vector2(395,535),new Vector2(690,955),new Vector2(1165,1295),new Vector2(1480,1690)}:new[]{new Vector2(575,805),new Vector2(1390,1620),new Vector2(1750,1995),new Vector2(2330,2540)};
 foreach(var span in spans)for(float s=span.x;s<span.y;s+=2)Probe(road.At(s,out var f),f,5,false);foreach(var b in branches.Where(b=>b.title=="Summit Traverse"))for(float s=0;s<b.Length;s+=2)Probe(b.At(s,out var f),f,Mathf.Min(4,b.halfWidth-1),false);
 // The receiving pavement is the support check, never the intentional airborne gap.
 foreach(var flight in race.GetComponent<MountainFlights>().flights){var starts=Resources.FindObjectsOfTypeAll<MeshFilter>().Where(m=>m.gameObject.scene==race.gameObject.scene&&m.name.StartsWith("Ground_CR122 main section")).Select(m=>m.transform.TransformPoint((m.sharedMesh.vertices[0]+m.sharedMesh.vertices[1])*.5f));var start=starts.Where(p=>Vector3.Dot(p-flight.lip,flight.forward)>35&&Vector3.Cross(Vector3.ProjectOnPlane(p-flight.lip,Vector3.up),flight.forward).magnitude<8).OrderBy(p=>Vector3.Dot(p-flight.lip,flight.forward)).First();float station=road.Project(start,out _);for(float s=station+.5f;s<station+55;s+=4)Probe(road.At(s,out var f),f,12,true);}
 var old=Newtonsoft.Json.Linq.JObject.Parse(File.ReadAllText("Docs/ReportCleanup/"+scene+"-routes.json"));bool same=old["road"].SelectMany(p=>p.Select(v=>(float)v)).SequenceEqual(road.points.SelectMany(p=>new[]{p.x,p.y,p.z}));foreach(var b in branches){var baseline=old["branches"].Single(x=>(string)x["title"]==b.title);same&=baseline["points"].SelectMany(p=>p.Select(v=>(float)v)).SequenceEqual(b.points.SelectMany(p=>new[]{p.x,p.y,p.z}));}
 bool matching=Object.FindObjectsByType<MeshCollider>().Where(c=>AssetDatabase.GetAssetPath(c.sharedMesh).StartsWith("Assets/Track/ReportCleanup/")&&c.GetComponent<MeshFilter>()).All(c=>c.sharedMesh==c.GetComponent<MeshFilter>().sharedMesh);rows.Add($"samples={samples}; pavementIntrusions={intrusions}; receivingSupportMissing={missing}; routeDataUnchanged={same}; visibleAndCollisionMeshesMatch={matching}");File.WriteAllLines("Docs/ReportCleanup/"+scene+"-final-surfaces.txt",rows);return string.Join("\n",rows);
 }
}


