UnityEditor.EditorApplication.delayCall+=()=>{try{
var results=new List<string>();void Check(bool pass,string label){results.Add((pass?"PASS ":"FAIL ")+label);}
foreach(string name in new[]{"DansBackyardReverse","DansBackyardForward"}){
UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/"+name+".unity");Physics.SyncTransforms();var race=UnityEngine.Object.FindAnyObjectByType<Racer.RaceDirector>();var state=UnityEngine.Object.FindAnyObjectByType<Racer.ReverseShortcutWorldState>();typeof(Racer.ReverseShortcutWorldState).GetMethod("OnEnable",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance).Invoke(state,null);race.FreeRoam=false;state.Refresh();Check(state.grate.activeSelf==!race.reverseCourse&&state.ridgeGate.activeSelf==!race.reverseCourse,name+" race-specific grate and ridge gate");Check(state.grate.GetComponentsInChildren<Collider>(true).Length>10,name+" visible grate has physical bars");race.FreeRoam=true;state.Refresh();Check(!state.grate.activeSelf&&!state.ridgeGate.activeSelf,name+" free roam opens both routes");
var branches=UnityEngine.Object.FindObjectsByType<Racer.WoodlandRoute>();Check(branches.Length==2,name+" retains exactly its two legal branches");
if(race.reverseCourse){var ridge=branches.First(b=>b.title.StartsWith("Abandoned"));var drain=branches.First(b=>b.title.StartsWith("Storm"));Check(branches.All(b=>!b.aiValidated),"New branches excluded from AI");Check(ridge.bypassedGates.Length==0&&drain.bypassedGates.SequenceEqual(new[]{3}),"Minimal gate entitlement: only drain CP3");var p=drain.At(31,out var f);Check(drain.Enter(p-f*.5f+Vector3.up,p+Vector3.up,f),"Legitimate underground entrance accepted");Check(!drain.Enter(p-f*.5f+Vector3.up*8,p+Vector3.up*8,f),"Surface-level travel above drain cannot claim shortcut");Check(!drain.Enter(p+f*.5f+Vector3.up,p+Vector3.up,-f),"Wrong-way entrance rejected");Check(drain.undergroundEnd>drain.undergroundStart+65,"Underground map span authored");Check(ridge.exitRoad-ridge.entryRoad>ridge.Length+15,"Ridge shortens main route by over 15m");Check(drain.exitRoad-drain.entryRoad>drain.Length+35,"Drain shortens main route by over 35m");
foreach(var brush in UnityEngine.Object.FindObjectsByType<Racer.ShortcutUndergrowth>().Where(b=>b.name=="Slow recoverable shortcut edge brush")){Check(brush.centres.Length>30&&brush.centres.All(p=>brush.Coverage(p)>.9f),"Visible ground brush slows failed lines");Check(brush.GetComponentsInChildren<Collider>().Length==0,"Recovery brush traversable; no invisible collision wall");Check(race.road.points.All(p=>brush.Coverage(p)==0),"Main route never receives new brush resistance");}
Check(!state.GetComponentsInChildren<Collider>(true).Any(c=>c.isTrigger),"Shortcut geometry adds no reset trigger");
}
else Check(branches.Any(b=>b.title=="Tree-Top Trail")&&branches.Any(b=>b.title=="Abandoned Cabin Jump"),"Forward original branches retained; Reverse entitlement absent");
// Inspect dependent colliders only in the new ridge/launch footprints. Existing
// ground-level properties and every unchanged course remain protected by diff.
var localTrees=UnityEngine.Object.FindObjectsByType<Collider>().Where(c=>(c.name.ToLower().Contains("trunk")||c.name.ToLower().Contains("tree"))&&c.bounds.center.x>275&&c.bounds.center.x<395&&c.bounds.center.z>78&&c.bounds.center.z<130).ToArray();float max=0;foreach(var c in localTrees){var p=c.bounds.center;var hits=Physics.RaycastAll(new Vector3(p.x,250,p.z),Vector3.down,500,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).OrderBy(h=>h.distance).ToArray();if(hits.Length>0)max=Mathf.Max(max,Mathf.Abs(c.bounds.min.y-hits[0].point.y));}Check(max<.12f,name+" ridge trees grounded: "+localTrees.Length+" maximum foot error="+max);
UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/"+name+".unity");
}
System.IO.File.WriteAllLines("Docs/ReverseShortcuts/state-checks.txt",results);UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");
}catch(Exception e){System.IO.File.WriteAllText("Docs/ReverseShortcuts/state-check-error.txt",e.ToString());}};return "Check scoped course state, entitlement, map metadata and support";
