using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class CheckMountainPolish {
 public static string Main(){var notes=new List<string>();foreach(string scene in new[]{"MountainLoopReverse","MountainLoop"}){EditorSceneManager.OpenScene("Assets/Scenes/"+scene+".unity");Physics.SyncTransforms();var race=Object.FindAnyObjectByType<RaceDirector>();race.road.Initialize();var b=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title=="Summit Traverse");int missing=0,obstructions=0,samples=0;float maxError=0;
 for(float s=0;s<b.Length-1;s+=2){var p=b.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;foreach(float lane in new[]{-3f,0f,3f}){var q=p+side*lane;var hits=Physics.RaycastAll(q+Vector3.up*2,Vector3.down,6,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).ToArray();samples++;if(hits.Length==0){missing++;notes.Add($"MISSING {scene} s={s} lane={lane} {q}");continue;}float y=hits.Max(h=>h.point.y);maxError=Math.Max(maxError,Math.Abs(y-p.y));if(y<p.y-.6f)notes.Add($"LOW {scene} s={s} lane={lane} dy={y-p.y:F3}");if(y>p.y+.5f){obstructions++;if(obstructions<15)notes.Add($"HIGH {scene} s={s} lane={lane} dy={y-p.y:F3} {hits.OrderByDescending(h=>h.point.y).First().collider.name}");}}}
 notes.Add($"{scene}: samples={samples} missing={missing} high={obstructions} maxHeightError={maxError:F3}");if(scene.EndsWith("Reverse")){b.At(b.Length-1,out var f);race.road.At(b.exitRoad,out var rf);notes.Add($"Merge angle={Vector3.Angle(f,rf):F2} deg; width={2*b.halfWidth}m; length={b.Length:F2}; bypassedGates={string.Join(",",b.bypassedGates)}");
 var catalog=JsonUtility.FromJson<CoursePreviewCatalog>(File.ReadAllText("Assets/Resources/WorldMaps/CoursePreviews.json"));var item=catalog.courses.Single(c=>c.scene==scene);item.id=race.courseId;item.main=race.road.points.ToArray();item.gates=race.gates.Select(g=>g.transform.position).ToArray();item.branches=Object.FindObjectsByType<WoodlandRoute>().Select(b=>new CoursePreviewCatalog.Path{points=b.points,undergroundStart=b.undergroundStart,undergroundEnd=b.undergroundEnd}).ToArray();File.WriteAllText("Assets/Resources/WorldMaps/CoursePreviews.json",JsonUtility.ToJson(catalog,true));}
 }
 File.WriteAllLines("Docs/MountainPolish/geometry-checks.txt",notes);AssetDatabase.Refresh();return string.Join("\n",notes);}
}

