using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using Racer;using Object=UnityEngine.Object;
public static class CheckCaveRestore {
 public static string Main(){Physics.SyncTransforms();var rows=new List<string>();void Check(bool ok,string s)=>rows.Add((ok?"PASS ":"FAIL ")+s);
 var b=Object.FindObjectsByType<WoodlandRoute>().Single(x=>x.title=="Echo Cave");var hill=GameObject.Find("Ground_Echo wooded hillside").GetComponent<MeshCollider>();var fall=GameObject.Find("Echo Cave partial rockfall");var edge=Object.FindObjectsByType<MeshFilter>().Where(m=>m.name.StartsWith("Grounded cave edge boulder")).ToArray();var rocks=fall.GetComponentsInChildren<MeshFilter>().Concat(edge).ToArray();int exposed=0,vertices=0;
 foreach(var mf in rocks){var c=mf.GetComponent<MeshCollider>();Check(c&&c.enabled&&!c.isTrigger&&c.sharedMesh==mf.sharedMesh,mf.name+" exact visible collision");foreach(var v in mf.sharedMesh.vertices){var p=mf.transform.TransformPoint(v);vertices++;if(!hill.Raycast(new Ray(new(p.x,200,p.z),Vector3.down),out var h,300)||h.point.y<p.y)exposed++;}}
 Check(exposed==0,$"Rock exterior containment vertices={vertices} exposed={exposed}");Check(!Object.FindObjectsByType<Transform>().Any(t=>t.name=="Angular cave wall ledge"),"No former eye-line wall slabs remain");
 int unsupported=0;foreach(var m in edge){var r=m.GetComponent<Renderer>();var p=r.bounds.center;var support=Physics.RaycastAll(new(p.x,r.bounds.max.y+1,p.z),Vector3.down,40).Where(h=>h.collider.name.StartsWith("Ground_")).OrderBy(h=>h.distance).FirstOrDefault();if(!support.collider||r.bounds.min.y>support.point.y+.05f)unsupported++;}Check(unsupported==0,$"Grounded edge boulders={edge.Length} unsupported={unsupported}");
 foreach(float s in new[]{180f,192f,200f}){var eye=b.At(s,out _)+Vector3.up*2.3f;var target=b.At(235,out _)+Vector3.up*1.4f;bool hit=Physics.RaycastAll(eye,(target-eye).normalized,(target-eye).magnitude).Any(h=>h.collider.transform.IsChildOf(fall.transform));Check(!hit,"Visible right passage from station "+s);}
 int blocked=0;for(float s=65;s<475;s+=1){var p=b.At(s,out var f);var q=Quaternion.LookRotation(Vector3.ProjectOnPlane(f,Vector3.up));if(Physics.OverlapBox(p+Vector3.up*.85f,new Vector3(1.05f,.55f,1.3f),q).Any(c=>c.name.StartsWith("Grounded cave edge boulder")))blocked++;}Check(blocked==0,$"ATV safe-line envelope contacts with edge rocks={blocked}");
 var exclusion=fall.GetComponent<JumpRecoveryExclusion>();Check(exclusion&&exclusion.Contains(b.At(213,out _)),"Existing rockfall recovery exclusion retained");
 File.WriteAllLines("Docs/CaveRestore/local-checks.txt",rows);return string.Join("\n",rows);}
}
