using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class CheckSevenRecovery {
 const BindingFlags F=BindingFlags.Instance|BindingFlags.NonPublic;
 public static string Main(){var rows=new List<string>();var original=UnityEngine.SceneManagement.SceneManager.GetActiveScene().path;
 try{foreach(var scene in new[]{"DansBackyardReverse","LakeWoods"}){
 EditorSceneManager.OpenScene("Assets/Scenes/"+scene+".unity");Physics.SyncTransforms();var race=Object.FindAnyObjectByType<RaceDirector>();var car=race.vehicle;var reset=car.GetComponent<VehicleRespawn>();typeof(ArcadeVehicle).GetMethod("Awake",F).Invoke(car,null);typeof(VehicleRespawn).GetMethod("Awake",F).Invoke(reset,null);typeof(VehicleRespawn).GetField("race",F).SetValue(reset,race);foreach(var body in Object.FindObjectsByType<Rigidbody>())if(body!=car.Body)body.gameObject.SetActive(false);
 typeof(RaceDirector).GetProperty("Branches").SetValue(race,Object.FindObjectsByType<WoodlandRoute>());race.Racers.Clear();var state=new RacerState("recovery fixture",car,race.gates.Length-1,3);race.Racers.Add(state);var record=typeof(VehicleRespawn).GetMethod("RecordSafePosition",F,null,new[]{typeof(float)},null);var support=typeof(VehicleRespawn).GetMethod("Supported",F);var unsafeJump=typeof(VehicleRespawn).GetMethod("UnsafeJump",F);var wheels=typeof(ArcadeVehicle).GetProperty("GroundedWheels");float now=10;
 bool Pose(WoodlandRoute b,float s,int contacts=4){var p=b?b.At(s,out var f):race.road.At(s,out f);var args=new object[]{p,Vector3.ProjectOnPlane(f,Vector3.up).normalized,Vector3.zero,Quaternion.identity};bool supported=(bool)support.Invoke(reset,args);var position=supported?(Vector3)args[2]:p+Vector3.up*.55f;var rotation=supported?(Quaternion)args[3]:Quaternion.LookRotation(f);if(contacts==0)position+=Vector3.up*8;car.transform.SetPositionAndRotation(position,rotation);car.Body.position=position;car.Body.rotation=rotation;car.Body.linearVelocity=f*10;car.Body.angularVelocity=Vector3.zero;wheels.SetValue(car,contacts);Physics.SyncTransforms();record.Invoke(reset,new object[]{now});now+=.11f;return supported;}
 void Case(string name,WoodlandRoute b,float start,float finish,bool land=false){reset.CancelRecovery();state.Branch.Clear();if(b)state.Branch.Begin(b);reset.SeedCoursePosition(b?b.At(start,out _):race.road.At(start,out _));if(land)Pose(b,start,0);for(float s=start;s<=finish;s+=.5f)Pose(b,s);float before=reset.SafeStation;var from=car.Body.position;car.Body.position+=new Vector3(9,-4,4);car.transform.position=car.Body.position;Physics.SyncTransforms();bool ok=reset.TryRecoverLocal();bool unsafeAt=(bool)unsafeJump.Invoke(reset,new object[]{car.Body.position});bool close=Mathf.Abs(finish-before)<10;rows.Add((ok&&!unsafeAt&&close?"PASS ":"FAIL ")+name+$" requested={finish:F1} earned={before:F2} selected={reset.SafeStation:F2} unsafe={unsafeAt}; "+reset.RecoveryDiagnostic);}
 if(scene.StartsWith("Dans")){
 var drain=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title.StartsWith("Storm"));var ridge=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title.StartsWith("Abandoned"));var guide=drain.GetComponent<ReverseShortcutGuidance>();
 Case("normal off-road crash",null,70,82);Case("Logging Ridge final descent",ridge,112,124);Case("shallow wet drain beneath surface road",drain,104,116);Case("failed exit jump keeps acceleration approach",drain,guide.takeoff-45,guide.takeoff-33);float pre=reset.SafeStation;for(float s=guide.takeoff-30;s<guide.landing;s+=2)Pose(drain,s,0);bool ok=reset.TryRecoverLocal();rows.Add((ok&&Math.Abs(reset.SafeStation-pre)<.01f?"PASS ":"FAIL ")+"failed jump retains pre-jump established point "+reset.RecoveryDiagnostic);
 Case("successful exit jump landing then crash",drain,guide.landing+8,guide.landing+20,true);
 state.Branch.Begin(drain);rows.Add(((bool)unsafeJump.Invoke(reset,new object[]{drain.At(14,out _)+Vector3.up*.5f})?"PASS ":"FAIL ")+"drain threshold excluded");state.Branch.Clear();var course=race.GetComponent<BackyardForwardCourse>();foreach(float delta in new[]{-8f,0f})rows.Add(((bool)unsafeJump.Invoke(reset,new object[]{course.flightStarts[2]+course.flightDirections[2]*delta+Vector3.up*.5f})?"PASS ":"FAIL ")+"pool-house ramp/crest excluded "+delta);state.Branch.Begin(drain);foreach(float s in new[]{guide.takeoff-10,guide.takeoff,guide.landing})rows.Add(((bool)unsafeJump.Invoke(reset,new object[]{drain.At(s,out _)+Vector3.up*.5f})?"PASS ":"FAIL ")+"exit ramp/crest/landing excluded station="+s);
 }
 else if(scene=="LakeWoods"){var b=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title=="Echo Cave");Case("Forward cave interior",b,155,167);var shell=GameObject.Find("Echo Cave enclosed rock").GetComponent<Collider>();var covered=Enumerable.Range(0,(int)b.Length).Where(s=>shell.Raycast(new Ray(b.At(s,out _)+Vector3.up*2,Vector3.up),out _,30)).ToArray();if(covered.Length>0)Case("Forest cave recovery",b,covered[0]+1,covered[Math.Min(covered.Length-1,12)]);}
 else{var b=Object.FindObjectsByType<WoodlandRoute>().First(b=>b.title.Contains("Granite"));Case("existing Granite shortcut recovery",b,155,170);var ramps=Object.FindObjectsByType<Collider>().Where(c=>c.name.StartsWith("Takeoff -")||c.name.StartsWith("Gully supported ramp")).ToArray();foreach(var ramp in ramps.Take(1)){state.Branch.Clear();rows.Add(((bool)unsafeJump.Invoke(reset,new object[]{ramp.bounds.center})?"PASS ":"FAIL ")+"another existing ramp excluded "+ramp.name);}}
 }
 File.WriteAllLines("Docs/SevenCorrections/recovery-checks.txt",rows);return string.Join("\n",rows);
 }finally{EditorSceneManager.OpenScene(original);}
 }
}


