EditorApplication.delayCall += () => {try {
var rows=new List<string>();System.IO.Directory.CreateDirectory("Assets/Track/McFaddenEntrance");AssetDatabase.Refresh();
foreach(var sceneName in new[]{"StreetLoopGreybox","LakeWoods","StreetLoopReverse","ForestLoopReverse","MountainLoop","MountainLoopReverse"}){
var scene=UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/"+sceneName+".unity");Physics.SyncTransforms();
var race=UnityEngine.Object.FindAnyObjectByType<Racer.RaceDirector>();var street=race.ambientRoad?race.ambientRoad:race.road;street.Initialize();
var drive=GameObject.Find("House 3 valley driveway").GetComponent<Racer.RaceRoad>();var surface=drive.GetComponentsInChildren<MeshFilter>().Single(m=>m.name=="Ground_House3 supported valley driveway");
var old=surface.sharedMesh;var vertices=old.vertices.ToList();var normals=old.normals.ToList();var uv=old.uv.ToList();var indices=new List<int>();int changed=0;
float Edge(Vector3 local){var p=surface.transform.TransformPoint(local);float s=street.Project(p,out float d);return d-street.HalfWidth(s);}
int Cross(int a,int b){float lo=0,hi=1;float da=Edge(vertices[a]);for(int n=0;n<22;n++){float mid=(lo+hi)*.5f;if((Edge(Vector3.Lerp(vertices[a],vertices[b],mid))>=0)==(da>=0))lo=mid;else hi=mid;}float t=(lo+hi)*.5f;int k=vertices.Count;vertices.Add(Vector3.Lerp(vertices[a],vertices[b],t));if(normals.Count>0)normals.Add(Vector3.Lerp(normals[a],normals[b],t).normalized);if(uv.Count>0)uv.Add(Vector2.Lerp(uv[a],uv[b],t));return k;}
var tris=old.triangles;for(int i=0;i<tris.Length;i+=3){var original=new[]{tris[i],tris[i+1],tris[i+2]};if(!original.Any(k=>surface.transform.TransformPoint(vertices[k]).x>500)||original.All(k=>Edge(vertices[k])>=0)){indices.AddRange(original);continue;}changed++;var polygon=new List<int>();for(int j=0;j<3;j++){int a=original[j],b=original[(j+1)%3];bool insideA=Edge(vertices[a])>=0,insideB=Edge(vertices[b])>=0;if(insideA)polygon.Add(a);if(insideA!=insideB)polygon.Add(Cross(a,b));}for(int j=1;j<polygon.Count-1;j++)indices.AddRange(new[]{polygon[0],polygon[j],polygon[j+1]});}
var mesh=UnityEngine.Object.Instantiate(old);mesh.name=sceneName+" McFadden driveway road-edge visual trim";mesh.SetVertices(vertices);if(normals.Count>0)mesh.SetNormals(normals);if(uv.Count>0)mesh.SetUVs(0,uv);mesh.SetTriangles(indices,0);mesh.RecalculateBounds();AssetDatabase.CreateAsset(mesh,"Assets/Track/McFaddenEntrance/"+sceneName+"-entrance.asset");surface.sharedMesh=mesh;
// Cosmetic trim only: preserve the accepted continuous collision surface byte-for-byte.
var sign=GameObject.Find("House 3 / Rocky Way Acres entrance").transform;var toward=Vector3.ProjectOnPlane(drive.points[1]-drive.points[0],Vector3.up).normalized;var at=drive.points[0]+toward*7f;
float Ground(Vector3 p)=>Physics.RaycastAll(new Vector3(p.x,300,p.z),Vector3.down,600,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).OrderBy(h=>Math.Abs(h.point.y-p.y)).First().point.y;
at.y=Ground(at);sign.SetPositionAndRotation(at,Quaternion.LookRotation(toward));var posts=sign.Cast<Transform>().Where(t=>t.name=="Tall grounded entrance post").ToArray();at.y=posts.Max(p=>Ground(new Vector3(p.position.x,at.y,p.position.z)));sign.position=at;
foreach(var post in posts){var p=post.position;float bottom=Ground(new Vector3(p.x,at.y,p.z))-.06f,top=at.y+6.8f;p.y=(bottom+top)/2;post.position=p;post.localScale=new Vector3(.4f,top-bottom,.4f);street.Project(p,out float distance);if(distance<street.HalfWidth(street.Project(p,out _))+.75f)throw new Exception("Sign too close to main road");rows.Add(sceneName+" post="+p.ToString("F3")+" road centre distance="+distance);}
Physics.SyncTransforms();UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(scene);UnityEditor.SceneManagement.EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();rows.Add(sceneName+" sign="+sign.position.ToString("F3")+" clipped triangles="+changed+" original collider retained="+AssetDatabase.GetAssetPath(surface.GetComponent<MeshCollider>().sharedMesh));
}
System.IO.File.WriteAllLines("Docs/McFaddenEntrance/correction.txt",rows);
}catch(Exception e){System.IO.File.WriteAllText("Docs/McFaddenEntrance/correction-error.txt",e.ToString());}};return "Scheduled local entrance trim and existing sign relocation";
