using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Object=UnityEngine.Object;
public static class CorrectCaveHillsideGrounding{
 public static string Main(){var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene();var current=scene.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Component>(true)).Where(c=>c).ToArray();var map=current.ToDictionary(c=>(GlobalObjectId.GetGlobalObjectIdSlow(c).targetObjectId,GlobalObjectId.GetGlobalObjectIdSlow(c).targetPrefabId),c=>c);File.Copy("Temp/CaveHillsideBaseline.unity","Assets/Scenes/CaveHillsideBaseline.unity",true);AssetDatabase.ImportAsset("Assets/Scenes/CaveHillsideBaseline.unity");var baseline=EditorSceneManager.OpenScene("Assets/Scenes/CaveHillsideBaseline.unity",OpenSceneMode.Additive);int restored=0;
 foreach(var c in baseline.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Component>(true)).Where(c=>c)){if(!map.TryGetValue((GlobalObjectId.GetGlobalObjectIdSlow(c).targetObjectId,GlobalObjectId.GetGlobalObjectIdSlow(c).targetPrefabId),out var dest))continue;if(c is MeshFilter mf&&dest is MeshFilter target&&target.sharedMesh!=mf.sharedMesh){target.sharedMesh=mf.sharedMesh;restored++;}if(c is Transform t&&dest is Transform dt&&(t.name.ToLower().Contains("tree")||t.name.ToLower().Contains("trunk")))dt.localPosition=t.localPosition;}
 EditorSceneManager.CloseScene(baseline,true);AssetDatabase.DeleteAsset("Assets/Scenes/CaveHillsideBaseline.unity");
 foreach(int row in new[]{0,140}){var g=GameObject.Find("Echo eroded hillside face "+row);var m=g.GetComponent<MeshFilter>().sharedMesh;var tri=m.triangles;for(int i=0;i<tri.Length;i+=3){int a=tri[i+1];tri[i+1]=tri[i+2];tri[i+2]=a;}m.triangles=tri;m.RecalculateNormals();EditorUtility.SetDirty(m);g.GetComponent<MeshCollider>().sharedMesh=null;g.GetComponent<MeshCollider>().sharedMesh=m;}
 Physics.SyncTransforms();var hill=GameObject.Find("Ground_Echo wooded hillside").GetComponent<Collider>();bool Affected(Collider c){var p=c.bounds.center;return hill.Raycast(new Ray(new(p.x,200,p.z),Vector3.down),out var hit,300)&&hit.point.y>c.bounds.min.y+.1f;}
 var affected=Object.FindObjectsByType<Collider>().Where(c=>(c.name.ToLower().Contains("tree")||c.name.ToLower().Contains("trunk"))&&Affected(c)).ToArray();typeof(Racer.Editor.BackyardReverseAuthoring).GetMethod("Trees",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,new object[]{(Func<Collider,bool>)(c=>false),(Func<Collider,bool>)(c=>affected.Contains(c))});
 EditorSceneManager.MarkSceneDirty(scene);EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();File.WriteAllText("Docs/CaveHillside/grounding-correction.txt",$"Restored original tree mesh references {restored}; scoped new hill support reseats {affected.Length}. Initial broad tree predicate and reversed portal normals corrected before validation.");return File.ReadAllText("Docs/CaveHillside/grounding-correction.txt");}
}
