using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class CorrectBackyardReverse {
const string Folder="Assets/Track/BackyardReverseCorrections", Evidence="Docs/BackyardReverseCorrections";
static Vector3[] path;static float[] stations;static Dictionary<Vector2Int,List<int>> cells;static RaceDirector race;static readonly List<string> report=new();
static float S(float a,float b,float x)=>Mathf.SmoothStep(0,1,Mathf.InverseLerp(a,b,x));
static float Ground(Vector3 p)=>Racer.Editor.BackyardReverseAuthoring.Ground(p);
static void Index(){cells=new();stations=new float[path.Length];for(int i=1;i<path.Length;i++){stations[i]=stations[i-1]+Vector3.Distance(path[i],path[i-1]);for(int x=Mathf.FloorToInt((Mathf.Min(path[i-1].x,path[i].x)-8)/16);x<=Mathf.FloorToInt((Mathf.Max(path[i-1].x,path[i].x)+8)/16);x++)for(int z=Mathf.FloorToInt((Mathf.Min(path[i-1].z,path[i].z)-8)/16);z<=Mathf.FloorToInt((Mathf.Max(path[i-1].z,path[i].z)+8)/16);z++){var key=new Vector2Int(x,z);if(!cells.TryGetValue(key,out var ids))cells[key]=ids=new();ids.Add(i);}}}
static float Near(Vector3 p,out Vector3 at,out float station){at=default;station=0;float best=float.MaxValue;if(!cells.TryGetValue(new(Mathf.FloorToInt(p.x/16),Mathf.FloorToInt(p.z/16)),out var ids))return best;foreach(int i in ids){var a=path[i-1];var f=path[i]-a;f.y=0;var q=p-a;q.y=0;float t=Mathf.Clamp01(Vector3.Dot(q,f)/Mathf.Max(.0001f,f.sqrMagnitude));float d=(q-f*t).sqrMagnitude;if(d<best){best=d;at=Vector3.Lerp(a,path[i],t);station=Mathf.Lerp(stations[i-1],stations[i],t);}}return Mathf.Sqrt(best);}
static Mesh Store(Mesh m,string name){string p=Folder+"/"+name+".asset";if(AssetDatabase.LoadAssetAtPath<Mesh>(p))throw new Exception("Already authored "+p);AssetDatabase.CreateAsset(m,p);return m;}
static void ResetRoad(){race.road.points=path;typeof(RaceRoad).GetField("distance",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance).SetValue(race.road,null);race.road.Initialize();}
public static string Main(){if(Application.isPlaying||UnityEngine.SceneManagement.SceneManager.GetActiveScene().isDirty)throw new Exception("Saved edit mode required");EditorApplication.delayCall+=Run;return "Apply scoped Reverse corrections to copied Reverse-only assets";}
static void Run(){try{Directory.CreateDirectory(Folder);AssetDatabase.Refresh();EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");Physics.SyncTransforms();race=Object.FindAnyObjectByType<RaceDirector>();var road=race.road;road.Initialize();path=road.points.ToArray();var original=path.ToArray();var c=race.GetComponent<BackyardForwardCourse>();var lands=c.landingStations.Select(s=>road.At(s,out _)).ToArray();
// Finish the north-gully turn before X190; the existing lip/landing stay fixed.
for(int i=0;i<path.Length;i++){var p=path[i];if(p.x>=160&&p.x<=218&&p.z>75&&p.z<110){float t=Mathf.InverseLerp(218,190,p.x);float blend=S(0,1,t);p.z=Mathf.Lerp(p.z,80.7f,blend);path[i]=p;}
// Align the wooded approach with the existing pool-house ramp axis.
else if(p.x>=307&&p.x<=389&&p.z>-25&&p.z<0){float blend=S(307,334,p.x);p.z=Mathf.Lerp(p.z,-3.1f+(p.x-389)*.2f,blend);path[i]=p;}
// Keep the runout clear of the approved Tree-Top landing edge, without editing it.
else if(p.x>=162&&p.x<=194&&p.z<-90){p.z-=1.4f*S(162,174,p.x)*(1-S(183,194,p.x));path[i]=p;}}
Index();
// Smooth only abrupt local support joins. The centre profile retains hills and grade.
var bumps=new[]{new Vector3(423.5f,0,83),new(172,0,-97),new(235,0,-33)};
float Blend(Vector3 p){float w=0;foreach(var b in bumps){float d=Vector2.Distance(new(p.x,p.z),new(b.x,b.z));w=Mathf.Max(w,1-S(7,15,d));}if(p.x>159&&p.x<219&&p.z>72&&p.z<112)w=Mathf.Max(w,S(159,170,p.x)*(1-S(211,219,p.x)));if(p.x>306&&p.x<390&&p.z>-25&&p.z<0)w=Mathf.Max(w,S(306,319,p.x)*(1-S(385,390,p.x)));return w;}
var smooth=path.ToArray();for(int i=0;i<path.Length;i++){if(Blend(path[i])<=0)continue;float sum=0,weight=0;for(int j=Math.Max(0,i-8);j<=Math.Min(path.Length-1,i+8);j++){float d=Vector2.Distance(new(path[i].x,path[i].z),new(path[j].x,path[j].z));float w=Mathf.Max(0,1-d/5);sum+=path[j].y*w;weight+=w;}smooth[i].y=Mathf.Lerp(path[i].y,sum/weight,Blend(path[i]));}path=smooth;Index();
var courseStarts=c.flightStarts.ToArray();bool Air(Vector3 p){for(int j=0;j<3;j++){var axis=c.flightDirections[j];float along=Vector3.Dot(p-courseStarts[j],axis),end=Vector3.Dot(lands[j]-courseStarts[j],axis);if(along>.4f&&along<end-1&&Mathf.Abs(Vector3.Dot(p-courseStarts[j],Vector3.Cross(Vector3.up,axis)))<7)return true;}return false;}
// Dependencies are inspected before touching supporting vertices.
var dependencies=Object.FindObjectsByType<Collider>().Where(x=>!x.name.StartsWith("Ground_")&&!x.isTrigger).Where(x=>{Near(x.bounds.center,out _,out _);return Blend(x.bounds.center)>0;}).Select(x=>new{x.name,min=x.bounds.min.ToString(),max=x.bounds.max.ToString()}).ToArray();File.WriteAllText(Evidence+"/dependencies-before.json",Newtonsoft.Json.JsonConvert.SerializeObject(dependencies,Newtonsoft.Json.Formatting.Indented));
int nmesh=0;foreach(var mf in Object.FindObjectsByType<MeshFilter>().Where(m=>m.name.StartsWith("Ground_")&&m.GetComponent<MeshCollider>()).ToArray()){var src=mf.sharedMesh;var vs=src.vertices;var ts=src.triangles;var colors=src.colors;var uv=src.uv;var uv1=new List<Vector4>();src.GetUVs(1,uv1);if(!vs.Any(v=>Near(mf.transform.TransformPoint(v),out _,out _)<7))continue;
var verts=new List<Vector3>();var cols=new List<Color>();var tex=new List<Vector2>();var tex1=new List<Vector4>();var indices=new List<int>();int shaped=0,painted=0;
for(int tri=0;tri<ts.Length;tri+=3){int a=ts[tri],b=ts[tri+1],d=ts[tri+2];var pa=mf.transform.TransformPoint(vs[a]);var pb=mf.transform.TransformPoint(vs[b]);var pc=mf.transform.TransformPoint(vs[d]);bool near=Near(pa,out _,out _)<6||Near(pb,out _,out _)<6||Near(pc,out _,out _)<6||Near((pa+pb+pc)/3,out _,out _)<6;int n=near?Mathf.Clamp(Mathf.CeilToInt(Mathf.Max(Vector3.Distance(pa,pb),Vector3.Distance(pa,pc))/.9f),1,6):1;
void Add(float u,float v){var p=pa+(pb-pa)*u+(pc-pa)*v;float dist=Near(p,out var at,out _);float w=Blend(p)*(1-S(3.1f,6,dist));if(w>0&&!Air(p)){float old=p.y;p.y=Mathf.Lerp(p.y,at.y,w);if(Mathf.Abs(old-p.y)>.001f)shaped++;}
var color=colors.Length==vs.Length?colors[a]+(colors[b]-colors[a])*u+(colors[d]-colors[a])*v:Color.white;
// Same vertex-color dirt style as the approved main trail, on the actual ground.
if(dist<3.3f&&!Air(p)&&p.x<468&&(p.x<392||p.z>42)){float paint=1-S(2.3f,3.3f,dist);color=Color.Lerp(color,new Color(.38f,.255f,.135f),paint*.93f);painted++;}
indices.Add(verts.Count);verts.Add(mf.transform.InverseTransformPoint(p));cols.Add(color);tex.Add(uv.Length==vs.Length?uv[a]+(uv[b]-uv[a])*u+(uv[d]-uv[a])*v:Vector2.zero);tex1.Add(uv1.Count==vs.Length?uv1[a]+(uv1[b]-uv1[a])*u+(uv1[d]-uv1[a])*v:Vector4.zero);}
for(int j=0;j<n;j++)for(int k=0;k<n-j;k++){Add(j/(float)n,k/(float)n);Add((j+1)/(float)n,k/(float)n);Add(j/(float)n,(k+1)/(float)n);if(j+k<n-1){Add((j+1)/(float)n,k/(float)n);Add((j+1)/(float)n,(k+1)/(float)n);Add(j/(float)n,(k+1)/(float)n);}}}
if(painted+shaped==0)continue;var mesh=new Mesh{indexFormat=UnityEngine.Rendering.IndexFormat.UInt32};mesh.SetVertices(verts);mesh.SetColors(cols);mesh.SetUVs(0,tex);mesh.SetUVs(1,tex1);mesh.SetTriangles(indices,0);mesh.RecalculateNormals();mesh.RecalculateBounds();mf.sharedMesh=Store(mesh,"terrain-"+(nmesh++));mf.GetComponent<MeshCollider>().sharedMesh=mesh;report.Add(mf.name+" support samples corrected="+shaped+", dirt samples="+painted);}
Physics.SyncTransforms();Object.DestroyImmediate(GameObject.Find("Narrow worn-earth Reverse trail"));for(int i=0;i<path.Length;i++)if(!Air(path[i])){var p=path[i];p.y=Ground(p);path[i]=p;}ResetRoad();Index();
for(int j=0;j<3;j++){c.launchStations[j]=road.Project(c.flightStarts[j],out _);c.landingStations[j]=road.Project(lands[j],out _);}var layout=Object.FindAnyObjectByType<ForestLayout>();layout.jumpStarts=c.launchStations;layout.jumpEnds=c.landingStations;
// Only the two affected approach gates follow the small line shifts.
foreach(int j in new[]{2,7}){var gate=race.gates[j];Near(gate.transform.position,out var at,out var s);road.At(s,out var f);at.y=Ground(at);gate.transform.SetPositionAndRotation(at+Vector3.up*1.5f,Quaternion.LookRotation(Vector3.ProjectOnPlane(f,Vector3.up)));}
foreach(var mf in Object.FindObjectsByType<MeshFilter>().Where(x=>x.name=="Reverse teal ground arrow")){Near(mf.transform.position,out var at,out var s);road.At(s,out var f);mf.transform.SetPositionAndRotation(at,Quaternion.LookRotation(Vector3.ProjectOnPlane(f,Vector3.up)));var mesh=Object.Instantiate(mf.sharedMesh);var vertices=mesh.vertices;for(int i=0;i<vertices.Length;i++){var p=mf.transform.TransformPoint(vertices[i]);p.y=Ground(p)+.035f;vertices[i]=mf.transform.InverseTransformPoint(p);}mesh.vertices=vertices;mesh.RecalculateNormals();mesh.RecalculateBounds();mf.sharedMesh=Store(mesh,"arrow-"+(nmesh++));}
// Natural timber closures across the wrong Forward continuations, clear of Reverse.
var manager=new GameObject("Reverse-only divergence closures").AddComponent<BackyardReverseBarriers>();manager.race=race;var closures=new List<GameObject>();var wood=AssetDatabase.LoadAssetAtPath<Material>("Assets/Track/BackyardShortcuts/Weathered cedar.mat");var forward=Object.FindObjectsByType<RaceRoad>().First(x=>x.name=="Forward navigation only - no road mesh");forward.Initialize();
foreach(var target in new[]{new Vector3(217,59.4f,-23),new(174,64.5f,70),new(21.1f,37,-80)}){float fs=forward.Project(target,out _);var pos=forward.At(fs,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;var go=new GameObject("Reverse timber closure A"+(closures.Count+1));go.transform.SetParent(manager.transform);go.transform.position=pos;for(int piece=0;piece<3;piece++){var log=GameObject.CreatePrimitive(PrimitiveType.Cube);log.name="Grounded timber barricade beam";log.transform.SetParent(go.transform);var a=pos-side*3.1f;var b=pos+side*3.1f;a.y=Ground(a);b.y=Ground(b);var right=(b-a).normalized;var front=Vector3.Cross(right,Vector3.up).normalized;var up=Vector3.Cross(front,right).normalized;log.transform.SetPositionAndRotation((a+b)*.5f+up*(.225f+piece*.45f),Quaternion.LookRotation(front,up));log.transform.localScale=new(Vector3.Distance(a,b),.45f,.55f);log.GetComponent<Renderer>().sharedMaterial=wood;}
closures.Add(go);Near(pos,out _,out float rs);report.Add(go.name+" "+pos+" Reverse center distance="+Near(pos,out _,out _));}manager.closures=closures.ToArray();manager.Refresh();
// Existing shortcut signs are not Reverse route instructions.
foreach(var t in Object.FindObjectsByType<Transform>().Where(t=>t.name.Contains("Shortcut")&&t.GetComponent<TextMesh>()).ToArray())t.gameObject.SetActive(false);
EditorUtility.SetDirty(race);EditorUtility.SetDirty(c);EditorUtility.SetDirty(layout);EditorSceneManager.MarkSceneDirty(UnityEngine.SceneManagement.SceneManager.GetActiveScene());EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());AssetDatabase.SaveAssets();Racer.Editor.BackyardReverseAuthoring.ExportReverse();File.WriteAllLines(Evidence+"/correction-done.txt",report);
}catch(Exception e){File.WriteAllText(Evidence+"/correction-error.txt",e.ToString());}}
}

