using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;
using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class CorrectReverseShortcuts {
 const string F="Assets/Track/ReverseCorrection",D="Docs/ReverseCorrection";static Transform root;static RaceDirector race;static RaceRoad[] roads;static WoodlandRoute ridge,drain;static Material earth,grass,concrete,wood,metal,water,gold;static int serial;static float exit,lip,landing,entrance;static List<string> notes=new();
 static float Ground(Vector3 p)=>Physics.RaycastAll(new(p.x,250,p.z),Vector3.down,500,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")&&!h.collider.transform.IsChildOf(root)).Select(h=>h.point.y).DefaultIfEmpty(p.y).Max();
 static float Support(Vector3 p)=>Physics.RaycastAll(new(p.x,250,p.z),Vector3.down,500,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).Select(h=>h.point.y).DefaultIfEmpty(p.y).Max();
 static bool Protected(Vector3 p){foreach(var r in roads){r.Project(p,out float d);if(d<3.8f)return true;}return false;}
 static Material Mat(string n,Color c){string path=F+"/"+n+".mat";var m=AssetDatabase.LoadAssetAtPath<Material>(path);if(!m){m=new Material(Shader.Find("Universal Render Pipeline/Lit")){name=n,color=c};AssetDatabase.CreateAsset(m,path);}return m;}
 static Mesh Store(Mesh m,string n){m.RecalculateNormals();m.RecalculateBounds();string path=F+"/"+n+"-"+(serial++)+".asset";var old=AssetDatabase.LoadAssetAtPath<Mesh>(path);if(old){EditorUtility.CopySerialized(m,old);Object.DestroyImmediate(m);return old;}AssetDatabase.CreateAsset(m,path);return m;}
 static GameObject MeshPart(string n,List<Vector3> v,List<int> t,Material mat,bool collision=true){var m=new Mesh{indexFormat=UnityEngine.Rendering.IndexFormat.UInt32};m.SetVertices(v);m.SetTriangles(t,0);m.uv=v.Select(p=>new Vector2(p.x,p.z)*.18f).ToArray();m=Store(m,n);var g=new GameObject(n,typeof(MeshFilter),typeof(MeshRenderer));g.transform.SetParent(root);g.GetComponent<MeshFilter>().sharedMesh=m;g.GetComponent<Renderer>().sharedMaterial=mat;if(collision)g.AddComponent<MeshCollider>().sharedMesh=m;return g;}
 static GameObject Box(string n,Vector3 p,Vector3 size,Quaternion q,Material mat,bool solid=false){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=n;g.transform.SetParent(root);g.transform.SetPositionAndRotation(p,q);g.transform.localScale=size;g.GetComponent<Renderer>().sharedMaterial=mat;if(!solid)Object.DestroyImmediate(g.GetComponent<Collider>());return g;}
 static Vector3[] Curve(Vector3[] k){var p=new List<Vector3>();for(int i=0;i<k.Length-1;i++){var a=k[Math.Max(0,i-1)];var b=k[i];var c=k[i+1];var d=k[Math.Min(k.Length-1,i+2)];int n=Mathf.CeilToInt(Vector3.Distance(b,c)/.5f);for(int j=0;j<n;j++){float t=j/(float)n;p.Add(.5f*(2*b+(-a+c)*t+(2*a-5*b+4*c-d)*t*t+(-a+3*b-3*c+d)*t*t*t));}}p.Add(k[^1]);return p.ToArray();}
 static void Reset(WoodlandRoute b){typeof(WoodlandRoute).GetField("lengths",BindingFlags.Instance|BindingFlags.NonPublic).SetValue(b,null);b.Initialize();}
 static WoodlandRoute Branch(string n,Vector3[] p,float width,float speed){var g=new GameObject(n);g.transform.SetParent(root);var b=g.AddComponent<WoodlandRoute>();b.title=n;b.points=p;b.halfWidth=width;b.recommendedSpeed=speed;b.entrySpeed=20;b.entrySpeedDistance=30;b.entryInset=14;b.entryMargin=1;b.entryHeightAbove=4;b.entryHeightBelow=2;b.entryRoad=race.road.Project(p[0],out _);b.exitRoad=race.road.Project(p[^1],out _);b.aiValidated=true;b.bypassedGates=Array.Empty<int>();return b;}
 static void Strip(string n,WoodlandRoute b,float start,float end,float half,Material mat,bool sides=false,float offset=0,float lift=0){var v=new List<Vector3>();var t=new List<int>();int rows=Mathf.CeilToInt((end-start)/.45f),cols=sides?4:2;for(int i=0;i<=rows;i++){var p=b.At(Mathf.Lerp(start,end,i/(float)rows),out var f);var r=Vector3.Cross(Vector3.up,f).normalized;foreach(float w in sides?new[]{-half-9,-half,half,half+9}:new[]{-half,half}){var q=p+r*(w+offset);q.y+=lift;if(Math.Abs(w)>half)q.y=Ground(q)-.015f;v.Add(q);}if(i>0)for(int j=0;j<cols-1;j++){int a=(i-1)*cols+j;var center=(v[a]+v[a+cols]+v[a+1])/3;if(Protected(center)&&Math.Abs(center.y-Ground(center))<2)continue;t.AddRange(new[]{a,a+cols,a+1,a+1,a+cols,a+cols+1});}}MeshPart(n,v,t,mat);}
 static void Arrow(WoodlandRoute b,float s){var p=b.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;foreach(int sign in new[]{-1,1}){var a=p-f*.7f+side*.7f*sign;var z=p+f*.5f;Box("Optional gold guidance",(a+z)*.5f+Vector3.up*.055f,new(.12f,.025f,Vector3.Distance(a,z)),Quaternion.LookRotation(z-a),gold);}}
 static void Ridge(Vector3[] old){ridge=Branch("Abandoned Logging Ridge",old,2.4f,23);float length=ridge.Length;var points=old.ToArray();for(int i=0;i<points.Length;i++){float s=ridge.Project(points[i],out _);float fade=Mathf.SmoothStep(0,1,s/23)*Mathf.SmoothStep(0,1,(length-s)/27);float roll=6.7f+1.6f*Mathf.Sin((s-15)*.075f)+.9f*Mathf.Sin(s*.18f);float hop=.85f*Mathf.Exp(-Mathf.Pow((s-52)/3.8f,2))+.7f*Mathf.Exp(-Mathf.Pow((s-87)/4,2));float roadDistance=roads.Min(r=>{r.Project(points[i],out float d);return d;}); fade*=Mathf.SmoothStep(0,1,Mathf.InverseLerp(4.2f,12,roadDistance));points[i].y=Ground(points[i])+.025f+fade*(roll+hop);}ridge.points=points;Reset(ridge);
 // Earth crest blended into a wide, irregular vegetated talus; no vertical skirt.
 var v=new List<Vector3>();var tri=new List<int>();int rows=Mathf.CeilToInt(ridge.Length/.5f);float[] ws={-16,-11,-6,-2.4f,-1.3f,0,1.3f,2.4f,6,11,16};for(int i=0;i<=rows;i++){float s=ridge.Length*i/rows;var p=ridge.At(s,out var f);var r=Vector3.Cross(Vector3.up,f).normalized;for(int j=0;j<ws.Length;j++){float w=ws[j];var q=p+r*w;float blend=Mathf.SmoothStep(0,1,Mathf.Clamp01((Math.Abs(w)-2.4f)/(11.5f+1.2f*Mathf.Sin(s*.12f+w))));q.y=Mathf.Lerp(p.y-.035f*Math.Abs(w),Ground(q)-.02f,blend);if(Protected(q))q.y=Ground(q)-.02f;v.Add(q);}if(i>0)for(int j=0;j<ws.Length-1;j++){int a=(i-1)*ws.Length+j;tri.AddRange(new[]{a,a+ws.Length,a+1,a+1,a+ws.Length,a+ws.Length+1});}}
 MeshPart("Ground_Natural rolling ridge",v,tri,grass);Strip("Ground_Worn logging crest",ridge,0,ridge.Length,2.35f,earth);
 for(float s=20;s<ridge.Length-18;s+=13){Strip("Grass intrusion",ridge,s,s+3.5f,.45f,grass,false,Mathf.Sin(s)*1.8f,.035f);var p=ridge.At(s,out var f);var r=Vector3.Cross(Vector3.up,f).normalized;var q=p+r*(s%26<13?4.3f:-4.3f);q.y=Support(q);Box("Abandoned fallen timber",q+Vector3.up*.32f,new(.65f,.6f,3.6f),Quaternion.LookRotation(f+r*.3f),wood,true);Arrow(ridge,s);}
 foreach(float s in new[]{38f,69f,101f}){var p=ridge.At(s,out var f);var r=Vector3.Cross(Vector3.up,f).normalized;var q=p+r*3.2f;q.y=Support(q);Box("Weathered stump",q+Vector3.up*.42f,new(.7f,.84f,.65f),Quaternion.Euler(0,s,0),wood,true);}notes.Add("Ridge crest raised by varying 4-9m; 4.8m top; two small earth hops; sloped vegetated sides.");}
 static void Drain(){float floor=Ground(new(103,0,-66.1f))+.15f;notes.Add("Exit floor derived from existing lower gully at (103,-66.1): "+floor);
 var k=new[]{new Vector3(179,0,80.7f),new(172,0,76),new(166.8f,0,73),new(154,53,68),new(145,44,51),new(141,37.5f,26),new(140,34,-5),new(137,32,-38),new(127,floor,-61),new(114.3f,floor,-66.1f),new(106,floor,-66.1f),new(94,floor+6,-66.1f),new(61,0,-66.1f),new(45,0,-61),new(26,0,-50)};
 for(int i=0;i<3;i++)k[i].y=Ground(k[i])+.025f;for(int i=12;i<k.Length;i++)k[i].y=Ground(k[i])+.03f;
 drain=Branch("Storm Drain / Gully Jump",Curve(k),3.8f,28);drain.entrySpeed=22;drain.entrySpeedDistance=160;drain.entryInset=24;drain.entryHeightAbove=3.2f;drain.bypassedGates=new[]{3};entrance=drain.Project(k[2],out _);exit=drain.Project(k[9],out _);lip=drain.Project(k[11],out _);landing=drain.Project(k[12],out _);float ramp=drain.Project(k[10],out _);
 for(int i=0;i<drain.points.Length;i++){float s=drain.Project(drain.points[i],out _);if(s>=exit&&s<=lip){float u=Mathf.Clamp01((s-ramp)/(lip-ramp));drain.points[i].y=floor+6*u*u;drain.points[i].z=-66.1f;}}Reset(drain);drain.undergroundStart=entrance;drain.undergroundEnd=exit;
 Strip("Culvert seamless floor",drain,0,exit+.1f,4.5f,concrete);Strip("Ground_Gully continuous curved takeoff",drain,exit,lip,4.2f,earth,true);Strip("Ground_Wide west bank landing",drain,landing-7,drain.Length,5,earth,true);
 var v=new List<Vector3>();var t=new List<int>();int count=Mathf.CeilToInt(exit-entrance);for(int i=0;i<=count;i++){float s=Mathf.Lerp(entrance,exit,i/(float)count);var p=drain.At(s,out var f);var r=Vector3.Cross(Vector3.up,f).normalized;float width=4.6f+.2f*Mathf.Sin(s*.045f);foreach(var q in new[]{p-r*width,p-r*width+Vector3.up*6.1f,p+r*width+Vector3.up*6.1f,p+r*width})v.Add(q);if(i>0)for(int j=0;j<3;j++){int a=(i-1)*4+j;t.AddRange(new[]{a,a+1,a+4,a+1,a+5,a+4});}}concrete.SetFloat("_Cull",0);MeshPart("Long storm culvert walls and ceiling",v,t,concrete);
 foreach(float s in new[]{entrance,exit}){var p=drain.At(s,out var f);f=Vector3.ProjectOnPlane(f,Vector3.up).normalized;var side=Vector3.Cross(Vector3.up,f);foreach(int sign in new[]{-1,1})Box("Supported culvert mouth pier",p+side*5*sign+Vector3.up*3,new(.7f,6.5f,1),Quaternion.LookRotation(f),concrete,true);Box("Culvert mouth lintel",p+Vector3.up*6.4f,new(10.7f,.7f,1),Quaternion.LookRotation(f),concrete,true);}
 // Water is a shallow reflective skin over the continuous driveable concrete.
 water.SetFloat("_Smoothness",.92f);water.SetFloat("_Metallic",.35f);for(float s=entrance+4;s<exit-5;s+=24)Strip("Shallow storm water",drain,s,Mathf.Min(s+19,exit-3),1.35f,water,false,.3f,.028f);
 for(float s=entrance+8;s<exit-4;s+=13){var p=drain.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;var q=Quaternion.LookRotation(f);Box("Culvert overhead expansion joint",p+Vector3.up*6.03f,new(9,.1f,.14f),q,metal);foreach(int sign in new[]{-1,1}){Box("Culvert vertical seam",p+side*4.48f*sign+Vector3.up*3,new(.1f,6,.14f),q,metal);Box("Wet edge channel",p+side*3.9f*sign+Vector3.up*.04f,new(.3f,.06f,8),q,water);}
 if(((int)s/13)%2==0){var pipe=GameObject.CreatePrimitive(PrimitiveType.Cylinder);pipe.name="Side stormwater inlet";pipe.transform.SetParent(root);pipe.transform.position=p+side*4.35f+Vector3.up*1.25f;pipe.transform.up=side;pipe.transform.localScale=new(.65f,.45f,.65f);pipe.GetComponent<Renderer>().sharedMaterial=metal;Object.DestroyImmediate(pipe.GetComponent<Collider>());Box("Edge sediment",p-side*4.15f+Vector3.up*.09f,new(.35f,.14f,1.1f),q,earth);}
 var light=new GameObject("Low maintenance tunnel light").AddComponent<Light>();light.transform.SetParent(root);light.transform.position=p+Vector3.up*5.6f;light.type=LightType.Point;light.range=17;light.intensity=.9f;light.color=new(.65f,.76f,.7f);}
 var ep=drain.At(entrance,out var ef);ef=Vector3.ProjectOnPlane(ef,Vector3.up).normalized;var er=Vector3.Cross(Vector3.up,ef);var grate=new GameObject("Forward closed drainage grate");grate.transform.SetParent(root);for(float x=-4.4f;x<=4.4f;x+=.55f){var bar=Box("Visible steel grate",ep+er*x+Vector3.up*3,new(.15f,6,.25f),Quaternion.LookRotation(ef),metal,true);bar.transform.SetParent(grate.transform);}var state=root.gameObject.AddComponent<ReverseShortcutWorldState>();state.grate=grate;var rp=ridge.At(14,out var rf);state.ridgeGate=Box("Forward logging gate",rp+Vector3.up*.9f,new(5,1.8f,.35f),Quaternion.LookRotation(rf),wood,true);state.Refresh();foreach(float s in new[]{5,entrance+3,exit+2,landing+5})Arrow(drain,s);notes.Add($"Tunnel underground length {exit-entrance:F2}m; exit (114.3,{floor},-66.1); lip {lip:F2}; landing {landing:F2}; full branch {drain.Length:F2}m");}
 static void TerrainPortals(){
 bool Cut(Vector3 p){float s=drain.Project(p,out float d);if(d>4.55f||s<7||s>exit+13||Protected(p))return false;var floor=drain.At(s,out _);return p.y>floor.y-.12f&&p.y<floor.y+6.15f;}
 foreach(var mf in Object.FindObjectsByType<MeshFilter>().Where(m=>m.name.StartsWith("Ground_")&&!m.transform.IsChildOf(root)&&m.GetComponent<MeshCollider>()).ToArray()){var src=mf.sharedMesh;var vs=src.vertices;var ts=src.triangles;if(!vs.Any(p=>Cut(mf.transform.TransformPoint(p))))continue;var colors=src.colors;var uv=src.uv;var u1=new List<Vector4>();src.GetUVs(1,u1);var verts=new List<Vector3>();var cs=new List<Color>();var tex=new List<Vector2>();var uv1=new List<Vector4>();var inds=new List<int>();int removed=0;
 for(int a=0;a<ts.Length;a+=3){int ia=ts[a],ib=ts[a+1],ic=ts[a+2];var pa=mf.transform.TransformPoint(vs[ia]);var pb=mf.transform.TransformPoint(vs[ib]);var pc=mf.transform.TransformPoint(vs[ic]);bool near=Cut(pa)||Cut(pb)||Cut(pc)||Cut((pa+pb+pc)/3);int n=near?Mathf.Clamp(Mathf.CeilToInt(Mathf.Max(Vector3.Distance(pa,pb),Vector3.Distance(pa,pc))/.3f),1,48):1;
 void Triangle(Vector2 a,Vector2 b,Vector2 c){Vector3 At(Vector2 q)=>pa+(pb-pa)*q.x+(pc-pa)*q.y;if(Cut((At(a)+At(b)+At(c))/3)){removed++;return;}foreach(var q in new[]{a,b,c}){inds.Add(verts.Count);verts.Add(mf.transform.InverseTransformPoint(At(q)));cs.Add(colors.Length==vs.Length?colors[ia]+(colors[ib]-colors[ia])*q.x+(colors[ic]-colors[ia])*q.y:Color.white);tex.Add(uv.Length==vs.Length?uv[ia]+(uv[ib]-uv[ia])*q.x+(uv[ic]-uv[ia])*q.y:Vector2.zero);uv1.Add(u1.Count==vs.Length?u1[ia]+(u1[ib]-u1[ia])*q.x+(u1[ic]-u1[ia])*q.y:Vector4.zero);}}
 for(int j=0;j<n;j++)for(int k=0;k<n-j;k++){Triangle(new(j/(float)n,k/(float)n),new((j+1)/(float)n,k/(float)n),new(j/(float)n,(k+1)/(float)n));if(j+k<n-1)Triangle(new((j+1)/(float)n,k/(float)n),new((j+1)/(float)n,(k+1)/(float)n),new(j/(float)n,(k+1)/(float)n));}}
 if(removed==0)continue;var mesh=new Mesh{indexFormat=UnityEngine.Rendering.IndexFormat.UInt32};mesh.SetVertices(verts);mesh.SetTriangles(inds,0);mesh.SetColors(cs);mesh.SetUVs(0,tex);mesh.SetUVs(1,uv1);mesh=Store(mesh,"Local bore mouths "+mf.name);mf.sharedMesh=mesh;mf.GetComponent<MeshCollider>().sharedMesh=mesh;notes.Add(mf.name+" mouth triangles removed="+removed);}Physics.SyncTransforms();}
 static void Trees(){Func<Collider,bool> clear=c=>{var p=c.bounds.center;ridge.Project(p,out float rd);float s=drain.Project(p,out float dd);return rd<3.1f||dd<6.8f&&s>exit-9&&s<drain.Length-4&&c.bounds.max.y>drain.At(s,out _).y-3;};Func<Collider,bool> seat=c=>{ridge.Project(c.bounds.center,out float rd);return rd<17;};typeof(Racer.Editor.BackyardReverseAuthoring).GetMethod("Trees",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,new object[]{clear,seat});Physics.SyncTransforms();}
 static void Brush(){var centres=new List<Vector3>();for(float s=22;s<ridge.Length-22;s+=6){var p=ridge.At(s,out var f);var r=Vector3.Cross(Vector3.up,f).normalized;foreach(int sign in new[]{-1,1}){var q=p+r*8*sign;if(Protected(q))continue;q.y=Support(q);centres.Add(q);}}var g=new GameObject("Recoverable rough ridge undergrowth");g.transform.SetParent(root);var slow=g.AddComponent<ShortcutUndergrowth>();slow.centres=centres.ToArray();slow.radius=3.5f;slow.protectedMain=race.road;foreach(var p in centres){var bush=GameObject.CreatePrimitive(PrimitiveType.Sphere);bush.name="Rough low ridge scrub";bush.transform.SetParent(root);bush.transform.position=p+Vector3.up*.45f;bush.transform.localScale=new(2.3f,.9f,2);bush.GetComponent<Renderer>().sharedMaterial=grass;Object.DestroyImmediate(bush.GetComponent<Collider>());}}
 public static string Main(){if(Application.isPlaying||UnityEngine.SceneManagement.SceneManager.GetActiveScene().isDirty)throw new Exception("Saved edit mode required");Directory.CreateDirectory(F);Directory.CreateDirectory(D);AssetDatabase.Refresh();notes.Clear();serial=0;
 foreach(string scene in new[]{"DansBackyardReverse","DansBackyardForward"}){EditorSceneManager.OpenScene("Assets/Scenes/"+scene+".unity");var prior=GameObject.Find("Reverse optional forest shortcuts");var oldRidge=prior.GetComponentsInChildren<WoodlandRoute>().FirstOrDefault(b=>b.title.StartsWith("Abandoned"));Vector3[] old=oldRidge?oldRidge.points.ToArray():Newtonsoft.Json.Linq.JObject.Parse(File.ReadAllText("Docs/ReverseShortcuts/geometry.json"))["branches"].First(b=>(string)b["title"]=="Abandoned Logging Ridge")["points"].Select(p=>new Vector3((float)p["x"],(float)p["y"],(float)p["z"])).ToArray();Object.DestroyImmediate(prior);
 // Restore only the obsolete shortcut's portal cuts from their recorded source meshes.
 foreach(var row in Newtonsoft.Json.Linq.JArray.Parse(File.ReadAllText("Docs/ReverseShortcuts/original-terrain.json"))){var g=GameObject.Find((string)row["name"]);if(!g)continue;var mf=g.GetComponent<MeshFilter>();if(!mf||!AssetDatabase.GetAssetPath(mf.sharedMesh).Contains("ReverseShortcuts/Portal"))continue;var m=AssetDatabase.LoadAssetAtPath<Mesh>(AssetDatabase.GUIDToAssetPath((string)row["guid"]));if(!m)throw new Exception("Missing original terrain");mf.sharedMesh=m;g.GetComponent<MeshCollider>().sharedMesh=m;}
 root=new GameObject("Reverse optional forest shortcuts").transform;race=Object.FindAnyObjectByType<RaceDirector>();roads=Object.FindObjectsByType<RaceRoad>();Physics.SyncTransforms();earth=Mat("Weathered logging earth",new(.32f,.265f,.16f));grass=Mat("Natural moss and grass",new(.22f,.29f,.12f));concrete=Mat("Damp layered concrete",new(.33f,.37f,.35f));wood=Mat("Decaying timber",new(.24f,.17f,.10f));metal=Mat("Storm iron",new(.11f,.14f,.13f));water=Mat("Shallow reflective storm flow",new(.12f,.25f,.27f));gold=Mat("Optional gold",new(1,.7f,.15f));Ridge(old);Physics.SyncTransforms();Drain();TerrainPortals();Trees();Brush();
 if(scene.EndsWith("Reverse")){object P(Vector3 p)=>new{x=p.x,y=p.y,z=p.z};File.WriteAllText(D+"/geometry.json",Newtonsoft.Json.JsonConvert.SerializeObject(new{branches=new[]{ridge,drain}.Select(b=>new{b.title,b.entryRoad,b.exitRoad,b.Length,b.halfWidth,b.aiValidated,b.undergroundStart,b.undergroundEnd,points=b.points.Select(P)}),exit,lip,landing},Newtonsoft.Json.Formatting.Indented));}else{Object.DestroyImmediate(ridge);Object.DestroyImmediate(drain);}EditorSceneManager.MarkSceneDirty(root.gameObject.scene);EditorSceneManager.SaveScene(root.gameObject.scene);AssetDatabase.SaveAssets();notes.Add(scene+" saved");}
 File.WriteAllLines(D+"/authoring.txt",notes);EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");return string.Join("\n",notes);}
 public static string RepairPorts(){serial=800;notes.Clear();Vector3[] dp=null;foreach(string name in new[]{"DansBackyardReverse","DansBackyardForward"}){EditorSceneManager.OpenScene("Assets/Scenes/"+name+".unity");root=GameObject.Find("Reverse optional forest shortcuts").transform;roads=Object.FindObjectsByType<RaceRoad>();drain=root.GetComponentsInChildren<WoodlandRoute>().FirstOrDefault(b=>b.title.StartsWith("Storm"));bool temp=!drain;if(temp){drain=root.gameObject.AddComponent<WoodlandRoute>();drain.points=dp;}else dp=drain.points.ToArray();exit=drain.Project(new(114.3f,0,-66.1f),out _);Physics.SyncTransforms();TerrainPortals();if(temp)Object.DestroyImmediate(drain);
 foreach(var brush in root.GetComponentsInChildren<ShortcutUndergrowth>())brush.centres=brush.centres.Where(p=>{brush.protectedMain.Project(p,out float d);return d>=4.1f;}).ToArray();
 var mf=root.GetComponentsInChildren<MeshFilter>().First(m=>m.name=="Ground_Natural rolling ridge");var mesh=mf.sharedMesh;var vertices=mesh.vertices;for(int i=0;i<vertices.Length;i++)vertices[i].y-=.08f;mesh.vertices=vertices;mesh.RecalculateBounds();mesh.RecalculateNormals();mf.GetComponent<MeshCollider>().sharedMesh=null;mf.GetComponent<MeshCollider>().sharedMesh=mesh;EditorUtility.SetDirty(mesh);
 EditorSceneManager.MarkSceneDirty(root.gameObject.scene);EditorSceneManager.SaveScene(root.gameObject.scene);AssetDatabase.SaveAssets();}File.WriteAllLines(D+"/mouth-correction.txt",notes);EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");return "Lower gully face opened through final sidewall; ridge overlap removed";} public static string RepairRidgeSupports(){serial=900;foreach(string scene in new[]{"DansBackyardReverse","DansBackyardForward"}){EditorSceneManager.OpenScene("Assets/Scenes/"+scene+".unity");root=GameObject.Find("Reverse optional forest shortcuts").transform;race=Object.FindAnyObjectByType<RaceDirector>();roads=Object.FindObjectsByType<RaceRoad>();var oldBranch=root.GetComponentsInChildren<WoodlandRoute>().FirstOrDefault(b=>b.title.StartsWith("Abandoned"));var old=oldBranch?oldBranch.points.ToArray():Newtonsoft.Json.Linq.JObject.Parse(File.ReadAllText(D+"/geometry.json"))["branches"].First(b=>(string)b["title"]=="Abandoned Logging Ridge")["points"].Select(p=>new Vector3((float)p["x"],(float)p["y"],(float)p["z"])).ToArray();
 foreach(var t in root.Cast<Transform>().Where(t=>t.name=="Abandoned Logging Ridge"||t.name=="Ground_Natural rolling ridge"||t.name=="Ground_Worn logging crest"||t.name=="Grass intrusion"||t.name=="Abandoned fallen timber"||t.name=="Weathered stump"||t.name=="Rough low ridge scrub"||t.name=="Recoverable rough ridge undergrowth"||t.name=="Optional gold guidance"&&t.position.x>275).ToArray())Object.DestroyImmediate(t.gameObject);
 earth=AssetDatabase.LoadAssetAtPath<Material>(F+"/Weathered logging earth.mat");grass=AssetDatabase.LoadAssetAtPath<Material>(F+"/Natural moss and grass.mat");wood=AssetDatabase.LoadAssetAtPath<Material>(F+"/Decaying timber.mat");gold=AssetDatabase.LoadAssetAtPath<Material>(F+"/Optional gold.mat");Physics.SyncTransforms();Ridge(old);Physics.SyncTransforms();Brush();
 var gate=root.GetComponent<ReverseShortcutWorldState>().ridgeGate;var p=ridge.At(14,out var f);gate.transform.SetPositionAndRotation(p+Vector3.up*.9f,Quaternion.LookRotation(f));
 typeof(Racer.Editor.BackyardReverseAuthoring).GetMethod("Trees",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,new object[]{(Func<Collider,bool>)(c=>false),(Func<Collider,bool>)(c=>{ridge.Project(c.bounds.center,out float d);return d<17;})});
 if(scene.EndsWith("Forward"))Object.DestroyImmediate(ridge);else ridge.gameObject.AddComponent<ReverseShortcutGuidance>().lookAhead=7;
 EditorSceneManager.MarkSceneDirty(root.gameObject.scene);EditorSceneManager.SaveScene(root.gameObject.scene);AssetDatabase.SaveAssets();}EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");File.WriteAllText(D+"/ridge-support-correction.txt","Ridge elevation tapers to original ground near every protected road; affected trees reseated.");return "Preserved Forward crossing by locally tapering the ridge";}}


