EditorApplication.delayCall+=()=>{var mode=Physics.simulationMode;float volume=AudioListener.volume;try{
UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");AudioListener.volume=0;Physics.simulationMode=SimulationMode.Script;
var race=UnityEngine.Object.FindAnyObjectByType<Racer.RaceDirector>();var car=race.vehicle;var course=race.GetComponent<Racer.BackyardForwardCourse>();
typeof(Racer.VehicleSurfaceContacts).GetMethod("Reset",System.Reflection.BindingFlags.Static|System.Reflection.BindingFlags.NonPublic).Invoke(null,null);typeof(Racer.ArcadeVehicle).GetMethod("Awake",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(car,null);(car.GetComponent<Racer.VehicleConfiguration>()??car.gameObject.AddComponent<Racer.VehicleConfiguration>()).Apply("moto");
foreach(var body in UnityEngine.Object.FindObjectsByType<Rigidbody>())if(body!=car.Body)body.gameObject.SetActive(false);
float Ground(Vector3 p)=>Physics.RaycastAll(new Vector3(p.x,250,p.z),Vector3.down,500,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")||h.collider.name=="Decorative Road pavement").OrderBy(h=>h.distance).First().point.y;
var results=new List<string>();var log=new List<string>{"case,time,x,y,z,speed,grounded"};
void Place(Vector3 p,Vector3 axis,float speed){p.y=Ground(p)+.55f;car.Body.position=p;car.Body.rotation=Quaternion.LookRotation(axis);car.transform.SetPositionAndRotation(p,car.Body.rotation);car.Body.linearVelocity=Vector3.zero;car.Body.angularVelocity=Vector3.zero;car.Body.isKinematic=false;car.ClearSteering();Physics.SyncTransforms();for(int settle=0;settle<60;settle++){car.Simulate(0,0,0,.02f);Physics.Simulate(.02f);}var tangent=axis+Vector3.up*((Ground(p+axis)-Ground(p-axis))*.5f);car.Body.linearVelocity=tangent.normalized*speed;Physics.SyncTransforms();}
foreach(var profile in new[]{"moto","atv"}) for(int j=2;j<3;j++){car.GetComponent<Racer.VehicleConfiguration>().Apply(profile);var lip=course.flightStarts[j];var axis=course.flightDirections[j];var approach=race.road.At(course.launchStations[j]-45,out var approachAxis);Place(approach,Vector3.ProjectOnPlane(approachAxis,Vector3.up).normalized,28);float airborne=0,longest=0,minimum=100;bool landed=false,entered=false,shortLanding=false;float distance=Vector3.Dot(race.road.At(course.landingStations[j],out _)-lip,axis);
for(int frame=0;frame<650;frame++){float along=Vector3.Dot(car.Body.position-lip,axis);if(along>-3&&along<3)minimum=Math.Min(minimum,Vector3.Dot(car.Body.linearVelocity,axis));if(along>0&&car.GroundedWheels==0){airborne+=.02f;entered=true;}else{longest=Math.Max(longest,airborne);airborne=0;}if(entered&&along>5&&along<distance-6&&car.GroundedWheels>=2)shortLanding=true;if(!shortLanding&&along>distance-2&&car.GroundedWheels>=2&&entered&&Math.Abs(Vector3.Dot(car.Body.position-lip,Vector3.Cross(Vector3.up,axis)))<4&&longest>1.2f){landed=true;break;}float speed=car.ForwardSpeed;var target=along>=-25?lip+axis*(along+12):race.road.At(race.road.Project(car.Body.position,out _)+12,out _);var delta=Quaternion.Inverse(Quaternion.LookRotation(Vector3.ProjectOnPlane(car.transform.forward,Vector3.up)))*(target-car.Body.position);float angle=Mathf.Atan2(delta.x,delta.z);float steer=Mathf.Clamp(Mathf.Atan(2*car.wheelbase*Mathf.Sin(angle)/12)/(Mathf.Lerp(car.slowSteerAngle,car.fastSteerAngle,Mathf.Clamp01(speed/car.topSpeed))*Mathf.Deg2Rad),-1,1);car.Simulate(speed<32?.8f:0,speed>34?.15f:0,steer,.02f);Physics.Simulate(.02f);Physics.SyncTransforms();if(frame%5==0){var p=car.Body.position;log.Add($"{profile}-jump{j+1},{frame*.02f:F2},{p.x:F3},{p.y:F3},{p.z:F3},{speed:F2},{car.GroundedWheels}");}}
results.Add((landed?"PASS ":"FAIL ")+profile+" major jump "+(j+1)+$" ordinary motor physics; grounded far-side landing={landed}, air={longest:F2}s, launch speed minimum={minimum:F2}m/s, final={car.Body.position:F2}");}
System.IO.File.WriteAllLines("Docs/BackyardReverse/pool-feature-drive.txt",results);System.IO.File.WriteAllLines("Docs/BackyardReverse/pool-feature-pace.csv",log);
}catch(Exception e){System.IO.File.WriteAllText("Docs/BackyardReverse/pool-feature-error.txt",e.ToString());}finally{Physics.simulationMode=mode;AudioListener.volume=volume;UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");}};return "Scheduled two pool-house motorcycle/ATV Reverse jump drives";

