EditorApplication.delayCall+=()=>{var mode=Physics.simulationMode;float volume=AudioListener.volume;try{
UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/StreetLoopGreybox.unity");AudioListener.volume=0;Physics.simulationMode=SimulationMode.Script;
var car=UnityEngine.Object.FindAnyObjectByType<Racer.RaceDirector>().vehicle;
typeof(Racer.ArcadeVehicle).GetMethod("Awake",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(car,null);(car.GetComponent<Racer.VehicleConfiguration>()??car.gameObject.AddComponent<Racer.VehicleConfiguration>()).Apply("moto");
foreach(var body in UnityEngine.Object.FindObjectsByType<Rigidbody>())if(body!=car.Body)body.gameObject.SetActive(false);
var p=new Vector3(478.3f,100,10);var h=Physics.RaycastAll(p,Vector3.down,60,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground")).OrderBy(h=>h.distance).First();p.y=h.point.y+.55f;car.Body.position=p;car.Body.rotation=Quaternion.LookRotation(Vector3.back);car.transform.SetPositionAndRotation(p,car.Body.rotation);car.Body.linearVelocity=Vector3.back*8;car.Body.angularVelocity=Vector3.zero;Physics.SyncTransforms();
var rows=new List<string>();float air=0,maxAir=0,min=100;bool reached=false;
for(int frame=0;frame<350;frame++){float speed=car.ForwardSpeed;if(frame>20)min=Math.Min(min,speed);if(car.GroundedWheels==0)air+=.02f;else air=0;maxAir=Math.Max(maxAir,air);if(frame%10==0)rows.Add($"{frame*.02f:F2} position={car.Body.position:F3} speed={speed:F3} grounded={car.GroundedWheels}");if(car.Body.position.z< -12){reached=true;break;}car.Simulate(speed<8?.35f:0,speed>10?.15f:0,0,.02f);Physics.Simulate(.02f);Physics.SyncTransforms();}
rows.Insert(0,$"Reached={reached}; minimum speed={min:F3}; max continuous air={maxAir:F3}; ordinary 0.02-second motorcycle physics steps across reported driveway side edge.");System.IO.File.WriteAllLines("Docs/Backyard/kyle-drive-"+(System.IO.File.Exists("Docs/Backyard/kyle-fixed.txt")?"after":"before")+".txt",rows);
}catch(Exception e){System.IO.File.WriteAllText("Docs/Backyard/kyle-drive-error.txt",e.ToString());}finally{Physics.simulationMode=mode;AudioListener.volume=volume;UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/StreetLoopGreybox.unity");}};return "Scheduled bounded Kyle driveway crossing";
