EditorApplication.delayCall += () => {var mode=Physics.simulationMode;float volume=AudioListener.volume;try {
UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/StreetLoopGreybox.unity");AudioListener.volume=0;Physics.simulationMode=SimulationMode.Script;
var race=UnityEngine.Object.FindAnyObjectByType<Racer.RaceDirector>();var car=race.vehicle;var drive=GameObject.Find("House 3 valley driveway").GetComponent<Racer.RaceRoad>();
typeof(Racer.ArcadeVehicle).GetMethod("Awake",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(car,null);(car.GetComponent<Racer.VehicleConfiguration>()??car.gameObject.AddComponent<Racer.VehicleConfiguration>()).Apply("moto");
foreach(var body in UnityEngine.Object.FindObjectsByType<Rigidbody>())if(body!=car.Body)body.gameObject.SetActive(false);
var start=drive.points[0];var forward=Vector3.ProjectOnPlane(drive.points[1]-start,Vector3.up).normalized;car.Body.position=start+Vector3.up*.65f;car.Body.rotation=Quaternion.LookRotation(forward);car.transform.SetPositionAndRotation(car.Body.position,car.Body.rotation);car.Body.linearVelocity=forward*5;car.Body.angularVelocity=Vector3.zero;Physics.SyncTransforms();
float air=0,maxAir=0,minSpeed=100,maxRise=0;var samples=new List<string>();bool passed=false;
for(int frame=0;frame<300;frame++){float progress=Vector3.Dot(car.Body.position-start,forward);float speed=car.Body.linearVelocity.magnitude;if(frame>15){minSpeed=Math.Min(minSpeed,speed);maxRise=Math.Max(maxRise,car.Body.position.y-start.y);}if(car.GroundedWheels==0)air+=.02f;else air=0;maxAir=Math.Max(maxAir,air);if(frame%10==0)samples.Add($"{frame*.02f:F2}s position={car.Body.position:F3} speed={speed:F3} grounded={car.GroundedWheels}");if(progress>12){passed=true;break;}car.Simulate(speed<6?.35f:0,speed>8?.2f:0,0,.02f);Physics.Simulate(.02f);Physics.SyncTransforms();}
bool ok=passed&&minSpeed>2&&maxAir<.5f; samples.Insert(0,$"{(ok?"PASS":"FAIL")} One motorcycle drive from main road through current driveway entrance. Reached 12m={passed}; min speed={minSpeed:F3}m/s; max continuous air={maxAir:F3}s; max rise={maxRise:F3}m. Original collision meshes and vehicle settings unchanged; 0.02s ordinary input/physics steps.");System.IO.File.WriteAllLines("Docs/McFaddenEntrance/drive-through.txt",samples);
}catch(Exception e){System.IO.File.WriteAllText("Docs/McFaddenEntrance/drive-error.txt",e.ToString());}finally{Physics.simulationMode=mode;AudioListener.volume=volume;UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/StreetLoopGreybox.unity");}};return "Scheduled one muted entrance drive-through";
