EditorApplication.delayCall+=()=>{var mode=Physics.simulationMode;float volume=AudioListener.volume;try{
UnityEditor.SceneManagement.EditorSceneManager.OpenScene(Racer.Editor.BackyardForwardAuthoring.ScenePath);AudioListener.volume=0;Physics.simulationMode=SimulationMode.Script;
var race=UnityEngine.Object.FindAnyObjectByType<Racer.RaceDirector>();var car=race.vehicle;var course=race.GetComponent<Racer.BackyardForwardCourse>();
typeof(Racer.VehicleSurfaceContacts).GetMethod("Reset",System.Reflection.BindingFlags.Static|System.Reflection.BindingFlags.NonPublic).Invoke(null,null);typeof(Racer.ArcadeVehicle).GetMethod("Awake",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(car,null);(car.GetComponent<Racer.VehicleConfiguration>()??car.gameObject.AddComponent<Racer.VehicleConfiguration>()).Apply("moto");
foreach(var body in UnityEngine.Object.FindObjectsByType<Rigidbody>())if(body!=car.Body)body.gameObject.SetActive(false);
float Ground(Vector3 p)=>Physics.RaycastAll(new Vector3(p.x,250,p.z),Vector3.down,500,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")||h.collider.name=="Decorative Road pavement").OrderBy(h=>h.distance).First().point.y;
var results=new List<string>();var log=new List<string>{"case,time,x,y,z,speed,grounded"};
void Place(Vector3 p,Vector3 axis,float speed){p.y=Ground(p)+.55f;car.Body.position=p;car.Body.rotation=Quaternion.LookRotation(axis);car.transform.SetPositionAndRotation(p,car.Body.rotation);car.Body.linearVelocity=Vector3.zero;car.Body.angularVelocity=Vector3.zero;car.Body.isKinematic=false;car.ClearSteering();Physics.SyncTransforms();for(int settle=0;settle<60;settle++){car.Simulate(0,0,0,.02f);Physics.Simulate(.02f);}var tangent=axis+Vector3.up*((Ground(p+axis)-Ground(p-axis))*.5f);car.Body.linearVelocity=tangent.normalized*speed;Physics.SyncTransforms();}
for(int j=0;j<3;j++){var lip=course.flightStarts[j];var axis=course.flightDirections[j];Place(lip-axis*38,axis,32);float airborne=0,longest=0,minimum=100;bool landed=false,entered=false,shortLanding=false;float distance=Vector3.Dot(race.road.At(course.landingStations[j],out _)-lip,axis);
for(int frame=0;frame<650;frame++){float along=Vector3.Dot(car.Body.position-lip,axis);if(along>-3&&along<3)minimum=Math.Min(minimum,Vector3.Dot(car.Body.linearVelocity,axis));if(along>0&&car.GroundedWheels==0){airborne+=.02f;entered=true;}else{longest=Math.Max(longest,airborne);airborne=0;}if(entered&&along>5&&along<distance-6&&car.GroundedWheels>=2)shortLanding=true;if(!shortLanding&&along>distance-2&&car.GroundedWheels>=2&&entered&&Math.Abs(Vector3.Dot(car.Body.position-lip,Vector3.Cross(Vector3.up,axis)))<4&&longest>1.2f){landed=true;break;}float speed=car.ForwardSpeed;var target=lip+axis*(along+12);var delta=Quaternion.Inverse(Quaternion.LookRotation(Vector3.ProjectOnPlane(car.transform.forward,Vector3.up)))*(target-car.Body.position);float angle=Mathf.Atan2(delta.x,delta.z);float steer=Mathf.Clamp(Mathf.Atan(2*car.wheelbase*Mathf.Sin(angle)/12)/(Mathf.Lerp(car.slowSteerAngle,car.fastSteerAngle,Mathf.Clamp01(speed/car.topSpeed))*Mathf.Deg2Rad),-1,1);car.Simulate(speed<32?.8f:0,speed>34?.15f:0,steer,.02f);Physics.Simulate(.02f);Physics.SyncTransforms();if(frame%5==0){var p=car.Body.position;log.Add($"jump{j+1},{frame*.02f:F2},{p.x:F3},{p.y:F3},{p.z:F3},{speed:F2},{car.GroundedWheels}");}}
results.Add((landed?"PASS ":"FAIL ")+"major jump "+(j+1)+$" ordinary motorcycle physics; grounded far-side landing={landed}, air={longest:F2}s, launch speed minimum={minimum:F2}m/s, final={car.Body.position:F2}");}
// Deliberately miss the dump at 8m/s, then drive along its floor and out the far slope.
{var axis=course.flightDirections[0];var lip=course.flightStarts[0];Place(lip-axis*2,axis,8);float minY=999;bool escaped=false;for(int frame=0;frame<1250;frame++){var p=car.Body.position;minY=Math.Min(minY,p.y);float along=Vector3.Dot(p-lip,axis);if(along>55&&car.GroundedWheels>=2){escaped=true;break;}float speed=car.ForwardSpeed;car.Simulate(speed<9?.8f:0,speed>11?.3f:0,0,.02f);Physics.Simulate(.02f);Physics.SyncTransforms();if(frame%10==0)log.Add($"dump-miss,{frame*.02f:F2},{p.x:F3},{p.y:F3},{p.z:F3},{speed:F2},{car.GroundedWheels}");}results.Add((escaped&&minY<lip.y-4?"PASS ":"FAIL ")+"failed dump jump falls inside and drives out, no reset; minimumY="+minY+" final="+car.Body.position);}
// Start in the ravine bottom and drive to its shallow southern mouth.
{var at=new Vector3(96.1f,0,-108.6f);var axis=new Vector3(-11.6f/169.3f,0,-1).normalized;Place(at,axis,7);bool escaped=false;float maxSlope=0;for(int frame=0;frame<1200;frame++){var p=car.Body.position;if(p.z<-173&&car.GroundedWheels>=2){escaped=true;break;}float speed=car.ForwardSpeed;car.Simulate(speed<9?.85f:0,speed>11?.3f:0,0,.02f);Physics.Simulate(.02f);Physics.SyncTransforms();if(frame%10==0)log.Add($"gully-escape,{frame*.02f:F2},{p.x:F3},{p.y:F3},{p.z:F3},{speed:F2},{car.GroundedWheels}");}results.Add((escaped?"PASS ":"FAIL ")+"ravine bottom to shallow southern escape, ordinary pedals and no reset; final="+car.Body.position);}
System.IO.File.WriteAllLines("Docs/BackyardForward/feature-drive.txt",results);System.IO.File.WriteAllLines("Docs/BackyardForward/feature-pace.csv",log);
}catch(Exception e){System.IO.File.WriteAllText("Docs/BackyardForward/feature-error.txt",e.ToString());}finally{Physics.simulationMode=mode;AudioListener.volume=volume;UnityEditor.SceneManagement.EditorSceneManager.OpenScene(Racer.Editor.BackyardForwardAuthoring.ScenePath);}};return "Scheduled three jump crossings and two recoverable failure-space drives";
