UnityEditor.EditorApplication.delayCall+=()=>{var mode=Physics.simulationMode;float volume=AudioListener.volume;try{
UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");AudioListener.volume=0;Physics.simulationMode=SimulationMode.Script;
var race=UnityEngine.Object.FindAnyObjectByType<Racer.RaceDirector>();var car=race.vehicle;
typeof(Racer.VehicleSurfaceContacts).GetMethod("Reset",System.Reflection.BindingFlags.Static|System.Reflection.BindingFlags.NonPublic).Invoke(null,null);typeof(Racer.ArcadeVehicle).GetMethod("Awake",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(car,null);var config=car.GetComponent<Racer.VehicleConfiguration>()??car.gameObject.AddComponent<Racer.VehicleConfiguration>();
foreach(var body in UnityEngine.Object.FindObjectsByType<Rigidbody>())if(body!=car.Body)body.gameObject.SetActive(false);
var results=new List<string>();var log=new List<string>{"case,time,s,x,y,z,speed,grounded"};
foreach(var profile in new[]{"moto","atv"})foreach(var b in UnityEngine.Object.FindObjectsByType<Racer.WoodlandRoute>()){
float lipS=b.Project(new Vector3(95.8f,0,-24),out _),landS=b.Project(new Vector3(80.5f,0,-66),out _);config.Apply(profile);var p=b.At(1,out var axis);car.Body.position=p+Vector3.up*.6f;car.Body.rotation=Quaternion.LookRotation(Vector3.ProjectOnPlane(axis,Vector3.up));car.transform.SetPositionAndRotation(car.Body.position,car.Body.rotation);car.Body.linearVelocity=car.Body.angularVelocity=Vector3.zero;car.Body.isKinematic=false;car.ClearSteering();Physics.SyncTransforms();for(int j=0;j<50;j++){car.Simulate(0,0,0,.02f);Physics.Simulate(.02f);}car.Body.linearVelocity=axis*22;Physics.SyncTransforms();
float air=0,longest=0,maxProgress=0,minimum=100;bool completed=false,landed=false;int frame=0;
for(;frame<1250;frame++){float s=b.Project(car.Body.position,out float lateral);maxProgress=Mathf.Max(maxProgress,s);if(car.GroundedWheels==0)air+=.02f;else{longest=Mathf.Max(longest,air);air=0;if(b.title.StartsWith("Storm")&&s>landS-7&&longest>1)landed=true;}race.road.Project(car.Body.position,out float mainLateral);if(s>b.Length-4&&mainLateral<5&&car.GroundedWheels>=2){completed=true;break;}if(s>lipS-6&&s<lipS+2)minimum=Mathf.Min(minimum,car.ForwardSpeed);
float look=b.title.StartsWith("Storm")&&s<b.undergroundEnd?5:6;var target=b.At(s+look,out _);if(b.title.StartsWith("Storm")&&s>lipS-16&&(s<landS-6||car.GroundedWheels==0&&s<landS+12)){var lip=b.At(lipS,out var flight);target=lip+Vector3.ProjectOnPlane(flight,Vector3.up).normalized*(Vector3.Dot(car.Body.position-lip,Vector3.ProjectOnPlane(flight,Vector3.up).normalized)+12);}
if(s>b.Length-15)target=race.road.At(race.road.Project(car.Body.position,out _)+look,out _);var delta=Quaternion.Inverse(Quaternion.LookRotation(Vector3.ProjectOnPlane(car.transform.forward,Vector3.up)))*(target-car.Body.position);float angle=Mathf.Atan2(delta.x,delta.z);float speed=car.ForwardSpeed;float steer=Mathf.Clamp(Mathf.Atan(2*car.wheelbase*Mathf.Sin(angle)/look)/(Mathf.Lerp(car.slowSteerAngle,car.fastSteerAngle,Mathf.Clamp01(speed/car.topSpeed))*Mathf.Deg2Rad),-1,1);float desired=b.title.StartsWith("Storm")?(s<b.undergroundEnd?22:30):24;car.Simulate(speed<desired?.85f:0,speed>desired+2?.25f:0,steer,.02f);Physics.Simulate(.02f);Physics.SyncTransforms();if(frame%5==0){p=car.Body.position;log.Add($"{profile}-{b.title},{frame*.02f:F2},{s:F2},{p.x:F3},{p.y:F3},{p.z:F3},{speed:F2},{car.GroundedWheels}");}}
results.Add((completed?"PASS ":"FAIL ")+profile+" "+b.title+$" time={frame*.02f:F2} progress={maxProgress:F1}/{b.Length:F1} air={longest:F2} landing={landed} lipSpeed={minimum:F2} final={car.Body.position:F2}");
}
System.IO.File.WriteAllLines("Docs/ReverseShortcuts/driving.txt",results);System.IO.File.WriteAllLines("Docs/ReverseShortcuts/driving.csv",log);
}catch(Exception e){System.IO.File.WriteAllText("Docs/ReverseShortcuts/driving-error.txt",e.ToString());}finally{Physics.simulationMode=mode;AudioListener.volume=volume;UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");}};return "Four targeted ordinary-physics shortcut drives";
