using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class EaseReverseCorrectionProfiles {
 public static string Main(){if(Application.isPlaying)throw new Exception("Edit mode required");var evidence=Newtonsoft.Json.Linq.JObject.Parse(File.ReadAllText("Docs/ReverseCorrection/geometry.json"));foreach(string scene in new[]{"DansBackyardReverse","DansBackyardForward"}){EditorSceneManager.OpenScene("Assets/Scenes/"+scene+".unity");var root=GameObject.Find("Reverse optional forest shortcuts").transform;var probes=new GameObject("Temporary profile samples"){hideFlags=HideFlags.HideAndDontSave};
 WoodlandRoute Probe(string title){var b=probes.AddComponent<WoodlandRoute>();b.points=evidence["branches"].First(x=>(string)x["title"]==title)["points"].Select(p=>new Vector3((float)p["x"],(float)p["y"],(float)p["z"])).ToArray();return b;}
 var ridge=Probe("Abandoned Logging Ridge");var drain=Probe("Storm Drain / Gully Jump");float y0=ridge.At(7,out _).y,y1=ridge.At(36,out _).y;float ramp=drain.Project(new(106,0,-66.1f),out _),lip=drain.Project(new(94,0,-66.1f),out _),floor=drain.At(ramp,out _).y;
 float RidgeDelta(float s){if(s<=7||s>=36)return 0;float u=(s-7)/29;float h=Mathf.Lerp(y0,y1,u*u*(3-2*u));return h-ridge.At(s,out _).y;}
 float RampDelta(float s){if(s<ramp||s>lip)return 0;float u=(s-ramp)/(lip-ramp);float h=floor+6*(-2*u*u*u+3*u*u)+(.45f*(lip-ramp))*(u*u*u-u*u);return h-drain.At(s,out _).y;}
 foreach(var mf in root.GetComponentsInChildren<MeshFilter>().Where(m=>m.name=="Ground_Natural rolling ridge"||m.name=="Ground_Worn logging crest"||m.name=="Grass intrusion"||m.name=="Broken logging wheel paths"||m.name=="Ground_Gully continuous curved takeoff")){bool gully=mf.name.Contains("Gully");var b=gully?drain:ridge;var mesh=mf.sharedMesh;var v=mesh.vertices;for(int i=0;i<v.Length;i++){var p=mf.transform.TransformPoint(v[i]);float s=b.Project(p,out float side);float weight=1-Mathf.SmoothStep(0,1,Mathf.InverseLerp(gully?4.2f:2.4f,gully?13.2f:16,side));p.y+=(gully?RampDelta(s):RidgeDelta(s))*weight;v[i]=mf.transform.InverseTransformPoint(p);}mesh.vertices=v;mesh.RecalculateNormals();mesh.RecalculateBounds();EditorUtility.SetDirty(mesh);if(mf.TryGetComponent<MeshCollider>(out var c)){c.sharedMesh=null;c.sharedMesh=mesh;}}
 foreach(var b in root.GetComponentsInChildren<WoodlandRoute>()){bool gully=b.title.StartsWith("Storm");var old=gully?drain:ridge;var p=b.points.ToArray();for(int i=0;i<p.Length;i++){float s=old.Project(p[i],out _);p[i].y+=gully?RampDelta(s):RidgeDelta(s);}b.points=p;typeof(WoodlandRoute).GetField("lengths",BindingFlags.Instance|BindingFlags.NonPublic).SetValue(b,null);EditorUtility.SetDirty(b);}
 foreach(var arrow in root.Cast<Transform>().Where(t=>t.name=="Optional gold guidance")){float s=(arrow.position.x>275?ridge:drain).Project(arrow.position,out _);arrow.position+=Vector3.up*(arrow.position.x>275?RidgeDelta(s):RampDelta(s));}
 Physics.SyncTransforms();typeof(Racer.Editor.BackyardReverseAuthoring).GetMethod("Trees",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,new object[]{(Func<Collider,bool>)(c=>false),(Func<Collider,bool>)(c=>{ridge.Project(c.bounds.center,out float rd);float ds=drain.Project(c.bounds.center,out float dd);return rd<17||dd<14&&ds>ramp-4&&ds<lip+4;})});
 float Ground(Vector3 p)=>Physics.RaycastAll(new(p.x,250,p.z),Vector3.down,500,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).Max(h=>h.point.y);
 foreach(var c in root.GetComponentsInChildren<BoxCollider>().Where(c=>c.name=="Abandoned fallen timber"||c.name=="Weathered stump")){c.transform.position+=Vector3.up*(Ground(c.bounds.center)-c.bounds.min.y);}foreach(var t in root.Cast<Transform>().Where(t=>t.name=="Rough low ridge scrub")){var p=t.position;p.y=Ground(p);t.position=p;}foreach(var brush in root.GetComponentsInChildren<ShortcutUndergrowth>())brush.centres=brush.centres.Select(p=>new Vector3(p.x,Ground(p),p.z)).ToArray();var gate=root.GetComponent<ReverseShortcutWorldState>().ridgeGate;var gp=ridge.At(14,out var gf);gp.y+=RidgeDelta(14);gate.transform.SetPositionAndRotation(gp+Vector3.up*.9f,Quaternion.LookRotation(Vector3.ProjectOnPlane(gf,Vector3.up)));
 Object.DestroyImmediate(probes);EditorSceneManager.MarkSceneDirty(root.gameObject.scene);EditorSceneManager.SaveScene(root.gameObject.scene);AssetDatabase.SaveAssets();}EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");File.WriteAllText("Docs/ReverseCorrection/profile-correction.txt","Ridge initial climb spread across stations 7-36 with a smooth crest. Gully takeoff retains 6m rise but eases its terminal grade to 0.45 instead of 1.0, targeting the existing west-bank landing. Only local surfaces/guidance changed; dependent vegetation reseated.");return "Two measured launch-profile failures corrected locally";}
}
