using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class EdgeCaveRestore {
 [Serializable]public class Line{public Vector3[] points;} static readonly BindingFlags F=BindingFlags.NonPublic|BindingFlags.Instance;static List<string> results=new(),log=new();
 public static string Main(){EditorApplication.delayCall+=()=>Run(true);return "Scheduled motorcycle/ATV local physics checks";}
 public static string Cave(){EditorApplication.delayCall+=()=>Run(true);return "Scheduled Forward cave motorcycle/ATV checks";}
 static void Run(bool cave){var mode=Physics.simulationMode;float volume=AudioListener.volume;try{EditorSceneManager.OpenScene("Assets/Scenes/"+(cave?"LakeWoods":"DansBackyardReverse")+".unity");AudioListener.volume=0;Physics.simulationMode=SimulationMode.Script;var race=Object.FindAnyObjectByType<RaceDirector>();var car=race.vehicle;typeof(VehicleSurfaceContacts).GetMethod("Reset",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,null);typeof(ArcadeVehicle).GetMethod("Awake",F).Invoke(car,null);car.enabled=false;var config=car.GetComponent<VehicleConfiguration>()??car.gameObject.AddComponent<VehicleConfiguration>();foreach(var body in Object.FindObjectsByType<Rigidbody>())if(body!=car.Body)body.gameObject.SetActive(false);var branches=Object.FindObjectsByType<WoodlandRoute>();log.Add("case,time,station,lateral,x,y,z,speed,wheels,up,vertical,angular");
 float Support(Vector3 p){return Physics.RaycastAll(p+Vector3.up*3,Vector3.down,12,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")&&!h.collider.transform.IsChildOf(car.transform)).Select(h=>h.point.y).DefaultIfEmpty(p.y).Max();}
 void Case(WoodlandRoute b,float start,float finish,float speed,float offset,string name){config.Apply(name.StartsWith("moto")?"moto":"atv");var p=b.At(start,out var f);f=Vector3.ProjectOnPlane(f,Vector3.up).normalized;p+=Vector3.Cross(Vector3.up,f)*offset;p.y=Support(p)+.55f;car.Body.isKinematic=false;car.Body.position=p;car.Body.rotation=Quaternion.LookRotation(f);car.transform.SetPositionAndRotation(p,car.Body.rotation);car.Body.linearVelocity=car.Body.angularVelocity=Vector3.zero;car.ClearSteering();Physics.SyncTransforms();for(int i=0;i<45;i++){car.Simulate(0,0,0,.02f);Physics.Simulate(.02f);}car.Body.linearVelocity=(f+Vector3.up*((Support(p+f)-Support(p-f))*.5f)).normalized*speed;float minUp=1,maxAir=0,air=0,maxSide=0,minSpeed=100,maxAngular=0,maxVertical=0;bool finished=false;int frames=Mathf.CeilToInt((finish-start)/speed/.02f*2)+200;
 for(int i=0;i<frames;i++){float s=b.Project(car.Body.position,out float lateral);minUp=Math.Min(minUp,car.transform.up.y);maxSide=Math.Max(maxSide,lateral);maxAngular=Math.Max(maxAngular,car.Body.angularVelocity.magnitude);maxVertical=Math.Max(maxVertical,car.Body.linearVelocity.y);minSpeed=Math.Min(minSpeed,car.ForwardSpeed);if(car.GroundedWheels==0){air+=.02f;maxAir=Math.Max(maxAir,air);}else air=0;if(s>finish&&car.GroundedWheels>=2){finished=true;break;}if(car.transform.up.y<.25f||car.Body.position.y<b.At(s,out _).y-12)break;float look=cave?10:7;var target=b.At(s+look,out var tf)+Vector3.Cross(Vector3.up,tf).normalized*offset;var delta=Quaternion.Inverse(Quaternion.LookRotation(Vector3.ProjectOnPlane(car.transform.forward,Vector3.up)))*(target-car.Body.position);float angle=Mathf.Atan2(delta.x,delta.z),steer=Mathf.Clamp(Mathf.Atan(2*car.wheelbase*Mathf.Sin(angle)/look)/(Mathf.Lerp(car.slowSteerAngle,car.fastSteerAngle,Mathf.Clamp01(car.ForwardSpeed/car.topSpeed))*Mathf.Deg2Rad),-1,1);car.Simulate(car.ForwardSpeed<speed?1:0,car.ForwardSpeed>speed+1?.35f:0,steer,.02f);Physics.Simulate(.02f);Physics.SyncTransforms();if(i%5==0){p=car.Body.position;log.Add($"{name},{i*.02f:F2},{s:F2},{lateral:F3},{p.x:F3},{p.y:F3},{p.z:F3},{car.ForwardSpeed:F2},{car.GroundedWheels},{car.transform.up.y:F3},{car.Body.linearVelocity.y:F3},{car.Body.angularVelocity.magnitude:F3}");}}
 results.Add((minSpeed<12?"PASS ":"FAIL ")+name+$" complete={finished} minUp={minUp:F3} maxSide={maxSide:F3} maxAir={maxAir:F2} minSpeed={minSpeed:F2} maxAngular={maxAngular:F2} maxUpward={maxVertical:F2} final={car.Body.position:F2}");File.WriteAllLines("Docs/CaveRestore/"+(cave?"edge":"local")+"-driving.txt",results);}
 foreach(var rock in Object.FindObjectsByType<MeshCollider>().Where(c=>new[]{"Grounded cave edge boulder 6","Grounded cave edge boulder 23","Grounded cave edge boulder 40"}.Contains(c.name))){var temp=new GameObject("Temporary original line");var old=temp.AddComponent<WoodlandRoute>();old.points=Newtonsoft.Json.JsonConvert.DeserializeObject<Line>(File.ReadAllText("Docs/FinalTwo/original-cave-line.json")).points;float s=old.Project(rock.bounds.center,out _);var p=old.At(s,out var f);float x=Vector3.Dot(rock.bounds.center-p,Vector3.Cross(Vector3.up,f).normalized);Case(old,s-13,s+9,24,x-Mathf.Sign(x)*.65f,"atv-edge-"+rock.name);Object.DestroyImmediate(temp);} File.WriteAllLines("Docs/CaveRestore/"+(cave?"edge":"local")+"-driving.csv",log);File.WriteAllText("Docs/CaveRestore/"+(cave?"edge":"local")+"-done.txt","Complete");
 }catch(Exception e){File.WriteAllText("Docs/CaveRestore/driving-error.txt",e.ToString());}finally{Physics.simulationMode=mode;AudioListener.volume=volume;EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");}}
}





