var race=UnityEngine.Object.FindAnyObjectByType<Racer.RaceDirector>();if(Application.isPlaying||race.gameObject.scene.name!="ForestLoopReverse")throw new Exception("Forest edit mode required");
var atlas=JsonUtility.FromJson<InspectRouteAtlas.Atlas>(System.IO.File.ReadAllText("Docs/ForestWaterJump/routes-baseline.json"));var c=atlas.courses.Single(c=>c.scene=="ForestLoopReverse");c.id=race.courseId;
c.routes.Single(r=>r.kind=="main").points=race.road.points;c.routes.Single(r=>r.kind=="main").samples=null;
var current=c.routes.Where(r=>r.kind!="shortcut").ToList();foreach(var b in UnityEngine.Object.FindObjectsByType<Racer.WoodlandRoute>())current.Add(new InspectRouteAtlas.Route{name=b.title,kind="shortcut",points=b.points,entry=b.entryRoad,exit=b.exitRoad,ai=b.aiValidated});c.routes=current.ToArray();
c.gates=race.gates.Select(g=>g.transform.position).ToArray();var layout=UnityEngine.Object.FindAnyObjectByType<Racer.ForestLayout>();c.jumps=layout.jumpNames;
c.features=Enumerable.Range(0,layout.jumpStarts.Length).Select(i=>new InspectRouteAtlas.Feature{name=layout.jumpNames[i],kind="forest-jump",start=race.road.At(layout.jumpStarts[i],out _),end=race.road.At(layout.jumpEnds[i],out _)}).ToArray();
c.landmarks=c.landmarks.Concat(UnityEngine.Object.FindObjectsByType<Racer.ShallowWater>().Where(w=>w.name.StartsWith("House 3")).Select(w=>new InspectRouteAtlas.Landmark{name=w.name,position=w.transform.position})).ToArray();
System.IO.File.WriteAllText("Docs/ForestWaterJump/routes-current.json",JsonUtility.ToJson(atlas));
var baseline=JsonUtility.FromJson<InspectRouteAtlas.Atlas>(System.IO.File.ReadAllText("Docs/ForestWaterJump/routes-baseline.json")).courses.Single(v=>v.scene=="ForestLoopReverse");var old=baseline.routes.Single(r=>r.kind=="main").points;int localY=0;
for(int i=0;i<old.Length;i++){if(old[i].x!=race.road.points[i].x||old[i].z!=race.road.points[i].z)throw new Exception("Main X/Z changed");if(old[i].y!=race.road.points[i].y)localY++;}
var original=AssetDatabase.LoadAssetAtPath<Mesh>("Assets/Track/RouteAtlas/ForestLoopReverse-property-Ground_560_240.asset");var now=GameObject.Find("Ground_560_240").GetComponent<MeshFilter>().sharedMesh;var a=original.vertices;var v=now.vertices;int ramp=0,pool=0;
for(int i=0;i<a.Length;i++){if(a[i].x!=v[i].x||a[i].z!=v[i].z)throw new Exception("Terrain X/Z changed");if(a[i].y==v[i].y)continue;var p=GameObject.Find("Ground_560_240").transform.TransformPoint(v[i]);if(p.x>430)ramp++;else pool++;}
foreach(var b in UnityEngine.Object.FindObjectsByType<Racer.WoodlandRoute>()){var prior=baseline.routes.Single(r=>r.name==b.title);if(!prior.points.SequenceEqual(b.points))throw new Exception("Existing shortcut points changed");}
if(!original.triangles.SequenceEqual(now.triangles))throw new Exception("Terrain topology changed");
var geo=Newtonsoft.Json.Linq.JObject.Parse(System.IO.File.ReadAllText("Docs/ForestWaterJump/geometry.json"));geo["rampEdits"]=ramp;geo["poolEdits"]=pool;System.IO.File.WriteAllText("Docs/ForestWaterJump/geometry.json",geo.ToString());
System.IO.File.WriteAllText("Docs/ForestWaterJump/data-preservation.txt",$"PASS: all {old.Length} main X/Z control points unchanged; only {localY} local ramp navigation heights changed. All existing optional branch points unchanged. Terrain X/Z and topology unchanged; {ramp} ramp and {pool} pool-basin vertex heights changed in a new Forest-only mesh asset. Existing source assets retained. Gates and house pose checked separately against checkpoint scene blocks.\n");return "Current six-course atlas data exported; route alignment and existing branch invariants passed";
