using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class FinalizeMountainPolish {
 public static string Dependencies(){var notes=new List<string>();foreach(string scene in new[]{"MountainLoop","MountainLoopReverse"}){
 EditorSceneManager.OpenScene("Assets/Scenes/"+scene+".unity");Physics.SyncTransforms();var support=GameObject.Find("Ground_MountainPolish supported shoulders").GetComponent<Collider>();
 var affected=Object.FindObjectsByType<Collider>().Where(c=>c.name.IndexOf("trunk",StringComparison.OrdinalIgnoreCase)>=0).Where(c=>support.Raycast(new Ray(new(c.bounds.center.x,c.bounds.min.y+20,c.bounds.center.z),Vector3.down),out var h,40)&&Math.Abs(h.point.y-c.bounds.min.y)>.08f).ToArray();
 notes.Add(scene+" trees intersecting new support: "+affected.Length);
 if(affected.Length>0){typeof(Racer.Editor.BackyardReverseAuthoring).GetMethod("Trees",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Static).Invoke(null,new object[]{(Func<Collider,bool>)(c=>false),(Func<Collider,bool>)(c=>affected.Contains(c))});EditorSceneManager.MarkSceneDirty(UnityEngine.SceneManagement.SceneManager.GetActiveScene());EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());}
 Physics.SyncTransforms();foreach(var c in affected){var p=c.bounds.center;var hits=Physics.RaycastAll(new(p.x,c.bounds.min.y+20,p.z),Vector3.down,80,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).ToArray();notes.Add(c.name+" footGap="+(c.bounds.min.y-hits.Max(h=>h.point.y)).ToString("F3"));}
 }AssetDatabase.SaveAssets();File.WriteAllLines("Docs/MountainPolish/support-dependencies.txt",notes);return string.Join("\n",notes);}
 public static string PrepareRelease(){if(EditorApplication.isPlaying)throw new Exception("Edit mode required");PlayerSettings.bundleVersion="0.61.0-review1";var mat=AssetDatabase.LoadAssetAtPath<Material>("Assets/Resources/VehicleGlazing.mat");mat.SetFloat("_SrcBlend",1);EditorUtility.SetDirty(mat);AssetDatabase.SaveAssets();
 var keep=AssetDatabase.GetDependencies(Directory.GetFiles("Assets/Scenes","*.unity"),true).ToHashSet();var deleted=new List<string>();foreach(string p in File.ReadAllLines("Temp/mountainpolish-new-assets.txt").Where(p=>p.EndsWith(".asset"))){if(keep.Contains(p)||!File.Exists(p))continue;if(!p.StartsWith("Assets/Track/MountainPolish/")&&!p.StartsWith("Assets/Track/BackyardReverse/"))throw new Exception("Unexpected cleanup path "+p);if(AssetDatabase.DeleteAsset(p))deleted.Add(p);}
 File.WriteAllLines("Docs/MountainPolish/unused-generated-assets.txt",deleted);AssetDatabase.SaveAssets();return "Version saved; removed "+deleted.Count+" unreferenced generated iteration meshes";}
}
