using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class FinalizeReverseCorrection {
 public static string Main(){if(Application.isPlaying)throw new Exception("Edit mode required");Vector3 gatePosition=default;Quaternion gateRotation=default;var report=new List<string>();foreach(string scene in new[]{"DansBackyardReverse","DansBackyardForward"}){EditorSceneManager.OpenScene("Assets/Scenes/"+scene+".unity");Physics.SyncTransforms();var root=GameObject.Find("Reverse optional forest shortcuts").transform;
 float Ground(Vector3 p,bool original=false)=>Physics.RaycastAll(new(p.x,250,p.z),Vector3.down,500,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")&&(!original||!h.collider.transform.IsChildOf(root))).Max(h=>h.point.y);
 foreach(var brush in root.GetComponentsInChildren<ShortcutUndergrowth>()){brush.centres=brush.centres.Select(p=>new Vector3(p.x,Ground(p),p.z)).Where(p=>{brush.protectedMain.Project(p,out float d);return d>4.1f;}).ToArray();report.Add(scene+" grounded recovery clusters="+brush.centres.Length);}
 if(scene.EndsWith("Reverse")){var branches=root.GetComponentsInChildren<WoodlandRoute>();var ridge=branches.First(b=>b.title.StartsWith("Abandoned"));var drain=branches.First(b=>b.title.StartsWith("Storm"));var p=ridge.At(14,out var f);gatePosition=p+Vector3.up*.9f;gateRotation=Quaternion.LookRotation(Vector3.ProjectOnPlane(f,Vector3.up));object P(Vector3 q)=>new{x=q.x,y=q.y,z=q.z};var exposure=Enumerable.Range(0,Mathf.FloorToInt(ridge.Length)).Select(i=>{var q=ridge.At(i,out _);return new{station=i,height=q.y-Ground(q,true)};}).ToArray();File.WriteAllText("Docs/ReverseCorrection/geometry.json",Newtonsoft.Json.JsonConvert.SerializeObject(new{branches=branches.Select(b=>new{b.title,b.entryRoad,b.exitRoad,b.Length,b.halfWidth,b.entryInset,b.aiValidated,b.bypassedGates,b.undergroundStart,b.undergroundEnd,points=b.points.Select(P)}),ridgeExposure=exposure,exit=drain.undergroundEnd,lip=drain.GetComponent<ReverseShortcutGuidance>().takeoff,landing=drain.GetComponent<ReverseShortcutGuidance>().landing},Newtonsoft.Json.Formatting.Indented));report.Add("Ridge peak elevation above original floor="+exposure.Max(e=>e.height));}
 var gate=root.GetComponent<ReverseShortcutWorldState>().ridgeGate;gate.transform.SetPositionAndRotation(gatePosition,gateRotation);EditorSceneManager.MarkSceneDirty(root.gameObject.scene);EditorSceneManager.SaveScene(root.gameObject.scene);}
 PlayerSettings.bundleVersion="0.55.0-review1";AssetDatabase.SaveAssets();var dependencies=new HashSet<string>(AssetDatabase.GetDependencies(new[]{"Assets/Scenes/DansBackyardReverse.unity","Assets/Scenes/DansBackyardForward.unity"},true));int removed=0;foreach(var path in Directory.GetFiles("Assets/Track/ReverseCorrection").Select(p=>p.Replace('\\','/')).Where(p=>p.EndsWith(".asset")||p.EndsWith(".mat")))if(!dependencies.Contains(path)){if(AssetDatabase.DeleteAsset(path))removed++;}report.Add("Unused task-generated candidate assets removed="+removed);File.WriteAllLines("Docs/ReverseCorrection/final-geometry.txt",report);EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");return string.Join("\n",report);}
}
