using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class FinalizeMountainCut {
 public static string Main(){if(Application.isPlaying)throw new Exception("Edit mode required");foreach(var t in Object.FindObjectsByType<MountainCutChecks>())Object.DestroyImmediate(t.gameObject);var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene();var lines=new List<string>();Physics.SyncTransforms();bool Local(Vector3 p)=>p.x>855&&p.x<1060&&p.z>-112&&p.z<185;
 float Ground(Vector3 p,float foot){return Physics.RaycastAll(new(p.x,foot+20,p.z),Vector3.down,80,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).Select(h=>h.point.y).DefaultIfEmpty(foot).Max();}
 foreach(var sign in Object.FindObjectsByType<PhysicalSign>().Where(t=>Local(t.transform.position))){var posts=sign.GetComponentsInChildren<Renderer>().Where(r=>r.name.IndexOf("post",StringComparison.OrdinalIgnoreCase)>=0).ToArray();if(posts.Length==0)continue;float foot=posts.Min(r=>r.bounds.min.y),dy=Ground(sign.transform.position,foot)-foot;sign.transform.position+=Vector3.up*(dy+.03f);lines.Add("Sign "+sign.name+" reseat="+dy);}
 foreach(var t in Object.FindObjectsByType<Transform>().Where(t=>t.name.StartsWith("Acorn clue /")&&Local(t.position))){var rs=t.GetComponentsInChildren<Renderer>();if(rs.Length==0)continue;float foot=rs.Min(r=>r.bounds.min.y);float dy=Ground(rs[0].bounds.center,foot)-foot;t.position+=Vector3.up*dy;lines.Add("Cairn reseat="+dy);}
 var trees=Object.FindObjectsByType<Collider>().Where(c=>c.name.IndexOf("trunk",StringComparison.OrdinalIgnoreCase)>=0&&Local(c.bounds.center)).ToArray();var affected=trees.Where(c=>Math.Abs(c.bounds.min.y-Ground(c.bounds.center,c.bounds.min.y))>.08f).ToArray();if(affected.Length>0)typeof(Racer.Editor.BackyardReverseAuthoring).GetMethod("Trees",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Static).Invoke(null,new object[]{(Func<Collider,bool>)(c=>false),(Func<Collider,bool>)(c=>affected.Contains(c))});Physics.SyncTransforms();lines.Add("Trees checked="+trees.Length+" reseated="+affected.Length+" maximum foot gap="+trees.Select(c=>Math.Abs(c.bounds.min.y-Ground(c.bounds.center,c.bounds.min.y))).DefaultIfEmpty().Max());
 PlayerSettings.bundleVersion="0.62.0-review1";var mat=AssetDatabase.LoadAssetAtPath<Material>("Assets/Resources/VehicleGlazing.mat");mat.SetFloat("_SrcBlend",1);EditorUtility.SetDirty(mat);EditorSceneManager.MarkSceneDirty(scene);EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();
 var road=Object.FindAnyObjectByType<RaceDirector>().road;var catalog=JsonUtility.FromJson<CoursePreviewCatalog>(File.ReadAllText("Assets/Resources/WorldMaps/CoursePreviews.json"));catalog.courses.Single(c=>c.scene=="MountainLoopReverse").main=road.points.ToArray();File.WriteAllText("Assets/Resources/WorldMaps/CoursePreviews.json",JsonUtility.ToJson(catalog,true));
 var keep=AssetDatabase.GetDependencies(Directory.GetFiles("Assets/Scenes","*.unity"),true).ToHashSet();var retired=new List<string>();foreach(string p in File.ReadAllLines("Temp/mountaincut-new-assets.txt").Where(p=>p.EndsWith(".asset"))){if(keep.Contains(p)||!File.Exists(p))continue;if(!p.StartsWith("Assets/Track/MountainCut/")&&!p.StartsWith("Assets/Track/BackyardReverse/"))throw new Exception("Unexpected candidate "+p);if(AssetDatabase.DeleteAsset(p))retired.Add(p);}File.WriteAllLines("Docs/MountainCut/retired-iterations.txt",retired);File.WriteAllLines("Docs/MountainCut/grounding-final.txt",lines);AssetDatabase.SaveAssets();return string.Join("\n",lines)+"\nRetired unreferenced meshes="+retired.Count;
 }
}
