using System;using System.IO;using System.Linq;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class FinishFinalTwo{
 public static string Main(){EditorSceneManager.OpenScene("Assets/Scenes/LakeWoods.unity");foreach(var mf in GameObject.Find("Echo Cave partial rockfall").GetComponentsInChildren<MeshFilter>()){var m=mf.sharedMesh;var t=m.triangles;for(int i=0;i<t.Length;i+=3){int x=t[i+1];t[i+1]=t[i+2];t[i+2]=x;}m.triangles=t;m.RecalculateNormals();EditorUtility.SetDirty(m);mf.GetComponent<MeshCollider>().sharedMesh=null;mf.GetComponent<MeshCollider>().sharedMesh=m;}AssetDatabase.SaveAssets();return "Corrected outward rock faces; same vertex bounds and passage";}
 public static string Check(){var b=Object.FindObjectsByType<WoodlandRoute>().Single(x=>x.title=="Echo Cave");var root=GameObject.Find("Echo Cave partial rockfall");var zone=root.GetComponent<JumpRecoveryExclusion>();var rows=new System.Collections.Generic.List<string>();Physics.SyncTransforms();var original=JsonUtility.FromJson<Line>(File.ReadAllText("Docs/FinalTwo/original-cave-line.json"));var tmp=new GameObject("Temporary old line");var old=tmp.AddComponent<WoodlandRoute>();old.points=original.points;
 foreach(float s in new[]{190f,205f,211f,225f,237f}){var p=old.At(s,out var f);rows.Add((zone.Contains(p+Vector3.up*.6f)?"PASS ":"FAIL ")+"Recovery excludes rockfall corridor station="+s);}
 rows.Add((!zone.Contains(old.At(180,out _))&&!zone.Contains(old.At(247,out _))?"PASS ":"FAIL ")+"Recovery available before/after local exclusion");
 foreach(float x in new[]{-4.5f,-2f,0f,3.05f}){var p=old.At(195,out var f)+Vector3.Cross(Vector3.up,f).normalized*x+Vector3.up*.7f;var end=old.At(228,out f)+Vector3.Cross(Vector3.up,f).normalized*x+Vector3.up*.7f;bool hit=Physics.SphereCastAll(p,.85f,(end-p).normalized,Vector3.Distance(p,end),1,QueryTriggerInteraction.Ignore).Any(h=>h.collider.transform.IsChildOf(root.transform));rows.Add((hit==(x<1)?"PASS ":"FAIL ")+"ATV-width sweep lateral="+x+" rock contact="+hit);}
 foreach(var mf in root.GetComponentsInChildren<MeshFilter>())rows.Add((mf.GetComponent<MeshCollider>().sharedMesh==mf.sharedMesh?"PASS ":"FAIL ")+mf.name+" visible and physical mesh identical");Object.DestroyImmediate(tmp);File.WriteAllLines("Docs/FinalTwo/local-clearance.txt",rows);return string.Join("\n",rows);}
 [Serializable]public class Line{public Vector3[] points;}
}
