using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class FinishReverseCorrectionSurface {
 public static string Main(){const string folder="Assets/Track/ReverseCorrection/";Vector3[] points=null;
 foreach(string scene in new[]{"DansBackyardReverse","DansBackyardForward"}){EditorSceneManager.OpenScene("Assets/Scenes/"+scene+".unity");Physics.SyncTransforms();var root=GameObject.Find("Reverse optional forest shortcuts").transform;var b=root.GetComponentsInChildren<WoodlandRoute>().FirstOrDefault(b=>b.title.StartsWith("Abandoned"));bool temporary=!b;if(temporary){b=root.gameObject.AddComponent<WoodlandRoute>();b.points=points;}else points=b.points.ToArray();var roads=Object.FindObjectsByType<RaceRoad>();
 var earth=AssetDatabase.LoadAssetAtPath<Material>(folder+"Weathered logging earth.mat");var grass=AssetDatabase.LoadAssetAtPath<Material>(folder+"Natural moss and grass.mat");earth.SetFloat("_Smoothness",0);grass.SetFloat("_Smoothness",0);EditorUtility.SetDirty(earth);EditorUtility.SetDirty(grass);root.GetComponentsInChildren<MeshRenderer>().First(r=>r.name=="Ground_Worn logging crest").sharedMaterial=grass;
 var verts=new List<Vector3>();var tris=new List<int>();for(float s=3;s<b.Length-3;s+=.6f){var p=b.At(s,out var f);bool road=roads.Any(r=>{r.Project(p,out float d);return d<4;});if(road)continue;var q=b.At(s+.6f,out var ff);bool patch=Mathf.FloorToInt(s/8)%4==1;foreach(float offset in patch?new[]{0f}:new[]{-.82f,.82f}){float half=patch?1.85f:.42f+.08f*Mathf.Sin(s*.7f);int start=verts.Count;foreach(var row in new[]{(p,f),(q,ff)}){var side=Vector3.Cross(Vector3.up,row.Item2).normalized;foreach(int sign in new[]{-1,1})verts.Add(row.Item1+side*(offset+half*sign)+Vector3.up*.055f);}tris.AddRange(new[]{start,start+2,start+1,start+1,start+2,start+3});}}
 var mesh=new Mesh();mesh.SetVertices(verts);mesh.SetTriangles(tris,0);mesh.RecalculateNormals();mesh.RecalculateBounds();AssetDatabase.CreateAsset(mesh,folder+scene+" worn logging wheel paths.asset");var g=new GameObject("Broken logging wheel paths",typeof(MeshFilter),typeof(MeshRenderer));g.transform.SetParent(root);g.GetComponent<MeshFilter>().sharedMesh=mesh;g.GetComponent<Renderer>().sharedMaterial=earth;
 var shape=AssetDatabase.LoadAssetAtPath<Mesh>("Assets/Vegetation/Phase6/IrregularCrown.asset");foreach(var bush in root.GetComponentsInChildren<MeshFilter>().Where(m=>m.name=="Rough low ridge scrub")){bush.sharedMesh=shape;bush.transform.localScale=new(2,1.35f,2);bush.transform.position-=Vector3.up*.45f;}
 foreach(var brush in root.GetComponentsInChildren<ShortcutUndergrowth>())brush.centres=brush.centres.Where(p=>{brush.protectedMain.Project(p,out float d);return d>=4.1f;}).ToArray();
 if(temporary)Object.DestroyImmediate(b);else Object.FindAnyObjectByType<RaceDirector>().courseId="backyard-reverse-v3-ridge-drain";
 EditorSceneManager.MarkSceneDirty(root.gameObject.scene);EditorSceneManager.SaveScene(root.gameObject.scene);AssetDatabase.SaveAssets();}EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");File.WriteAllText("Docs/ReverseCorrection/surface-finish.txt","Broken worn wheel paths, patchy earth and established irregular foliage; collision unchanged. Reverse v3 keeps historical Records separate.");return "Abandoned logging surface finished";}
}
