EditorApplication.delayCall+=()=>{try{
var report=new List<string>();
foreach(var line in System.IO.File.ReadAllLines("Docs/YardReset/original-terrain-guids.txt")){
var parts=line.Split('|');var source=AssetDatabase.LoadAssetAtPath<Mesh>(AssetDatabase.GUIDToAssetPath(parts[1]));var mesh=AssetDatabase.LoadAssetAtPath<Mesh>("Assets/Track/YardReset/"+parts[0]+"-Ground_560_320.asset");var sv=source.vertices;var sc=source.colors;var st=source.triangles;if(sc.Length!=sv.Length)throw new Exception("Original terrain colors missing");
var cells=new Dictionary<Vector2Int,List<int>>();Vector2Int Cell(Vector3 p)=>new(Mathf.FloorToInt(p.x/2),Mathf.FloorToInt(p.z/2));
for(int i=0;i<st.Length;i+=3){var min=Cell(Vector3.Min(sv[st[i]],Vector3.Min(sv[st[i+1]],sv[st[i+2]])));var max=Cell(Vector3.Max(sv[st[i]],Vector3.Max(sv[st[i+1]],sv[st[i+2]])));for(int x=min.x;x<=max.x;x++)for(int z=min.y;z<=max.y;z++){var key=new Vector2Int(x,z);if(!cells.TryGetValue(key,out var list)){list=new List<int>();cells[key]=list;}list.Add(i);}}
var colorCache=new Dictionary<Vector2,Color>();Color Sample(Vector3 p){var key=new Vector2(p.x,p.z);if(colorCache.TryGetValue(key,out var cached))return cached;var cell=Cell(p);for(int dx=-1;dx<=1;dx++)for(int dz=-1;dz<=1;dz++){if(!cells.TryGetValue(cell+new Vector2Int(dx,dz),out var list))continue;foreach(int t in list){var a=sv[st[t]];var b=sv[st[t+1]];var c=sv[st[t+2]];float det=(b.z-c.z)*(a.x-c.x)+(c.x-b.x)*(a.z-c.z);if(Math.Abs(det)<.00001f)continue;float u=((b.z-c.z)*(p.x-c.x)+(c.x-b.x)*(p.z-c.z))/det;float v=((c.z-a.z)*(p.x-c.x)+(a.x-c.x)*(p.z-c.z))/det;float w=1-u-v;if(Mathf.Min(u,v,w)<-.0001f)continue;var color=sc[st[t]]*u+sc[st[t+1]]*v+sc[st[t+2]]*w;colorCache[key]=color;return color;}}throw new Exception("No original color sample "+p);}
var old=mesh.vertices;var oldUv=mesh.uv;var oldTris=mesh.triangles;var positions=new List<Vector3>();var colors=new List<Color>();var uv=new List<Vector2>();var indices=new int[oldTris.Length];var welded=new Dictionary<Vector3Int,int>();
for(int i=0;i<oldTris.Length;i++){int v=oldTris[i];var p=old[v];var key=new Vector3Int(Mathf.RoundToInt(p.x*10000),Mathf.RoundToInt(p.y*10000),Mathf.RoundToInt(p.z*10000));if(!welded.TryGetValue(key,out int n)){n=positions.Count;welded[key]=n;positions.Add(p);colors.Add(Sample(p));uv.Add(oldUv.Length==old.Length?oldUv[v]:Vector2.zero);}indices[i]=n;}
mesh.Clear();mesh.indexFormat=UnityEngine.Rendering.IndexFormat.UInt32;mesh.SetVertices(positions);mesh.SetUVs(0,uv);mesh.SetColors(colors);mesh.SetTriangles(indices,0);mesh.RecalculateNormals();mesh.RecalculateBounds();EditorUtility.SetDirty(mesh);report.Add(parts[0]+": restored original interpolated vertex colors; welded "+old.Length+" -> "+positions.Count+" vertices; same triangle surfaces within 0.1mm");
}
var font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");var mat=new Material(Shader.Find("Racer/WorldText"));mat.mainTexture=font.material.mainTexture;AssetDatabase.CreateAsset(mat,"Assets/Track/YardReset/Reference lettering.mat");
foreach(string name in Racer.Editor.YardResetAuthoring.Scenes){var scene=UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/"+name+".unity");var root=GameObject.Find("TEMPORARY Backyard anchor validation - no route").transform;foreach(Transform anchor in root){var labels=anchor.GetComponentsInChildren<TextMesh>();for(int i=1;i<labels.Length;i++)UnityEngine.Object.DestroyImmediate(labels[i].gameObject);var label=labels[0];label.font=font;label.characterSize=.12f;label.transform.localPosition=Vector3.up*4.3f;label.transform.rotation=Quaternion.Euler(0,90,0);label.GetComponent<Renderer>().sharedMaterial=mat;label.gameObject.AddComponent<Racer.TemporaryAnchorLabel>();}UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(scene);UnityEditor.SceneManagement.EditorSceneManager.SaveScene(scene);}
AssetDatabase.SaveAssets();System.IO.File.WriteAllLines("Docs/YardReset/presentation-done.txt",report);
}catch(Exception e){System.IO.File.WriteAllText("Docs/YardReset/presentation-error.txt",e.ToString());}};return "Restore terrain colors and make each marker a single depth-tested readable label";
