EditorApplication.delayCall+=()=>{try{
var rows=new List<string>();var font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
foreach(string name in Racer.Editor.YardResetAuthoring.Scenes){var scene=UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/"+name+".unity");var concrete=GameObject.Find("Ground_Dan beige concrete descent and parking").GetComponent<MeshCollider>();var terrain=GameObject.Find("Ground_560_320").GetComponent<MeshFilter>();var mesh=terrain.sharedMesh;var v=mesh.vertices;int trimmed=0;float largest=0;var b=concrete.bounds;
for(int i=0;i<v.Length;i++){var p=terrain.transform.TransformPoint(v[i]);if(p.x<b.min.x||p.x>b.max.x||p.z<b.min.z||p.z>b.max.z)continue;if(!concrete.Raycast(new Ray(new Vector3(p.x,200,p.z),Vector3.down),out var hit,400))continue;float ceiling=hit.point.y-.035f;if(p.y<=ceiling)continue;largest=Math.Max(largest,p.y-ceiling);p.y=ceiling;v[i]=terrain.transform.InverseTransformPoint(p);trimmed++;}
mesh.vertices=v;mesh.RecalculateNormals();mesh.RecalculateBounds();EditorUtility.SetDirty(mesh);terrain.GetComponent<MeshCollider>().sharedMesh=null;terrain.GetComponent<MeshCollider>().sharedMesh=mesh;
var root=GameObject.Find("TEMPORARY Backyard anchor validation - no route");foreach(var text in root.GetComponentsInChildren<TextMesh>())text.GetComponent<Renderer>().sharedMaterial=font.material;
rows.Add(name+": removed local terrain intrusion beneath existing concrete: "+trimmed+" vertices, largest="+largest+"; single camera-facing development labels remain visible through foliage without clearing trees");UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(scene);UnityEditor.SceneManagement.EditorSceneManager.SaveScene(scene);}
AssetDatabase.SaveAssets();System.IO.File.WriteAllLines("Docs/YardReset/surface-edges-done.txt",rows);
}catch(Exception e){System.IO.File.WriteAllText("Docs/YardReset/surface-edges-error.txt",e.ToString());}};return "Finish pavement edge support and visible forest reference labels";
