using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class FixSevenContacts {
 public static string Main(){EditorApplication.delayCall+=Run;return "Scheduled removal of measured terrain/mesh intersections";}
 static void Run(){try{EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");Physics.SyncTransforms();var ridge=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title.StartsWith("Abandoned"));var drain=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title.StartsWith("Storm"));var natural=GameObject.Find("Ground_Natural rolling ridge").GetComponent<MeshFilter>();Object.DestroyImmediate(natural.GetComponent<MeshCollider>());
 var flags=BindingFlags.NonPublic|BindingFlags.Static;typeof(Racer.Editor.BackyardReverseAuthoring).GetMethod("Sculpt",flags).Invoke(null,new object[]{(Func<Vector3,bool>)(p=>{if(p.x<266||p.x>323||p.z<98||p.z>145)return false;float s=ridge.Project(p,out float d);return s>80&&d<16;}),(Func<Vector3,Vector3>)(p=>{float s=ridge.Project(p,out float d);float blend=(1-Mathf.SmoothStep(0,1,Mathf.InverseLerp(3.8f,16,d)))*Mathf.SmoothStep(0,1,Mathf.InverseLerp(80,82,s));p.y=Mathf.Lerp(p.y,ridge.At(s,out _).y,blend);return p;}),"Integrated ridge descent"});
 // Remove the old disconnected apron on the final descent, visually and physically.
 var m=Object.Instantiate(natural.sharedMesh);var v=m.vertices;var t=m.triangles;var keep=new List<int>();for(int i=0;i<t.Length;i+=3){var p=natural.transform.TransformPoint((v[t[i]]+v[t[i+1]]+v[t[i+2]])/3);if(p.x<322&&ridge.Project(p,out _)>82)continue;keep.AddRange(new[]{t[i],t[i+1],t[i+2]});}m.triangles=keep.ToArray();m.RecalculateBounds();m.RecalculateNormals();AssetDatabase.CreateAsset(m,"Assets/Track/SevenCorrections/Retained elevated ridge.asset");natural.sharedMesh=m;natural.gameObject.AddComponent<MeshCollider>().sharedMesh=m;
 // Original entrance terrain intruded through the lower floor. Remove its faces inside the bore, not its visual alone.
 int removed=0;foreach(var mf in Object.FindObjectsByType<MeshFilter>().Where(x=>x.name.StartsWith("Ground_")&&x.name!="Ground_Culvert seamless floor"&&x.GetComponent<MeshCollider>()&&x.GetComponent<Renderer>().bounds.Intersects(new Bounds(new(159,58,63),new(50,40,58))))){var src=mf.sharedMesh;v=src.vertices;t=src.triangles;keep=new();int count=0;for(int i=0;i<t.Length;i+=3){var p=mf.transform.TransformPoint((v[t[i]]+v[t[i+1]]+v[t[i+2]])/3);if(p.x>138&&p.x<180&&p.z>35&&p.z<85){float s=drain.Project(p,out float d);float y=drain.At(s,out _).y;if(s>.2f&&s<70&&d<3.55f&&p.y>y-4&&p.y<y+5.3f){count++;continue;}}keep.AddRange(new[]{t[i],t[i+1],t[i+2]});}if(count==0)continue;m=Object.Instantiate(src);m.triangles=keep.ToArray();m.RecalculateBounds();m.RecalculateNormals();AssetDatabase.CreateAsset(m,AssetDatabase.GenerateUniqueAssetPath("Assets/Track/SevenCorrections/Clean entrance bore.asset"));mf.sharedMesh=m;mf.GetComponent<MeshCollider>().sharedMesh=null;mf.GetComponent<MeshCollider>().sharedMesh=m;removed+=count;}
 Physics.SyncTransforms();float Ground(Vector3 p)=>Physics.RaycastAll(new(p.x,250,p.z),Vector3.down,500,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).Max(h=>h.point.y);typeof(Racer.Editor.BackyardReverseAuthoring).GetMethod("Trees",flags).Invoke(null,new object[]{(Func<Collider,bool>)(c=>false),(Func<Collider,bool>)(c=>{if(c.bounds.center.x<265||c.bounds.center.x>323)return false;float s=ridge.Project(c.bounds.center,out float d);return s>80&&d<16;})});foreach(var c in Object.FindObjectsByType<BoxCollider>().Where(c=>c.name=="Abandoned fallen timber"||c.name=="Weathered stump")){float s=ridge.Project(c.bounds.center,out _);if(s>80)c.transform.position+=Vector3.up*(Ground(c.bounds.center)-c.bounds.min.y);}
 var glazing=AssetDatabase.LoadAssetAtPath<Material>("Assets/Resources/VehicleGlazing.mat");glazing.SetFloat("_SrcBlend",1);EditorUtility.SetDirty(glazing);EditorSceneManager.MarkSceneDirty(natural.gameObject.scene);EditorSceneManager.SaveScene(natural.gameObject.scene);AssetDatabase.SaveAssets();File.WriteAllText("Docs/SevenCorrections/contact-correction.txt","Final ridge descent integrated into original terrain; removed detached apron tail and overlapping collision. Removed "+removed+" original terrain triangles intersecting driveable drain bore; floor retained.");}catch(Exception e){File.WriteAllText("Docs/SevenCorrections/contact-error.txt",e.ToString());}}
}
