using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class FixReverseCorrectionHorizontalSupport {
 public static string Main(){var report=new List<string>();foreach(string scene in new[]{"DansBackyardReverse","DansBackyardForward"}){EditorSceneManager.OpenScene("Assets/Scenes/"+scene+".unity");var root=GameObject.Find("Reverse optional forest shortcuts").transform;var segments=Object.FindObjectsByType<RaceRoad>().SelectMany(r=>r.points.Zip(r.points.Skip(1),(a,b)=>(a,b))).Where(x=>Math.Max(x.a.x,x.b.x)>260&&Math.Min(x.a.x,x.b.x)<410&&Math.Max(x.a.z,x.b.z)>60&&Math.Min(x.a.z,x.b.z)<145).ToArray();
 float Road(Vector3 p){float best=999;foreach(var e in segments){var a=new Vector2(e.a.x,e.a.z);var v=new Vector2(e.b.x-e.a.x,e.b.z-e.a.z);var q=new Vector2(p.x,p.z)-a;float t=Mathf.Clamp01(Vector2.Dot(q,v)/Mathf.Max(.001f,v.sqrMagnitude));best=Mathf.Min(best,(q-v*t).magnitude);}return best;}
 Physics.SyncTransforms();var cache=new Dictionary<Vector3,float>();float Height(Vector3 p){if(cache.TryGetValue(p,out float value))return value;float d=Road(p);if(d>=12)return p.y;float ground=Physics.RaycastAll(new(p.x,250,p.z),Vector3.down,500,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")&&!h.collider.transform.IsChildOf(root)).Max(h=>h.point.y);value=Mathf.Lerp(ground+.015f,p.y,Mathf.SmoothStep(0,1,Mathf.InverseLerp(4.4f,12,d)));cache[p]=value;return value;}
 foreach(var mf in root.GetComponentsInChildren<MeshFilter>().Where(m=>m.name=="Ground_Natural rolling ridge"||m.name=="Ground_Worn logging crest"||m.name=="Grass intrusion"||m.name=="Broken logging wheel paths")){var mesh=mf.sharedMesh;var v=mesh.vertices;for(int i=0;i<v.Length;i++){var p=mf.transform.TransformPoint(v[i]);p.y=Height(p);v[i]=mf.transform.InverseTransformPoint(p);}mesh.vertices=v;mesh.RecalculateNormals();mesh.RecalculateBounds();EditorUtility.SetDirty(mesh);if(mf.TryGetComponent<MeshCollider>(out var collider)){collider.sharedMesh=null;collider.sharedMesh=mesh;}}
 var ridge=root.GetComponentsInChildren<WoodlandRoute>().FirstOrDefault(b=>b.title.StartsWith("Abandoned"));if(ridge){var p=ridge.points.ToArray();for(int i=0;i<p.Length;i++)p[i].y=Height(p[i]);ridge.points=p;typeof(WoodlandRoute).GetField("lengths",BindingFlags.Instance|BindingFlags.NonPublic).SetValue(ridge,null);EditorUtility.SetDirty(ridge);}
 Physics.SyncTransforms();typeof(Racer.Editor.BackyardReverseAuthoring).GetMethod("Trees",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,new object[]{(Func<Collider,bool>)(c=>false),(Func<Collider,bool>)(c=>c.bounds.center.x>270&&c.bounds.center.x<400&&c.bounds.center.z>65&&c.bounds.center.z<140)});
 foreach(var c in root.GetComponentsInChildren<BoxCollider>().Where(c=>c.name=="Abandoned fallen timber"||c.name=="Weathered stump")){var p=c.bounds.center;float y=Physics.RaycastAll(new(p.x,250,p.z),Vector3.down,500,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).Max(h=>h.point.y);c.transform.position+=Vector3.up*(y-c.bounds.min.y);}
 foreach(var t in root.Cast<Transform>().Where(t=>t.name=="Rough low ridge scrub")){var p=t.position;p.y=Physics.RaycastAll(new(p.x,250,p.z),Vector3.down,500,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).Max(h=>h.point.y);t.position=p;}
 report.Add(scene+": horizontal road protection applied to "+cache.Count+" distinct ridge vertices; complete trees and props reseated");EditorSceneManager.MarkSceneDirty(root.gameObject.scene);EditorSceneManager.SaveScene(root.gameObject.scene);AssetDatabase.SaveAssets();}File.WriteAllLines("Docs/ReverseCorrection/horizontal-support.txt",report);EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");return string.Join("\n",report);}
}
