UnityEditor.EditorApplication.delayCall += () => { try {
UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/MountainLoopReverse.unity");
var road=UnityEngine.Object.FindAnyObjectByType<Racer.RaceDirector>().road;road.Initialize();
var origin=road.At(140,out _);double[] Basis(Vector3 p){double x=(p.x-origin.x)/40,z=(p.z-origin.z)/40;return new[]{1d,x,z,x*x,x*z,z*z,x*x*x,x*x*z,x*z*z,z*z*z};}
var matrix=new double[10,11];
for(float s=100;s<=180;s+=1){var p=road.At(s,out var f);foreach(float lane in new[]{-7f,0,7}){var q=p+Vector3.Cross(Vector3.up,f).normalized*lane;var a=Basis(q);for(int i=0;i<10;i++){for(int j=0;j<10;j++)matrix[i,j]+=a[i]*a[j];matrix[i,10]+=a[i]*(p.y+.04f);}}}
for(int i=0;i<10;i++)matrix[i,i]+=.000001;
for(int i=0;i<10;i++){int pivot=i;for(int j=i+1;j<10;j++)if(Math.Abs(matrix[j,i])>Math.Abs(matrix[pivot,i]))pivot=j;for(int k=i;k<=10;k++){var temp=matrix[i,k];matrix[i,k]=matrix[pivot,k];matrix[pivot,k]=temp;}double d=matrix[i,i];for(int k=i;k<=10;k++)matrix[i,k]/=d;for(int j=0;j<10;j++)if(j!=i){double f=matrix[j,i];for(int k=i;k<=10;k++)matrix[j,k]-=f*matrix[i,k];}}
float Height(Vector3 p){var a=Basis(p);double y=0;for(int i=0;i<10;i++)y+=a[i]*matrix[i,10];return (float)y;}
float Smooth(float u){u=Mathf.Clamp01(u);return u*u*u*(10+u*(-15+6*u));}
float maxMove=0;int changed=0;
Vector3 Map(Vector3 p){float s=road.Project(p,out _);if(s<=100||s>=180)return p;var at=road.At(s,out _);float lateral=Vector2.Distance(new Vector2(at.x,at.z),new Vector2(p.x,p.z));if(lateral>=22||Math.Abs(p.y-at.y)>9)return p;float w=Smooth((s-100)/18)*Smooth((180-s)/20)*(1-Smooth((lateral-7)/15));float y=Mathf.Lerp(p.y,Height(p),w);maxMove=Mathf.Max(maxMove,Math.Abs(y-p.y));p.y=y;return p;}
foreach(var mf in UnityEngine.Object.FindObjectsByType<MeshFilter>().Where(m=>m.name=="Ground_CR133 mountain driving surface"||m.name=="Ground_CR133 mountain earth banks")){
var original=UnityEditor.AssetDatabase.LoadAssetAtPath<Mesh>("Assets/Track/LocalRecovery/MountainLoopReverse-first-arrow-"+(mf.name.Contains("driving")?"only":"shoulder")+"-"+mf.name+".asset");
var mesh=UnityEngine.Object.Instantiate(original);var verts=mesh.vertices.ToList();var colors=mesh.colors.ToList();bool hasColors=colors.Count==verts.Count;var indices=mesh.triangles;var output=new List<int>();var mids=new Dictionary<(int,int),int>();
int Mid(int a,int b){var key=a<b?(a,b):(b,a);if(mids.TryGetValue(key,out var value))return value;value=verts.Count;verts.Add((verts[a]+verts[b])*.5f);if(hasColors)colors.Add((colors[a]+colors[b])*.5f);mids[key]=value;return value;}
void Split(int a,int b,int c,int depth){var pa=mf.transform.TransformPoint(verts[a]);var pb=mf.transform.TransformPoint(verts[b]);var pc=mf.transform.TransformPoint(verts[c]);var p=(pa+pb+pc)/3;float station=road.Project(p,out var lateral);float ab=(pa-pb).sqrMagnitude,bc=(pb-pc).sqrMagnitude,ca=(pc-pa).sqrMagnitude;if(depth<14&&station>98&&station<182&&lateral<28&&Mathf.Max(ab,bc,ca)>.36f){if(ab>=bc&&ab>=ca){int m=Mid(a,b);Split(a,m,c,depth+1);Split(m,b,c,depth+1);}else if(bc>=ca){int m=Mid(b,c);Split(a,b,m,depth+1);Split(a,m,c,depth+1);}else{int m=Mid(c,a);Split(a,b,m,depth+1);Split(m,b,c,depth+1);}return;}output.Add(a);output.Add(b);output.Add(c);}
for(int i=0;i<indices.Length;i+=3)Split(indices[i],indices[i+1],indices[i+2],0);
mesh.indexFormat=UnityEngine.Rendering.IndexFormat.UInt32;mesh.SetVertices(verts);mesh.SetTriangles(output,0);if(hasColors)mesh.SetColors(colors);var v=mesh.vertices;bool touched=false;for(int i=0;i<v.Length;i++){var p=mf.transform.TransformPoint(v[i]);var q=Map(p);if((p-q).sqrMagnitude>.000000001f)touched=true;v[i]=mf.transform.InverseTransformPoint(q);}if(!touched){UnityEngine.Object.DestroyImmediate(mesh);continue;}mesh.vertices=v;mesh.RecalculateNormals();mesh.RecalculateBounds();var saved=UnityEditor.AssetDatabase.LoadAssetAtPath<Mesh>("Assets/Track/LocalRecovery/Surgical-second-arrow-"+mf.name+".asset");if(saved){UnityEditor.EditorUtility.CopySerialized(mesh,saved);UnityEngine.Object.DestroyImmediate(mesh);mesh=saved;UnityEditor.EditorUtility.SetDirty(saved);}else UnityEditor.AssetDatabase.CreateAsset(mesh,"Assets/Track/LocalRecovery/Surgical-second-arrow-"+mf.name+".asset");mf.sharedMesh=mesh;mf.GetComponent<MeshCollider>().sharedMesh=mesh;changed++;}
Physics.SyncTransforms();
foreach(var arrow in UnityEngine.Object.FindObjectsByType<MeshFilter>().Where(m=>m.name=="Main teal trail arrow")) {var p=arrow.GetComponent<Renderer>().bounds.center;float station=road.Project(p,out _);if(station>185)continue;foreach(var c in arrow.GetComponentsInChildren<Collider>(true))UnityEngine.Object.DestroyImmediate(c);if(station<100)continue;var mesh=UnityEngine.Object.Instantiate(arrow.sharedMesh);var v=mesh.vertices;for(int i=0;i<v.Length;i++){var q=arrow.transform.TransformPoint(v[i]);var hits=Physics.RaycastAll(q+Vector3.up*5,Vector3.down,10,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name=="Ground_CR133 mountain driving surface").OrderBy(h=>h.distance).ToArray();if(hits.Length>0)q.y=hits[0].point.y+.035f;v[i]=arrow.transform.InverseTransformPoint(q);}mesh.vertices=v;mesh.RecalculateNormals();mesh.RecalculateBounds();var saved=UnityEditor.AssetDatabase.LoadAssetAtPath<Mesh>("Assets/Track/LocalRecovery/Surgical-second-arrow-visual.asset");if(saved){UnityEditor.EditorUtility.CopySerialized(mesh,saved);UnityEngine.Object.DestroyImmediate(mesh);mesh=saved;UnityEditor.EditorUtility.SetDirty(saved);}else UnityEditor.AssetDatabase.CreateAsset(mesh,"Assets/Track/LocalRecovery/Surgical-second-arrow-visual.asset");arrow.sharedMesh=mesh;}
var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene();UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(scene);UnityEditor.SceneManagement.EditorSceneManager.SaveScene(scene);UnityEditor.AssetDatabase.SaveAssets();
System.IO.File.WriteAllText("Docs/SurgicalTracks/mountain.txt",$"Second arrow at station 139.97: alternating triangle planes corrected with a continuous cubic height field. Core stations 118–160, feathered to unchanged boundaries at 100 and 180. Meshes={changed}; maximum local vertex displacement={maxMove:F4}m. First-arrow patch unchanged; all early arrows visual-only. Road route, physics, recovery, AI unchanged.");
}catch(Exception e){System.IO.File.WriteAllText("Docs/SurgicalTracks/mountain-error.txt",e.ToString());}};return "Scheduled second-arrow correction";
