using System;using System.Linq;using System.IO;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class FixMountainMergeSeam {
 public static string Main(){EditorSceneManager.OpenScene("Assets/Scenes/MountainLoopReverse.unity");var b=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title=="Summit Traverse");float y0=b.At(380,out _).y,y1=b.At(450,out _).y;
 float Y(float s){float t=Mathf.Clamp01((s-380)/70),t2=t*t,t3=t2*t;return (2*t3-3*t2+1)*y0+(-2*t3+3*t2)*y1+(t3-t2)*70*.16f;}
 float W(float s,float d)=>Mathf.SmoothStep(0,1,Mathf.InverseLerp(375,385,s))*(1-Mathf.SmoothStep(0,1,Mathf.InverseLerp(440,455,s)))*(1-Mathf.SmoothStep(0,1,Mathf.InverseLerp(6,9,d)));
 int count=0;foreach(var mf in Object.FindObjectsByType<MeshFilter>().Where(m=>m.sharedMesh&&(m.name.Contains("driving surface")||m.name.Contains("supported shoulders")||m.name.Contains("Optional gold")||m.name.Contains("Main teal")))){var v=mf.sharedMesh.vertices;bool changed=false;bool support=mf.name.Contains("supported shoulders");for(int i=0;i<v.Length;i++){var p=mf.transform.TransformPoint(v[i]);float s=b.Project(p,out float d),w=W(s,d);if(w<=0||Math.Abs(p.y-Y(s))>6)continue;float target=Y(s)+(support?-.08f:.04f);if(support&&p.y<target)continue;p.y=Mathf.Lerp(p.y,target,w);v[i]=mf.transform.InverseTransformPoint(p);count++;changed=true;}if(!changed)continue;var mesh=Object.Instantiate(mf.sharedMesh);mesh.vertices=v;mesh.RecalculateNormals();mesh.RecalculateBounds();AssetDatabase.CreateAsset(mesh,AssetDatabase.GenerateUniqueAssetPath("Assets/Track/MountainPolish/final-seam-"+mf.name.Replace('/','-')+".asset"));mf.sharedMesh=mesh;if(mf.TryGetComponent<MeshCollider>(out var mc))mc.sharedMesh=mesh;}
 for(int i=0;i<b.points.Length;i++){var p=b.points[i];float s=b.Project(p,out _);p.y=Mathf.Lerp(p.y,Y(s),W(s,0));b.points[i]=p;}EditorUtility.SetDirty(b);Physics.SyncTransforms();var road=Object.FindAnyObjectByType<RaceDirector>().road;var pavement=GameObject.Find("Ground_CR133 mountain driving surface").GetComponent<Collider>();for(int i=0;i<road.points.Length;i++){var p=road.points[i];float s=b.Project(p,out float d);if(W(s,d)<=0)continue;if(pavement.Raycast(new Ray(p+Vector3.up*5,Vector3.down),out var h,10))road.points[i]=new(p.x,h.point.y-.04f,p.z);}EditorUtility.SetDirty(road);
 EditorSceneManager.MarkSceneDirty(b.gameObject.scene);EditorSceneManager.SaveScene(b.gameObject.scene);AssetDatabase.SaveAssets();File.WriteAllText("Docs/MountainPolish/final-seam.txt","Continuous final merge grade; clamped old support below pavement. Vertices="+count+"; y380="+y0+"; y450="+y1);return "Continuous local merge grade, vertices="+count;}
}

