using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using Racer;using Object=UnityEngine.Object;
public static class InspectMountainCleanup {
 public static readonly Vector3[] Points={new(814.9f,118,68.4f),new(874.2f,113.7f,-91.2f),new(804.7f,95,-162.9f),new(826.2f,99.8f,-119.7f),new(1276.6f,109.7f,-279.4f),new(983.3f,145.4f,-302.6f),new(748.1f,85.7f,-111.2f),new(965.8f,165.7f,131.6f),new(1001.7f,163.1f,103.8f),new(885.7f,116.3f,-46.9f)};
 public static string Main(){
 if(Application.isPlaying)throw new Exception("Edit mode required");Directory.CreateDirectory("Docs/MountainCleanup");Physics.SyncTransforms();var road=Object.FindAnyObjectByType<RaceDirector>().road;road.Initialize();var branches=Object.FindObjectsByType<WoodlandRoute>();foreach(var b in branches)b.Initialize();var rows=new List<string>();var colliders=Object.FindObjectsByType<Collider>();var back=Physics.queriesHitBackfaces;Physics.queriesHitBackfaces=true;
 var go=new GameObject("Temporary diagnostic camera",typeof(Camera));var cam=go.GetComponent<Camera>();cam.CopyFrom(Camera.main);cam.enabled=false;
 for(int i=0;i<Points.Length;i++){var p=Points[i];float s=road.Project(p,out float d);var rp=road.At(s,out var f);rows.Add($"A{i+1}: {p} main s={s:F3} d={d:F3} road={rp} forward={f}");foreach(var b in branches){float bs=b.Project(p,out float bd);rows.Add($" branch {b.title} s={bs:F2} d={bd:F2} at={b.At(bs,out _)}");}
 foreach(var c in colliders.Where(c=>Vector3.Distance(c.bounds.ClosestPoint(p),p)<18).OrderBy(c=>c.name))rows.Add($" collider {c.name} {c.GetType().Name} min={c.bounds.min} max={c.bounds.max}");
 for(float offset=-15;offset<=15;offset+=1){var q=road.At(s+offset,out _);var hits=Physics.RaycastAll(q+Vector3.up*5,Vector3.down,60,1,QueryTriggerInteraction.Ignore).OrderByDescending(h=>h.point.y).ToArray();rows.Add($" probe {s+offset:F2} routeY={q.y:F3}: "+string.Join(";",hits.Select(h=>$"{h.collider.name}={h.point.y:F3}")));}
 cam.transform.SetPositionAndRotation(rp-f*7+Vector3.up*4,Quaternion.LookRotation(f*22-Vector3.up*2));cam.fieldOfView=70;var rt=new RenderTexture(1280,800,24);var prior=RenderTexture.active;cam.targetTexture=rt;cam.Render();RenderTexture.active=rt;var tex=new Texture2D(1280,800,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,1280,800),0,0);tex.Apply();File.WriteAllBytes($"Docs/MountainCleanup/A{i+1}-before.png",tex.EncodeToPNG());RenderTexture.active=prior;cam.targetTexture=null;rt.Release();Object.DestroyImmediate(tex);Object.DestroyImmediate(rt);
 }Object.DestroyImmediate(go);Physics.queriesHitBackfaces=back;File.WriteAllLines("Docs/MountainCleanup/inspection.txt",rows);File.WriteAllText("Docs/MountainCleanup/routes-before.json",Newtonsoft.Json.JsonConvert.SerializeObject(new{road=road.points.Select(p=>new[]{p.x,p.y,p.z}),branches=branches.Select(b=>new{b.title,points=b.points.Select(p=>new[]{p.x,p.y,p.z})})},Newtonsoft.Json.Formatting.Indented));return "Ten coordinate inspections and baseline views saved";
 }
}
