using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class InspectCleanupWorld {
 const string Out="Docs/WorldCleanup";
 static object P(Vector3 p)=>new{x=p.x,y=p.y,z=p.z};
 public static string Main(){if(Application.isPlaying||UnityEngine.SceneManagement.SceneManager.GetActiveScene().isDirty)throw new Exception("Saved edit mode required");EditorApplication.delayCall+=Run;return "Inspection scheduled";}
 public static string Frontage(){EditorApplication.delayCall+=()=>{var original=UnityEngine.SceneManagement.SceneManager.GetActiveScene().path;try{EditorSceneManager.OpenScene("Assets/Scenes/StreetLoopGreybox.unity");var h=GameObject.Find("Friend across street - blue circle").transform;var street=GameObject.Find("Phase 3 - Race Systems").GetComponent<RaceRoad>();street.Initialize();var road=street.At(street.Project(h.position,out _),out _);Shot("anderson-road-final",road+Vector3.up*2,h.position+Vector3.up*4,false);Shot("anderson-overhead-final",h.position+Vector3.up*90,h.position,true);File.WriteAllText(Out+"/frontage-done.txt","Final frontage captured");}catch(Exception e){File.WriteAllText(Out+"/frontage-error.txt",e.ToString());}finally{EditorSceneManager.OpenScene(original);}};return "Final frontage scheduled";}
 static void Run(){var original=UnityEngine.SceneManagement.SceneManager.GetActiveScene().path;try{EditorSceneManager.OpenScene("Assets/Scenes/StreetLoopGreybox.unity");Physics.SyncTransforms();var race=Object.FindAnyObjectByType<RaceDirector>();var house=GameObject.Find("Friend across street - blue circle").transform;var street=GameObject.Find("Phase 3 - Race Systems").GetComponent<RaceRoad>();street.Initialize();var road=street.At(street.Project(house.position,out _),out _);Shot("anderson-road",road+Vector3.up*2,house.position+Vector3.up*4,false);Shot("anderson-overhead",house.position+Vector3.up*90,house.position,true);
 var colliders=Object.FindObjectsByType<Collider>().Where(c=>!c.name.StartsWith("Ground_")&&Vector2.Distance(new(c.bounds.center.x,c.bounds.center.z),new(house.position.x,house.position.z))<65).Select(c=>new{c.name,c.isTrigger,min=P(c.bounds.min),max=P(c.bounds.max)}).ToArray();File.WriteAllText(Out+"/anderson-colliders.json",Newtonsoft.Json.JsonConvert.SerializeObject(colliders,Newtonsoft.Json.Formatting.Indented));
 var rows=new List<object>();foreach(var site in race.GetComponent<ExplorationCollection>().sites.Where(s=>s.approach=="Western gullies")){var samples=new List<object>();float low=999,high=-999;for(int x=-40;x<=40;x+=5)for(int z=-40;z<=40;z+=5){var q=site.position+new Vector3(x,0,z);var hits=Physics.RaycastAll(new(q.x,300,q.z),Vector3.down,600).Where(h=>h.collider.name.StartsWith("Ground_")).OrderBy(h=>h.distance).ToArray();if(hits.Length==0)continue;float y=hits[0].point.y;low=Mathf.Min(low,y);high=Mathf.Max(high,y);samples.Add(P(hits[0].point));}Shot("western-"+site.id,site.position+new Vector3(0,58,-48),site.position,false);rows.Add(new{site.id,site.title,minHeight=low,maxHeight=high,samples});}
 File.WriteAllText(Out+"/western-terrain.json",Newtonsoft.Json.JsonConvert.SerializeObject(rows,Newtonsoft.Json.Formatting.Indented));File.WriteAllText(Out+"/inspection-done.txt","Terrain and Anderson views captured");}catch(Exception e){File.WriteAllText(Out+"/inspection-error.txt",e.ToString());}finally{EditorSceneManager.OpenScene(original);}}
 static void Shot(string n,Vector3 p,Vector3 target,bool overhead){var go=new GameObject("Temporary inspection camera");var cam=go.AddComponent<Camera>();cam.CopyFrom(Camera.main);cam.enabled=false;cam.transform.SetPositionAndRotation(p,Quaternion.LookRotation(target-p,overhead?Vector3.forward:Vector3.up));cam.fieldOfView=65;var rt=new RenderTexture(1400,900,24);var prior=RenderTexture.active;bool fog=RenderSettings.fog;RenderSettings.fog=false;try{cam.targetTexture=rt;cam.Render();RenderTexture.active=rt;var t=new Texture2D(1400,900,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,1400,900),0,0);t.Apply();File.WriteAllBytes(Out+"/"+n+".png",t.EncodeToPNG());Object.DestroyImmediate(t);}finally{RenderTexture.active=prior;RenderSettings.fog=fog;Object.DestroyImmediate(go);rt.Release();Object.DestroyImmediate(rt);}}
}
