"""Original stylized wildlife sound design; no sampled third-party recordings."""
import math, random, struct, wave
from pathlib import Path

root=Path(__file__).resolve().parents[1]/'Assets/Audio/Wildlife'
root.mkdir(parents=True,exist_ok=True)
rate=44100
for species in ('Deer','Coyote'):
    for variant in range(2):
        rng=random.Random(7400+variant)
        duration=.95 if species=='Deer' else 3.3
        data=[]; low=0.; phase=0.
        for i in range(int(rate*duration)):
            t=i/rate; noise=rng.uniform(-1,1); low=.87*low+.13*noise
            if species=='Deer':
                # Breath burst followed by papery hoof/leaf rustle.
                burst=math.exp(-((t-.19)/.11)**2)
                rustle=sum(math.exp(-((t-p)/.04)**2) for p in (.49,.66,.79))
                value=(noise-low)*(.72*burst+.11*rustle)+low*.9*burst
            else:
                # Rising yip into a wavering short howl, with breath and harmonics.
                env=(1-math.exp(-t*15))*max(0,1-t/duration)**.55
                pitch=480+270*math.sin(min(t/1.05,1)*math.pi/2)-110*max(0,t-1.25)+18*math.sin(t*34)
                phase+=2*math.pi*pitch/rate
                value=env*(.49*math.sin(phase)+.17*math.sin(2*phase)+.065*math.sin(3*phase)+.07*low)
                value*=min(1,t*35,(duration-t)*18)
            data.append(value)
        peak=max(abs(x) for x in data)
        with wave.open(str(root/f'{species}-original-{variant+1}.wav'),'wb') as out:
            out.setparams((1,2,rate,len(data),'NONE','not compressed'))
            out.writeframes(b''.join(struct.pack('<h',int(x/peak*.88*32767)) for x in data))
(root/'REVERSE-WILDLIFE-NOTICE.txt').write_text('Deer and coyote stylized calls are original procedural sound design for Racer. Generated by Tools/Prepare-ReverseWildlifeAudio.py; no third-party samples. Existing wildlife recordings and their license remain unchanged.\n')
