using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using Racer;using Object=UnityEngine.Object;
public static class ProbeMountainCleanup {
 public static string Main(){var r=Object.FindAnyObjectByType<RaceDirector>();var road=r.road;var b=Object.FindObjectsByType<WoodlandRoute>().Single(x=>x.title=="Summit Traverse");var rows=new List<string>();
 foreach(var section in new[]{("A1",180f,245f,false),("A5",2140f,2220f,false),("A9",0f,45f,true),("A4",1555f,1605f,false),("A10",325f,385f,true),("A6",2460f,2570f,false)}){for(float s=section.Item2;s<=section.Item3;s+=2){var p=section.Item4?b.At(s,out _):road.At(s,out _);Vector3 f;if(section.Item4)b.At(s,out f);else road.At(s,out f);var right=Vector3.Cross(Vector3.up,f).normalized;foreach(float lane in new[]{-5f,-3f,0,3f,5f}){var q=p+right*lane;var hits=Physics.RaycastAll(q+Vector3.up*8,Vector3.down,24,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).OrderByDescending(h=>h.point.y);rows.Add($"{section.Item1},{s:F1},{lane},{q.x:F2},{q.y:F3},{q.z:F2}: "+string.Join(";",hits.Select(h=>$"{h.collider.name}={h.point.y:F3}")));}}}
 File.WriteAllLines("Docs/MountainCleanup/lanes-before.txt",rows);
 var boxes=Object.FindObjectsByType<BoxCollider>().Where(c=>c.name.Contains("closed late cut")||c.name.Contains("Far-side shortcut separator")||c.name.Contains("side-entry timber")).Select(c=>new{name=c.name,p=c.transform.position.ToString("F3"),scale=c.transform.lossyScale.ToString("F3"),min=c.bounds.min.ToString("F3"),max=c.bounds.max.ToString("F3")});File.WriteAllText("Docs/MountainCleanup/barriers-before.json",Newtonsoft.Json.JsonConvert.SerializeObject(boxes,Newtonsoft.Json.Formatting.Indented));
 File.WriteAllText("Docs/MountainCleanup/flights.txt",Newtonsoft.Json.JsonConvert.SerializeObject(r.GetComponent<MountainFlights>().flights,Newtonsoft.Json.Formatting.Indented,new Newtonsoft.Json.JsonSerializerSettings{ReferenceLoopHandling=Newtonsoft.Json.ReferenceLoopHandling.Ignore}));return "Lane and barrier diagnostics saved";
 }
}
