using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class ProgressiveDrain {
 static float Herm(float a,float z,float da,float dz,float len,float u)=> (2*u*u*u-3*u*u+1)*a+(u*u*u-2*u*u+u)*len*da+(-2*u*u*u+3*u*u)*z+(u*u*u-u*u)*len*dz;
 public static string Main(){EditorApplication.delayCall+=Run;return "Scheduled lower-curvature continuous drain descent";}
 static void Run(){try{EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");var b=Object.FindObjectsByType<WoodlandRoute>().Single(x=>x.title.StartsWith("Storm"));var probe=new GameObject("Temporary old drain",typeof(WoodlandRoute));var old=probe.GetComponent<WoodlandRoute>();old.points=b.points.ToArray();float y0=old.points[0].y,y35=y0-9.1f,y95=y35-19.2f,yEnd=old.At(b.undergroundEnd,out _).y;
 float H(float s){if(s<=35)return Herm(y0,y35,-.20f,-.32f,35,s/35);if(s<=95)return y35-(s-35)*.32f;if(s<=140)return Herm(y95,yEnd+.22f,-.32f,-.02f,45,(s-95)/45);if(s<b.undergroundEnd)return Herm(yEnd+.22f,yEnd,-.02f,0,b.undergroundEnd-140,(s-140)/(b.undergroundEnd-140));return old.At(s,out _).y;}
 float Delta(Vector3 p){float s=old.Project(p,out _);return H(s)-old.At(s,out _).y;}
 foreach(var name in new[]{"Ground_Culvert seamless floor","Long storm culvert walls and ceiling","Continuous shallow storm flow"}){var mf=GameObject.Find(name).GetComponent<MeshFilter>();var m=Object.Instantiate(mf.sharedMesh);var v=m.vertices;for(int i=0;i<v.Length;i++){var p=mf.transform.TransformPoint(v[i]);p.y+=Delta(p);v[i]=mf.transform.InverseTransformPoint(p);}m.vertices=v;m.RecalculateNormals();m.RecalculateBounds();AssetDatabase.CreateAsset(m,AssetDatabase.GenerateUniqueAssetPath("Assets/Track/SevenCorrections/Progressive "+name+".asset"));mf.sharedMesh=m;if(mf.GetComponent<MeshCollider>()){mf.GetComponent<MeshCollider>().sharedMesh=null;mf.GetComponent<MeshCollider>().sharedMesh=m;}}
 var root=GameObject.Find("Reverse optional forest shortcuts").transform;var atmosphere=GameObject.Find("Storm Drain atmosphere").transform;foreach(var t in root.GetComponentsInChildren<Transform>(true).Concat(atmosphere.GetComponentsInChildren<Transform>(true)).Where(t=>t.GetComponent<Renderer>()||t.GetComponent<Light>()).Distinct()){if(t.GetComponentInParent<UndergroundLife>())continue;float s=old.Project(t.position,out float d);if(d<7&&s>=0&&s<b.undergroundEnd)t.position+=Vector3.up*Delta(t.position);}
 var life=Object.FindObjectsByType<UndergroundLife>().First(x=>!x.cave);life.entrance+=Vector3.up*Delta(life.entrance);for(int i=0;i<life.rats.Length;i++){life.rats[i].position+=Vector3.up*Delta(life.rats[i].position);life.refuges[i]+=Vector3.up*Delta(life.refuges[i]);}EditorUtility.SetDirty(life);var points=b.points.ToArray();for(int i=0;i<points.Length;i++)points[i].y=H(old.Project(points[i],out _));b.points=points;EditorUtility.SetDirty(b);Object.DestroyImmediate(probe);
 Physics.SyncTransforms();int count=0;foreach(var mf in Object.FindObjectsByType<MeshFilter>().Where(x=>x.name.StartsWith("Ground_")&&x.name!="Ground_Culvert seamless floor"&&x.GetComponent<MeshCollider>()&&x.GetComponent<Renderer>().bounds.Intersects(new Bounds(new(152,52,18),new(65,50,140))))){var src=mf.sharedMesh;var v=src.vertices;var t=src.triangles;var keep=new List<int>();int removed=0;for(int i=0;i<t.Length;i+=3){var p=mf.transform.TransformPoint((v[t[i]]+v[t[i+1]]+v[t[i+2]])/3);if(p.x>109&&p.x<180&&p.z>-69&&p.z<85){float s=b.Project(p,out float d);float y=b.At(s,out _).y;float width=s<65?4.4f:3.5f;if(s>.2f&&s<b.undergroundEnd-1&&d<width&&p.y>y-1&&p.y<y+5.25f){removed++;continue;}}keep.AddRange(new[]{t[i],t[i+1],t[i+2]});}if(removed==0)continue;var m=Object.Instantiate(src);m.triangles=keep.ToArray();m.RecalculateBounds();AssetDatabase.CreateAsset(m,AssetDatabase.GenerateUniqueAssetPath("Assets/Track/SevenCorrections/Progressive drain bore clearance.asset"));mf.sharedMesh=m;mf.GetComponent<MeshCollider>().sharedMesh=m;count+=removed;}
 EditorSceneManager.MarkSceneDirty(b.gameObject.scene);EditorSceneManager.SaveScene(b.gameObject.scene);AssetDatabase.SaveAssets();File.WriteAllText("Docs/SevenCorrections/progressive-drain.txt","Entrance grade -0.20 eases to -0.32 across35m; constant slope through95m then long gradual flattening to original exit. Addresses suspension losing contact and striking bend/ceiling during descending airborne travel at27m/s. Matched all floor/shell/water/props/rats; removed "+count+" intersecting bore triangles.");}catch(Exception e){File.WriteAllText("Docs/SevenCorrections/progressive-error.txt",e.ToString());}}
}
