using System;using System.IO;using System.Linq;using System.Reflection;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class ReducePoolJump {
 public static string Main(){EditorApplication.delayCall+=Run;return "Scheduled confirmed pool-house takeoff reduction";}
 static void Run(){try{EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");Physics.SyncTransforms();var race=Object.FindAnyObjectByType<RaceDirector>();var road=race.road;road.Initialize();var c=race.GetComponent<BackyardForwardCourse>();var lip=c.flightStarts[2];var axis=c.flightDirections[2];var oldLip=lip;var landing=c.landingStations.Select(s=>road.At(s,out _)).ToArray();var basePoint=lip-axis*38;float y0=Racer.Editor.BackyardReverseAuthoring.Ground(basePoint);float y1=86.15f;var flags=BindingFlags.NonPublic|BindingFlags.Static;
 float H(float d){float u=Mathf.Clamp01(d/38);return (2*u*u*u-3*u*u+1)*y0+(u*u*u-2*u*u+u)*38*.19f+(-2*u*u*u+3*u*u)*y1+(u*u*u-u*u)*38*.08f;}
 bool Region(Vector3 p){float d=Vector3.Dot(p-basePoint,axis),side=Mathf.Abs(Vector3.Dot(p-basePoint,Vector3.Cross(Vector3.up,axis)));return d>=0&&d<=38.15f&&side<5.3f;}
 typeof(Racer.Editor.BackyardReverseAuthoring).GetMethod("Sculpt",flags).Invoke(null,new object[]{(Func<Vector3,bool>)Region,(Func<Vector3,Vector3>)(p=>{float d=Vector3.Dot(p-basePoint,axis),side=Mathf.Abs(Vector3.Dot(p-basePoint,Vector3.Cross(Vector3.up,axis)));p.y=Mathf.Lerp(p.y,H(d),1-Mathf.SmoothStep(0,1,Mathf.InverseLerp(2.65f,5.3f,side)));return p;}),"Reduced pool house takeoff"});Physics.SyncTransforms();lip.y=Racer.Editor.BackyardReverseAuthoring.Ground(lip);c.flightStarts[2]=lip;for(int i=0;i<road.points.Length;i++){var p=road.points[i];float a=Vector3.Dot(p-lip,axis);if(Region(p))p.y=Racer.Editor.BackyardReverseAuthoring.Ground(p);else if(a>0&&a<Vector3.Dot(landing[2]-lip,axis)&&Mathf.Abs(Vector3.Dot(p-lip,Vector3.Cross(Vector3.up,axis)))<4)p.y=Mathf.Lerp(lip.y,landing[2].y,a/Vector3.Dot(landing[2]-lip,axis));road.points[i]=p;}
 typeof(RaceRoad).GetField("distance",BindingFlags.NonPublic|BindingFlags.Instance).SetValue(road,null);road.Initialize();for(int i=0;i<c.launchStations.Length;i++){c.launchStations[i]=road.Project(c.flightStarts[i],out _);c.landingStations[i]=road.Project(landing[i],out _);}var layout=Object.FindAnyObjectByType<ForestLayout>();layout.jumpStarts=c.launchStations;layout.jumpEnds=c.landingStations;typeof(Racer.Editor.BackyardReverseAuthoring).GetMethod("Trees",flags).Invoke(null,new object[]{(Func<Collider,bool>)(x=>false),(Func<Collider,bool>)(x=>Region(x.bounds.center))});
 foreach(var mf in Object.FindObjectsByType<MeshFilter>().Where(m=>m.name=="Reverse teal ground arrow")){var src=mf.sharedMesh;var v=src.vertices;bool changed=false;for(int i=0;i<v.Length;i++){var p=mf.transform.TransformPoint(v[i]);if(Region(p)){p.y=Racer.Editor.BackyardReverseAuthoring.Ground(p)+.03f;v[i]=mf.transform.InverseTransformPoint(p);changed=true;}}if(changed){var m=Object.Instantiate(src);m.vertices=v;m.RecalculateNormals();m.RecalculateBounds();AssetDatabase.CreateAsset(m,AssetDatabase.GenerateUniqueAssetPath("Assets/Track/SevenCorrections/Reduced jump guidance.asset"));mf.sharedMesh=m;}}
 race.courseId="backyard-reverse-v4-continuous-shortcuts";EditorUtility.SetDirty(race);EditorUtility.SetDirty(road);EditorUtility.SetDirty(c);EditorUtility.SetDirty(layout);EditorSceneManager.MarkSceneDirty(race.gameObject.scene);EditorSceneManager.SaveScene(race.gameObject.scene);AssetDatabase.SaveAssets();File.WriteAllText("Docs/SevenCorrections/pool-jump.txt",$"Dan confirmed main pool-house jump, not the ground crest. Lip {oldLip:F3} -> {lip:F3}; final slope 0.08 (formerly about 0.24), base {basePoint:F3} Y={y0:F3}; intended landing unchanged; trees and arrows reseated, flight/recovery metadata follows new height.");}catch(Exception e){File.WriteAllText("Docs/SevenCorrections/pool-error.txt",e.ToString());}}
}
