using System;using System.IO;using System.Linq;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class RefineUndergroundPolish {
 public static string Main(){
 EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");Physics.SyncTransforms();var text=GameObject.Find("LOGGING RIDGE").transform;var board=GameObject.Find("Logging Ridge sign board").transform;var post=GameObject.Find("Logging Ridge grounded sign post").transform;var delta=-text.forward*4;var foot=post.position-Vector3.up*1.2f+delta;float y=Physics.RaycastAll(foot+Vector3.up*5,Vector3.down,10,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).OrderBy(h=>Mathf.Abs(h.point.y-foot.y)).First().point.y;delta.y=y-(post.position.y-1.2f);foreach(var t in new[]{text,board,post})t.position+=delta;EditorSceneManager.MarkSceneDirty(text.gameObject.scene);EditorSceneManager.SaveScene(text.gameObject.scene);
 EditorSceneManager.OpenScene("Assets/Scenes/ForestLoopReverse.unity");Physics.SyncTransforms();var root=GameObject.Find("Forest Reverse natural cave atmosphere").transform;var shell=GameObject.Find("Echo Cave enclosed rock").GetComponent<Collider>();var b=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title=="Fern Gully");var rock=AssetDatabase.LoadAssetAtPath<Material>("Assets/Track/UndergroundPolish/Fallen cave stone.mat");var wood=AssetDatabase.LoadAssetAtPath<Material>("Assets/Track/UndergroundPolish/Cave exposed roots.mat");var irregular=AssetDatabase.LoadAssetAtPath<Mesh>("Assets/Vegetation/Phase6/IrregularCrown.asset");
 void Part(string n,Vector3 p,Vector3 scale,Quaternion q,Material mat,bool stone){var go=GameObject.CreatePrimitive(PrimitiveType.Cube);go.name=n;go.transform.SetParent(root);go.transform.SetPositionAndRotation(p,q);go.transform.localScale=scale;go.GetComponent<Renderer>().sharedMaterial=mat;Object.DestroyImmediate(go.GetComponent<Collider>());if(stone&&irregular)go.GetComponent<MeshFilter>().sharedMesh=irregular;}
 int added=0;for(float s=281.5f;s<294;s+=1.8f){var p=b.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;foreach(int edge in new[]{-1,1}){
 var at=p+side*edge*4.3f;var ground=Physics.RaycastAll(at+Vector3.up*3,Vector3.down,6,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).OrderBy(h=>Mathf.Abs(h.point.y-at.y)).ToArray();if(ground.Length>0){at.y=ground[0].point.y;Part("Natural cave shoulder outcrop",at+Vector3.up*.2f,new(.6f,.55f,.85f),Quaternion.Euler(0,s*7,0),rock,true);added++;}
 at=p+side*edge*3.7f;if(shell.Raycast(new Ray(at+Vector3.up*2,Vector3.up),out var roof,30)){Part("Cave tapered ceiling stone",roof.point-Vector3.up*.35f,new(.5f,1.2f,.55f),Quaternion.Euler(180,s*13,0),rock,true);Part("Cave dangling root",roof.point-Vector3.up*.7f,new(.08f,1.55f,.08f),Quaternion.Euler(13,s*7,12),wood,false);Part("Cave branching root",roof.point-Vector3.up*.25f+side*.3f,new(.08f,.7f,.08f),Quaternion.Euler(0,0,55),wood,false);added+=3;}
 }}EditorSceneManager.MarkSceneDirty(root.gameObject.scene);EditorSceneManager.SaveScene(root.gameObject.scene);AssetDatabase.SaveAssets();File.AppendAllText("Docs/UndergroundPolish/cave-span.txt",$"\nAdded {added} cave-local shoulder/ceiling rocks and roots, all non-colliding and outside central corridor.");EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");AssetDatabase.Refresh();return "Sign clear of checkpoint upright; mottled surfaces and cave-local natural details";
 }
}
