EditorApplication.delayCall+=()=>{try{
var scene=UnityEditor.SceneManagement.EditorSceneManager.OpenScene(Racer.Editor.BackyardForwardAuthoring.ScenePath);var race=UnityEngine.Object.FindAnyObjectByType<Racer.RaceDirector>();race.road.Initialize();var course=race.GetComponent<Racer.BackyardForwardCourse>();
float Blend(float a,float b,float t)=>Mathf.SmoothStep(0,1,Mathf.InverseLerp(a,b,t));
float Delta(Vector3 p){float result=0;for(int j=0;j<3;j++){var axis=course.flightDirections[j];var q=p-course.flightStarts[j];float along=Vector3.Dot(q,axis),side=Math.Abs(Vector3.Dot(q,Vector3.Cross(Vector3.up,axis)));if(along>0||along<-42||side>6)continue;float h=j==0?5.2f:j==1?3.6f:2.3f;float oldRun=j==0?30:26;float old=along>=-oldRun?h*Mathf.Pow((along+oldRun)/oldRun,2):0;float next=h*Mathf.Pow((along+42)/42,2);float width=j==0?3.5f:2.65f;result+=(next-old)*(1-Blend(width,width+2,side));}return result;}
int changed=0;foreach(var mf in GameObject.Find("Memory loop - north is +Z").GetComponentsInChildren<MeshFilter>()){if(!AssetDatabase.GetAssetPath(mf.sharedMesh).StartsWith(Racer.Editor.BackyardForwardAuthoring.Folder+"/Ground_"))continue;var mesh=mf.sharedMesh;var v=mesh.vertices;bool edit=false;for(int i=0;i<v.Length;i++){var p=mf.transform.TransformPoint(v[i]);float dy=Delta(p);if(Math.Abs(dy)<.00001f)continue;p.y+=dy;v[i]=mf.transform.InverseTransformPoint(p);edit=true;changed++;}if(edit){mesh.vertices=v;mesh.RecalculateNormals();mesh.RecalculateBounds();EditorUtility.SetDirty(mesh);mf.GetComponent<MeshCollider>().sharedMesh=null;mf.GetComponent<MeshCollider>().sharedMesh=mesh;}}
var points=race.road.points;for(int i=0;i<points.Length;i++)points[i].y+=Delta(points[i]);var obj=race.road.gameObject;UnityEngine.Object.DestroyImmediate(race.road);race.road=obj.AddComponent<Racer.RaceRoad>();race.road.forestTrail=true;race.road.points=points;race.road.Initialize();for(int j=0;j<3;j++){var landing=points.OrderBy(p=>Math.Abs(Vector3.Dot(p-course.flightStarts[j],course.flightDirections[j])-(j==0?51.15f:j==1?46:35))+Math.Abs(Vector3.Dot(p-course.flightStarts[j],Vector3.Cross(Vector3.up,course.flightDirections[j])))*10).First();course.launchStations[j]=race.road.Project(course.flightStarts[j],out _);course.landingStations[j]=race.road.Project(landing,out _);}
var layout=UnityEngine.Object.FindAnyObjectByType<Racer.ForestLayout>();for(int j=0;j<3;j++){layout.jumpStarts[j]=course.launchStations[j];layout.jumpEnds[j]=course.landingStations[j];}
bool Clearance(Vector3 p){for(int j=0;j<3;j++){var q=p-course.flightStarts[j];float along=Vector3.Dot(q,course.flightDirections[j]);float side=Math.Abs(Vector3.Dot(q,Vector3.Cross(Vector3.up,course.flightDirections[j])));if(along>=-44&&along<=(j==0?73:j==1?72:62)&&side<7.5f)return true;}return false;}
int removed=0;foreach(var c in UnityEngine.Object.FindObjectsByType<Collider>().Where(c=>c.name.IndexOf("tree",StringComparison.OrdinalIgnoreCase)>=0||c.name.IndexOf("trunk",StringComparison.OrdinalIgnoreCase)>=0).ToArray())if(Clearance(c.bounds.center)){UnityEngine.Object.DestroyImmediate(c.gameObject);removed++;}
int components=0,batch=0;foreach(var mf in GameObject.Find("Woods replacing later subdivisions").GetComponentsInChildren<MeshFilter>()){
var mesh=mf.sharedMesh;var v=mesh.vertices;var tris=mesh.triangles;var parent=Enumerable.Range(0,v.Length).ToArray();int Find(int n){while(parent[n]!=n){parent[n]=parent[parent[n]];n=parent[n];}return n;}void Union(int a,int b){parent[Find(a)]=Find(b);}
var welded=new Dictionary<Vector3Int,int>();for(int i=0;i<v.Length;i++){var key=Vector3Int.RoundToInt(v[i]*1000);if(welded.TryGetValue(key,out int other))Union(i,other);else welded[key]=i;}for(int i=0;i<tris.Length;i+=3){Union(tris[i],tris[i+1]);Union(tris[i],tris[i+2]);}
var cut=new HashSet<int>();for(int i=0;i<v.Length;i++)if(Clearance(mf.transform.TransformPoint(v[i])))cut.Add(Find(i));if(cut.Count==0)continue;var kept=new List<int>();for(int i=0;i<tris.Length;i+=3)if(!cut.Contains(Find(tris[i])))kept.AddRange(new[]{tris[i],tris[i+1],tris[i+2]});var copy=UnityEngine.Object.Instantiate(mesh);copy.SetTriangles(kept,0);copy.RecalculateBounds();AssetDatabase.CreateAsset(copy,Racer.Editor.BackyardForwardAuthoring.Folder+"/Flight-tree-clearance-"+(batch++)+".asset");mf.sharedMesh=copy;components+=cut.Count;
}
Physics.SyncTransforms();UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(scene);UnityEditor.SceneManagement.EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();Racer.Editor.BackyardForwardAuthoring.Export();System.IO.File.WriteAllText("Docs/BackyardForward/flight-refinement.txt",$"Lengthened integrated takeoff curvature to 42m; {changed} terrain samples; {removed} additional individual flight-corridor tree removals and {components} connected visual components cleared for actual airborne clearance/visibility. Normal wooded trail unchanged. Existing scene/property assets untouched.");
}catch(Exception e){System.IO.File.WriteAllText("Docs/BackyardForward/flight-refinement-error.txt",e.ToString());}};return "Scheduled local takeoff transition and airborne tree clearance correction";
