using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class RefineSeven {
 const string F="Assets/Track/SevenCorrections/";static int n;
 static Mesh Store(Mesh m,string label){m.RecalculateNormals();m.RecalculateBounds();AssetDatabase.CreateAsset(m,AssetDatabase.GenerateUniqueAssetPath(F+label+".asset"));return m;}
 public static string Main(){AssetDatabase.Refresh();EditorSceneManager.OpenScene("Assets/Scenes/LakeWoods.unity");var b=Object.FindObjectsByType<WoodlandRoute>().Single(x=>x.title=="Echo Cave");var root=GameObject.Find("Echo Cave enclosed rock").transform.parent;var rng=new System.Random(57001);var cube=GameObject.CreatePrimitive(PrimitiveType.Cube).GetComponent<MeshFilter>();var source=cube.sharedMesh;Object.DestroyImmediate(cube.gameObject);
 // Unique angular forms instead of box repeats; welded corner jitter keeps every rock closed.
 foreach(var mf in root.GetComponentsInChildren<MeshFilter>().Where(m=>m.name=="Angular cave wall ledge"||m.name=="Hanging angular cave formation"||m.name=="Fallen cave stone")){var v=source.vertices.ToArray();var shifts=new Dictionary<Vector3,Vector3>();for(int i=0;i<v.Length;i++){if(!shifts.TryGetValue(v[i],out var p)){p=v[i]+new Vector3((float)rng.NextDouble()-.5f,(float)rng.NextDouble()-.5f,(float)rng.NextDouble()-.5f)*.48f;shifts[v[i]]=p;}v[i]=p;}var m=Object.Instantiate(source);m.vertices=v;mf.sharedMesh=Store(m,"Angular rock "+(n++));mf.transform.localScale=Vector3.Scale(mf.transform.localScale,new Vector3(.8f+(float)rng.NextDouble()*.5f,.65f+(float)rng.NextDouble()*.8f,.6f+(float)rng.NextDouble()*.85f));mf.transform.position+=mf.transform.forward*((float)rng.NextDouble()*2-1);}
 foreach(var mf in root.GetComponentsInChildren<MeshFilter>().Where(m=>m.name=="Shallow cave puddle"||m.name=="Cave gravel floor patch")){var v=new List<Vector3>{Vector3.zero};var tr=new List<int>();int count=9;for(int i=0;i<count;i++){float a=i*2*Mathf.PI/count,r=.34f+(float)rng.NextDouble()*.2f;v.Add(new(Mathf.Sin(a)*r,0,Mathf.Cos(a)*r));}for(int i=1;i<=count;i++)tr.AddRange(new[]{0,i,i==count?1:i+1});var m=new Mesh();m.SetVertices(v);m.SetTriangles(tr,0);mf.sharedMesh=Store(m,"Irregular damp patch "+(n++));}
 Physics.SyncTransforms();var floorMat=AssetDatabase.LoadAssetAtPath<Material>(F+"Cave gravel and stone.mat");var vs=new List<Vector3>();var cs=new List<Color>();var ts=new List<int>();bool prev=false;int row=0;for(float s=60;s<=479;s+=1){if(s>286&&s<384){prev=false;continue;}var p=b.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;for(int j=0;j<13;j++){var q=p+side*((j-6)*.7f);var hits=Physics.RaycastAll(q+Vector3.up*3,Vector3.down,12,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).OrderBy(h=>h.distance).ToArray();q.y=(hits.Length>0?hits[0].point.y:q.y)+.022f;vs.Add(q);float val=.68f+.25f*Mathf.PerlinNoise(q.x*1.8f,q.z*1.8f)+.13f*Mathf.Sin(s*.21f+j);cs.Add(new(val,val,val*.92f,1));}if(prev)for(int j=0;j<12;j++){int a=(row-1)*13+j;ts.AddRange(new[]{a,a+13,a+1,a+1,a+13,a+14});}row++;prev=true;}var mesh=new Mesh{indexFormat=UnityEngine.Rendering.IndexFormat.UInt32};mesh.SetVertices(vs);mesh.SetTriangles(ts,0);mesh.SetColors(cs);var ground=new GameObject("Cave natural gravel floor",typeof(MeshFilter),typeof(MeshRenderer));ground.transform.SetParent(root);ground.GetComponent<MeshFilter>().sharedMesh=Store(mesh,"Cave natural gravel floor");ground.GetComponent<Renderer>().sharedMaterial=floorMat;EditorSceneManager.MarkSceneDirty(root.gameObject.scene);EditorSceneManager.SaveScene(root.gameObject.scene);AssetDatabase.SaveAssets();
 EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");root=GameObject.Find("Reverse optional forest shortcuts").transform;b=Object.FindObjectsByType<WoodlandRoute>().Single(x=>x.title.StartsWith("Storm"));foreach(var t in root.Cast<Transform>().Where(t=>t.name=="Continuous shallow storm water").ToArray())Object.DestroyImmediate(t.gameObject);var water=new Material(Shader.Find("Racer/ShallowDrainWater"));AssetDatabase.CreateAsset(water,F+"Moving shallow stormwater.mat");vs=new();ts=new();int rows=Mathf.CeilToInt((b.undergroundEnd-b.undergroundStart-6)/.5f);for(int i=0;i<=rows;i++){float s=Mathf.Lerp(b.undergroundStart+3,b.undergroundEnd-3,i/(float)rows);var p=b.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;float w=1.25f+.35f*Mathf.Sin(s*.17f);vs.Add(p-side*w+Vector3.up*.032f);vs.Add(p+side*w+Vector3.up*.032f);if(i>0){int a=(i-1)*2;ts.AddRange(new[]{a,a+2,a+1,a+1,a+2,a+3});}}mesh=new Mesh();mesh.SetVertices(vs);mesh.SetTriangles(ts,0);mesh.uv=vs.Select(p=>new Vector2(p.x,p.z)).ToArray();var flow=new GameObject("Continuous shallow storm flow",typeof(MeshFilter),typeof(MeshRenderer));flow.transform.SetParent(root);flow.GetComponent<MeshFilter>().sharedMesh=Store(mesh,"Continuous shallow storm flow");flow.GetComponent<Renderer>().sharedMaterial=water;EditorSceneManager.MarkSceneDirty(root.gameObject.scene);EditorSceneManager.SaveScene(root.gameObject.scene);AssetDatabase.SaveAssets();return "Natural rock silhouettes, gravel floor and continuous rippling stormwater refined";
 }
}
