using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class RefineReverseSupport {
public static string Main(){EditorApplication.delayCall+=()=>{try{EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");var race=Object.FindAnyObjectByType<RaceDirector>();var road=race.road;road.Initialize();var course=race.GetComponent<BackyardForwardCourse>();var land=course.landingStations.Select(s=>road.At(s,out _)).ToArray();var report=new List<string>();
float S(float a,float b,float v)=>Mathf.SmoothStep(0,1,Mathf.InverseLerp(a,b,v));
float Near(Vector3 p,out Vector3 at){float best=float.MaxValue;at=default;for(int i=1;i<road.points.Length;i++){var a=road.points[i-1];var f=road.points[i]-a;f.y=0;var q=p-a;q.y=0;float t=Mathf.Clamp01(Vector3.Dot(q,f)/Mathf.Max(.001f,f.sqrMagnitude));float d=(q-f*t).sqrMagnitude;if(d<best){best=d;at=Vector3.Lerp(a,road.points[i],t);}}return Mathf.Sqrt(best);}
foreach(var mf in Object.FindObjectsByType<MeshFilter>().Where(m=>m.name=="Ground_560_320"||m.name=="Ground_560_400")){var mesh=mf.sharedMesh;if(!AssetDatabase.GetAssetPath(mesh).StartsWith("Assets/Track/BackyardReverseCorrections/"))throw new Exception("Owned copied mesh required");var v=mesh.vertices;int count=0;for(int i=0;i<v.Length;i++){var p=mf.transform.TransformPoint(v[i]);float y=p.y;
if(p.x>=402&&p.x<=448&&p.z>72&&p.z<93){float dist=Near(p,out _);float w=S(402,410,p.x)*(1-S(440,448,p.x))*(1-S(3.1f,6,dist));p.y=Mathf.Lerp(p.y,84.4f-.0038f*(p.x-425)*(p.x-425),w);}
if(p.x>=346&&p.x<=391&&p.z>-18&&p.z<5){var axis=new Vector3(1,0,.2f).normalized;float side=Mathf.Abs(Vector3.Dot(p-new Vector3(389,0,-3.1f),Vector3.Cross(Vector3.up,axis)));float w=S(346,357,p.x)*(1-S(3.2f,5.5f,side));float d=(p.x-345.98f)/axis.x;float target=p.x<=388.6f?80.66f+.14f*d+.05f/45*d*d:79.1f+(p.x-389)*.12f;p.y=Mathf.Lerp(p.y,target,w);}
if(Mathf.Abs(p.y-y)>.0001f){v[i]=mf.transform.InverseTransformPoint(p);count++;}}
mesh.vertices=v;mesh.RecalculateNormals();mesh.RecalculateBounds();mf.GetComponent<MeshCollider>().sharedMesh=null;mf.GetComponent<MeshCollider>().sharedMesh=mesh;EditorUtility.SetDirty(mesh);report.Add(mf.name+" corrected vertices="+count);}
Physics.SyncTransforms();for(int i=0;i<road.points.Length;i++){var p=road.points[i];if(p.x>=402&&p.x<=448&&p.z>72&&p.z<93||p.x>=346&&p.x<=388.6f&&p.z>-18&&p.z<5){p.y=Racer.Editor.BackyardReverseAuthoring.Ground(p);road.points[i]=p;}}var lip=new Vector3(388.6f,0,-3.18f);lip.y=Racer.Editor.BackyardReverseAuthoring.Ground(lip);course.flightStarts[2]=lip;typeof(RaceRoad).GetField("distance",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).SetValue(road,null);road.Initialize();for(int j=0;j<3;j++){course.launchStations[j]=road.Project(course.flightStarts[j],out _);course.landingStations[j]=road.Project(land[j],out _);}var layout=Object.FindAnyObjectByType<ForestLayout>();layout.jumpStarts=course.launchStations;layout.jumpEnds=course.landingStations;EditorSceneManager.MarkSceneDirty(UnityEngine.SceneManagement.SceneManager.GetActiveScene());EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());AssetDatabase.SaveAssets();Racer.Editor.BackyardReverseAuthoring.ExportReverse();File.WriteAllLines("Docs/BackyardReverseCorrections/support-refinement.txt",report);}catch(Exception e){File.WriteAllText("Docs/BackyardReverseCorrections/support-refinement-error.txt",e.ToString());}};return "Remove takeoff deceleration lip and locally round the northern terrain join";}}
