using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class ReviseBackyardShortcuts {
 const string F="Assets/Track/BackyardShortcuts/";static Transform root;static Material wood,dark,dirt,leaf;static RaceDirector race;static List<string> report=new();
 static float Ground(Vector3 p)=>Physics.RaycastAll(new Vector3(p.x,250,p.z),Vector3.down,500,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).OrderBy(h=>h.distance).First().point.y;
 static Material Mat(string n,Color c){var m=AssetDatabase.LoadAssetAtPath<Material>(F+n+".mat");if(!m){m=new Material(wood);m.name=n;m.color=c;AssetDatabase.CreateAsset(m,F+n+".mat");}return m;}
 static Mesh Save(string n,Mesh mesh){mesh.RecalculateNormals();mesh.RecalculateBounds();var old=AssetDatabase.LoadAssetAtPath<Mesh>(F+n+".asset");if(old){EditorUtility.CopySerialized(mesh,old);Object.DestroyImmediate(mesh);return old;}AssetDatabase.CreateAsset(mesh,F+n+".asset");return mesh;}
 static GameObject Part(string n,Vector3 p,Vector3 scale,Quaternion q,Material m,bool solid=false){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=n;g.transform.SetParent(root);g.transform.SetPositionAndRotation(p,q);g.transform.localScale=scale;g.GetComponent<Renderer>().sharedMaterial=m;if(!solid)Object.DestroyImmediate(g.GetComponent<Collider>());return g;}
 static void Beam(string n,Vector3 a,Vector3 b,float w,Material m=null)=>Part(n,(a+b)/2,new(w,w,Vector3.Distance(a,b)),Quaternion.LookRotation(b-a),m?m:dark);
 static float Hermite(float x,float a,float b,float ya,float yb,float ma,float mb){float t=Mathf.InverseLerp(a,b,x),t2=t*t,t3=t2*t;return (2*t3-3*t2+1)*ya+(t3-2*t2+t)*(b-a)*ma+(-2*t3+3*t2)*yb+(t3-t2)*(b-a)*mb;}
 static void Heights(WoodlandRoute b,Func<float,float> y){float s=0;var old=b.points.ToArray();for(int i=0;i<old.Length;i++){if(i>0)s+=Vector2.Distance(new(old[i].x,old[i].z),new(old[i-1].x,old[i-1].z));b.points[i].y=y(s);}EditorUtility.SetDirty(b);}
 static GameObject Surface(string n,WoodlandRoute b,float start,float end,Func<float,float> width,Material m,bool visual=true){var v=new List<Vector3>();var tri=new List<int>();int count=Mathf.CeilToInt((end-start)/.4f);for(int i=0;i<=count;i++){float s=Mathf.Lerp(start,end,(float)i/count);var p=b.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;v.Add(p-side*width(s)/2);v.Add(p+side*width(s)/2);if(i>0){int k=(i-1)*2;tri.AddRange(new[]{k,k+2,k+1,k+1,k+2,k+3});}}var mesh=new Mesh();mesh.SetVertices(v);mesh.SetTriangles(tri,0);mesh=Save(n,mesh);var g=new GameObject(n);g.transform.SetParent(root);g.AddComponent<MeshCollider>().sharedMesh=mesh;if(visual){g.AddComponent<MeshFilter>().sharedMesh=mesh;g.AddComponent<MeshRenderer>().sharedMaterial=m;}return g;}
 static void Planks(WoodlandRoute b,float start,float end,Func<float,float> width,string name){int i=0;for(float s=start+.27f;s<end;s+=.57f){var p=b.At(s,out var f);float w=width(s);Part(name,p-Vector3.up*.055f,new(w+(i%3)*.07f,.11f,.53f),Quaternion.LookRotation(f),i++%4==0?dark:wood);}}
 static void TreeAnchor(WoodlandRoute b,float s,float width){var p=b.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;var trees=Object.FindObjectsByType<Collider>(FindObjectsSortMode.None).Where(c=>(c.name.ToLower().Contains("tree")||c.name.ToLower().Contains("trunk"))&&c.bounds.max.y>p.y+.5f&&Mathf.Abs(Vector3.Dot(c.bounds.center-p,side))>width/2+.5f).OrderBy(c=>Vector2.Distance(new(c.bounds.center.x,c.bounds.center.z),new(p.x,p.z))).ToArray();if(trees.Length==0)throw new Exception("No tree for platform");var tree=trees[0];var anchor=new Vector3(tree.bounds.center.x,p.y-.25f,tree.bounds.center.z);if(Vector2.Distance(new(anchor.x,anchor.z),new(p.x,p.z))>11)throw new Exception("Tree anchor too distant");foreach(float sign in new[]{-1f,1f}){var edge=p+f*1.6f*sign-Vector3.up*.16f;Beam("Kid-built tree bearer",anchor,edge,.21f);Beam("Crude brace to existing tree",anchor-Vector3.up*1.9f,edge,.17f);}Part("Timber strapped around existing trunk",anchor,new(1.6f,.22f,1.6f),Quaternion.identity,dark);report.Add($"Platform {s}: anchored to {tree.name} at {anchor}");}
 static void Brush(WoodlandRoute b,float start,float end,float radius){var g=new GameObject(b.title+" traversable dense undergrowth");g.transform.SetParent(root);var brush=g.AddComponent<ShortcutUndergrowth>();brush.protectedMain=race.road;brush.radius=radius;var centres=new List<Vector3>();for(float s=start;s<=end;s+=4)centres.Add(b.At(s,out _));brush.centres=centres.ToArray();var temp=GameObject.CreatePrimitive(PrimitiveType.Sphere);var source=temp.GetComponent<MeshFilter>().sharedMesh;var combines=new List<CombineInstance>();var random=new System.Random(b.title.Length*137);float minX=centres.Min(p=>p.x)-radius,maxX=centres.Max(p=>p.x)+radius,minZ=centres.Min(p=>p.z)-radius,maxZ=centres.Max(p=>p.z)+radius;for(float x=minX;x<maxX;x+=2.2f)for(float z=minZ;z<maxZ;z+=2.2f){var p=new Vector3(x+(float)random.NextDouble(),0,z+(float)random.NextDouble());float coverage=brush.Coverage(p);if(coverage<.18f)continue;float s=b.Project(p,out float lateral);if(b.title.StartsWith("Abandoned")&&s<43&&lateral<4)continue;p.y=Ground(p);float h=1.0f+(float)random.NextDouble()*1.1f;combines.Add(new CombineInstance{mesh=source,transform=Matrix4x4.TRS(p+Vector3.up*h*.48f,Quaternion.Euler(0,random.Next(360),0),new Vector3(2.9f,h,2.6f))});}
 var mesh=new Mesh{indexFormat=UnityEngine.Rendering.IndexFormat.UInt32};mesh.CombineMeshes(combines.ToArray());mesh=Save(b.title+" dense brush",mesh);g.AddComponent<MeshFilter>().sharedMesh=mesh;g.AddComponent<MeshRenderer>().sharedMaterial=leaf;Object.DestroyImmediate(temp);report.Add($"{b.title}: {combines.Count} overlapping collider-free bushes, radius {radius}");
 }
 public static string Main(){if(Application.isPlaying||SceneManagerDirty())throw new Exception("Saved edit mode required");EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardForward.unity");race=Object.FindAnyObjectByType<RaceDirector>();root=GameObject.Find("Backyard optional forest shortcuts").transform;wood=AssetDatabase.LoadAssetAtPath<Material>(F+"Weathered cedar.mat");dark=AssetDatabase.LoadAssetAtPath<Material>(F+"Old dark timber.mat");dirt=Mat("Tree jump packed earth",new(.30f,.24f,.13f));leaf=Mat("Dense forest undergrowth",new(.15f,.25f,.075f));
 var tree=Object.FindObjectsByType<WoodlandRoute>().First(b=>b.title=="Tree-Top Trail");var cabin=Object.FindObjectsByType<WoodlandRoute>().First(b=>b.title=="Abandoned Cabin Jump");
 // Preserve route objects/signs and the original forest approach/landing ground markings.
 foreach(Transform t in root.Cast<Transform>().ToArray()){if(t.GetComponent<WoodlandRoute>()||t.name.Contains("sign")||t.name=="Cabin wooded approach"||t.name=="Cabin wooded landing and return")continue;Object.DestroyImmediate(t.gameObject);}
 float baseY=Ground(tree.At(15,out _));float lip=baseY+.52f;
 float TreeY(float s){if(s<15)return Ground(tree.At(s,out _));if(s<29)return Hermite(s,15,29,baseY,lip,-.1f,.09f);if(s<48)return lip+.08f+Mathf.Max(0,s-33)*.04f;if(s<60)return Hermite(s,48,60,lip+.68f,lip+.08f,.04f,-.16f);if(s<78)return Hermite(s,60,78,lip+.08f,55.6f,-.16f,-.32f);if(s<94)return Hermite(s,78,94,55.6f,49.8f,-.32f,-.38f);if(s<98)return Hermite(s,94,98,49.8f,49f,-.38f,0);return Ground(tree.At(s,out _));}
 Heights(tree,TreeY);tree.entrySpeed=25;tree.entrySpeedDistance=49;tree.recommendedSpeed=20;tree.halfWidth=1.65f;
 var earth=Surface("Takeoff - Short treehouse dirt jump",tree,15,29,s=>Mathf.Lerp(2.5f,4.5f,Mathf.InverseLerp(15,21,s)),dirt);
 // Visible earth skirts make the local ramp a supported dirt mound, without changing terrain.
 var rv=earth.GetComponent<MeshFilter>().sharedMesh.vertices;var skirtV=new List<Vector3>();var skirtT=new List<int>();for(int side=0;side<2;side++){for(int i=side;i<rv.Length;i+=2){var p=rv[i];skirtV.Add(p);var q=p;q.y=Ground(q)-.05f;skirtV.Add(q);if(i>side){int k=skirtV.Count-4;skirtT.AddRange(new[]{k,k+1,k+2,k+1,k+3,k+2,k+2,k+1,k,k+2,k+3,k+1});}}}var skirt=new Mesh();skirt.SetVertices(skirtV);skirt.SetTriangles(skirtT,0);skirt=Save("Dirt jump grounded sides",skirt);var sg=new GameObject("Dirt jump grounded sides");sg.transform.SetParent(root);sg.AddComponent<MeshFilter>().sharedMesh=skirt;sg.AddComponent<MeshRenderer>().sharedMaterial=dirt;sg.AddComponent<MeshCollider>().sharedMesh=skirt;
 float Width(float s){if(s<=46)return 5.8f;if(s<49)return Mathf.Lerp(5.8f,3.3f,(s-46)/3);if(s>=56&&s<=61||s>=74&&s<=79)return 4.8f;return 3.3f;}
 Surface("Landing - Treehouse platforms and narrow bridges",tree,33,98,Width,wood);Planks(tree,33,98,Width,"Mismatched hand-nailed treehouse board");foreach(float s in new[]{40f,58f,76f,92f})TreeAnchor(tree,s,Width(s));
 foreach(float s in new[]{57f,75f}){var p=tree.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;foreach(float sign in new[]{-1f,1f}){var a=p+side*2.5f+f*sign*1.5f;Beam("Short homemade railing post",a,a+Vector3.up*.85f,.09f); }Beam("Short homemade handrail",p+side*2.5f-f*1.5f+Vector3.up*.85f,p+side*2.5f+f*1.5f+Vector3.up*.85f,.10f);}
 float foot=Ground(cabin.At(22,out _));float roofStart=foot+3.0f;float CabinY(float s){if(s<22)return Ground(cabin.At(s,out _));if(s<25)return Hermite(s,22,25,foot,foot+.76f,.15f,.32f);if(s<=41)return foot+.76f+(s-25)*.32f;return Ground(cabin.At(s,out _));}
 Heights(cabin,CabinY);cabin.entrySpeed=34;cabin.entrySpeedDistance=46;cabin.recommendedSpeed=34;
 // One welded strip through the board/roof junction; no doubled faces, seam or lip.
 Surface("Takeoff - Leaning boards through cabin roof",cabin,22,41,s=>s<32?3.3f:6.4f,wood,false);
 for(int i=0;i<6;i++){float offset=(i-2.5f)*.55f;var verts=new List<Vector3>();var tris=new List<int>();for(int j=0;j<=40;j++){float s=Mathf.Lerp(22,32,j/40f);var p=cabin.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;verts.Add(p+side*(offset-.26f));verts.Add(p+side*(offset+.26f));if(j>0){int k=(j-1)*2;tris.AddRange(new[]{k,k+2,k+1,k+1,k+2,k+3});}}var m=new Mesh();m.SetVertices(verts);m.SetTriangles(tris,0);m=Save("Leaning weathered board "+i,m);var g=new GameObject("Long loose leaning board "+i);g.transform.SetParent(root);g.AddComponent<MeshFilter>().sharedMesh=m;g.AddComponent<MeshRenderer>().sharedMaterial=i%2==0?dark:wood;}
 // Render roof separately, but the welded strip above owns all top collision.
 var roof=Surface("Abandoned cabin modest shed roof",cabin,32,41,s=>6.4f,wood);Object.DestroyImmediate(roof.GetComponent<Collider>());Planks(cabin,32,41,s=>6.4f,"Cabin weathered roof board");
 for(float s=32.2f;s<40.9f;s+=.62f){var p=cabin.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;foreach(float sign in new[]{-1f,1f}){var top=p+side*sign*3.0f;float low=Ground(top)-.1f;Part("Abandoned cabin wall",new(top.x,(low+p.y-.22f)/2,top.z),new(.16f,p.y-.22f-low,.60f),Quaternion.LookRotation(f),wood,true);}}
 foreach(float s in new[]{32.2f,40.8f}){var p=cabin.At(s,out var f);float low=Ground(p)-.12f;Part("Cabin end wall below roof",new(p.x,(low+p.y-.35f)/2,p.z),new(5.85f,p.y-.35f-low,.16f),Quaternion.LookRotation(f),dark,true);}
 foreach(float s in new[]{35f,38f}){var p=cabin.At(s,out var f);var side=Vector3.Cross(Vector3.up,f).normalized;Part("Boarded cabin window",p-side*3.10f-Vector3.up*1.2f,new(.10f,.9f,1.2f),Quaternion.LookRotation(f),dark);}
 Brush(tree,39,83,17);Brush(cabin,53,69,18);
 foreach(var b in new[]{tree,cabin})foreach(float s in b==tree?new[]{8f,24f,43f,58f,76f,94f}:new[]{8f,26f,37f,110f}){var p=b.At(s,out var f)+Vector3.up*.12f;var side=Vector3.Cross(Vector3.up,f).normalized;var gold=AssetDatabase.LoadAssetAtPath<Material>(F+"Shortcut gold.mat");foreach(float sign in new[]{-1f,1f})Beam("Gold optional route chevron",p-f*.9f+side*.7f*sign,p+f*.4f,.11f,gold);}
 EditorSceneManager.MarkSceneDirty(root.gameObject.scene);EditorSceneManager.SaveScene(root.gameObject.scene);AssetDatabase.SaveAssets();File.WriteAllLines("Docs/ShortcutRevision/authoring.txt",report);return string.Join("\n",report);
 }
 static bool SceneManagerDirty()=>UnityEngine.SceneManagement.SceneManager.GetActiveScene().isDirty;
}
