using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;public static class RunReverseCorrectionFinalChecks {public static string Main(){if(Application.isPlaying)throw new Exception("Edit mode required");State();Recovery();Supports();return "State, recovery and protected supports completed; inspect evidence files";}static string State(){System.Action work=()=>{try{
var results=new List<string>();void Check(bool pass,string label){results.Add((pass?"PASS ":"FAIL ")+label);}
foreach(string name in new[]{"DansBackyardReverse","DansBackyardForward"}){
UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/"+name+".unity");Physics.SyncTransforms();var race=UnityEngine.Object.FindAnyObjectByType<Racer.RaceDirector>();var state=UnityEngine.Object.FindAnyObjectByType<Racer.ReverseShortcutWorldState>();typeof(Racer.ReverseShortcutWorldState).GetMethod("OnEnable",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance).Invoke(state,null);race.FreeRoam=false;state.Refresh();Check(state.grate.activeSelf==!race.reverseCourse&&state.ridgeGate.activeSelf==!race.reverseCourse,name+" race-specific grate and ridge gate");Check(state.grate.GetComponentsInChildren<Collider>(true).Length>10,name+" visible grate has physical bars");race.FreeRoam=true;state.Refresh();Check(!state.grate.activeSelf&&!state.ridgeGate.activeSelf,name+" free roam opens both routes");
var branches=UnityEngine.Object.FindObjectsByType<Racer.WoodlandRoute>();Check(branches.Length==2,name+" retains exactly its two legal branches");
if(race.reverseCourse){var ridge=branches.First(b=>b.title.StartsWith("Abandoned"));var drain=branches.First(b=>b.title.StartsWith("Storm"));Check(branches.All(b=>b.aiValidated&&b.GetComponent<Racer.ReverseShortcutGuidance>()),"Both branches available to existing rival AI choice");Check(ridge.bypassedGates.Length==0&&drain.bypassedGates.SequenceEqual(new[]{3}),"Minimal gate entitlement: only drain CP3");var p=drain.At(31,out var f);Check(drain.Enter(p-f*.5f+Vector3.up,p+Vector3.up,f),"Legitimate underground entrance accepted");Check(!drain.Enter(p-f*.5f+Vector3.up*8,p+Vector3.up*8,f),"Surface-level travel above drain cannot claim shortcut");Check(!drain.Enter(p+f*.5f+Vector3.up,p+Vector3.up,-f),"Wrong-way entrance rejected");Check(drain.undergroundEnd>drain.undergroundStart+140,"Underground map span authored");Check(ridge.exitRoad-ridge.entryRoad>ridge.Length+15,"Ridge shortens main route by over 15m");Check(drain.exitRoad-drain.entryRoad>drain.Length,"Drain shortens main route by a positive distance");
foreach(var brush in UnityEngine.Object.FindObjectsByType<Racer.ShortcutUndergrowth>().Where(b=>b.name=="Recoverable rough ridge undergrowth")){Check(brush.centres.Length>0&&brush.centres.All(p=>brush.Coverage(p)>.9f),"Visible ground brush slows failed lines");Check(brush.GetComponentsInChildren<Collider>().Length==0,"Recovery brush traversable; no invisible collision wall");Check(race.road.points.All(p=>brush.Coverage(p)==0),"Main route never receives new brush resistance");}
Check(!state.GetComponentsInChildren<Collider>(true).Any(c=>c.isTrigger),"Shortcut geometry adds no reset trigger");
}
else Check(branches.Any(b=>b.title=="Tree-Top Trail")&&branches.Any(b=>b.title=="Abandoned Cabin Jump"),"Forward original branches retained; Reverse entitlement absent");
// Inspect dependent colliders only in the new ridge/launch footprints. Existing
// ground-level properties and every unchanged course remain protected by diff.
var localTrees=UnityEngine.Object.FindObjectsByType<Collider>().Where(c=>(c.name.ToLower().Contains("trunk")||c.name.ToLower().Contains("tree"))&&c.bounds.center.x>275&&c.bounds.center.x<395&&c.bounds.center.z>78&&c.bounds.center.z<130).ToArray();float max=0;foreach(var c in localTrees){var p=c.bounds.center;var hits=Physics.RaycastAll(new Vector3(p.x,250,p.z),Vector3.down,500,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).OrderBy(h=>h.distance).ToArray();if(hits.Length>0)max=Mathf.Max(max,Mathf.Abs(c.bounds.min.y-hits[0].point.y));}Check(max<.12f,name+" ridge trees grounded: "+localTrees.Length+" maximum foot error="+max);
UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/"+name+".unity");
}
System.IO.File.WriteAllLines("Docs/ReverseCorrection/state-checks.txt",results);UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");
}catch(Exception e){System.IO.File.WriteAllText("Docs/ReverseCorrection/state-check-error.txt",e.ToString());}};work();return "Check scoped course state, entitlement, map metadata and support";


}
static string Recovery(){System.Action work=()=>{var mode=Physics.simulationMode;float volume=AudioListener.volume;try{
UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");AudioListener.volume=0;Physics.simulationMode=SimulationMode.Script;var race=UnityEngine.Object.FindAnyObjectByType<Racer.RaceDirector>();var car=race.vehicle;typeof(Racer.VehicleSurfaceContacts).GetMethod("Reset",System.Reflection.BindingFlags.Static|System.Reflection.BindingFlags.NonPublic).Invoke(null,null);typeof(Racer.ArcadeVehicle).GetMethod("Awake",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(car,null);var configuration=car.GetComponent<Racer.VehicleConfiguration>()??car.gameObject.AddComponent<Racer.VehicleConfiguration>();foreach(var body in UnityEngine.Object.FindObjectsByType<Rigidbody>())if(body!=car.Body)body.gameObject.SetActive(false);var ridge=UnityEngine.Object.FindObjectsByType<Racer.WoodlandRoute>().First(b=>b.title.StartsWith("Abandoned"));var brushes=UnityEngine.Object.FindObjectsByType<Racer.ShortcutUndergrowth>().Where(b=>b.name=="Recoverable rough ridge undergrowth").ToArray();var brushStep=typeof(Racer.ShortcutUndergrowth).GetMethod("FixedUpdate",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance);
float Ground(Vector3 p)=>Physics.RaycastAll(new Vector3(p.x,250,p.z),Vector3.down,500,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).OrderBy(h=>h.distance).First().point.y;
var results=new List<string>();foreach(string profile in new[]{"moto","atv"})foreach(bool gully in new[]{false,true}){configuration.Apply(profile);var p=ridge.At(45,out var f);if(gully){p=new Vector3(96,0,-75);f=Vector3.forward;}else p+=Vector3.Cross(Vector3.up,f).normalized*5.5f;p.y=Ground(p)+2;car.Body.position=p;car.Body.rotation=Quaternion.LookRotation(Vector3.ProjectOnPlane(f,Vector3.up));car.transform.SetPositionAndRotation(p,car.Body.rotation);car.Body.linearVelocity=car.Body.angularVelocity=Vector3.zero;car.Body.isKinematic=false;car.ClearSteering();Physics.SyncTransforms();var targets=gully?new[]{new Vector3(106,0,-36),new Vector3(109,0,-15),new Vector3(107,0,20),new Vector3(102,0,45),new Vector3(105,0,95),new Vector3(112,0,125)}:new[]{ridge.At(51,out _),ridge.At(66,out _),ridge.At(83,out _)};int target=0,frame=0;bool escaped=false;for(;frame<1750;frame++){var here=car.Body.position;float distance=Vector2.Distance(new Vector2(here.x,here.z),new Vector2(targets[target].x,targets[target].z));if(distance<6){if(target==targets.Length-1&&car.GroundedWheels>=2){escaped=true;break;}if(target<targets.Length-1)target++;}var delta=Quaternion.Inverse(Quaternion.LookRotation(Vector3.ProjectOnPlane(car.transform.forward,Vector3.up)))*(targets[target]-here);float look=Mathf.Max(4,Mathf.Min(12,new Vector2(delta.x,delta.z).magnitude));float angle=Mathf.Atan2(delta.x,delta.z);float speed=car.ForwardSpeed;float steer=Mathf.Clamp(Mathf.Atan(2*car.wheelbase*Mathf.Sin(angle)/look)/(Mathf.Lerp(car.slowSteerAngle,car.fastSteerAngle,Mathf.Clamp01(speed/car.topSpeed))*Mathf.Deg2Rad),-1,1);car.Simulate(speed<12?.85f:0,speed>14?.2f:0,steer,.02f);foreach(var brush in brushes)brushStep.Invoke(brush,null);Physics.Simulate(.02f);Physics.SyncTransforms();}results.Add((escaped?"PASS ":"FAIL ")+profile+" "+(gully?"gully undershoot to existing northern shallow exit":"ridge fall to trail rejoin")+$" time={frame*.02f:F2}s final={car.Body.position:F2}; ordinary motor and actual brush resistance");}
System.IO.File.WriteAllLines("Docs/ReverseCorrection/recovery-checks.txt",results);
}catch(Exception e){System.IO.File.WriteAllText("Docs/ReverseCorrection/recovery-error.txt",e.ToString());}finally{Physics.simulationMode=mode;AudioListener.volume=volume;UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");}};work();return "Four bounded failed-line recovery checks; no full races";

}
static string Supports(){System.Action work=()=>{var temps=new List<GameObject>();try{
UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");var old=Newtonsoft.Json.Linq.JArray.Parse(System.IO.File.ReadAllText("Docs/ReverseShortcuts/original-terrain.json"));var sources=new List<Collider>();foreach(var row in old){var name=(string)row["name"];var current=GameObject.Find(name);if(!current||!current.GetComponent<MeshCollider>())continue;var mesh=UnityEditor.AssetDatabase.LoadAssetAtPath<Mesh>(UnityEditor.AssetDatabase.GUIDToAssetPath((string)row["guid"]));if(!mesh)continue;var g=new GameObject("Temporary original terrain support"){hideFlags=HideFlags.HideAndDontSave,layer=2};g.transform.SetPositionAndRotation(current.transform.position,current.transform.rotation);g.transform.localScale=current.transform.lossyScale;g.AddComponent<MeshCollider>().sharedMesh=mesh;temps.Add(g);sources.Add(g.GetComponent<Collider>());}
Physics.SyncTransforms();var results=new List<string>();int checkedPoints=0;float max=0;foreach(var road in UnityEngine.Object.FindObjectsByType<Racer.RaceRoad>())for(int i=2;i<road.points.Length-2;i+=4){var center=road.points[i];if(center.x<25||center.x>410||center.z< -110||center.z>145)continue;var side=Vector3.Cross(Vector3.up,road.points[i+1]-road.points[i-1]).normalized;foreach(float offset in new[]{-2f,0f,2f}){var p=center+side*offset;var ray=new Ray(new Vector3(p.x,250,p.z),Vector3.down);float before=float.NegativeInfinity;foreach(var c in sources)if(c.Raycast(ray,out var h,500))before=Mathf.Max(before,h.point.y);var now=Physics.RaycastAll(ray,500,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")||h.collider.name=="Culvert seamless floor").Select(h=>h.point.y).DefaultIfEmpty(float.NegativeInfinity).Max();if(float.IsNegativeInfinity(before))continue;checkedPoints++;float delta=Mathf.Abs(before-now);max=Mathf.Max(max,delta);if(delta>.12f)results.Add("FAIL "+road.name+" p="+p+" original="+before+" current="+now+" delta="+delta);}}
results.Insert(0,(max<=.12f?"PASS ":"FAIL ")+"Existing route centre/shoulder support samples="+checkedPoints+" maximum change="+max);System.IO.File.WriteAllLines("Docs/ReverseCorrection/road-supports.txt",results);
}catch(Exception e){System.IO.File.WriteAllText("Docs/ReverseCorrection/road-support-error.txt",e.ToString());}finally{foreach(var g in temps)if(g)UnityEngine.Object.DestroyImmediate(g);UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");}};work();return "Compare protected road supports directly to checkpoint terrain meshes";

}}
