using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class ScreenAnderson {
 static float Near(Vector3 p,Vector3[] pts){float best=float.MaxValue;for(int i=1;i<pts.Length;i++){var v=pts[i]-pts[i-1];v.y=0;var q=p-pts[i-1];q.y=0;best=Mathf.Min(best,(q-v*Mathf.Clamp01(Vector3.Dot(q,v)/v.sqrMagnitude)).sqrMagnitude);}return Mathf.Sqrt(best);}
 public static string Main(){if(Application.isPlaying||UnityEngine.SceneManagement.SceneManager.GetActiveScene().isDirty)throw new Exception("Saved edit mode required");EditorApplication.delayCall+=Run;return "Focused Anderson frontage planting scheduled";}
 static void Run(){var original=UnityEngine.SceneManagement.SceneManager.GetActiveScene().path;try{var report=new List<object>();foreach(var sn in RacePlaylists.Scenes){var scene=EditorSceneManager.OpenScene("Assets/Scenes/"+sn+".unity");Physics.SyncTransforms();var h=GameObject.Find("Friend across street - blue circle").transform;var street=GameObject.Find("Phase 3 - Race Systems").GetComponent<RaceRoad>();var drive=GameObject.Find("Kyle descending driveway").GetComponent<RaceRoad>();var root=new GameObject("Anderson wooded frontage screening").transform;var parts=new List<CombineInstance>();var temps=new List<Mesh>();var accepted=new List<Vector3>();var random=new System.Random(45001);float R(float a,float b)=>Mathf.Lerp(a,b,(float)random.NextDouble());var existing=Object.FindObjectsByType<BoxCollider>().Where(c=>c.name.ToLowerInvariant().Contains("trunk")).Select(c=>c.bounds.center).ToArray();
 for(int i=0;i<1400&&accepted.Count<22;i++){var p=h.position+h.forward*R(10,25)+h.right*R(-27,27);if(Near(p,street.points)<10.5f||Near(p,drive.points)<6.5f||accepted.Concat(existing).Any(q=>Vector2.Distance(new(p.x,p.z),new(q.x,q.z))<3.8f))continue;
 var hits=Physics.RaycastAll(new(p.x,300,p.z),Vector3.down,600,~0,QueryTriggerInteraction.Ignore).OrderBy(x=>x.distance).ToArray();if(hits.Length==0||!hits[0].collider.name.StartsWith("Ground_")||hits[0].normal.y<.45f)continue;p=hits[0].point;
 if(Physics.OverlapBox(p+Vector3.up*4,new Vector3(1.3f,3.5f,1.3f),Quaternion.identity,~0,QueryTriggerInteraction.Ignore).Any(c=>!c.name.StartsWith("Ground_")&&!c.GetComponentInParent<ArcadeVehicle>()))continue;
 float height=R(12,17),radius=R(3.4f,4.8f);var crown=Object.Instantiate(AssetDatabase.LoadAssetAtPath<Mesh>("Assets/Vegetation/Phase6/"+(i%2==0?"BroadCrown":"IrregularCrown")+".asset"));crown.colors=Enumerable.Repeat(Color.Lerp(new(.24f,.34f,.19f),new(.34f,.42f,.22f),R(0,1)),crown.vertexCount).ToArray();temps.Add(crown);parts.Add(new(){mesh=crown,transform=Matrix4x4.TRS(p+Vector3.up*1.6f,Quaternion.Euler(0,R(0,360),0),new(radius,height*.87f,radius))});var bark=Object.Instantiate(AssetDatabase.LoadAssetAtPath<Mesh>("Assets/Vegetation/Phase6/Trunk.asset"));bark.colors=Enumerable.Repeat(new Color(.25f,.20f,.145f),bark.vertexCount).ToArray();temps.Add(bark);var size=new Vector3(.52f,height*.65f,.52f);var center=p+Vector3.up*size.y*.5f;parts.Add(new(){mesh=bark,transform=Matrix4x4.TRS(center,Quaternion.identity,size)});var c=new GameObject("Anderson frontage trunk").AddComponent<BoxCollider>();c.transform.SetParent(root);c.transform.position=center;c.size=size;accepted.Add(p);}
 var mesh=new Mesh{indexFormat=UnityEngine.Rendering.IndexFormat.UInt32};mesh.CombineMeshes(parts.ToArray());AssetDatabase.CreateAsset(mesh,"Assets/Vegetation/WorldCleanup/"+sn+"-AndersonScreen.asset");root.gameObject.AddComponent<MeshFilter>().sharedMesh=mesh;root.gameObject.AddComponent<MeshRenderer>().sharedMaterial=AssetDatabase.LoadAssetAtPath<Material>("Assets/Vegetation/Phase6/Forest.mat");foreach(var m in temps)Object.DestroyImmediate(m);report.Add(new{scene=sn,count=accepted.Count,positions=accepted.Select(p=>new{x=p.x,y=p.y,z=p.z}).ToArray()});EditorSceneManager.MarkSceneDirty(scene);EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();File.AppendAllText("Docs/WorldCleanup/screen-progress.txt",sn+" "+accepted.Count+"\n");}
 File.WriteAllText("Docs/WorldCleanup/anderson-screen.json",Newtonsoft.Json.JsonConvert.SerializeObject(report,Newtonsoft.Json.Formatting.Indented));}catch(Exception e){File.WriteAllText("Docs/WorldCleanup/screen-error.txt",e.ToString());}finally{EditorSceneManager.OpenScene(original);}}
}
