EditorApplication.delayCall+=()=>{try{
var r=UnityEngine.Object.FindAnyObjectByType<Racer.RaceDirector>();var c=r.GetComponent<Racer.BackyardForwardCourse>();var road=r.road;var lip=c.flightStarts[2];var axis=c.flightDirections[2];var land=c.landingStations.Select(s=>road.At(s,out _)).ToArray();float start=c.launchStations[2]-45;var basePoint=road.At(start,out _);float y0=Racer.Editor.BackyardReverseAuthoring.Ground(basePoint);float height(Vector3 p){float d=Vector3.Dot(p-basePoint,axis);return y0+.14f*d+.05f/45*d*d;}
var forward=UnityEngine.Object.FindObjectsByType<Racer.RaceRoad>().First(x=>x.name=="Forward navigation only - no road mesh");
var flags=System.Reflection.BindingFlags.Static|System.Reflection.BindingFlags.NonPublic;
Func<Vector3,bool> region=p=>{if(p.x<340||p.x>391||p.z<-18||p.z>3)return false;float s=road.Project(p,out var side);forward.Project(p,out float fd);return s>=start&&s<=c.launchStations[2]+.2f&&side<5.3f&&fd>5.5f;};
typeof(Racer.Editor.BackyardReverseAuthoring).GetMethod("Sculpt",flags).Invoke(null,new object[]{region,(Func<Vector3,Vector3>)(p=>{road.Project(p,out float side);p.y=Mathf.Lerp(p.y,height(p),1-Mathf.SmoothStep(0,1,Mathf.InverseLerp(2.65f,5.3f,side)));return p;}),"pool-runup"});
for(int i=0;i<road.points.Length;i++){var p=road.points[i];if(region(p))p.y=Racer.Editor.BackyardReverseAuthoring.Ground(p);road.points[i]=p;}lip.y=Racer.Editor.BackyardReverseAuthoring.Ground(lip);c.flightStarts[2]=lip;
for(int i=0;i<road.points.Length;i++){var p=road.points[i];float a=Vector3.Dot(p-lip,axis);if(a>0&&a<Vector3.Dot(land[2]-lip,axis)&&Math.Abs(Vector3.Dot(p-lip,Vector3.Cross(Vector3.up,axis)))<4)p.y=Mathf.Lerp(lip.y,land[2].y,a/Vector3.Dot(land[2]-lip,axis));road.points[i]=p;}
typeof(Racer.RaceRoad).GetField("distance",flags&~System.Reflection.BindingFlags.Static|System.Reflection.BindingFlags.Instance).SetValue(road,null);road.Initialize();for(int j=0;j<3;j++){c.launchStations[j]=road.Project(c.flightStarts[j],out _);c.landingStations[j]=road.Project(land[j],out _);}var f=UnityEngine.Object.FindAnyObjectByType<Racer.ForestLayout>();f.jumpStarts=c.launchStations;f.jumpEnds=c.landingStations;
typeof(Racer.Editor.BackyardReverseAuthoring).GetMethod("Trees",flags).Invoke(null,new object[]{(Func<Collider,bool>)(x=>false),(Func<Collider,bool>)(x=>region(x.bounds.center))});
// Ground existing trail color and direction meshes on the final local support.
foreach(var mf in UnityEngine.Object.FindObjectsByType<MeshFilter>().Where(m=>m.name=="Narrow worn-earth Reverse trail"||m.name=="Reverse teal ground arrow")){var m=mf.sharedMesh;var v=m.vertices;bool change=false;for(int i=0;i<v.Length;i++){var p=mf.transform.TransformPoint(v[i]);if(region(p)){p.y=Racer.Editor.BackyardReverseAuthoring.Ground(p)+.03f;v[i]=mf.transform.InverseTransformPoint(p);change=true;}}if(change){m.vertices=v;m.RecalculateNormals();m.RecalculateBounds();EditorUtility.SetDirty(m);}}
UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(UnityEngine.SceneManagement.SceneManager.GetActiveScene());UnityEditor.SceneManagement.EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());AssetDatabase.SaveAssets();Racer.Editor.BackyardReverseAuthoring.ExportReverse();System.IO.File.WriteAllText("Docs/BackyardReverse/pool-profile-done.txt","Continuous convex final run-up; lip="+lip+"; base="+basePoint);
}catch(Exception e){System.IO.File.WriteAllText("Docs/BackyardReverse/pool-profile-error.txt",e.ToString());}};return "Smooth the local pool-house run-up into one continuous profile";
