EditorApplication.delayCall+=()=>{try{
if(Application.isPlaying||UnityEngine.SceneManagement.SceneManager.GetActiveScene().isDirty)throw new Exception("Saved edit mode required");
const string folder="Assets/Track/Backyard";System.IO.Directory.CreateDirectory(folder);AssetDatabase.Refresh();var report=new List<string>();
foreach(string name in new[]{"StreetLoopGreybox","StreetLoopReverse","LakeWoods","ForestLoopReverse","MountainLoop","MountainLoopReverse"}){
var scene=UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/"+name+".unity");Physics.SyncTransforms();var mf=GameObject.Find("Ground_CR113 Kyle driveway edge join").GetComponent<MeshFilter>();var original=mf.sharedMesh;var vs=original.vertices;var ts=original.triangles;var verts=new List<Vector3>();var tris=new List<int>();float maxChange=0;
Vector3 Adjust(Vector3 v){var p=mf.transform.TransformPoint(v);float distance=Vector2.Distance(new Vector2(p.x,p.z),new Vector2(478.3f,-1.9f));if(distance>=10)return v;var hits=Physics.RaycastAll(new Vector3(p.x,200,p.z),Vector3.down,300,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")&&h.collider!=mf.GetComponent<Collider>()&&!h.collider.name.Contains("CR113")).OrderBy(h=>Math.Abs(h.point.y-p.y)).ToArray();if(hits.Length==0)throw new Exception("No underlying terrain");float blend=1-Mathf.SmoothStep(0,1,Mathf.InverseLerp(4,10,distance));float target=Mathf.Lerp(p.y,hits[0].point.y+.025f,blend);maxChange=Math.Max(maxChange,Math.Abs(p.y-target));p.y=target;return mf.transform.InverseTransformPoint(p);}
for(int tri=0;tri<ts.Length;tri+=3){var a=vs[ts[tri]];var b=vs[ts[tri+1]];var c=vs[ts[tri+2]];int n=Mathf.CeilToInt(Math.Max(Vector3.Distance(a,b),Math.Max(Vector3.Distance(a,c),Vector3.Distance(b,c)))/.5f);var indices=new Dictionary<(int,int),int>();int Id(int i,int j){if(indices.TryGetValue((i,j),out int ix))return ix;ix=verts.Count;verts.Add(Adjust(a+(b-a)*(i/(float)n)+(c-a)*(j/(float)n)));indices[(i,j)]=ix;return ix;}for(int i=0;i<n;i++)for(int j=0;j<n-i;j++){tris.AddRange(new[]{Id(i,j),Id(i+1,j),Id(i,j+1)});if(i+j<n-1)tris.AddRange(new[]{Id(i+1,j),Id(i+1,j+1),Id(i,j+1)});}}
var mesh=new Mesh{indexFormat=UnityEngine.Rendering.IndexFormat.UInt32};mesh.SetVertices(verts);mesh.SetTriangles(tris,0);mesh.RecalculateNormals();mesh.RecalculateBounds();AssetDatabase.CreateAsset(mesh,folder+"/"+name+"-Kyle-edge.asset");mf.sharedMesh=mesh;mf.GetComponent<MeshCollider>().sharedMesh=mesh;UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(scene);UnityEditor.SceneManagement.EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();report.Add(name+": only Kyle driveway mesh replaced; maximum adjustment="+maxChange+"m; blends to existing terrain +0.025m inside 4m, fades out by 10m of supplied X/Z; original terrain/roads unchanged.");
}System.IO.File.WriteAllLines("Docs/Backyard/kyle-fixed.txt",report);
}catch(Exception e){System.IO.File.WriteAllText("Docs/Backyard/kyle-fix-error.txt",e.ToString());}};return "Scheduled local driveway edge smoothing";
