using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class SubdivideMountainMerge {
 public static string Main(){EditorSceneManager.OpenScene("Assets/Scenes/MountainLoopReverse.unity");var b=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title=="Summit Traverse");int refined=0;foreach(var mf in Object.FindObjectsByType<MeshFilter>().Where(m=>m.sharedMesh&&(m.name.Contains("driving surface")||m.name.Contains("supported shoulders")))){bool support=mf.name.Contains("supported shoulders");var mesh=mf.sharedMesh;var old=mesh.vertices.Select(mf.transform.TransformPoint).ToArray();var cs=mesh.colors;var ix=mesh.triangles;var v=new List<Vector3>();var col=new List<Color>();var indices=new List<int>();
 float Flat(Vector3 a,Vector3 c)=>Vector2.Distance(new(a.x,a.z),new(c.x,c.z));
 Vector3 Map(Vector3 p){float s=b.Project(p,out float d);if(s<375||s>455||d>9)return p;float target=b.At(s,out _).y+(support?-.08f:.04f);if(Math.Abs(p.y-target)>6||(support&&p.y<target))return p;float w=Mathf.SmoothStep(0,1,Mathf.InverseLerp(375,385,s))*(1-Mathf.SmoothStep(0,1,Mathf.InverseLerp(440,455,s)))*(1-Mathf.SmoothStep(0,1,Mathf.InverseLerp(6,9,d)));p.y=Mathf.Lerp(p.y,target,w);return p;}
 void Add(Vector3 a,Vector3 c,Vector3 d,Color ca,Color cc,Color cd,int depth){float ac=Flat(a,c),ce=Flat(c,d),ea=Flat(d,a);float s=b.Project((a+c+d)/3,out float distance);bool local=Flat((a+c+d)/3,b.At(415,out _))<65&&Math.Abs(((a+c+d)/3).y-b.At(s,out _).y)<15;if(local&&Math.Max(ac,Math.Max(ce,ea))>2.5f&&depth<9){refined++;if(ac>=ce&&ac>=ea){var m=(a+c)/2;var cm=(ca+cc)/2;Add(a,m,d,ca,cm,cd,depth+1);Add(m,c,d,cm,cc,cd,depth+1);}else if(ce>=ea){var m=(c+d)/2;var cm=(cc+cd)/2;Add(a,c,m,ca,cc,cm,depth+1);Add(a,m,d,ca,cm,cd,depth+1);}else{var m=(d+a)/2;var cm=(cd+ca)/2;Add(a,c,m,ca,cc,cm,depth+1);Add(m,c,d,cm,cc,cd,depth+1);}return;}foreach(var pair in new[]{(a,ca),(c,cc),(d,cd)}){indices.Add(v.Count);v.Add(mf.transform.InverseTransformPoint(Map(pair.Item1)));col.Add(pair.Item2);}}
 for(int i=0;i<ix.Length;i+=3){int a=ix[i],c=ix[i+1],d=ix[i+2];Add(old[a],old[c],old[d],cs.Length>0?cs[a]:Color.white,cs.Length>0?cs[c]:Color.white,cs.Length>0?cs[d]:Color.white,0);}var copy=new Mesh{indexFormat=UnityEngine.Rendering.IndexFormat.UInt32};copy.SetVertices(v);copy.SetColors(col);copy.SetTriangles(indices,0);copy.RecalculateNormals();copy.RecalculateBounds();AssetDatabase.CreateAsset(copy,AssetDatabase.GenerateUniqueAssetPath("Assets/Track/MountainPolish/grade-"+mf.name+".asset"));mf.sharedMesh=copy;mf.GetComponent<MeshCollider>().sharedMesh=copy;}
 Physics.SyncTransforms();EditorSceneManager.MarkSceneDirty(b.gameObject.scene);EditorSceneManager.SaveScene(b.gameObject.scene);AssetDatabase.SaveAssets();File.WriteAllText("Docs/MountainPolish/merge-tessellation.txt","Local long triangle subdivision and grade refit: "+refined);return "Local merge triangles refined="+refined;}
}
