using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
// Local saved-scene repair. Route/navigation/checkpoint transforms are never changed.
public static class ReportReceivingSupport {
 const string Folder="Assets/Track/ReportCleanup";
 struct V {public Vector3 p;public Color c;public V(Vector3 p,Color c){this.p=p;this.c=c;}public static V Lerp(V a,V b,float t)=>new V(Vector3.Lerp(a.p,b.p,t),Color.Lerp(a.c,b.c,t));}
 class Face {public List<V> v;public Face(params V[] a){v=a.ToList();}}
 static Color Earth=new(.39f,.48f,.29f),Rock=new(.34f,.36f,.29f);
 static V E(Vector3 p)=>new(p,Earth);static V R(Vector3 p)=>new(p,Rock);
 static List<V> Clip(List<V> poly,Plane plane,bool inside){var result=new List<V>();for(int i=0;i<poly.Count;i++){var a=poly[i];var b=poly[(i+1)%poly.Count];float da=plane.GetDistanceToPoint(a.p),db=plane.GetDistanceToPoint(b.p);bool ia=inside?da>=-.00001f:da<=.00001f,ib=inside?db>=-.00001f:db<=.00001f;if(ia)result.Add(a);if(ia!=ib)result.Add(V.Lerp(a,b,da/(da-db)));}return result;}
 static IEnumerable<Face> Subtract(Face f,Plane[] planes){foreach(var plane in planes)if(f.v.All(v=>plane.GetDistanceToPoint(v.p)<-.00001f))return new[]{f};var intersection=f.v;foreach(var p in planes){intersection=Clip(intersection,p,true);if(intersection.Count<3)return new[]{f};}var outside=new List<Face>();var rest=f.v;foreach(var p in planes){var part=Clip(rest,p,false);if(part.Count>=3)outside.Add(new Face(part.ToArray()));rest=Clip(rest,p,true);if(rest.Count<3)break;}return outside;}
 static Plane[] Box(Vector3 a,Vector3 b,float width,float bottom,float top){var f=Vector3.ProjectOnPlane(b-a,Vector3.up).normalized;var right=Vector3.Cross(Vector3.up,f);var up=Vector3.Cross(b-a,right).normalized;if(up.y<0)up=-up;return new[]{new Plane(f,a-f*.15f),new Plane(-f,b+f*.15f),new Plane(right,a-right*width),new Plane(-right,a+right*width),new Plane(up,a+Vector3.up*bottom),new Plane(-up,a+Vector3.up*top)};}
 static List<Face> Read(MeshFilter mf){var m=mf.sharedMesh;var v=m.vertices;var c=m.colors;var t=m.triangles;return Enumerable.Range(0,t.Length/3).Select(i=>new Face(Enumerable.Range(0,3).Select(j=>{int k=t[i*3+j];return new V(mf.transform.TransformPoint(v[k]),c.Length==v.Length?c[k]:Earth);}).ToArray())).ToList();}
 static Mesh Store(string name,List<Face> faces){var vs=new List<Vector3>();var cs=new List<Color>();var ix=new List<int>();foreach(var face in faces)for(int j=1;j+1<face.v.Count;j++){var a=face.v[0];var b=face.v[j];var c=face.v[j+1];if(Vector3.Cross(b.p-a.p,c.p-a.p).sqrMagnitude<.00000001f)continue;int k=vs.Count;vs.AddRange(new[]{a.p,b.p,c.p});cs.AddRange(new[]{a.c,b.c,c.c});ix.AddRange(new[]{k,k+1,k+2});}var mesh=new Mesh{indexFormat=UnityEngine.Rendering.IndexFormat.UInt32};mesh.SetVertices(vs);mesh.SetColors(cs);mesh.SetTriangles(ix,0);mesh.RecalculateNormals();mesh.RecalculateBounds();string path=Folder+"/"+name+".asset";var old=AssetDatabase.LoadAssetAtPath<Mesh>(path);if(old){EditorUtility.CopySerialized(mesh,old);Object.DestroyImmediate(mesh);return old;}AssetDatabase.CreateAsset(mesh,path);return mesh;}
 static void Assign(MeshFilter mf,string name,List<Face> faces){var mesh=Store(name,faces);mf.transform.SetPositionAndRotation(Vector3.zero,Quaternion.identity);mf.transform.localScale=Vector3.one;mf.sharedMesh=mesh;if(mf.TryGetComponent<MeshCollider>(out var mc)){mc.sharedMesh=null;mc.sharedMesh=mesh;}}
 static void Quad(List<Face> f,Vector3 a,Vector3 b,Vector3 c,Vector3 d,bool rock=false,bool doubleSide=false){var col=rock?Rock:Earth;f.Add(new Face(new(a,col),new(b,col),new(c,col)));f.Add(new Face(new(a,col),new(c,col),new(d,col)));if(doubleSide){f.Add(new Face(new(c,col),new(b,col),new(a,col)));f.Add(new Face(new(d,col),new(c,col),new(a,col)));}}
 static bool Local(Vector3 p)=>p.x>855&&p.x<1060&&p.z>-112&&p.z<185;
 static GameObject Make(string name,List<Face> fs,Material mat){var g=new GameObject("Ground_"+name,typeof(MeshFilter),typeof(MeshRenderer),typeof(MeshCollider));g.GetComponent<MeshRenderer>().sharedMaterial=mat;Assign(g.GetComponent<MeshFilter>(),name,fs);return g;}
 static void Save(){var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene();EditorSceneManager.MarkSceneDirty(scene);EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();}
 public static string Main(){var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene();var race=Object.FindAnyObjectByType<RaceDirector>();var pavement=GameObject.Find("Ground_CR133 mountain driving surface").GetComponent<MeshCollider>();var mat=GameObject.Find("Ground_CR133 mountain earth banks").GetComponent<Renderer>().sharedMaterial;var notes=new List<string>();var sections=Resources.FindObjectsOfTypeAll<MeshFilter>().Where(m=>m.gameObject.scene==scene&&m.name.StartsWith("Ground_CR122 main section")).ToArray();int index=0;
 foreach(var flight in race.GetComponent<MountainFlights>().flights){Vector3 Start(MeshFilter m)=>m.transform.TransformPoint((m.sharedMesh.vertices[0]+m.sharedMesh.vertices[1])*.5f);var section=sections.Where(m=>Vector3.Dot(Start(m)-flight.lip,flight.forward)>35&&Vector3.Cross(Vector3.ProjectOnPlane(Start(m)-flight.lip,Vector3.up),flight.forward).magnitude<8).OrderBy(m=>Vector3.Dot(Start(m)-flight.lip,flight.forward)).First();var start=Start(section);var f=Vector3.ProjectOnPlane(flight.forward,Vector3.up).normalized;var right=Vector3.Cross(Vector3.up,f);float width=Vector3.Distance(section.sharedMesh.vertices[0],section.sharedMesh.vertices[1])*.5f-.15f;var cache=new Dictionary<Vector2,(Vector3 top,Vector3 bottom)>();
 (Vector3 top,Vector3 bottom) Point(float u,float v){var key=new Vector2(u,v);if(cache.TryGetValue(key,out var found))return found;var p=start+f*u+right*v;if(!pavement.Raycast(new Ray(p+Vector3.up*8,Vector3.down),out var hit,30))throw new Exception("Receiving pavement missing at "+p);p.y=hit.point.y-.07f;var basePoint=p+f*(1.2f+.35f*Mathf.Sin(v*.4f))+right*Mathf.Sign(v)*1.5f;var support=Physics.RaycastAll(new(basePoint.x,p.y+2,basePoint.z),Vector3.down,150,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider!=pavement&&h.collider.name.StartsWith("Ground_")).OrderByDescending(h=>h.point.y).ToArray();basePoint.y=Mathf.Min(p.y-.2f,support.Length>0?support[0].point.y-.1f:45);return cache[key]=(p,basePoint);}
 var faces=new List<Face>();for(float u=.03f;u<16;u+=1){float uu=Mathf.Min(16,u+1);for(float v=-width;v<width;v+=2){float vv=Mathf.Min(width,v+2);var a=Point(u,v);var b=Point(uu,v);var c=Point(uu,vv);var d=Point(u,vv);Quad(faces,a.top,b.top,c.top,d.top);Quad(faces,d.bottom,c.bottom,b.bottom,a.bottom,true);if(u==.03f)Quad(faces,a.top,d.top,d.bottom,a.bottom,true);if(uu==16)Quad(faces,c.top,b.top,b.bottom,c.bottom,true);if(v==-width)Quad(faces,a.top,a.bottom,b.bottom,b.top,true);if(vv==width)Quad(faces,c.top,c.bottom,d.bottom,d.top,true);}}
 Make("ReportCleanup "+scene.name+" receiving bank "+index++,faces,mat);Physics.SyncTransforms();notes.Add(flight.name+": terrain seated against the first 16m of existing receiving pavement. Starts="+start+"; preceding flight gap untouched; bank joins sampled surrounding ground.");}
 Save();File.WriteAllLines("Docs/ReportCleanup/"+scene.name+"-receiving-support.txt",notes);return string.Join("\n",notes);}
}
