using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class TestReverseCorrections {
public static string Main(){EditorApplication.delayCall+=Run;return "Ten scoped motorcycle/ATV approach and bump drives; three timber contacts";}
static void Run(){var mode=Physics.simulationMode;float volume=AudioListener.volume;const string folder="Docs/BackyardReverseCorrections";try{EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");AudioListener.volume=0;Physics.simulationMode=SimulationMode.Script;var race=Object.FindAnyObjectByType<RaceDirector>();race.road.Initialize();var car=race.vehicle;var course=race.GetComponent<BackyardForwardCourse>();var flags=System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance;
typeof(VehicleSurfaceContacts).GetMethod("Reset",System.Reflection.BindingFlags.Static|System.Reflection.BindingFlags.NonPublic).Invoke(null,null);typeof(ArcadeVehicle).GetMethod("Awake",flags).Invoke(car,null);var config=car.GetComponent<VehicleConfiguration>()??car.gameObject.AddComponent<VehicleConfiguration>();foreach(var body in Object.FindObjectsByType<Rigidbody>())if(body!=car.Body)body.gameObject.SetActive(false);
var results=new List<string>();var log=new List<string>{"case,time,x,y,z,speed,vertical,grounded"};float desired=32;float Ground(Vector3 p)=>Racer.Editor.BackyardReverseAuthoring.Ground(p);
void Place(Vector3 p,Vector3 axis,float speed){p.y=Ground(p)+.55f;car.Body.position=p;car.Body.rotation=Quaternion.LookRotation(axis);car.transform.SetPositionAndRotation(p,car.Body.rotation);car.Body.linearVelocity=Vector3.zero;car.Body.angularVelocity=Vector3.zero;car.Body.isKinematic=false;car.ClearSteering();Physics.SyncTransforms();for(int n=0;n<60;n++){car.Simulate(0,0,0,.02f);Physics.Simulate(.02f);}var tangent=axis+Vector3.up*((Ground(p+axis)-Ground(p-axis))*.5f);car.Body.linearVelocity=tangent.normalized*speed;Physics.SyncTransforms();}
void Drive(Vector3 target){float speed=car.ForwardSpeed;var delta=Quaternion.Inverse(Quaternion.LookRotation(Vector3.ProjectOnPlane(car.transform.forward,Vector3.up)))*(target-car.Body.position);float angle=Mathf.Atan2(delta.x,delta.z);float steer=Mathf.Clamp(Mathf.Atan(2*car.wheelbase*Mathf.Sin(angle)/12)/(Mathf.Lerp(car.slowSteerAngle,car.fastSteerAngle,Mathf.Clamp01(speed/car.topSpeed))*Mathf.Deg2Rad),-1,1);car.Simulate(speed<desired?.8f:0,speed>desired+1?.45f:0,steer,.02f);Physics.Simulate(.02f);Physics.SyncTransforms();}
void Log(string name,int frame){if(frame%5!=0)return;var p=car.Body.position;log.Add($"{name},{frame*.02f:F2},{p.x:F3},{p.y:F3},{p.z:F3},{car.ForwardSpeed:F2},{car.Body.linearVelocity.y:F2},{car.GroundedWheels}");}
foreach(string profile in new[]{"moto","atv"}){config.Apply(profile);foreach(int j in System.Array.Empty<int>()){var lip=course.flightStarts[j];var axis=course.flightDirections[j];var anchor=j==0?new Vector3(215,74,106):new(308,74,-18);float start=race.road.Project(anchor,out _);var p=race.road.At(start,out var f);desired=j==0?22:32;Place(p,Vector3.ProjectOnPlane(f,Vector3.up).normalized,desired);float air=0,longest=0,minSpeed=100,heading=180,offset=100;bool entered=false,landed=false,shortLanding=false;float distance=Vector3.Dot(race.road.At(course.landingStations[j],out _)-lip,axis);
for(int frame=0;frame<650;frame++){float along=Vector3.Dot(car.Body.position-lip,axis);desired=j==0&&car.Body.position.x>183?22:32;if(along>-3&&along<3){minSpeed=Mathf.Min(minSpeed,car.ForwardSpeed);heading=Vector3.Angle(Vector3.ProjectOnPlane(car.transform.forward,Vector3.up),axis);offset=Mathf.Abs(Vector3.Dot(car.Body.position-lip,Vector3.Cross(Vector3.up,axis)));}if(along>0&&car.GroundedWheels==0){air+=.02f;entered=true;}else{longest=Math.Max(longest,air);air=0;}if(entered&&along>5&&along<distance-6&&car.GroundedWheels>=2)shortLanding=true;if(!shortLanding&&entered&&along>distance-2&&car.GroundedWheels>=2&&Mathf.Abs(Vector3.Dot(car.Body.position-lip,Vector3.Cross(Vector3.up,axis)))<5&&longest>1.2f){landed=true;break;}float s=race.road.Project(car.Body.position,out _);var target=along>=-25?lip+axis*(along+12):race.road.At(s+12,out _);Drive(target);Log(profile+"-ramp"+j,frame);}
results.Add((landed&&heading<10&&offset<2?"PASS ":"FAIL ")+profile+" ramp "+j+$" landed={landed} air={longest:F2} launchSpeed={minSpeed:F2} headingError={heading:F2} centreError={offset:F2} final={car.Body.position:F2}");}
var areas=new[]{new Vector3(416.6f,84.7f,82.1f),new(172.2f,46.3f,-98.9f),new(235,60.7f,-31.3f)};foreach(int j in new[]{2}){var reference=areas[j];float centre=race.road.Project(reference,out _);var at=race.road.At(centre,out var f);float lateral=Mathf.Clamp(Vector3.Dot(reference-at,Vector3.Cross(Vector3.up,f).normalized),-2.3f,2.3f);var p=race.road.At(centre-18,out f)+Vector3.Cross(Vector3.up,f).normalized*lateral;desired=j==2?23:28;Place(p,Vector3.ProjectOnPlane(f,Vector3.up).normalized,desired);float air=0,longest=0,vertical=0,minimum=100;bool finished=false;for(int frame=0;frame<260;frame++){float s=race.road.Project(car.Body.position,out _);if(s>centre+(j==2?4:20)){finished=true;break;}if(car.GroundedWheels==0)air+=.02f;else{longest=Mathf.Max(longest,air);air=0;}vertical=Mathf.Max(vertical,car.Body.linearVelocity.y);minimum=Mathf.Min(minimum,car.ForwardSpeed);var target=race.road.At(s+12,out var tf)+Vector3.Cross(Vector3.up,tf).normalized*lateral;Drive(target);Log(profile+"-bump"+j,frame);}longest=Mathf.Max(longest,air);results.Add((finished&&longest<.65f&&vertical<7&&minimum>12?"PASS ":"FAIL ")+profile+" bump "+j+$" finished={finished} air={longest:F2} upward={vertical:F2} minSpeed={minimum:F2}");}}
File.WriteAllLines(folder+"/turn-driving.txt",results);File.WriteAllLines(folder+"/turn-pace.csv",log);
}catch(Exception e){File.WriteAllText(folder+"/turn-driving-error.txt",e.ToString());}finally{Physics.simulationMode=mode;AudioListener.volume=volume;EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");}}
}


