UnityEditor.EditorApplication.delayCall+=()=>{try{
UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");Physics.SyncTransforms();var root=GameObject.Find("Reverse optional forest shortcuts").transform;var roads=UnityEngine.Object.FindObjectsByType<Racer.RaceRoad>();
float Ground(Vector3 p)=>Physics.RaycastAll(new Vector3(p.x,250,p.z),Vector3.down,500,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")&&!h.collider.transform.IsChildOf(root)).Select(h=>h.point.y).DefaultIfEmpty(-999).Max();
float Road(Vector3 p){float best=999;foreach(var r in roads){r.Project(p,out float d);best=Mathf.Min(best,d);}return best;}
var rows=new List<string>();foreach(var mf in root.GetComponentsInChildren<MeshFilter>().Where(m=>m.GetComponent<MeshCollider>()&&(m.name.StartsWith("Ground_")||m.name=="Culvert continuous floor"))){var src=mf.sharedMesh;var v=src.vertices;var tri=src.triangles;var vertices=new List<Vector3>();var indices=new List<int>();int cut=0;
bool Near(Vector3 p)=>Road(p)<5&&Mathf.Abs(p.y-Ground(p))<3;
for(int i=0;i<tri.Length;i+=3){var a=v[tri[i]];var b=v[tri[i+1]];var c=v[tri[i+2]];bool near=Near(a)||Near(b)||Near(c)||Near((a+b+c)/3);int n=near?Mathf.Clamp(Mathf.CeilToInt(Mathf.Max(Vector3.Distance(a,b),Vector3.Distance(a,c))/.35f),1,28):1;
void Triangle(Vector2 x,Vector2 y,Vector2 z){Vector3 At(Vector2 t)=>a+(b-a)*t.x+(c-a)*t.y;var p=(At(x)+At(y)+At(z))/3;if(near&&Road(p)<3.8f&&Mathf.Abs(p.y-Ground(p))<3){cut++;return;}foreach(var t in new[]{x,y,z}){indices.Add(vertices.Count);vertices.Add(At(t));}}
for(int j=0;j<n;j++)for(int k=0;k<n-j;k++){Triangle(new(j/(float)n,k/(float)n),new((j+1)/(float)n,k/(float)n),new(j/(float)n,(k+1)/(float)n));if(j+k<n-1)Triangle(new((j+1)/(float)n,k/(float)n),new((j+1)/(float)n,(k+1)/(float)n),new(j/(float)n,(k+1)/(float)n));}}
if(cut==0)continue;var copy=new Mesh{indexFormat=UnityEngine.Rendering.IndexFormat.UInt32};copy.SetVertices(vertices);copy.SetTriangles(indices,0);copy.uv=vertices.Select(p=>new Vector2(p.x,p.z)*.2f).ToArray();copy.RecalculateNormals();copy.RecalculateBounds();UnityEditor.EditorUtility.CopySerialized(copy,src);UnityEngine.Object.DestroyImmediate(copy);mf.GetComponent<MeshCollider>().sharedMesh=null;mf.GetComponent<MeshCollider>().sharedMesh=src;UnityEditor.EditorUtility.SetDirty(src);rows.Add(mf.name+" removed only overlapping apron triangles="+cut);}
UnityEditor.AssetDatabase.SaveAssets();System.IO.File.WriteAllLines("Docs/ReverseShortcuts/protected-apron-trim.txt",rows);UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");
}catch(Exception e){System.IO.File.WriteAllText("Docs/ReverseShortcuts/protected-apron-error.txt",e.ToString());}};return "Trim new apron overlap; original roads and terrain untouched";
