EditorApplication.delayCall+=()=>{var original=UnityEngine.SceneManagement.SceneManager.GetActiveScene().path;var rows=new List<string>();void Check(bool ok,string text)=>rows.Add((ok?"PASS ":"FAIL ")+text);try{
foreach(var name in Racer.RacePlaylists.Scenes){UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/"+name+".unity");Physics.SyncTransforms();float Ground(Vector3 p)=>Physics.RaycastAll(new(p.x,500,p.z),Vector3.down,1000,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).OrderBy(h=>h.distance).First().point.y;
var pool=GameObject.Find("House 3 pool and lake");Check(pool&&pool.transform.Find("House 3 swimming pool")&&pool.transform.Find("House 3 lake"),name+" accepted permanent pool and lake exist");if(pool){var edges=pool.GetComponentsInChildren<Transform>().Where(t=>t.name=="Pool edge").ToArray();float maxGap=edges.Max(t=>t.GetComponent<Renderer>().bounds.min.y-Ground(t.position));Check(maxGap<.2f,name+" coping supported by local terrain, largest center gap="+maxGap);Check(pool.GetComponentsInChildren<Collider>().Length==8,name+" pool rim and full shell collision present");}
var house=GameObject.Find("Original house 2").transform;Check(Vector2.Distance(new(house.position.x,house.position.z),new(440,-82))<.01f,name+" single original Roger house centered");Check(UnityEngine.Object.FindObjectsByType<Transform>().Count(t=>t.name=="Original house 2")==1,name+" Roger house not duplicated");var support=house.GetComponentsInChildren<Collider>().Where(c=>c.name.Contains("Foundation")||c.name.Contains("Wall")||c.name.Contains("Body")).ToArray();if(support.Length==0)support=house.GetComponentsInChildren<Collider>();float floor=support.Min(c=>c.bounds.min.y);float gap=support.Where(c=>Math.Abs(c.bounds.min.y-floor)<.3f).SelectMany(c=>new[]{new Vector3(c.bounds.min.x+.1f,0,c.bounds.min.z+.1f),new Vector3(c.bounds.max.x-.1f,0,c.bounds.min.z+.1f),new Vector3(c.bounds.min.x+.1f,0,c.bounds.max.z-.1f),new Vector3(c.bounds.max.x-.1f,0,c.bounds.max.z-.1f)}).Select(p=>floor-Ground(p)).Max();Check(gap<.2f,name+" Roger foundation corners supported; gap="+gap);
var trees=UnityEngine.Object.FindObjectsByType<Collider>().Where(c=>(c.name.ToLowerInvariant().Contains("tree")||c.name.ToLowerInvariant().Contains("trunk"))&&Vector2.Distance(new(c.bounds.center.x,c.bounds.center.z),new(370.3f,12.7f))<65).ToArray();float error=trees.Select(c=>Math.Abs(c.bounds.min.y-Ground(c.bounds.center))).DefaultIfEmpty(0).Max();Check(error<.04f,name+" final terrain tree feet, count="+trees.Length+" max error="+error);
var text=UnityEngine.Object.FindObjectsByType<TextMesh>(FindObjectsInactive.Include).Where(t=>!Racer.SceneryText.IsFloating(t)).ToArray();Check(text.Length>0&&text.All(t=>t.GetComponent<Renderer>().sharedMaterial.shader.name=="Racer/SummitText"),name+" physical lettering retained, depth tested, single readable face; count="+text.Length);
if(name=="StreetLoopReverse"){var axis=new Vector3(.35f,0,1).normalized;var start=new Vector3(334.05f,0,-212);var conflicts=UnityEngine.Object.FindObjectsByType<BoxCollider>().Where(c=>c.name.Contains("woodland trunk")).Where(c=>{var q=c.bounds.center-start;float s=Vector3.Dot(q,axis),d=Math.Abs(Vector3.Dot(q,Vector3.Cross(Vector3.up,axis)));return s>-42&&s<100&&d<10&&c.bounds.max.y>55;}).ToArray();Check(conflicts.Length==0,"Street Reverse Laurel approach/ramp/flight/runout free of density-pass trunks");}
}
System.IO.File.WriteAllLines("Docs/BackyardReverse/world-checks.txt",rows);
}catch(Exception e){System.IO.File.WriteAllText("Docs/BackyardReverse/world-check-error.txt",e.ToString());}finally{UnityEditor.SceneManagement.EditorSceneManager.OpenScene(original);}};return "Scoped shared world checks scheduled";
