EditorApplication.delayCall+=()=>{try{
if(Application.isPlaying)throw new Exception("Edit mode required");var scene=UnityEditor.SceneManagement.EditorSceneManager.OpenScene(Racer.Editor.BackyardForwardAuthoring.ScenePath);Physics.SyncTransforms();var checks=new List<string>();void Check(bool ok,string message)=>checks.Add((ok?"PASS ":"FAIL ")+message);
float Ground(Vector3 p)=>Physics.RaycastAll(new Vector3(p.x,250,p.z),Vector3.down,500,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")).OrderBy(h=>h.distance).First().point.y;
var mf=GameObject.Find("Memory loop - north is +Z").GetComponentsInChildren<MeshFilter>().Single(m=>m.name=="Ground_480_320");var original=AssetDatabase.LoadAssetAtPath<Mesh>("Assets/Track/BackyardForward/Ground_480_320.asset");var mesh=mf.sharedMesh;var axis=new Vector3(-50.6f,0,-7.5f).normalized;var side=Vector3.Cross(Vector3.up,axis);var origin=new Vector3(309.2f,0,15.7f);float Radius(Vector3 p){var q=p-origin;return Mathf.Sqrt(Mathf.Pow((Vector3.Dot(q,axis)-25.5f)/24.5f,2)+Mathf.Pow(Vector3.Dot(q,side)/23,2));}
Check(mf.GetComponent<MeshCollider>().sharedMesh==mesh,"Visible terrain and collider use the identical bowl mesh");Check(mesh.triangles.SequenceEqual(original.triangles),"Original continuous terrain topology retained without holes or added walls");var v=mesh.vertices;var old=original.vertices;int outside=0;for(int i=0;i<v.Length;i++)if(Radius(mf.transform.TransformPoint(old[i]))>=1&&v[i]!=old[i])outside++;Check(outside==0,"Every terrain vertex outside the local ellipse is unchanged");
float floor=Ground(origin+axis*25.5f),launch=Ground(origin),landing=Ground(new Vector3(258.6f,0,8.2f));Check(Math.Abs(floor-61.5f)<.01f&&landing-floor>6&&launch-floor>18,$"Measured floor={floor:F3}, launch={launch:F3}, landing={landing:F3}; substantial supported bowl");
var route=UnityEngine.Object.FindAnyObjectByType<Racer.RaceDirector>().road.points;var baseline=Newtonsoft.Json.Linq.JObject.Parse(System.IO.File.ReadAllText("Docs/BackyardForward/geometry.json"));var before=baseline["route"].ToObject<Vector3[]>();Check(route.SequenceEqual(before),"Every accepted route point is unchanged");
var deps=Newtonsoft.Json.Linq.JArray.Parse(System.IO.File.ReadAllText("Docs/DumpCorrection/dependencies-before.json"));var trees=UnityEngine.Object.FindObjectsByType<Collider>().Where(c=>c.name.Contains("trunk")||c.name.Contains("Tree")).ToArray();int grounded=0,removed=0;float maxError=0;
foreach(var d in deps.Where(d=>((string)d["name"]).Contains("trunk")||((string)d["name"]).Contains("Tree"))){var p=d["position"].ToObject<Vector3>();var c=trees.FirstOrDefault(c=>Math.Abs(c.transform.position.x-p.x)<.001f&&Math.Abs(c.transform.position.z-p.z)<.001f);if(!c){removed++;continue;}float oldGround=(float)d["ground"],dy=c.transform.position.y-p.y;float expected=Ground(c.bounds.center)-oldGround;maxError=Math.Max(maxError,Math.Abs(dy-expected));if(Math.Abs(dy)>.015f)grounded++;}
Check(removed==2&&grounded==9&&maxError<.025f,$"Affected tree bases retain ground offsets: 2 removed, {grounded} regrounded, maximum error={maxError:F5}m");
var junk=GameObject.Find("Old dump - scattered salvage - no collision");Check(junk.GetComponentsInChildren<Collider>().Length==0,"Junk adds no colliders, trigger/reset volumes or invisible walls");float maximumGap=0;foreach(var part in junk.GetComponentsInChildren<MeshFilter>()){float gap=float.PositiveInfinity;foreach(var vertex in part.sharedMesh.vertices){var p=part.transform.TransformPoint(vertex);gap=Math.Min(gap,p.y-Ground(p));}maximumGap=Math.Max(maximumGap,Math.Abs(gap+.035f));}Check(maximumGap<.025f,$"Every junk mesh touches terrain: maximum grounding error={maximumGap:F5}m");
System.IO.File.WriteAllLines("Docs/DumpCorrection/geometry-checks.txt",checks);
}catch(Exception e){System.IO.File.WriteAllText("Docs/DumpCorrection/geometry-error.txt",e.ToString());}};return "Scheduled dump-only geometry/dependency verification";
