using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Racer;using Object=UnityEngine.Object;
public static class VerifyUndergroundStructure {
 public static string Main(){var rows=new List<string>();var old=UnityEngine.SceneManagement.SceneManager.GetActiveScene().path;bool back=Physics.queriesHitBackfaces;try{
 EditorSceneManager.OpenScene("Assets/Scenes/DansBackyardReverse.unity");Physics.SyncTransforms();Physics.queriesHitBackfaces=true;var b=Object.FindObjectsByType<WoodlandRoute>().Single(b=>b.title.StartsWith("Storm"));float min=100;string limiting="";for(float s=b.undergroundStart;s<b.undergroundStart+24;s+=1){var p=b.At(s,out var f);foreach(float side in new[]{-1f,0,1f}){var q=p+Vector3.Cross(Vector3.up,f).normalized*side;var hits=Physics.RaycastAll(q+Vector3.up*.25f,Vector3.up,12,1,QueryTriggerInteraction.Ignore).Where(h=>!h.rigidbody).OrderBy(h=>h.distance).ToArray();if(hits.Length>0&&hits[0].distance+.25f<min){min=hits[0].distance+.25f;limiting=hits[0].collider.name+" at station "+s;}}}
 rows.Add((min>3?"PASS ":"FAIL ")+"Entrance central 2m corridor vertical clearance minimum="+min+" limiting="+limiting);
 var floor=GameObject.Find("Ground_Culvert seamless floor").GetComponent<MeshFilter>();var candidates=AssetDatabase.FindAssets("t:Mesh",new[]{"Assets/Track/ReverseCorrection"}).Select(AssetDatabase.GUIDToAssetPath).Where(p=>p.Contains("Culvert seamless floor")).Select(AssetDatabase.LoadAssetAtPath<Mesh>).ToArray();rows.Add((candidates.Any(m=>m.vertices.SequenceEqual(floor.sharedMesh.vertices)&&m.triangles.SequenceEqual(floor.sharedMesh.triangles))?"PASS ":"FAIL ")+"Continuous drain floor vertices/triangles preserved exactly");
 var root=GameObject.Find("Storm Drain atmosphere");rows.Add((root.GetComponentsInChildren<Collider>(true).Length==0?"PASS ":"FAIL ")+"All drain clutter, rats and sign have no collision; renderers="+root.GetComponentsInChildren<Renderer>(true).Length);var life=root.GetComponentInChildren<UndergroundLife>();rows.Add((life.rats.Length==4&&life.refuges.Length==4?"PASS ":"FAIL ")+"Four fixed rats with wall refuges and no spawn loop");
 var arrows=Object.FindObjectsByType<Renderer>().Where(r=>r.name.Contains("arrow")||r.name.Contains("teal / reassurance")).Where(r=>Vector3.Distance(r.bounds.center,new(464.6f,82.2f,-2.1f))<30).ToArray();rows.Add((!arrows.Any(r=>r.name=="Main teal / reassurance")?"PASS ":"FAIL ")+"Stray atlas arrow removed; local remaining arrows="+string.Join(";",arrows.Select(r=>r.name+" at "+r.bounds.center)));
 EditorSceneManager.OpenScene("Assets/Scenes/ForestLoopReverse.unity");root=GameObject.Find("Forest Reverse natural cave atmosphere");rows.Add((root.GetComponentsInChildren<Collider>(true).Length==0?"PASS ":"FAIL ")+"Natural cave detail adds no collision; renderers="+root.GetComponentsInChildren<Renderer>(true).Length);
 File.WriteAllLines("Docs/UndergroundPolish/structure-checks.txt",rows);return string.Join("\n",rows);
 }finally{Physics.queriesHitBackfaces=back;EditorSceneManager.OpenScene(old);}}
}
