UnityEditor.EditorApplication.delayCall += () => {try {
var rows=new List<string>();var errors=new List<string>();
foreach(string scene in new[]{"StreetLoopGreybox","StreetLoopReverse"}){
UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/"+scene+".unity");Physics.SyncTransforms();var road=UnityEngine.Object.FindAnyObjectByType<Racer.RaceDirector>().road;road.Initialize();float center=road.Project(new Vector3(500,88,-101),out _);int samples=0,missing=0;float maxError=0;
foreach(float lane in new[]{-4.4f,-2,0,2,4.4f})for(float s=center-180.137f;s<center+160;s+=.25f){var p=road.At(s,out var f)+Vector3.Cross(Vector3.up,f).normalized*lane;var hits=Physics.RaycastAll(p+Vector3.up*8,Vector3.down,16,1,QueryTriggerInteraction.Ignore).Where(h=>!h.rigidbody).OrderBy(h=>h.distance).ToArray();if(hits.Length==0){missing++;continue;}maxError=Mathf.Max(maxError,Math.Abs(hits[0].point.y-p.y));samples++;}
rows.Add($"{scene} normal road: samples={samples}, gaps={missing}, max height error={maxError:F5}m");if(missing!=0||maxError>.35f)errors.Add(scene+" road support");
}
var start=new Vector3(340,0,-190);var axis=new Vector3(1,0,.65f).normalized;var side=Vector3.Cross(Vector3.up,axis);var mc=GameObject.Find("Ground_560_240").GetComponent<MeshCollider>();int count=0,missingRamp=0,stacked=0;float angle=0,maxProfileError=0;string worst="";
foreach(float lane in new[]{-3.5f,-2,0,2,3.5f}){Vector3 prev=Vector3.up;bool hasPrev=false;for(float s=-2.137f;s<25.9f;s+=.1f){var p=start+axis*s+side*lane;var hits=Physics.RaycastAll(p+Vector3.up*150,Vector3.down,130,1,QueryTriggerInteraction.Ignore).Where(h=>!h.rigidbody&&h.collider.name.StartsWith("Ground_")).OrderBy(h=>h.distance).ToArray();if(hits.Length==0){missingRamp++;continue;}var h=hits[0];if(hasPrev&&Vector3.Angle(prev,h.normal)>angle){angle=Vector3.Angle(prev,h.normal);worst=$"s={s:F3}, lane={lane}, collider={h.collider.name}";}prev=h.normal;hasPrev=true;if(s>6)maxProfileError=Mathf.Max(maxProfileError,Math.Abs(h.point.y-(69.5233f+.12f*s+.6f*s*s/52)));stacked+=hits.Count(v=>Math.Abs(v.point.y-h.point.y)<.01f)>1?1:0;count++;}}
rows.Add($"Straight ramp: samples={count}; gaps={missingRamp}; stacked top surfaces={stacked}; maximum adjacent .1m normal change={angle:F3}deg; worst={worst}; profile error={maxProfileError:F5}m; visible/collision identical={mc.sharedMesh==mc.GetComponent<MeshFilter>().sharedMesh}");if(missingRamp!=0||stacked!=0||maxProfileError>.01f||angle>3)errors.Add("Ramp surface");
// Outside the local footprint, the near-side ground still matches its historical baseline.
var tmp=new GameObject("Temporary baseline",typeof(MeshCollider));tmp.layer=31;tmp.transform.SetPositionAndRotation(mc.transform.position,mc.transform.rotation);tmp.transform.localScale=mc.transform.lossyScale;var bc=tmp.GetComponent<MeshCollider>();bc.sharedMesh=AssetDatabase.LoadAssetAtPath<Mesh>(AssetDatabase.GUIDToAssetPath("d5712e5358ab6234988ecc278e527e41"));Physics.SyncTransforms();float perimeter=0;int perimeterCount=0;
for(float s=-1;s<=29;s+=.25f)foreach(float t in new[]{-10.01f,10.01f}){var p=start+axis*s+side*t;var ray=new Ray(p+Vector3.up*200,Vector3.down);if(mc.Raycast(ray,out var a,300)&&bc.Raycast(ray,out var b,300)){perimeter=Mathf.Max(perimeter,Math.Abs(a.point.y-b.point.y));perimeterCount++;}}
rows.Add($"Outer side seam: {perimeterCount} samples, maximum baseline mismatch={perimeter:F6}m");if(perimeter>.001f)errors.Add("Perimeter seam");UnityEngine.Object.DestroyImmediate(tmp);
var lip=start+axis*26+Vector3.up*(69.5233f+10.92f);rows.Add("Gravity="+Physics.gravity+"; launch="+lip);
foreach(float speed in new[]{32f,38f}){var v=(axis+Vector3.up*.72f).normalized*speed;bool landed=false;for(float t=.03f;t<8;t+=.01f){var p=lip+v*t+Physics.gravity*(.5f*t*t);if(p.y>150)continue;var hits=Physics.RaycastAll(new Vector3(p.x,160,p.z),Vector3.down,200,1,QueryTriggerInteraction.Ignore).Where(h=>!h.rigidbody&&h.collider.name.StartsWith("Ground_")).OrderBy(h=>h.distance).ToArray();if(hits.Length>0&&p.y<=hits[0].point.y){float distance=Vector3.Dot(p-lip,axis);landed=distance>65&&hits[0].point.y>70;rows.Add($"Geometric flight at {speed}m/s: contact distance={distance:F2}m, point={hits[0].point}, clears chasm={landed}; actual vehicle jump left to user playtest");break;}}if(!landed)errors.Add("Geometric flight "+speed);}
rows.Add("Recent shortcut root absent="+(GameObject.Find("Laurel separate shortcut ramp")==null));rows.Add("FAILURES="+errors.Count);rows.AddRange(errors);System.IO.File.WriteAllLines("Docs/SimpleLaurel/verification.txt",rows);
void Shot(string name,Vector3 p,Vector3 target){var obj=new GameObject("Temporary camera",typeof(Camera));var cam=obj.GetComponent<Camera>();cam.transform.SetPositionAndRotation(p,Quaternion.LookRotation(target-p));cam.fieldOfView=65;cam.farClipPlane=1500;var rt=new RenderTexture(1200,800,24);var tex=new Texture2D(1200,800,TextureFormat.RGB24,false);var prior=RenderTexture.active;cam.targetTexture=rt;cam.Render();RenderTexture.active=rt;tex.ReadPixels(new Rect(0,0,1200,800),0,0);tex.Apply();System.IO.File.WriteAllBytes("Docs/SimpleLaurel/"+name+".png",tex.EncodeToPNG());RenderTexture.active=prior;UnityEngine.Object.DestroyImmediate(tex);UnityEngine.Object.DestroyImmediate(rt);UnityEngine.Object.DestroyImmediate(obj);}
Shot("ramp",new Vector3(340,74,-188),new Vector3(440,78,-158));Shot("overview",new Vector3(390,150,-255),new Vector3(390,70,-168));
}catch(Exception e){System.IO.File.WriteAllText("Docs/SimpleLaurel/verification-error.txt",e.ToString());}};return "Scheduled targeted geometry verification";


