EditorApplication.delayCall+=()=>{try{
var rows=new List<string>();var scene=UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/StreetLoopGreybox.unity");
float Ground(Vector3 p)=>Physics.RaycastAll(new Vector3(p.x,250,p.z),Vector3.down,500,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")||h.collider.name=="Decorative Road pavement").OrderBy(h=>Math.Abs(h.point.y-p.y)).First().point.y;
void Check(bool ok,string label){rows.Add((ok?"PASS ":"FAIL ")+label);}
var concrete=UnityEngine.Object.FindObjectsByType<MeshFilter>().Single(m=>m.name=="Ground_Dan beige concrete descent and parking");var verts=concrete.sharedMesh.vertices.Select(concrete.transform.TransformPoint).ToArray();var flat=verts.Where(p=>p.x>=391.9f&&p.x<=409.5f).ToArray();
Check(flat.Length>100&&flat.Max(p=>p.y)-flat.Min(p=>p.y)<.0001f,"Parking is completely flat across the full existing apron; min="+flat.Min(p=>p.y)+" max="+flat.Max(p=>p.y));
Check(concrete.GetComponent<MeshCollider>().sharedMesh==concrete.sharedMesh,"Driveway visible and collision mesh are identical");float supportGap=0,minSupportGap=999;int supportSamples=0;for(int i=0;i<verts.Length;i+=20){var p=verts[i];var ground=Physics.RaycastAll(new Vector3(p.x,200,p.z),Vector3.down,400,1,QueryTriggerInteraction.Ignore).Where(h=>System.Text.RegularExpressions.Regex.IsMatch(h.collider.name,@"^Ground_\d+_\d+$")).OrderBy(h=>Math.Abs(h.point.y-p.y)).ToArray();if(ground.Length>0){supportGap=Math.Max(supportGap,p.y-ground[0].point.y);minSupportGap=Math.Min(minSupportGap,p.y-ground[0].point.y);supportSamples++;}}Check(supportGap<.15f&&minSupportGap>-.01f,"Concrete terrain support max separation="+supportGap+" minimum separation="+minSupportGap+" across "+supportSamples+" samples");
var root=GameObject.Find("TEMPORARY Backyard anchor validation - no route").transform;Check(root.childCount==8,"Eight temporary anchors");
for(int i=0;i<8;i++){var t=root.GetChild(i);var p=Racer.Editor.YardResetAuthoring.Anchors[i];Check(Math.Abs(t.position.x-p.x)<.0001f&&Math.Abs(t.position.z-p.z)<.0001f&&Math.Abs(t.position.y-Ground(t.position))<.03f&&t.GetComponentsInChildren<Collider>().Length==0&&t.GetComponentsInChildren<TextMesh>().Length==1&&t.GetComponentInChildren<TextMesh>().font!=null,"Marker "+(i+1)+" hard X/Z, grounded, one readable camera-facing label, no collider: "+t.position.ToString("F4"));}
Check(!UnityEditor.EditorBuildSettings.scenes.Any(s=>s.path.Contains("DansBackyard")),"Rejected scenes absent from build list");Check(Racer.RacePlaylists.Scenes.Length==6,"Six established selectable courses");
Check(!UnityEngine.Object.FindObjectsByType<Transform>().Any(t=>t.name.StartsWith("Ground_Backyard")),"No rejected Backyard surfaces or replacement course");
var mails=UnityEngine.Object.FindObjectsByType<Transform>().Where(t=>t.name=="Mailbox - Dan - blue X").ToArray();Check(mails.Length==1&&mails[0].position.z<4&&mails[0].position.x>463&&Math.Abs(mails[0].position.y-Ground(mails[0].position))<.01f,"One existing mailbox at main entrance left side, grounded; "+mails[0].position);
var fences=UnityEngine.Object.FindObjectsByType<Transform>().Where(t=>(t.name=="Fence endpoint A"||t.name=="Fence endpoint B")&&t.position.x>388&&t.position.x<468&&t.position.z>0&&t.position.z<36).ToArray();float fenceError=fences.Max(t=>Math.Abs(t.position.y-Ground(t.position)));Check(fenceError<.12f,"Fence endpoint support max error="+fenceError);
// Only foundation contacts affected by this footprint are sampled; no world-wide scan.
foreach(var c in GameObject.Find("Dan - blue X").GetComponentsInChildren<Collider>().Where(c=>c.name=="Garage walls"||c.name=="Pool house walls")){var b=c.bounds;float maxGap=-999;foreach(float x in new[]{b.min.x+.2f,b.max.x-.2f})foreach(float z in new[]{b.min.z+.2f,b.max.z-.2f})maxGap=Math.Max(maxGap,b.min.y-Ground(new Vector3(x,b.min.y,z)));Check(maxGap<.15f,c.name+" supported foundation; largest corner gap="+maxGap);}
var kyle=UnityEngine.Object.FindObjectsByType<MeshFilter>().Single(m=>m.name=="Ground_CR113 Kyle driveway edge join");Check(AssetDatabase.GetAssetPath(kyle.sharedMesh)=="Assets/Track/Backyard/StreetLoopGreybox-Kyle-edge.asset","Accepted Kyle mesh retained exactly");
var playlistDir="Temp/YardResetPlaylistCheck";System.IO.Directory.CreateDirectory(playlistDir);System.IO.File.WriteAllText(playlistDir+"/race-playlists-v1.json","{\"version\":1,\"playlists\":[{\"name\":\"Retained mixed playlist\",\"entries\":[{\"course\":0,\"laps\":1},{\"course\":6,\"laps\":1}]}]}");var playlists=new Racer.RacePlaylists(playlistDir);Check(playlists.Error==null&&playlists.Definitions.Count==1&&playlists.Definitions[0].entries.Count==2&&playlists.Save(),"Existing playlist with removed Backyard entry remains readable, editable and retained");bool rejected=false;try{Racer.RacePlaylists.Begin(playlists.Definitions[0]);}catch(ArgumentException){rejected=true;}Check(rejected,"Removed course cannot load through a saved playlist");
System.IO.File.WriteAllLines("Docs/YardReset/checks.txt",rows);
foreach(var view in new[]{("entrance",new Vector3(478,84,9),new Vector3(446,80,9)),("parking",new Vector3(414,89,14),new Vector3(399,79.46f,18)),("property-overhead",new Vector3(432,160,15),new Vector3(432,80,15)),("restored-forest",new Vector3(300,150,90),new Vector3(290,72,0)),("anchor-7",new Vector3(115,48,-122),new Vector3(96,41,-108))}){
var go=new GameObject("Temporary verification camera");var cam=go.AddComponent<Camera>();cam.CopyFrom(Camera.main);cam.enabled=false;cam.transform.SetPositionAndRotation(view.Item2,Quaternion.LookRotation(view.Item3-view.Item2,view.Item1=="property-overhead"?Vector3.forward:Vector3.up));var rt=new RenderTexture(1400,900,24);cam.targetTexture=rt;foreach(var label in root.GetComponentsInChildren<TextMesh>())label.transform.rotation=cam.transform.rotation;cam.Render();var prev=RenderTexture.active;RenderTexture.active=rt;var tex=new Texture2D(1400,900,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,1400,900),0,0);tex.Apply();System.IO.File.WriteAllBytes("Docs/YardReset/"+view.Item1+".png",tex.EncodeToPNG());RenderTexture.active=prev;cam.targetTexture=null;UnityEngine.Object.DestroyImmediate(tex);UnityEngine.Object.DestroyImmediate(rt);UnityEngine.Object.DestroyImmediate(go);
}
System.IO.File.WriteAllText("Docs/YardReset/verification-done.txt",string.Join("\n",rows));
}catch(Exception e){System.IO.File.WriteAllText("Docs/YardReset/verification-error.txt",e.ToString());}};return "Scheduled focused support, marker and restoration checks and views";
