using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using Racer;
public static class VerifyShortcutRevisionGeometry {
 public static string Main(){var race=UnityEngine.Object.FindAnyObjectByType<RaceDirector>();var root=GameObject.Find("Backyard optional forest shortcuts");var branches=UnityEngine.Object.FindObjectsByType<WoodlandRoute>();var checks=new List<string>();void Check(bool ok,string text)=>checks.Add((ok?"PASS ":"FAIL ")+text);
 Check(root.GetComponentsInChildren<Transform>().All(t=>t.name!="Timber grounded support"),"Old rows of ground support posts removed");Check(root.GetComponentsInChildren<Transform>().Count(t=>t.name=="Timber strapped around existing trunk")==4,"Four platforms braced to existing trees");Check(root.GetComponentsInChildren<Transform>().Count(t=>t.name.StartsWith("Long loose leaning board"))==6,"Six adjacent long boards; short cabin approach");
 var cabin=branches.First(b=>b.title=="Abandoned Cabin Jump");var roof=root.GetComponentsInChildren<MeshCollider>().Single(c=>c.name=="Takeoff - Leaning boards through cabin roof");Check(roof.sharedMesh.isReadable,"One readable welded cabin board/roof collider");int blocked=0;float maxStep=0,lastGrade=0;for(float s=23;s<40.5;s+=.25f){var p=cabin.At(s,out var f);float grade=f.y/new Vector2(f.x,f.z).magnitude;if(s>23)maxStep=Mathf.Max(maxStep,Mathf.Abs(grade-lastGrade));lastGrade=grade;var hits=Physics.OverlapBox(p+Vector3.up*.75f,new(.95f,.38f,1.2f),Quaternion.LookRotation(Vector3.ProjectOnPlane(f,Vector3.up)),1,QueryTriggerInteraction.Ignore);blocked+=hits.Count(c=>c!=roof&&!c.name.StartsWith("Ground_")&&!c.attachedRigidbody);}Check(blocked==0,$"Cabin full car-body clearance: {blocked} intersecting obstructions");Check(maxStep<.07f,$"Cabin adjoining sampled grade step {maxStep:F4}; roof constant grade .32");
 var brush=UnityEngine.Object.FindObjectsByType<ShortcutUndergrowth>();Check(brush.Length==2&&brush.All(b=>b.GetComponents<Collider>().Length==0),"Two traversable bush fields; no bush rigid colliders");Check(race.road.points.All(p=>brush.All(b=>b.Coverage(p)==0)),"Zero resistance on all 1684 protected main-route samples");
 foreach(var b in branches){var field=brush.Single(f=>f.name.StartsWith(b.title));int covered=0,total=0;float a=b==cabin?53:40,z=b==cabin?69:82;for(float s=a;s<=z;s+=3)foreach(float offset in new[]{-10f,-5f,0,5,10}){var p=b.At(s,out var f)+Vector3.Cross(Vector3.up,f).normalized*offset;total++;if(field.Coverage(p)>.9f)covered++;}Check(covered==total,$"{b.title}: dense ground coverage under/both sides including ±5 and ±10m: {covered}/{total}");Check(b.aiValidated&&b.bypassedGates.Length>0,$"{b.title}: production AI/checkpoint/minimap branch metadata retained");}
 var tree=branches.First(b=>b.title=="Tree-Top Trail");Check(tree.points[0]==new Vector3(218.676865f,61.39138f,-5.618362f),"Tree entry unchanged");
 File.WriteAllLines("Docs/ShortcutRevision/geometry-checks.txt",checks);File.WriteAllText("Docs/ShortcutRevision/geometry.json",Newtonsoft.Json.JsonConvert.SerializeObject(new {branches=branches.Select(b=>new{b.title,b.entryRoad,b.exitRoad,b.entryInset,b.halfWidth,b.bypassedGates,b.aiValidated,length=b.Length,points=b.points.Select(p=>new{p.x,p.y,p.z})})}));return string.Join("\n",checks);
 }
}
