EditorApplication.delayCall+=()=>{try{
var scene=UnityEditor.SceneManagement.EditorSceneManager.OpenScene(Racer.Editor.BackyardForwardAuthoring.ScenePath);var race=UnityEngine.Object.FindAnyObjectByType<Racer.RaceDirector>();race.road.Initialize();var course=race.GetComponent<Racer.BackyardForwardCourse>();var rows=new List<string>();Physics.SyncTransforms();
void Check(bool ok,string label)=>rows.Add((ok?"PASS ":"FAIL ")+label);
float Ground(Vector3 p)=>Physics.RaycastAll(new Vector3(p.x,250,p.z),Vector3.down,500,1,QueryTriggerInteraction.Ignore).Where(h=>h.collider.name.StartsWith("Ground_")||h.collider.name=="Decorative Road pavement").OrderBy(h=>h.distance).First().point.y;
for(int i=0;i<course.anchors.Length;i++){var p=course.anchors[i];float near=race.road.points.Min(q=>Vector2.Distance(new(p.x,p.z),new(q.x,q.z)));Check(near<.02f,$"Anchor {i+1} exact X/Z reached; nearest {near:F4}m");}
var concrete=UnityEngine.Object.FindObjectsByType<MeshFilter>().Single(m=>m.name=="Ground_Dan beige concrete descent and parking");Check(AssetDatabase.GetAssetPath(concrete.sharedMesh)=="Assets/Track/YardReset/StreetLoopGreybox-concrete.asset","Accepted property pavement reused exactly");var flat=concrete.sharedMesh.vertices.Select(concrete.transform.TransformPoint).Where(p=>p.x>=391.9f&&p.x<=409.5f).ToArray();Check(flat.Max(p=>p.y)-flat.Min(p=>p.y)<.0001f,$"Parking completely flat at {flat[0].y:F5}");
Check(!UnityEngine.Object.FindObjectsByType<MeshFilter>().Any(m=>m.name.Contains("Forward navigation")&&m.sharedMesh),"No forest road/deck mesh");
Check(race.gates.Skip(1).All(g=>g.GetComponentsInChildren<Renderer>().All(r=>r.sharedMaterial.name=="RaceGate")),"All ordinary checkpoints are accepted blue gates");Check(race.gates.All(g=>g.GetComponentsInChildren<Collider>().Length==0),"No checkpoint collider hazards");
foreach(var c in GameObject.Find("Dan - blue X").GetComponentsInChildren<Collider>().Where(c=>c.name=="Garage walls"||c.name=="Pool house walls")){var b=c.bounds;float gap=-999;foreach(float x in new[]{b.min.x+.2f,b.max.x-.2f})foreach(float z in new[]{b.min.z+.2f,b.max.z-.2f})gap=Math.Max(gap,b.min.y-Ground(new(x,b.min.y,z)));Check(gap<.15f,c.name+" foundation supported; gap="+gap);}
var trees=UnityEngine.Object.FindObjectsByType<Collider>().Where(c=>c.name.IndexOf("trunk",StringComparison.OrdinalIgnoreCase)>=0||c.name.IndexOf("tree",StringComparison.OrdinalIgnoreCase)>=0).ToArray();int close=0;for(float s=300;s<race.road.Length-140;s+=25){var p=race.road.At(s,out _);if(trees.Any(c=>Vector2.Distance(new(p.x,p.z),new(c.bounds.center.x,c.bounds.center.z))<13))close++;}Check(close>=20,"Wooded corridor: "+close+" sampled stations have trees within 13m");
var profiles=new List<string>{"feature,x,z,y"};foreach(var entry in new[]{("dump",new Vector3(309.2f,0,15.7f),new Vector3(-50.6f,0,-7.5f).normalized,65f),("first-gully",new Vector3(130,0,-108.6f),Vector3.left,70f),("second-gully",new Vector3(75,0,60.7f),Vector3.right,70f)}){for(float d=0;d<=entry.Item4;d+=1){var p=entry.Item2+entry.Item3*d;profiles.Add($"{entry.Item1},{p.x:F3},{p.z:F3},{Ground(p):F3}");}}
var axis=new Vector3(-50.6f,0,-7.5f).normalized;var bottom=course.anchors[4]+axis*24;Check(Ground(course.anchors[4])-Ground(bottom)>6,"Dump physically depressed below raised dirt launch; drop="+(Ground(course.anchors[4])-Ground(bottom)));
foreach(var z in new[]{-108.6f,0f,60.7f}){float x=96.1f+(z+108.6f)*11.6f/169.3f;float center=Ground(new(x,0,z)),east=Ground(new(x+24,0,z)),west=Ground(new(x-24,0,z));Check(Math.Min(east,west)-center>5,"Same continuous ravine deep at z="+z+"; lower rim to bottom="+(Math.Min(east,west)-center));}
System.IO.File.WriteAllLines("Docs/BackyardForward/geometry-checks.txt",rows);System.IO.File.WriteAllLines("Docs/BackyardForward/terrain-profiles.csv",profiles);
foreach(var view in new[]{("start",new Vector3(467,84,8),new Vector3(423,82,9)),("parking",new Vector3(413,88,17),new Vector3(396,79,10)),("dump",new Vector3(316,84,16.7f),new Vector3(280,69,11.5f)),("big-gully",new Vector3(124,48,-108.6f),new Vector3(83,32,-108.6f)),("same-ravine",new Vector3(125,155,-20),new Vector3(102,40,-20)),("second-crossing",new Vector3(86,56,60.7f),new Vector3(126,50,60.7f)),("woods",new Vector3(230,61,-59),new Vector3(209,51,-85)),("return",new Vector3(437,102,116),new Vector3(457,80,63))}){
var go=new GameObject("Temporary Forward inspection camera");var cam=go.AddComponent<Camera>();cam.CopyFrom(Camera.main);cam.enabled=false;cam.transform.SetPositionAndRotation(view.Item2,Quaternion.LookRotation(view.Item3-view.Item2));var rt=new RenderTexture(1280,800,24);cam.targetTexture=rt;cam.Render();var prev=RenderTexture.active;RenderTexture.active=rt;var tex=new Texture2D(1280,800,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,1280,800),0,0);tex.Apply();System.IO.File.WriteAllBytes("Docs/BackyardForward/"+view.Item1+".png",tex.EncodeToPNG());RenderTexture.active=prev;cam.targetTexture=null;UnityEngine.Object.DestroyImmediate(tex);UnityEngine.Object.DestroyImmediate(rt);UnityEngine.Object.DestroyImmediate(go);}
System.IO.File.WriteAllText("Docs/BackyardForward/geometry-done.txt",string.Join("\n",rows));
}catch(Exception e){System.IO.File.WriteAllText("Docs/BackyardForward/geometry-error.txt",e.ToString());}};return "Scheduled focused terrain/property/anchor and presentation checks";
