UnityEditor.EditorApplication.delayCall += () => { try {
var rows=new List<string>();var failures=new List<string>();
foreach(var sceneName in new[]{"StreetLoopGreybox","StreetLoopReverse","MountainLoopReverse"}){
UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/"+sceneName+".unity");Physics.SyncTransforms();var road=UnityEngine.Object.FindAnyObjectByType<Racer.RaceDirector>().road;road.Initialize();
if(sceneName.StartsWith("Street")){
float center=road.Project(new Vector3(500,88,-101),out _);int samples=0,missing=0;float maxError=0,maxStep=0;
foreach(float lane in new[]{-4.4f,-2,0,2,4.4f}){float previous=0;for(float s=center-180.137f;s<=center+160;s+=.25f){var p=road.At(s,out var f)+Vector3.Cross(Vector3.up,f).normalized*lane;var hits=Physics.RaycastAll(p+Vector3.up*8,Vector3.down,16,1,QueryTriggerInteraction.Ignore).Where(h=>!h.rigidbody).OrderBy(h=>h.distance).ToArray();if(hits.Length==0){missing++;failures.Add($"{sceneName} gap s={s} lane={lane}");continue;}var h=hits[0];float error=Math.Abs(h.point.y-p.y);maxError=Mathf.Max(maxError,error);if(samples>0&&previous!=0)maxStep=Mathf.Max(maxStep,Math.Abs(h.point.y-previous));previous=h.point.y;samples++;if(error>.35f)failures.Add($"{sceneName} surface displacement s={s:F2} lane={lane}: {h.collider.name} offset={error:F3}");}}
rows.Add($"{sceneName} normal Laurel route: {samples} samples; missing={missing}; maximum centerline height error={maxError:F5}m; maximum .25m step={maxStep:F5}m.");
if(sceneName.EndsWith("Reverse")){
var branch=UnityEngine.Object.FindObjectsByType<Racer.WoodlandRoute>().Single(b=>b.title=="Laurel Switchbacks");var lip=new Vector3(498.8f,88.2f,-115);var axis=new Vector3(-.1f,0,1).normalized;float lipStation=branch.Project(lip,out _);int count=0;float error=0,angle=0;int stacked=0;
foreach(float lane in new[]{-2f,0,2}){Vector3 previous=Vector3.up;for(float s=.137f;s<lipStation-.1f;s+=.25f){var p=branch.At(s,out var f)+Vector3.Cross(Vector3.up,f).normalized*lane+Vector3.up*.04f;var hits=Physics.RaycastAll(p+Vector3.up*3,Vector3.down,6,1,QueryTriggerInteraction.Ignore).Where(h=>!h.rigidbody).OrderBy(h=>h.distance).ToArray();if(hits.Length==0){failures.Add($"Shortcut gap {s} lane={lane}");continue;}var h=hits[0];error=Mathf.Max(error,Math.Abs(h.point.y-p.y));if(Math.Abs(h.point.y-p.y)>.08f)failures.Add($"Shortcut obstacle at {s:F2}/{lane}: {h.collider.name} offset={h.point.y-p.y:F3}");if(s>lipStation-35&&s<lipStation-.25f)angle=Mathf.Max(angle,Vector3.Angle(previous,h.normal));previous=h.normal;stacked+=hits.Count(x=>Math.Abs(x.point.y-h.point.y)<.02f)>1?1:0;count++;}}
rows.Add($"Shortcut: {count} lane samples, maximum height error={error:F5}m; ramp adjacent normal change={angle:F3}deg; stacked surfaces={stacked}.");
foreach(float speed in new[]{18f,24,32,38,49,52,56,61}){bool landed=false;Vector3 contact=default;string name="";for(float t=.01f;t<=2;t+=.005f){var p=lip+axis*(speed*t)+Vector3.up*(speed*.03f*t+Physics.gravity.y*.5f*t*t);var hits=Physics.RaycastAll(p+Vector3.up*5,Vector3.down,10,1,QueryTriggerInteraction.Ignore).Where(h=>!h.rigidbody&&h.collider.name.StartsWith("Ground_")).OrderBy(h=>h.distance).ToArray();if(hits.Length>0&&p.y<=hits[0].point.y+.01f){contact=hits[0].point;name=hits[0].collider.name;float station=road.Project(contact,out var lateral);landed=lateral<=4.6f&&!name.Contains("ramp");break;}}rows.Add($"Ballistic {speed}m/s: existing main road={landed}; contact={contact}; surface={name}");if(!landed)failures.Add("Ballistic envelope missed at "+speed);}
}
}else{
foreach(var range in new[]{new Vector2(40,100),new Vector2(118,160),new Vector2(100,180)}){float maxAngle=0,maxStep=0;int misses=0;string worst="";foreach(float lane in new[]{-4.4f,-2,0,2,4.4f}){Vector3 prior=Vector3.up;float py=0;for(float s=range.x+.137f;s<range.y;s+=.1f){var p=road.At(s,out var f)+Vector3.Cross(Vector3.up,f).normalized*lane;var hits=Physics.RaycastAll(p+Vector3.up*5,Vector3.down,10,1,QueryTriggerInteraction.Ignore).Where(h=>!h.rigidbody).OrderBy(h=>h.distance).ToArray();if(hits.Length==0){misses++;continue;}var h=hits[0];if(py!=0){float a=Vector3.Angle(prior,h.normal);if(a>maxAngle){maxAngle=a;worst=$"s={s:F2} lane={lane} {h.collider.name}";}maxStep=Mathf.Max(maxStep,Math.Abs(h.point.y-py));}prior=h.normal;py=h.point.y;}}rows.Add($"Mountain {range}: gaps={misses}; maximum adjacent .1m normal change={maxAngle:F3}deg; step={maxStep:F4}m; worst={worst}");if(misses>0)failures.Add("Mountain gap");}
foreach(var a in UnityEngine.Object.FindObjectsByType<MeshFilter>().Where(m=>m.name=="Main teal trail arrow").OrderBy(m=>road.Project(m.GetComponent<Renderer>().bounds.center,out _)).Take(3))rows.Add($"Early arrow station={road.Project(a.GetComponent<Renderer>().bounds.center,out _):F2}; child colliders={a.GetComponentsInChildren<Collider>(true).Length}");
}
}
rows.Add("FAILURES="+failures.Count);rows.AddRange(failures.Take(60));System.IO.File.WriteAllLines("Docs/SurgicalTracks/verification.txt",rows);
}catch(Exception e){System.IO.File.WriteAllText("Docs/SurgicalTracks/verification-error.txt",e.ToString());}};return "Scheduled targeted structural verification";
