var dir="Docs/CR016-017";var rows=new System.Collections.Generic.List<string>();int failures=0;
void Check(bool ok,string s){rows.Add((ok?"PASS ":"FAIL ")+s);if(!ok)failures++;}
var sites=GameObject.Find(Racer.Editor.Phase6Review.Root).transform.Cast<Transform>().ToArray();
var baseline=Newtonsoft.Json.Linq.JObject.Parse(System.IO.File.ReadAllText(dir+"/baseline.json"));var oldSites=(Newtonsoft.Json.Linq.JArray)baseline["sites"];
int moved=0;for(int i=0;i<sites.Length;i++){if(sites[i].name.StartsWith("Dan"))continue;var a=oldSites[i]["position"].Select(x=>(float)x).ToArray();var q=oldSites[i]["rotation"].Select(x=>(float)x).ToArray();if(Vector3.Distance(sites[i].position,new Vector3(a[0],a[1],a[2]))>.0001f||Quaternion.Angle(sites[i].rotation,new Quaternion(q[0],q[1],q[2],q[3]))>.001f)moved++;}
Check(moved==0,"All 46 unrelated buildings retain baseline positions and rotations");Check(!GameObject.Find("Original house 1"),"House 1 absent");
var dan=sites.First(t=>t.name.StartsWith("Dan"));Check(Mathf.Abs(dan.position.z+13)<.001f,"House southern inset 15.1m from old yard edge; moved 116.581m south");
float area=Mathf.PI*Racer.Editor.CompactYard.Radius*Racer.Editor.CompactYard.Radius;Check(Mathf.Abs(area/9003.472f-.25f)<.001f,$"Yard horizontal area 9003.472 -> {area:F3} m2; ratio {area/9003.472f:F5}; narrow access separate");
int floatCorners=0,buried=0;foreach(var t in sites){var f=t.Find("Foundation");float floor=t.position.y+t.Find("Phase 6 architecture").localPosition.y;foreach(float x in new[]{-.5f,.5f})foreach(float z in new[]{-.5f,.5f}){var p=f.TransformPoint(new Vector3(x,-.5f,z));float y=Racer.Editor.Phase6Buildings.Ground(p);if(p.y-y>.05f)floatCorners++;if(y>floor+.05f)buried++;}}Check(floatCorners==0&&buried==0,$"Foundations floating corners={floatCorners}, terrain above floors={buried}");
var woods=GameObject.Find("Woods replacing later subdivisions");var trees=woods.GetComponentsInChildren<BoxCollider>();var added=trees.Where(c=>c.name.StartsWith("CR016 trunk")).ToArray();for(int i=0;i<added.Length;i++)added[i].name="CR016 trunk "+i.ToString("D3");
Check(trees.Length-added.Length==11888,$"All 11888 prior trees retained; {added.Length} added; total {trees.Length}");
int conflict=0,unsupported=0;float gap=999;foreach(var c in added){var p=c.bounds.center;if(Racer.Editor.Phase6Buildings.YardClear(p)||Racer.Editor.CompactYard.AccessDistance(p)<6)conflict++;if(Mathf.Abs(c.bounds.min.y-Racer.Editor.Phase6Buildings.Ground(p))>.02f)unsupported++;foreach(var o in trees){if(o==c)continue;gap=Mathf.Min(gap,Vector2.Distance(new Vector2(p.x,p.z),new Vector2(o.bounds.center.x,o.bounds.center.z)));}}
Check(conflict==0&&unsupported==0,$"Added tree yard/access conflicts={conflict}, unsupported={unsupported}");Check(gap>=6.79f,$"Added trunk minimum center gap {gap:F3}m; width .75m");
var props=UnityEngine.Object.FindObjectsByType<Racer.BreakableProp>();Check(props.Length==18,$"18 breakable assemblies, actual {props.Length}");Check(props.All(p=>p.GetComponentsInChildren<Collider>().All(c=>c.isTrigger)),"All breakable collisions are trigger-only; no solid fragments or solver impulses");
var ground=GameObject.Find("Memory loop - north is +Z");var coords=new System.Collections.Generic.Dictionary<Vector2,Vector3>();int seams=0;foreach(var mf in ground.GetComponentsInChildren<MeshFilter>()){var v=mf.sharedMesh.vertices;var n=mf.sharedMesh.normals;for(int i=0;i<v.Length;i++){var k=new Vector2(v[i].x,v[i].z);var d=new Vector3(v[i].y,n[i].x,n[i].z);if(coords.TryGetValue(k,out var old)&&Vector3.Distance(old,d)>.00001f)seams++;coords[k]=d;}}Check(seams==0,"Terrain tile height/normal seam mismatches="+seams);
Check(ground.GetComponentsInChildren<MeshFilter>().All(f=>f.sharedMesh==f.GetComponent<MeshCollider>().sharedMesh),"Terrain collision matches visible mesh");
// Extend only low fence post bottoms to meet slope, retaining rail heights and placement.
foreach(var p in props.Where(p=>p.name.Contains("fence"))){foreach(var t in p.GetComponentsInChildren<Transform>().Where(t=>t.name.EndsWith("post"))){float bottom=t.position.y-t.lossyScale.y*.5f;float g=Racer.Editor.Phase6Buildings.Ground(t.position);if(bottom>g){float dy=bottom-g+.03f;t.position-=Vector3.up*dy*.5f;t.localScale+=Vector3.up*dy;UnityEditor.PrefabUtility.RecordPrefabInstancePropertyModifications(t);}}}
System.IO.File.WriteAllText(dir+"/props.json",Newtonsoft.Json.JsonConvert.SerializeObject(props.Select(p=>new {p.name,position=new[]{p.transform.position.x,p.transform.position.y,p.transform.position.z},size=new[]{p.GetComponent<BoxCollider>().size.x,p.GetComponent<BoxCollider>().size.y,p.GetComponent<BoxCollider>().size.z}}),Newtonsoft.Json.Formatting.Indented));
System.IO.File.WriteAllText(dir+"/local-trunks.json",Newtonsoft.Json.JsonConvert.SerializeObject(trees.Where(c=>c.bounds.center.x>290&&c.bounds.center.x<480&&c.bounds.center.z> -40&&c.bounds.center.z<145).Select(c=>new[]{c.bounds.center.x,c.bounds.min.y,c.bounds.center.z,c.bounds.size.x})));
UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(UnityEngine.SceneManagement.SceneManager.GetActiveScene());UnityEditor.SceneManagement.EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());
rows.Add("RESULT failures="+failures);System.IO.File.WriteAllLines(dir+"/geometry.txt",rows);return rows;
